/**
 * Resident maintenance request REST endpoint — Task #1277 / #1314 / #1484.
 *
 * Maintenance requests can already be created by the AI assistant via the
 * MCP `create_maintenance_request` tool. This module adds:
 *
 *   POST /api/maintenance-requests   — resident submits a new request
 *   GET  /api/maintenance-requests   — resident lists their own requests
 *                                      (filtered by residenceId query param)
 *
 * Both endpoints mirror the residence-scope guard the MCP tool already
 * enforces:
 *   - the residence must exist,
 *   - the caller must be allowed to access the residence per `canUserAccessResidence`
 *     (admins/managers via their accessible orgs; residents/tenants via an
 *     ACTIVE `userResidences` link).
 *
 * Validation reuses `insertMaintenanceRequestSchema` (and therefore the
 * shared `MAINTENANCE_CATEGORY_VALUES` enum + DB CHECK constraint applied
 * by migration 0009_maintenance_category_check.sql), so an invalid category
 * is rejected by Zod with a 400 before we ever touch the database — no
 * surface can drift away from the canonical 9-value enum.
 *
 * Persistence is routed through `storage.createMaintenanceRequest()` so the
 * storage layer (cache invalidation, MemStorage in tests) stays consistent
 * with manager-side flows.
 */
import type { Express } from 'express';
import { requireAuth } from '../../auth';
import { canUserAccessResidence } from '../../rbac';
import { insertMaintenanceRequestSchema } from '../../../shared/schemas/operations';
import { storage } from '../../storage';
import { z } from 'zod';
import {
  getMaintenanceRequestsForUser,
  getMaintenanceRequestsForResidence,
} from '../../db/queries/maintenance-queries';
import { buildUserContext } from '../../db/queries/scope-query';

// `insertMaintenanceRequestSchema.priority` is `z.string().default('medium')`,
// which would let any string slip through and only fail at the DB enum level
// (a 500). Tighten it to the same 5-value enum the `maintenance_priority`
// pgEnum + DB column already enforce, so invalid priorities are rejected at
// validation time with a clean 400.
const PRIORITY_VALUES = ['low', 'medium', 'high', 'urgent', 'emergency'] as const;
type MaintenancePriority = (typeof PRIORITY_VALUES)[number];
const prioritySchema = z.enum(PRIORITY_VALUES).default('medium');

// Max 3 images; each image string (base64 data URL) must not exceed ~10 MB
// encoded — 10 * 1024 * 1024 * (4/3) ≈ 13_981_013 characters. We use
// 14_000_000 as a round cap that gracefully covers a ~10 MB raw image.
const MAX_IMAGE_COUNT = 3;
const MAX_IMAGE_STRING_LENGTH = 14_000_000;

const restCreateSchema = insertMaintenanceRequestSchema
  .omit({
    submittedBy: true,
    assignedTo: true,
    scheduledDate: true,
  })
  .extend({
    priority: prioritySchema,
    images: z
      .array(
        z
          .string()
          .max(
            MAX_IMAGE_STRING_LENGTH,
            `Each image must not exceed ${MAX_IMAGE_STRING_LENGTH} characters`
          )
      )
      .max(MAX_IMAGE_COUNT, `At most ${MAX_IMAGE_COUNT} images are allowed`)
      .optional(),
  });

// The `residences.id` column is text (UUID-generated by default) so we
// validate only that the value is non-empty rather than enforcing UUID format.
const listQuerySchema = z.object({
  residenceId: z.string().min(1, 'residenceId must not be empty').optional(),
});

export default function register(app: Express): void {
  /**
   * GET /api/maintenance-requests
   *
   * Returns maintenance requests visible to the authenticated user.
   * If `residenceId` is supplied it is further filtered to that residence
   * (and the caller must have access to it). Without `residenceId` all
   * requests the user may see are returned (their own for residents/tenants,
   * all property requests for managers/admins).
   */
  app.get('/api/maintenance-requests', requireAuth, async (req: any, res: any) => {
    try {
      const user = req.user;
      if (!user?.id) {
        return res.status(401).json({ message: 'Authentication required' });
      }

      const parsed = listQuerySchema.safeParse(req.query);
      if (!parsed.success) {
        return res.status(400).json({
          message: 'Invalid query parameters',
          errors: parsed.error.flatten(),
        });
      }

      const { residenceId } = parsed.data;

      const userContext = await buildUserContext(user.id, user.role);

      let rows: unknown[];

      if (residenceId) {
        const hasAccess = await canUserAccessResidence(user.id, residenceId);
        if (!hasAccess) {
          return res.status(403).json({
            message: 'Access denied to this residence',
            code: 'RESIDENCE_ACCESS_DENIED',
          });
        }
        rows = await getMaintenanceRequestsForResidence(residenceId, userContext);
      } else {
        rows = await getMaintenanceRequestsForUser(userContext);
      }

      return res.status(200).json(rows);
    } catch (err: any) {
      console.error('[GET /api/maintenance-requests] failed', err);
      return res.status(500).json({
        message: 'Failed to fetch maintenance requests',
        code: 'INTERNAL_ERROR',
      });
    }
  });

  app.post('/api/maintenance-requests', requireAuth, async (req: any, res: any) => {
    try {
      const user = req.user;
      if (!user?.id) {
        return res.status(401).json({ message: 'Authentication required' });
      }

      const parsed = restCreateSchema.safeParse(req.body);
      if (!parsed.success) {
        return res.status(400).json({
          message: 'Invalid maintenance request',
          errors: parsed.error.flatten(),
        });
      }
      const data = parsed.data;

      const hasAccess = await canUserAccessResidence(user.id, data.residenceId);
      if (!hasAccess) {
        return res.status(403).json({
          message: 'Access denied to this residence',
          code: 'RESIDENCE_ACCESS_DENIED',
        });
      }

      const priority: MaintenancePriority = data.priority ?? 'medium';
      const row = await storage.createMaintenanceRequest({
        residenceId: data.residenceId,
        title: data.title,
        description: data.description,
        category: data.category,
        priority,
        submittedBy: user.id,
        images: data.images && data.images.length > 0 ? data.images : undefined,
      });

      return res.status(201).json(row);
    } catch (err: any) {
      console.error('[POST /api/maintenance-requests] failed', err);
      return res.status(500).json({
        message: 'Failed to create maintenance request',
        code: 'INTERNAL_ERROR',
      });
    }
  });
}
