import { describe, it, expect, beforeEach, afterEach, jest } from '@jest/globals';
import { render, screen, waitFor, act, fireEvent } from '@testing-library/react';
import '@testing-library/jest-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import React, { ReactNode } from 'react';
import ModularBillForm from '../../../client/src/components/bill-management/ModularBillForm';

type ApiCall = { method: string; url: string; data?: unknown };
const apiCalls: ApiCall[] = [];

// Each test sets the AI response shape it wants returned by the mocked
// /api/bills/extract-data endpoint before triggering the fake upload.
let nextAiResponse: any = null;
let nextAiSuccess = true;

const mockApiRequest = jest.fn(
  async (method: string, url: string, data?: unknown) => {
    apiCalls.push({ method, url, data });

    if (url === '/api/bills/extract-data') {
      return {
        ok: true,
        status: 200,
        json: async () => ({
          success: nextAiSuccess,
          data: nextAiSuccess ? nextAiResponse : null,
          error: nextAiSuccess ? undefined : 'simulated extraction failure',
          metadata: { confidence: 0.9 },
        }),
      };
    }

    if (method === 'PUT' && url.startsWith('/api/bills/')) {
      return {
        ok: true,
        status: 200,
        json: async () => ({
          id: 'auto-gen-test',
          billNumber: 'BILL-001',
          buildingId: 'building-test',
        }),
      };
    }

    return { ok: true, status: 200, json: async () => ({}) };
  }
);

jest.mock('@/hooks/use-language', () => ({
  useLanguage: () => ({
    language: 'en',
    setLanguage: jest.fn(),
    toggleLanguage: jest.fn(),
    t: (key: string) => key,
  }),
}));

jest.mock('@/hooks/use-toast', () => ({
  useToast: () => ({ toast: jest.fn() }),
}));

jest.mock('@/lib/queryClient', () => ({
  apiRequest: (...args: unknown[]) => (mockApiRequest as any)(...args),
  queryClient: { invalidateQueries: jest.fn() },
}));

jest.mock('@/components/document-management', () => ({
  SharedUploader: (props: any) => (
    <button
      type="button"
      data-testid="trigger-fake-upload"
      onClick={() => {
        const file = new File(['hello'], 'invoice.pdf', { type: 'application/pdf' });
        props.onDocumentChange(file, null);
      }}
    >
      upload
    </button>
  ),
}));

jest.mock('@/components/common/AttachedFileSection', () => ({
  AttachedFileSection: () => null,
}));

jest.mock('@/components/common/StandardFormGrid', () => ({
  StandardFormGrid: ({ children }: { children: ReactNode }) => <div>{children}</div>,
}));

jest.mock(
  '../../../client/src/components/bill-management/ConfidenceIndicator',
  () => ({ ConfidenceIndicator: () => null })
);

if (typeof Element.prototype.hasPointerCapture !== 'function') {
  (Element.prototype as any).hasPointerCapture = function () { return false; };
}
if (typeof Element.prototype.scrollIntoView !== 'function') {
  (Element.prototype as any).scrollIntoView = function () {};
}
if (typeof URL.createObjectURL !== 'function') {
  (URL as any).createObjectURL = () => 'blob:mock';
}

type BillOverrides = Partial<Record<string, any>>;

function renderForm(billOverrides: BillOverrides = {}) {
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: { retry: false },
      mutations: { retry: false },
    },
  });
  // Auto-generated bill so the GeminiBillExtractor can mount on the manual
  // tab as soon as the fake upload fires (no Tabs / Radix pointer
  // interaction required for the AI tab in jsdom).
  const autoGeneratedBill: any = {
    id: 'auto-gen-test',
    buildingId: 'building-test',
    title: '',
    vendor: '',
    paymentType: 'unique',
    paymentCount: '1',
    costs: [],
    totalAmount: '',
    startDate: '',
    isAutoGenerated: true,
    status: 'draft',
    category: 'other',
    ...billOverrides,
  };
  return render(
    <QueryClientProvider client={queryClient}>
      <ModularBillForm bill={autoGeneratedBill} buildingId="building-test" />
    </QueryClientProvider>
  );
}

async function triggerFakeUpload() {
  await act(async () => {
    fireEvent.click(await screen.findByTestId('trigger-fake-upload'));
  });
  await waitFor(() => {
    expect(
      apiCalls.some(c => c.url === '/api/bills/extract-data' && c.method === 'POST')
    ).toBe(true);
  });
}

async function clickSaveAndGetPutPayload(): Promise<any> {
  const saveButton = await screen.findByTestId('button-update-bill');
  await act(async () => {
    fireEvent.click(saveButton);
  });
  await waitFor(() => {
    expect(
      apiCalls.some(c => c.method === 'PUT' && c.url.startsWith('/api/bills/'))
    ).toBe(true);
  });
  const putCall = apiCalls.find(
    c => c.method === 'PUT' && c.url.startsWith('/api/bills/')
  )!;
  return putCall.data as any;
}

/**
 * Adjacent-path coverage for `convertBillResponseToFormData` →
 * `handleAiExtractionComplete` → save. The installment regression test
 * (#369) covers the customPayments-only branch end-to-end; these tests
 * exercise the other AI response shapes that the converter unit tests
 * already exercise in isolation, so a regression in prefill or save wiring
 * also surfaces as a failing assertion.
 */
describe('GeminiBillExtractor → ModularBillForm AI extraction edge cases', () => {
  let originalFetch: typeof globalThis.fetch;

  beforeEach(() => {
    apiCalls.length = 0;
    mockApiRequest.mockClear();
    nextAiResponse = null;
    nextAiSuccess = true;

    originalFetch = globalThis.fetch;
    (globalThis as any).fetch = jest.fn(async () => ({
      ok: true,
      status: 200,
      text: async () => '',
      json: async () => ({ id: 'doc-1' }),
    }));
  });

  afterEach(() => {
    (globalThis as any).fetch = originalFetch;
  });

  it('frequency=custom + customPaymentDates: divides total evenly across the dates and saves an installment plan', async () => {
    nextAiResponse = {
      vendorName: 'Plumber Co',
      totalAmount: '900.00',
      // dueDate keeps a different value from any customPaymentDates entry so
      // that `startDate` assertions stay unambiguous. The form's schema
      // requires startDate to be non-empty for save to succeed.
      dueDate: '2025-12-20',
      paymentType: 'recurring',
      frequency: 'custom',
      customPaymentDates: ['2026-01-15', '2026-02-15', '2026-03-15'],
      category: 'repairs',
    };

    renderForm();
    await triggerFakeUpload();

    // Three equal installments of 300.00 derived from 900 / 3.
    await waitFor(() => {
      expect(screen.getAllByDisplayValue('300.00')).toHaveLength(3);
    });
    expect(screen.getByDisplayValue('2026-01-15')).toBeInTheDocument();
    expect(screen.getByDisplayValue('2026-02-15')).toBeInTheDocument();
    expect(screen.getByDisplayValue('2026-03-15')).toBeInTheDocument();
    expect(screen.getByDisplayValue('Plumber Co')).toBeInTheDocument();

    const recurrentRadio = screen.getByTestId('radio-bill-type-recurrent');
    const installmentRadio = screen.getByTestId('radio-payment-structure-installment');
    await waitFor(() => {
      expect(recurrentRadio.getAttribute('aria-checked')).toBe('true');
    });
    expect(installmentRadio.getAttribute('aria-checked')).toBe('true');

    const payload = await clickSaveAndGetPutPayload();
    expect(payload.billType).toBe('recurrent');
    expect(payload.paymentStructure).toBe('installment');
    expect(payload.paymentType).toBe('recurrent');
    expect(payload.paymentCount).toBe('multiple');
    expect(payload.recurrence).toBe(true);
    // The form always flips recurringPaymentsEqual=false when the AI
    // delivers a per-payment list, even when all amounts happen to match.
    // That keeps the custom-payments UI visible and the schedule "custom".
    expect(payload.schedulePayment).toBe('custom');
    expect(payload.recurringPaymentsEqual).toBe(false);
    expect(payload.costs).toEqual(['300.00', '300.00', '300.00']);
    expect(payload.scheduleCustom).toEqual([
      '2026-01-15',
      '2026-02-15',
      '2026-03-15',
    ]);
    expect(payload.totalAmount).toBe('900.00');
    expect(payload.vendor).toBe('Plumber Co');
  });

  it('recurring monthly equal-installment plan (no custom payments) maps to recurrent + installment + monthly', async () => {
    nextAiResponse = {
      vendorName: 'Lease Co',
      totalAmount: '1200.00',
      paymentType: 'recurring installment',
      frequency: 'monthly',
      recurringPaymentAmount: '100.00',
      recurringPaymentsEqual: true,
      dueDate: '2026-02-01',
      category: 'professional_services',
    };

    renderForm();
    await triggerFakeUpload();

    // Recurring amount input is populated from the AI extraction.
    await waitFor(() => {
      expect(screen.getByDisplayValue('100.00')).toBeInTheDocument();
    });
    expect(screen.getByDisplayValue('Lease Co')).toBeInTheDocument();
    expect(screen.getByDisplayValue('2026-02-01')).toBeInTheDocument();

    const recurrentRadio = screen.getByTestId('radio-bill-type-recurrent');
    const installmentRadio = screen.getByTestId('radio-payment-structure-installment');
    await waitFor(() => {
      expect(recurrentRadio.getAttribute('aria-checked')).toBe('true');
    });
    expect(installmentRadio.getAttribute('aria-checked')).toBe('true');

    // No custom payment dates should be rendered for an equal recurring plan.
    expect(screen.queryByDisplayValue('2026-01-15')).not.toBeInTheDocument();

    const payload = await clickSaveAndGetPutPayload();
    expect(payload.billType).toBe('recurrent');
    expect(payload.paymentStructure).toBe('installment');
    expect(payload.paymentType).toBe('recurrent');
    expect(payload.paymentCount).toBe('multiple');
    expect(payload.recurrence).toBe(true);
    // Schedule is preserved (NOT collapsed to "custom") since this isn't a
    // per-payment plan, and the saver expands the recurring amount into a
    // 12-payment cost array.
    expect(payload.schedulePayment).toBe('monthly');
    expect(payload.recurringPaymentsEqual).toBe(true);
    expect(payload.recurringPaymentAmount).toBe('100.00');
    expect(payload.costs).toHaveLength(12);
    expect(payload.costs.every((c: string) => c === '100.00')).toBe(true);
    // scheduleCustom stays empty because this isn't a custom plan.
    expect(payload.scheduleCustom).toEqual([]);
    expect(payload.vendor).toBe('Lease Co');
    expect(payload.startDate).toBe('2026-02-01');
  });

  it('recurring monthly single-payment bill preserves schedulePayment="monthly" on save (no silent flip to yearly)', async () => {
    // AI extracts a recurring bill that is paid in a single amount each
    // cycle (e.g. monthly insurance premium). The form should detect
    // `recurrent + single` and the saver must respect the monthly cadence
    // instead of unconditionally rewriting it to "yearly".
    nextAiResponse = {
      vendorName: 'Monthly Insurance Co',
      totalAmount: '85.00',
      dueDate: '2026-03-01',
      paymentType: 'recurring',
      frequency: 'monthly',
      category: 'insurance',
    };

    renderForm();
    await triggerFakeUpload();

    await waitFor(() => {
      expect(screen.getByDisplayValue('Monthly Insurance Co')).toBeInTheDocument();
    });
    expect(screen.getByDisplayValue('2026-03-01')).toBeInTheDocument();

    const recurrentRadio = screen.getByTestId('radio-bill-type-recurrent');
    const singleRadio = screen.getByTestId('radio-payment-structure-single');
    await waitFor(() => {
      expect(recurrentRadio.getAttribute('aria-checked')).toBe('true');
    });
    expect(singleRadio.getAttribute('aria-checked')).toBe('true');

    const payload = await clickSaveAndGetPutPayload();
    expect(payload.billType).toBe('recurrent');
    expect(payload.paymentStructure).toBe('single');
    // The AI-extracted monthly cadence must survive the save round-trip.
    expect(payload.schedulePayment).toBe('monthly');
    // yearInterval is only relevant for yearly schedules and must not be
    // attached to a monthly recurring single-payment bill.
    expect(payload.yearInterval).toBeUndefined();
    expect(payload.vendor).toBe('Monthly Insurance Co');
    expect(payload.startDate).toBe('2026-03-01');
  });

  it('one-time single-payment bill maps to unique + single and saves the singlePaymentAmount', async () => {
    nextAiResponse = {
      vendorName: 'Hydro Quebec',
      totalAmount: '125.50',
      dueDate: '2026-05-15',
      issueDate: '2026-04-15',
      billNumber: 'INV-9001',
      description: 'Monthly electricity service',
      paymentType: 'one-time',
      category: 'utilities',
    };

    renderForm();
    await triggerFakeUpload();

    // singlePaymentAmount is populated from totalAmount on a one-time bill.
    await waitFor(() => {
      expect(screen.getByDisplayValue('125.50')).toBeInTheDocument();
    });
    expect(screen.getByDisplayValue('Hydro Quebec')).toBeInTheDocument();
    expect(screen.getByDisplayValue('2026-05-15')).toBeInTheDocument();
    expect(screen.getByDisplayValue('2026-04-15')).toBeInTheDocument();
    expect(screen.getByDisplayValue('INV-9001')).toBeInTheDocument();

    const uniqueRadio = screen.getByTestId('radio-bill-type-unique');
    const singleRadio = screen.getByTestId('radio-payment-structure-single');
    await waitFor(() => {
      expect(uniqueRadio.getAttribute('aria-checked')).toBe('true');
    });
    expect(singleRadio.getAttribute('aria-checked')).toBe('true');

    const payload = await clickSaveAndGetPutPayload();
    expect(payload.billType).toBe('unique');
    expect(payload.paymentStructure).toBe('single');
    expect(payload.paymentType).toBe('unique');
    expect(payload.paymentCount).toBe('1');
    expect(payload.recurrence).toBe(false);
    expect(payload.singlePaymentAmount).toBe('125.50');
    expect(payload.totalAmount).toBe('125.50');
    expect(payload.costs).toEqual(['125.50']);
    expect(payload.scheduleCustom).toEqual([]);
    // schedulePayment is stripped from the payload for unique bills.
    expect(payload.schedulePayment).toBeUndefined();
    expect(payload.vendor).toBe('Hydro Quebec');
    expect(payload.startDate).toBe('2026-05-15');
    expect(payload.issueDate).toBe('2026-04-15');
    expect(payload.vendorInvoiceNumber).toBe('INV-9001');
  });

  it('preserves user-filled fields when AI returns malformed/partial data, and stays saveable', async () => {
    // The user has already typed values into the form (modeled here as a
    // bill that ships with non-empty initial values). The AI then returns
    // a partial response: a different vendor and total, no payment-type or
    // frequency hints, no custom payments.
    nextAiResponse = {
      vendorName: 'AI Suggested Vendor',
      totalAmount: '999.00',
      description: 'AI guessed description',
      category: 'utilities',
    };

    renderForm({
      title: 'User Title',
      vendor: 'User Vendor',
      description: 'User notes',
      costs: ['250.00'],
      totalAmount: '250',
      startDate: '2026-01-15',
      category: 'maintenance',
    });

    await triggerFakeUpload();

    // Wait for the extractor's apiRequest to fire so the prefill effect has
    // had a chance to run before we assert "nothing changed for the user".
    await waitFor(() => {
      expect(mockApiRequest).toHaveBeenCalledWith(
        'POST',
        '/api/bills/extract-data',
        expect.anything()
      );
    });

    // User-filled non-structural fields are preserved exactly as entered –
    // setIfEmpty must not overwrite a non-empty existing value.
    expect(screen.getByDisplayValue('User Vendor')).toBeInTheDocument();
    expect(screen.getByDisplayValue('User Title')).toBeInTheDocument();
    expect(screen.getByDisplayValue('User notes')).toBeInTheDocument();
    expect(screen.getByDisplayValue('250.00')).toBeInTheDocument();
    expect(screen.getByDisplayValue('2026-01-15')).toBeInTheDocument();

    // The AI's competing values must NOT have leaked into the form.
    expect(screen.queryByDisplayValue('AI Suggested Vendor')).not.toBeInTheDocument();
    expect(screen.queryByDisplayValue('999.00')).not.toBeInTheDocument();
    expect(screen.queryByDisplayValue('AI guessed description')).not.toBeInTheDocument();

    // Structure stays unique + single (the partial AI response had no
    // paymentType, frequency, or customPayments to flip the structure).
    const uniqueRadio = screen.getByTestId('radio-bill-type-unique');
    const singleRadio = screen.getByTestId('radio-payment-structure-single');
    expect(uniqueRadio.getAttribute('aria-checked')).toBe('true');
    expect(singleRadio.getAttribute('aria-checked')).toBe('true');

    // Save still works and the user's values round-trip.
    const payload = await clickSaveAndGetPutPayload();
    expect(payload.vendor).toBe('User Vendor');
    expect(payload.title).toBe('User Title');
    expect(payload.description).toBe('User notes');
    expect(payload.category).toBe('maintenance');
    expect(payload.startDate).toBe('2026-01-15');
    expect(payload.singlePaymentAmount).toBe('250.00');
    expect(payload.costs).toEqual(['250.00']);
    expect(payload.totalAmount).toBe('250.00');
    expect(payload.billType).toBe('unique');
    expect(payload.paymentStructure).toBe('single');
  });
});
