import { describe, it, expect, beforeEach, jest } from '@jest/globals';
import { render, screen, waitFor, act, fireEvent } from '@testing-library/react';
import '@testing-library/jest-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import React, { ReactNode } from 'react';
import ModularBillForm from '../../../client/src/components/bill-management/ModularBillForm';

type ApiCall = { method: string; url: string; data?: unknown };
const apiCalls: ApiCall[] = [];
const mockApiRequest = jest.fn(
  async (method: string, url: string, data?: unknown) => {
    apiCalls.push({ method, url, data });

    if (url === '/api/bills/extract-data') {
      return {
        ok: true,
        status: 200,
        json: async () => ({
          success: true,
          data: {
            vendorName: 'Roofing Inc',
            totalAmount: '1000.00',
            // dueDate kept distinct from any customPayments date so that
            // assertions on the installment date inputs aren't ambiguous.
            dueDate: '2026-03-15',
            description: 'Roof repair installment plan',
            paymentType: 'one-time',
            category: 'repairs',
            customPayments: [
              { amount: '400.00', date: '2026-04-01', description: 'Deposit' },
              { amount: '300.00', date: '2026-05-01' },
              { amount: '300.00', date: '2026-06-01' },
            ],
          },
          metadata: { confidence: 0.92 },
        }),
      };
    }

    if (method === 'PUT' && url.startsWith('/api/bills/')) {
      return {
        ok: true,
        status: 200,
        json: async () => ({
          id: 'auto-gen-test',
          billNumber: 'BILL-001',
          buildingId: 'building-test',
        }),
      };
    }

    return { ok: true, status: 200, json: async () => ({}) };
  }
);

jest.mock('@/hooks/use-language', () => ({
  useLanguage: () => ({
    language: 'en',
    setLanguage: jest.fn(),
    toggleLanguage: jest.fn(),
    t: (key: string) => key,
  }),
}));

jest.mock('@/hooks/use-toast', () => ({
  useToast: () => ({ toast: jest.fn() }),
}));

jest.mock('@/lib/queryClient', () => ({
  apiRequest: (...args: unknown[]) => (mockApiRequest as any)(...args),
  queryClient: { invalidateQueries: jest.fn() },
}));

jest.mock('@/components/document-management', () => ({
  SharedUploader: (props: any) => (
    <button
      type="button"
      data-testid="trigger-fake-upload"
      onClick={() => {
        const file = new File(['hello'], 'invoice.pdf', { type: 'application/pdf' });
        props.onDocumentChange(file, null);
      }}
    >
      upload
    </button>
  ),
}));

jest.mock('@/components/common/AttachedFileSection', () => ({
  AttachedFileSection: () => null,
}));

jest.mock('@/components/common/StandardFormGrid', () => ({
  StandardFormGrid: ({ children }: { children: ReactNode }) => <div>{children}</div>,
}));

jest.mock(
  '../../../client/src/components/bill-management/ConfidenceIndicator',
  () => ({ ConfidenceIndicator: () => null })
);

if (typeof Element.prototype.hasPointerCapture !== 'function') {
  (Element.prototype as any).hasPointerCapture = function () { return false; };
}
if (typeof Element.prototype.scrollIntoView !== 'function') {
  (Element.prototype as any).scrollIntoView = function () {};
}
if (typeof URL.createObjectURL !== 'function') {
  (URL as any).createObjectURL = () => 'blob:mock';
}

function renderForm() {
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: { retry: false },
      mutations: { retry: false },
    },
  });
  // Use an auto-generated bill so the GeminiBillExtractor mounts on the
  // (default) manual tab as soon as a file is uploaded. The Tabs component
  // is skipped when a bill prop is provided, which avoids relying on Radix
  // pointer events that jsdom does not fully simulate.
  const autoGeneratedBill: any = {
    id: 'auto-gen-test',
    buildingId: 'building-test',
    title: '',
    vendor: '',
    paymentType: 'unique',
    paymentCount: '1',
    // Seeded with a leftover `'0.00'` cost — the exact scenario described in
    // task #508. Before the schema scoping fix, this populated
    // `singlePaymentAmount = '0.00'` and the field-level `> 0` refinement
    // tripped on save even after the AI flipped the bill to installment
    // (where singlePaymentAmount is hidden / unused). Keeping the value here
    // is what makes this test lock in the regression fix end-to-end: a
    // regression that re-enables the rule for inactive structures will
    // surface as the save assertions below failing because no PUT is fired.
    costs: ['0.00'],
    totalAmount: '0.00',
    startDate: '',
    isAutoGenerated: true,
    status: 'draft',
    category: 'other',
  };
  return render(
    <QueryClientProvider client={queryClient}>
      <ModularBillForm bill={autoGeneratedBill} buildingId="building-test" />
    </QueryClientProvider>
  );
}

/**
 * End-to-end coverage for the installment-detection regression fix.
 *
 * `convertBillResponseToFormData` was patched (task #369) so that an AI
 * response carrying only a `customPayments` array — without the older
 * `customPaymentDates` array or `frequency: 'custom'` flag — still flips the
 * bill into recurrent + installment mode and preserves the per-payment
 * amounts and dates. The unit test verifies the converter in isolation; this
 * test exercises the full extractor → form prefill → save flow so a
 * regression elsewhere in the extraction pipeline (response parsing, schema
 * mapping, mutation wiring) still surfaces as a failing assertion.
 */
describe('GeminiBillExtractor → ModularBillForm installment plan integration', () => {
  let originalFetch: typeof globalThis.fetch;
  let originalConsoleError: typeof console.error;

  beforeEach(() => {
    apiCalls.length = 0;
    mockApiRequest.mockClear();

    // ModularBillForm calls fetch directly to attach the uploaded document to
    // the existing auto-generated bill. We're not testing that path here, so
    // stub it to avoid jsdom "Only absolute URLs are supported" noise.
    originalFetch = globalThis.fetch;
    (globalThis as any).fetch = jest.fn(async () => ({
      ok: true,
      status: 200,
      text: async () => '',
      json: async () => ({ id: 'doc-1' }),
    }));

    originalConsoleError = console.error;
  });

  afterEach(() => {
    (globalThis as any).fetch = originalFetch;
    console.error = originalConsoleError;
  });

  it('flips the bill to recurrent installment, preserves per-payment data, and saves it', async () => {
    renderForm();

    // Trigger the fake upload, which mounts the (real) GeminiBillExtractor.
    // The extractor will POST /api/bills/extract-data via the mocked
    // apiRequest, and our mock returns an AI response that contains only a
    // `customPayments` array (no `customPaymentDates`, no `frequency: custom`).
    await act(async () => {
      fireEvent.click(await screen.findByTestId('trigger-fake-upload'));
    });

    // Wait for the extractor to fire the extract-data call.
    await waitFor(() => {
      expect(
        apiCalls.some(c => c.url === '/api/bills/extract-data' && c.method === 'POST')
      ).toBe(true);
    });

    // The form should now show all three custom payment amounts. These inputs
    // only render when paymentStructure === 'installment' AND either
    // schedulePayment === 'custom' or recurringPaymentsEqual === false – i.e.
    // they are proof that the extractor flipped the bill into the installment
    // branch even though the AI response did not include the legacy signals.
    await waitFor(() => {
      expect(screen.getByDisplayValue('400.00')).toBeInTheDocument();
    });
    expect(screen.getAllByDisplayValue('300.00')).toHaveLength(2);

    // Custom payment dates should also be preserved (rendered into date
    // inputs, which only show up when schedulePayment === 'custom').
    expect(screen.getByDisplayValue('2026-04-01')).toBeInTheDocument();
    expect(screen.getByDisplayValue('2026-05-01')).toBeInTheDocument();
    expect(screen.getByDisplayValue('2026-06-01')).toBeInTheDocument();

    // Vendor was empty before extraction → AI value populates it.
    expect(screen.getByDisplayValue('Roofing Inc')).toBeInTheDocument();

    // The recurrent radio should now be selected (billType = 'recurrent') and
    // the installment radio should be selected (paymentStructure = 'installment').
    const recurrentRadio = screen.getByTestId('radio-bill-type-recurrent');
    const installmentRadio = screen.getByTestId('radio-payment-structure-installment');
    await waitFor(() => {
      expect(recurrentRadio.getAttribute('aria-checked')).toBe('true');
    });
    expect(installmentRadio.getAttribute('aria-checked')).toBe('true');

    // Now save the bill and assert the payload sent to the backend matches
    // the installment plan – costs and scheduleCustom should mirror the AI
    // customPayments rather than collapsing to a single-payment bill.
    const saveButton = await screen.findByTestId('button-update-bill');
    await act(async () => {
      fireEvent.click(saveButton);
    });

    await waitFor(() => {
      expect(
        apiCalls.some(c => c.method === 'PUT' && c.url.startsWith('/api/bills/'))
      ).toBe(true);
    });

    const putCall = apiCalls.find(
      c => c.method === 'PUT' && c.url.startsWith('/api/bills/')
    )!;
    const payload = putCall.data as any;

    expect(payload.billType).toBe('recurrent');
    expect(payload.paymentStructure).toBe('installment');
    expect(payload.paymentType).toBe('recurrent');
    expect(payload.paymentCount).toBe('multiple');
    expect(payload.recurrence).toBe(true);
    expect(payload.schedulePayment).toBe('custom');
    expect(payload.recurringPaymentsEqual).toBe(false);

    // Per-payment amounts and dates round-tripped through the form intact.
    expect(payload.costs).toEqual(['400.00', '300.00', '300.00']);
    expect(payload.scheduleCustom).toEqual([
      '2026-04-01',
      '2026-05-01',
      '2026-06-01',
    ]);

    // totalAmount is recomputed from the custom payments at save time.
    expect(payload.totalAmount).toBe('1000.00');
    expect(payload.vendor).toBe('Roofing Inc');
  });
});
