import { describe, it, expect, beforeEach, jest } from '@jest/globals';
import { render, screen, waitFor, act, fireEvent } from '@testing-library/react';
import '@testing-library/jest-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import React, { ReactNode } from 'react';
import ModularBillForm from '../../../client/src/components/bill-management/ModularBillForm';

const mockApiRequest = jest.fn();

jest.mock('@/hooks/use-language', () => ({
  useLanguage: () => ({
    language: 'en',
    setLanguage: jest.fn(),
    toggleLanguage: jest.fn(),
    t: (key: string) => key,
  }),
}));

jest.mock('@/hooks/use-toast', () => ({
  useToast: () => ({ toast: jest.fn() }),
}));

jest.mock('@/lib/queryClient', () => ({
  apiRequest: (...args: unknown[]) => mockApiRequest(...args),
  queryClient: { invalidateQueries: jest.fn() },
}));

// Capture callbacks/props handed down to AI components so the test can drive
// the AI extraction flow without going through the real Gemini service.
const capturedExtractor: { onExtractionComplete?: (data: any) => void } = {};

jest.mock('@/components/document-management', () => ({
  SharedUploader: (props: any) => {
    return (
      <button
        type="button"
        data-testid="trigger-fake-upload"
        onClick={() => {
          const file = new File(['hello'], 'invoice.pdf', { type: 'application/pdf' });
          props.onDocumentChange(file, null);
        }}
      >
        upload
      </button>
    );
  },
}));

jest.mock(
  '../../../client/src/components/bill-management/GeminiBillExtractor',
  () => ({
    GeminiBillExtractor: (props: any) => {
      capturedExtractor.onExtractionComplete = props.onExtractionComplete;
      return null;
    },
  })
);

jest.mock('@/components/common/AttachedFileSection', () => ({
  AttachedFileSection: () => null,
}));

jest.mock('@/components/common/StandardFormGrid', () => ({
  StandardFormGrid: ({ children }: { children: ReactNode }) => <div>{children}</div>,
}));

jest.mock(
  '../../../client/src/components/bill-management/ConfidenceIndicator',
  () => ({ ConfidenceIndicator: () => null })
);

if (typeof Element.prototype.hasPointerCapture !== 'function') {
  (Element.prototype as any).hasPointerCapture = function () { return false; };
}
if (typeof Element.prototype.scrollIntoView !== 'function') {
  (Element.prototype as any).scrollIntoView = function () {};
}
if (typeof URL.createObjectURL !== 'function') {
  (URL as any).createObjectURL = () => 'blob:mock';
}

function renderForm() {
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: { retry: false },
      mutations: { retry: false },
    },
  });
  // Render with an auto-generated bill so the GeminiBillExtractor mounts on
  // the (default) manual tab as soon as a file is uploaded. This lets us
  // exercise the AI extraction flow without depending on Radix Tabs pointer
  // events (which jsdom does not fully simulate).
  const autoGeneratedBill: any = {
    id: 'auto-gen-test',
    buildingId: 'building-test',
    title: '',
    vendor: '',
    paymentType: 'unique',
    costs: ['0.00'],
    totalAmount: '0.00',
    startDate: '',
    isAutoGenerated: true,
  };
  return render(
    <QueryClientProvider client={queryClient}>
      <ModularBillForm bill={autoGeneratedBill} buildingId="building-test" />
    </QueryClientProvider>
  );
}

describe('ModularBillForm – non-destructive AI pre-fill', () => {
  let originalFetch: typeof globalThis.fetch;
  let originalConsoleError: typeof console.error;

  beforeEach(() => {
    capturedExtractor.onExtractionComplete = undefined;
    mockApiRequest.mockReset();
    mockApiRequest.mockResolvedValue({ ok: true, json: async () => ({}) });

    // ModularBillForm calls fetch directly to attach uploaded documents to
    // existing bills. We're not testing that path here, so stub it to avoid
    // jsdom "Only absolute URLs are supported" noise.
    originalFetch = globalThis.fetch;
    (globalThis as any).fetch = jest.fn(async () => ({
      ok: true,
      status: 200,
      text: async () => '',
      json: async () => ({ id: 'doc-1' }),
    }));

    originalConsoleError = console.error;
    console.error = jest.fn();
  });

  afterEach(() => {
    (globalThis as any).fetch = originalFetch;
    console.error = originalConsoleError;
  });

  it('does not overwrite a vendor invoice number the user already typed when AI extraction runs', async () => {
    renderForm();

    // User types a vendor invoice number (this marks the field as touched)
    const invoiceInput = await screen.findByTestId('input-vendor-invoice-number');
    await act(async () => {
      fireEvent.change(invoiceInput, { target: { value: 'USER-TYPED-001' } });
      fireEvent.blur(invoiceInput);
    });
    expect((invoiceInput as HTMLInputElement).value).toBe('USER-TYPED-001');

    // User uploads a document, which makes the GeminiBillExtractor render
    const trigger = await screen.findByTestId('trigger-fake-upload');
    await act(async () => {
      fireEvent.click(trigger);
    });

    await waitFor(() => {
      expect(capturedExtractor.onExtractionComplete).toBeDefined();
    });

    // Simulate AI returning a different invoice number AND a vendor name
    await act(async () => {
      capturedExtractor.onExtractionComplete!({
        success: true,
        confidence: 0.95,
        formData: {
          title: 'AI Extracted Title',
          vendor: 'AI Vendor Co',
          vendorInvoiceNumber: 'AI-OVERWRITE-999',
          totalAmount: '500.00',
          singlePaymentAmount: '500.00',
          startDate: '2026-06-01',
          issueDate: '2026-05-01',
          billType: 'unique',
          paymentStructure: 'single',
          paymentCount: '1',
          recurrence: false,
          category: 'utilities',
          customPayments: [],
        },
      });
    });

    // Touched field is preserved – AI must not clobber it
    await waitFor(() => {
      expect((invoiceInput as HTMLInputElement).value).toBe('USER-TYPED-001');
    });

    // Empty / untouched fields ARE populated by the AI
    expect(screen.getByDisplayValue('AI Vendor Co')).toBeInTheDocument();
    expect(screen.getByDisplayValue('AI Extracted Title')).toBeInTheDocument();
  });

  it('still pre-fills empty fields when re-running AI extraction after the user only touched some fields', async () => {
    renderForm();

    // Touch ONLY the invoice number
    const invoiceInput = await screen.findByTestId('input-vendor-invoice-number');
    await act(async () => {
      fireEvent.change(invoiceInput, { target: { value: 'KEEP-ME' } });
      fireEvent.blur(invoiceInput);
    });

    // First AI extraction
    await act(async () => {
      fireEvent.click(await screen.findByTestId('trigger-fake-upload'));
    });
    await waitFor(() => expect(capturedExtractor.onExtractionComplete).toBeDefined());

    await act(async () => {
      capturedExtractor.onExtractionComplete!({
        success: true,
        confidence: 0.9,
        formData: {
          title: 'First Title',
          vendor: 'First Vendor',
          vendorInvoiceNumber: 'AI-FIRST',
          totalAmount: '100.00',
          singlePaymentAmount: '100.00',
          startDate: '2026-01-01',
          billType: 'unique',
          paymentStructure: 'single',
          paymentCount: '1',
          recurrence: false,
          category: 'utilities',
          customPayments: [],
        },
      });
    });

    // First extraction should have populated the empty fields
    await waitFor(() => {
      expect(screen.getByDisplayValue('First Vendor')).toBeInTheDocument();
    });
    expect(screen.getByDisplayValue('First Title')).toBeInTheDocument();
    // But it must not have overwritten the touched invoice number
    expect((invoiceInput as HTMLInputElement).value).toBe('KEEP-ME');

    // Re-run AI extraction with completely different data (simulating
    // re-uploading a different document or a re-extraction).
    await act(async () => {
      capturedExtractor.onExtractionComplete!({
        success: true,
        confidence: 0.9,
        formData: {
          title: 'Second Title – should NOT overwrite',
          vendor: 'Second Vendor – should NOT overwrite',
          vendorInvoiceNumber: 'AI-SECOND',
          totalAmount: '999.00',
          singlePaymentAmount: '999.00',
          startDate: '2026-12-31',
          billType: 'unique',
          paymentStructure: 'single',
          paymentCount: '1',
          recurrence: false,
          category: 'utilities',
          customPayments: [],
        },
      });
    });

    // After re-running extraction, fields populated by the earlier extraction
    // remain intact (they're no longer empty), and the touched invoice number
    // is also preserved. This guards the non-destructive pre-fill behaviour.
    await waitFor(() => {
      expect(screen.getByDisplayValue('First Vendor')).toBeInTheDocument();
    });
    expect(screen.getByDisplayValue('First Title')).toBeInTheDocument();
    expect((invoiceInput as HTMLInputElement).value).toBe('KEEP-ME');
    expect(screen.queryByDisplayValue('Second Vendor – should NOT overwrite')).toBeNull();
    expect(screen.queryByDisplayValue('Second Title – should NOT overwrite')).toBeNull();
  });
});
