/**
 * @jest-environment node
 *
 * End-to-end tests for DocumentInlineViewer, driven against the running
 * Koveo dev server with real Chromium. Fails loudly (no silent skip) when
 * Chromium or the app is unavailable so CI cannot mask regressions.
 */

import { describe, it, expect, beforeAll, afterAll } from '@jest/globals';
import path from 'node:path';
import fs from 'node:fs';
import os from 'node:os';
import puppeteer, { type Browser, type Page, type CDPSession } from 'puppeteer';

const BASE_URL = (process.env.E2E_BASE_URL || 'http://localhost:5000').replace(/\/+$/, '');
const TEST_EMAIL = process.env.E2E_USER_EMAIL || 'marie.tremblay@demo.koveo.ca';
const TEST_PASSWORD = process.env.E2E_USER_PASSWORD || 'demo123456';

function findChromium(): string | null {
  const fromEnv = process.env.PUPPETEER_EXECUTABLE_PATH;
  if (fromEnv && fs.existsSync(fromEnv)) return fromEnv;
  const candidates = [
    '/nix/store/zi4f80l169xlmivz8vja8wlphq74qqk0-chromium-125.0.6422.141/bin/chromium',
    '/usr/bin/chromium',
    '/usr/bin/chromium-browser',
    '/usr/bin/google-chrome',
    '/usr/bin/google-chrome-stable',
  ];
  for (const c of candidates) {
    if (fs.existsSync(c)) return c;
  }
  return null;
}

function buildPdfBuffer(): Buffer {
  const pdf =
    '%PDF-1.4\n' +
    '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n' +
    '2 0 obj\n<< /Type /Pages /Count 1 /Kids [3 0 R] >>\nendobj\n' +
    '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 144] ' +
    '/Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n' +
    '4 0 obj\n<< /Length 55 >>\nstream\n' +
    'BT /F1 18 Tf 20 100 Td (Inline viewer e2e PDF) Tj ET\n' +
    'endstream\nendobj\n' +
    '5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n' +
    'xref\n0 6\n' +
    '0000000000 65535 f \n0000000010 00000 n \n0000000060 00000 n \n' +
    '0000000111 00000 n \n0000000211 00000 n \n0000000316 00000 n \n' +
    'trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n390\n%%EOF\n';
  return Buffer.from(pdf, 'utf-8');
}

class AppApi {
  private cookie = '';

  async login(email: string, password: string): Promise<void> {
    const res = await fetch(`${BASE_URL}/api/auth/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email, password }),
    });
    if (!res.ok) {
      throw new Error(`API login failed: ${res.status} ${await res.text()}`);
    }
    const setCookie =
      res.headers.get('set-cookie') ??
      (res.headers as unknown as { getSetCookie?: () => string[] })
        .getSetCookie?.()
        ?.join(', ') ??
      '';
    if (!setCookie) throw new Error('API login did not return a session cookie');
    this.cookie = setCookie
      .split(/,(?=[^;]+=)/)
      .map((c) => c.split(';')[0].trim())
      .filter(Boolean)
      .join('; ');
  }

  get sessionCookie(): string {
    if (!this.cookie) throw new Error('AppApi.login must be called first');
    return this.cookie;
  }

  async get<T>(url: string): Promise<T> {
    const res = await fetch(`${BASE_URL}${url}`, {
      headers: { Cookie: this.sessionCookie },
    });
    if (!res.ok) throw new Error(`GET ${url} failed: ${res.status}`);
    return (await res.json()) as T;
  }

  async findBuildingId(): Promise<string> {
    const body = await this.get<
      Array<{ id: string }> | { buildings: Array<{ id: string }> }
    >('/api/manager/buildings');
    const list = Array.isArray(body) ? body : body.buildings;
    if (!Array.isArray(list) || list.length === 0) {
      throw new Error('No buildings accessible to the test user');
    }
    return list[0].id;
  }

  async findOrgIdForBuilding(buildingId: string): Promise<string> {
    const body = await this.get<
      | Array<{ id: string; organizationId: string }>
      | { buildings: Array<{ id: string; organizationId: string }> }
    >('/api/manager/buildings');
    const list = Array.isArray(body) ? body : body.buildings;
    const found = list.find((b) => b.id === buildingId);
    if (!found?.organizationId) {
      throw new Error(`Could not resolve organization for building ${buildingId}`);
    }
    return found.organizationId;
  }

  async findBillId(buildingId: string): Promise<string> {
    const bills = await this.get<Array<{ id: string; isAutoGenerated?: boolean }>>(
      `/api/bills?buildingId=${encodeURIComponent(buildingId)}&limit=25`
    );
    const usable = bills.find((b) => !b.isAutoGenerated) ?? bills[0];
    if (!usable) throw new Error(`No bills found for building ${buildingId}`);
    return usable.id;
  }

  async uploadDocument(opts: {
    pdf: Buffer;
    name: string;
    fileName: string;
    buildingId: string;
    attachedToType?: 'bill';
    attachedToId?: string;
  }): Promise<{ id: string; name: string; fileName: string }> {
    const form = new FormData();
    const blob = new Blob([new Uint8Array(opts.pdf)], { type: 'application/pdf' });
    form.append('file', blob, opts.fileName);
    form.append('name', opts.name);
    form.append('documentType', 'other');
    form.append('buildingId', opts.buildingId);
    if (opts.attachedToType && opts.attachedToId) {
      form.append('attachedToType', opts.attachedToType);
      form.append('attachedToId', opts.attachedToId);
    }
    const res = await fetch(`${BASE_URL}/api/documents/upload`, {
      method: 'POST',
      headers: { Cookie: this.sessionCookie },
      body: form,
    });
    if (!res.ok) {
      throw new Error(`Document upload failed: ${res.status} ${await res.text()}`);
    }
    const body = (await res.json()) as {
      document: { id: string; name: string; fileName: string };
    };
    return body.document;
  }
}

let chromium: string;
let browser: Browser;
let browserCdp: CDPSession;
let downloadDir: string;
let api: AppApi;
let buildingId: string;
let billId: string;
let orgId: string;
let standaloneDoc: { id: string; name: string; fileName: string };
let billDoc: { id: string; name: string; fileName: string };

beforeAll(async () => {
  const found = findChromium();
  if (!found) {
    throw new Error(
      'Chromium executable not found. Install Chromium or set ' +
        'PUPPETEER_EXECUTABLE_PATH. This e2e test is mandatory and is not ' +
        'silently skipped to avoid masking regressions in CI.'
    );
  }
  chromium = found;

  let healthOk = false;
  try {
    const probe = await fetch(`${BASE_URL}/api/health`, {
      signal: AbortSignal.timeout(5000),
    });
    healthOk = probe.ok;
  } catch {
    healthOk = false;
  }
  if (!healthOk) {
    throw new Error(
      `Koveo app is not reachable at ${BASE_URL}/api/health. Start the dev ` +
        'server or set E2E_BASE_URL before running the e2e suite.'
    );
  }

  api = new AppApi();
  await api.login(TEST_EMAIL, TEST_PASSWORD);

  buildingId = await api.findBuildingId();
  orgId = await api.findOrgIdForBuilding(buildingId);
  billId = await api.findBillId(buildingId);

  const pdf = buildPdfBuffer();
  const stamp = Date.now();
  standaloneDoc = await api.uploadDocument({
    pdf,
    name: `E2E Inline Viewer Doc ${stamp}`,
    fileName: `e2e-inline-${stamp}.pdf`,
    buildingId,
  });
  billDoc = await api.uploadDocument({
    pdf,
    name: `E2E Inline Viewer Bill Doc ${stamp}`,
    fileName: `e2e-inline-bill-${stamp}.pdf`,
    buildingId,
    attachedToType: 'bill',
    attachedToId: billId,
  });

  downloadDir = fs.mkdtempSync(path.join(os.tmpdir(), 'inline-viewer-e2e-'));
  browser = await puppeteer.launch({
    headless: true,
    executablePath: chromium,
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--disable-gpu',
    ],
  });
  browserCdp = await browser.target().createCDPSession();
  await browserCdp.send('Browser.setDownloadBehavior', {
    behavior: 'allow',
    downloadPath: downloadDir,
    eventsEnabled: true,
  });
}, 90_000);

afterAll(async () => {
  if (browser) await browser.close().catch(() => undefined);
  if (downloadDir && fs.existsSync(downloadDir)) {
    fs.rmSync(downloadDir, { recursive: true, force: true });
  }
}, 30_000);

async function newAuthedPage(): Promise<Page> {
  const page = await browser.newPage();
  await page.setViewport({ width: 1400, height: 900 });
  await page.evaluateOnNewDocument(() => {
    (window as unknown as { __popupCount: number }).__popupCount = 0;
    const original = window.open;
    window.open = function (...args: unknown[]) {
      (window as unknown as { __popupCount: number }).__popupCount += 1;
      return original.apply(window, args as Parameters<typeof window.open>);
    } as typeof window.open;
  });
  await page.goto(`${BASE_URL}/auth/login`, { waitUntil: 'domcontentloaded' });
  await page.waitForSelector('[data-testid=input-email]', { visible: true });
  await page.type('[data-testid=input-email]', TEST_EMAIL);
  await page.type('[data-testid=input-password]', TEST_PASSWORD);
  await Promise.all([
    page
      .waitForNavigation({ waitUntil: 'networkidle2', timeout: 30_000 })
      .catch(() => undefined),
    page.click('button[type=submit]'),
  ]);
  await page.waitForFunction(
    () => !window.location.pathname.startsWith('/auth/login'),
    { timeout: 30_000 }
  );
  return page;
}

async function openDocumentCardInlineViewer(
  page: Page,
  documentId: string
): Promise<void> {
  await page.waitForSelector(`[data-testid="document-card-${documentId}"]`, {
    timeout: 30_000,
  });
  const viewActionSelector = `[data-testid="view-document-${documentId}"]`;
  await page.waitForSelector(viewActionSelector, { timeout: 15_000 });
  await page.evaluate((sel) => {
    const el = document.querySelector(sel) as HTMLElement | null;
    if (!el) throw new Error(`view action button ${sel} not in DOM`);
    el.scrollIntoView({ block: 'center' });
    el.click();
  }, viewActionSelector);
  await page.waitForSelector('[data-testid=button-view-document-file]', {
    visible: true,
    timeout: 15_000,
  });
  await page.click('[data-testid=button-view-document-file]');
}

async function assertInlineViewerOpen(page: Page, expectedFileUrl: string): Promise<void> {
  await page.waitForSelector('[data-testid=iframe-inline-viewer]', {
    visible: true,
    timeout: 15_000,
  });
  const src = await page.$eval(
    '[data-testid=iframe-inline-viewer]',
    (el) => (el as HTMLIFrameElement).getAttribute('src')
  );
  expect(src).toBe(expectedFileUrl);
  await page.waitForSelector('[data-testid=button-inline-viewer-download]', {
    visible: true,
  });
  await page.waitForSelector('[data-testid=button-inline-viewer-close]', {
    visible: true,
  });

  const fetched = await page.evaluate(async (u: string) => {
    const r = await fetch(u, { credentials: 'include' });
    const buf = await r.arrayBuffer();
    return {
      ok: r.ok,
      status: r.status,
      type: r.headers.get('Content-Type'),
      size: buf.byteLength,
    };
  }, expectedFileUrl);
  expect(fetched.ok).toBe(true);
  expect(fetched.status).toBe(200);
  expect(fetched.type).toMatch(/application\/pdf/);
  expect(fetched.size).toBeGreaterThan(100);

  const popups = await page.evaluate(
    () => (window as unknown as { __popupCount?: number }).__popupCount ?? 0
  );
  expect(popups).toBe(0);
}

async function waitForDownloadedFile(
  before: Set<string>,
  expectedSubstring: string,
  timeoutMs = 20_000
): Promise<string> {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    const current = fs
      .readdirSync(downloadDir)
      .filter((f) => !before.has(f) && !f.endsWith('.crdownload'));
    const match = current.find((f) => f.includes(expectedSubstring));
    if (match) {
      const stat = fs.statSync(path.join(downloadDir, match));
      if (stat.size > 0) return match;
    }
    await new Promise((r) => setTimeout(r, 150));
  }
  throw new Error(
    `No downloaded file containing "${expectedSubstring}" appeared within ${timeoutMs}ms`
  );
}

describe('DocumentInlineViewer (real browser, real app)', () => {
  it('opens the inline viewer iframe and renders a PDF for a building document', async () => {
    const page = await newAuthedPage();
    try {
      await page.goto(
        `${BASE_URL}/manager/buildings/${buildingId}/documents`,
        { waitUntil: 'networkidle2', timeout: 30_000 }
      );
      await openDocumentCardInlineViewer(page, standaloneDoc.id);
      await assertInlineViewerOpen(page, `/api/documents/${standaloneDoc.id}/file`);
    } finally {
      await page.close();
    }
  }, 120_000);

  it('clicking Download in the viewer saves a real file to disk', async () => {
    const page = await newAuthedPage();
    try {
      await page.goto(
        `${BASE_URL}/manager/buildings/${buildingId}/documents`,
        { waitUntil: 'networkidle2', timeout: 30_000 }
      );
      await openDocumentCardInlineViewer(page, standaloneDoc.id);
      await page.waitForSelector('[data-testid=iframe-inline-viewer]', {
        visible: true,
      });

      const before = new Set(fs.readdirSync(downloadDir));
      await page.click('[data-testid=button-inline-viewer-download]');

      const saved = await waitForDownloadedFile(before, standaloneDoc.fileName);
      const bytes = fs.readFileSync(path.join(downloadDir, saved));
      expect(bytes.length).toBeGreaterThan(100);
      expect(bytes.slice(0, 5).toString('utf-8')).toBe('%PDF-');
    } finally {
      await page.close();
    }
  }, 120_000);

  it('Escape key closes the inline viewer dialog', async () => {
    const page = await newAuthedPage();
    try {
      await page.goto(
        `${BASE_URL}/manager/buildings/${buildingId}/documents`,
        { waitUntil: 'networkidle2', timeout: 30_000 }
      );
      await openDocumentCardInlineViewer(page, standaloneDoc.id);
      await page.waitForSelector('[data-testid=iframe-inline-viewer]', {
        visible: true,
      });
      await page.keyboard.press('Escape');
      await page.waitForSelector('[data-testid=iframe-inline-viewer]', {
        hidden: true,
        timeout: 10_000,
      });
      expect(await page.$('[data-testid=iframe-inline-viewer]')).toBeNull();
    } finally {
      await page.close();
    }
  }, 120_000);

  it('opens the inline viewer for a document attached to a bill', async () => {
    const page = await newAuthedPage();
    try {
      await page.goto(
        `${BASE_URL}/manager/bills?organization=${orgId}&building=${buildingId}`,
        { waitUntil: 'networkidle2', timeout: 30_000 }
      );

      const editBtn = `[data-testid="button-edit-bill-${billId}"]`;
      await page.waitForSelector(editBtn, { timeout: 30_000 });
      await page.click(editBtn);

      // The edit dialog renders attached documents via AttachedFileSection,
      // each with a duplicate `button-view-file` testId. Scope by row text
      // to find the row matching our uploaded fixture file name.
      await page.waitForFunction(
        (fileName: string) => {
          const buttons = Array.from(
            document.querySelectorAll('[data-testid="button-view-file"]')
          );
          return buttons.some((btn) => {
            let row: Element | null = btn;
            for (let i = 0; i < 6 && row; i += 1) {
              row = row.parentElement;
              if (row && row.textContent?.includes(fileName)) return true;
            }
            return false;
          });
        },
        { timeout: 30_000 },
        billDoc.fileName
      );
      const clicked = await page.evaluate((fileName: string) => {
        const buttons = Array.from(
          document.querySelectorAll<HTMLButtonElement>(
            '[data-testid="button-view-file"]'
          )
        );
        for (const btn of buttons) {
          let row: Element | null = btn;
          for (let i = 0; i < 6 && row; i += 1) {
            row = row.parentElement;
            if (row && row.textContent?.includes(fileName)) {
              btn.scrollIntoView({ block: 'center' });
              btn.click();
              return true;
            }
          }
        }
        return false;
      }, billDoc.fileName);
      expect(clicked).toBe(true);

      await assertInlineViewerOpen(page, `/api/documents/${billDoc.id}/file`);
    } finally {
      await page.close();
    }
  }, 120_000);
});
