import { useState, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { apiRequest } from '@/lib/queryClient';
import { useLanguage } from '@/hooks/use-language';
import { useToast } from '@/hooks/use-toast';
import type { Bill, Document } from '@shared/schema';
import type { UploadContext } from '@shared/config/upload-config';

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
  FormDescription,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Calendar, Sparkles, Upload, FileText, Lightbulb, X } from 'lucide-react';
import { SharedUploader } from '@/components/document-management';
import { GeminiBillExtractor } from './GeminiBillExtractor';
import { AttachedFileSection } from '@/components/common/AttachedFileSection';

interface AutoGeneratedBillWorkflowProps {
  autoGeneratedBill: Bill | null;
  isOpen: boolean;
  onClose: () => void;
  onSuccess?: (billId: string) => void;
}

const newBillSchema = z.object({
  title: z.string().min(1, 'Title is required').max(200, 'Title must be less than 200 characters'),
  description: z.string().max(1000, 'Description must be less than 1000 characters').optional(),
  category: z.enum([
    'insurance',
    'maintenance',
    'salary',
    'utilities',
    'cleaning',
    'security',
    'landscaping',
    'professional_services',
    'administration',
    'repairs',
    'supplies',
    'taxes',
    'technology',
    'reserves',
    'other',
  ]),
  vendor: z.string().max(150, 'Vendor name must be less than 150 characters').optional(),
  totalAmount: z.string().min(1, 'Amount is required').refine((val) => {
    const num = parseFloat(val);
    return !isNaN(num) && num > 0 && num <= 999999.99;
  }, 'Amount must be between $0.01 and $999,999.99'),
  startDate: z.string().min(1, 'Start date is required').refine((val) => {
    return !isNaN(Date.parse(val));
  }, 'Start date must be a valid date'),
  endDate: z.string().optional().refine((val) => {
    if (!val) return true;
    return !isNaN(Date.parse(val));
  }, 'End date must be a valid date'),
  notes: z.string().max(2000, 'Notes must be less than 2000 characters').optional(),
});

type NewBillFormData = z.infer<typeof newBillSchema>;

export default function AutoGeneratedBillWorkflow({
  autoGeneratedBill,
  isOpen,
  onClose,
  onSuccess,
}: AutoGeneratedBillWorkflowProps) {
  const { t } = useLanguage();
  const { toast } = useToast();
  const queryClient = useQueryClient();
  
  // AI Analysis state
  const [uploadedFile, setUploadedFile] = useState<File | null>(null);
  const [attachedDocument, setAttachedDocument] = useState<Document | null>(null);
  const [aiExtractionLoading, setAiExtractionLoading] = useState(false);
  const [aiExtractionData, setAiExtractionData] = useState<any>(null);
  const [activeTab, setActiveTab] = useState<'manual' | 'ai'>('manual');

  // Helper function to generate intelligent suggestions
  const generateSuggestions = (bill: Bill | null) => {
    if (!bill) return {};
    
    // Generate next period date suggestions
    const nextPeriodDate = new Date();
    if (bill.schedulePayment === 'monthly') {
      nextPeriodDate.setMonth(nextPeriodDate.getMonth() + 1);
    } else if (bill.schedulePayment === 'quarterly') {
      nextPeriodDate.setMonth(nextPeriodDate.getMonth() + 3);
    } else if (bill.schedulePayment === 'yearly') {
      nextPeriodDate.setFullYear(nextPeriodDate.getFullYear() + 1);
    } else {
      nextPeriodDate.setMonth(nextPeriodDate.getMonth() + 1); // Default to monthly
    }
    
    return {
      title: bill.title || '',
      description: bill.description || '',
      category: bill.category || 'other',
      vendor: bill.vendor || '',
      totalAmount: bill.totalAmount?.toString() || '',
      startDate: nextPeriodDate.toISOString().split('T')[0],
      endDate: bill.endDate || '',
      notes: bill.notes || '',
    };
  };

  // Form setup with intelligent suggestions from auto-generated bill
  const form = useForm<NewBillFormData>({
    resolver: zodResolver(newBillSchema),
    defaultValues: generateSuggestions(autoGeneratedBill)
  });
  
  // Update form when autoGeneratedBill changes
  useEffect(() => {
    if (autoGeneratedBill) {
      const suggestions = generateSuggestions(autoGeneratedBill);
      Object.entries(suggestions).forEach(([key, value]) => {
        if (value !== undefined && value !== null) {
          form.setValue(key as keyof NewBillFormData, value);
        }
      });
    }
  }, [autoGeneratedBill, form]);

  // Handle AI extraction results
  const handleAiExtractionComplete = (data: {
    success: boolean;
    formData?: any;
    confidence?: number;
    error?: string;
    rawData?: any;
    isLoading?: boolean;
  }) => {
    if (data.isLoading) {
      setAiExtractionLoading(true);
      return;
    }
    
    setAiExtractionLoading(false);
    
    if (data.success && data.formData) {
      setAiExtractionData(data);
      
      // Auto-populate form with AI-extracted data
      Object.entries(data.formData).forEach(([key, value]) => {
        if (value !== undefined && value !== null && value !== '') {
          if (key === 'totalAmount' && typeof value === 'number') {
            form.setValue(key as keyof NewBillFormData, value.toString());
          } else if (value && typeof value === 'string') {
            form.setValue(key as keyof NewBillFormData, value);
          }
        }
      });
      
      toast({
        title: 'AI Extraction Complete',
        description: `Extracted bill data with ${Math.round((data.confidence || 0) * 100)}% confidence`,
      });
      
      // Switch to manual tab to show extracted data
      setActiveTab('manual');
    } else if (data.error) {
      toast({
        title: 'AI Extraction Failed',
        description: data.error,
        variant: 'destructive',
      });
    }
  };
  
  // Handle file upload
  const handleDocumentChange = (file: File | null, text: string | null) => {
    setUploadedFile(file);
    
    if (text) {
      // Handle text input - could be enhanced with text analysis
      form.setValue('description', text);
    }
  };

  // Create bill from auto-generated template mutation
  const createBillMutation = useMutation({
    mutationFn: async (formData: NewBillFormData) => {
      // Prepare request data to match server expectations
      const requestData = {
        templateId: autoGeneratedBill?.id || '',
        suggestedDate: formData.startDate,
        newBillData: {
          title: formData.title,
          description: formData.description,
          category: formData.category,
          vendor: formData.vendor,
          totalAmount: parseFloat(formData.totalAmount),
          startDate: formData.startDate,
          endDate: formData.endDate || null,
          notes: formData.notes,
          status: 'draft' as const,
          paymentType: 'unique' as const, // Default for auto-generated bills
          isAiAnalyzed: !!aiExtractionData,
          aiAnalysisData: aiExtractionData || null,
        },
      };

      // Note: File upload not supported by this endpoint - files should be handled separately
      const response = await apiRequest('POST', '/api/bills/from-auto-generated', requestData);
      const responseData = await response.json();
      return responseData;
    },
    onSuccess: (responseData: any) => {
      queryClient.invalidateQueries({ queryKey: ['/api/bills'] });
      queryClient.invalidateQueries({ queryKey: ['/api/bills/auto-generated'] });
      
      toast({
        title: 'Success',
        description: 'Bill created successfully from auto-generated template',
      });
      
      onSuccess?.(responseData.bill?.id);
      handleClose();
    },
    onError: (error: any) => {
      toast({
        title: 'Error',
        description: error.message || 'Failed to create bill from template',
        variant: 'destructive',
      });
    }
  });
  
  // Handle dialog close with cleanup
  const handleClose = () => {
    form.reset();
    setUploadedFile(null);
    setAttachedDocument(null);
    setAiExtractionData(null);
    setAiExtractionLoading(false);
    setActiveTab('manual');
    onClose();
  };


  const onSubmit = (data: NewBillFormData) => {
    createBillMutation.mutate(data);
  };

  if (!autoGeneratedBill) return null;

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-blue-500" />
            Create Bill from Auto-Generated Template
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-6">
          {/* AI Analysis Workflow */}
          <Tabs value={activeTab} onValueChange={(value: 'manual' | 'ai') => setActiveTab(value)} className="w-full">
            <TabsList className="grid w-full grid-cols-2">
              <TabsTrigger value="manual" className="flex items-center gap-2">
                <Lightbulb className="h-4 w-4" />
                Manual Entry
                {aiExtractionData && (
                  <Badge variant="secondary" className="ml-2">AI Enhanced</Badge>
                )}
              </TabsTrigger>
              <TabsTrigger value="ai" className="flex items-center gap-2">
                <Sparkles className="h-4 w-4" />
                AI Analysis
              </TabsTrigger>
            </TabsList>
            
            <TabsContent value="ai" className="space-y-4">
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Upload className="h-5 w-5" />
                    Upload Bill Document for AI Analysis
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <SharedUploader
                    onDocumentChange={handleDocumentChange}
                    formType="bills"
                    uploadContext={{
                      type: 'bills',
                      contextId: autoGeneratedBill?.buildingId || 'unknown',
                      subContext: 'auto-generated'
                    } as UploadContext}
                    aiAnalysisEnabled={true}
                    onAiAnalysisComplete={handleAiExtractionComplete}
                    showAiToggle={false}
                    allowedFileTypes={[
                      'application/pdf',
                      'image/jpeg',
                      'image/jpg', 
                      'image/png'
                    ]}
                    maxFileSize={25}
                    className="border-dashed border-2 border-gray-300 dark:border-gray-600"
                  />
                  
                  {aiExtractionLoading && (
                    <div className="mt-4 p-4 bg-blue-50 dark:bg-blue-950 border border-blue-200 dark:border-blue-800 rounded-lg">
                      <div className="flex items-center gap-2">
                        <Sparkles className="h-4 w-4 animate-spin text-blue-500" />
                        <span className="text-sm text-blue-800 dark:text-blue-200">
                          AI is analyzing your document...
                        </span>
                      </div>
                    </div>
                  )}
                  
                  {aiExtractionData && (
                    <div className="mt-4 p-4 bg-green-50 dark:bg-green-950 border border-green-200 dark:border-green-800 rounded-lg">
                      <div className="flex items-center gap-2 mb-2">
                        <Sparkles className="h-4 w-4 text-green-500" />
                        <span className="text-sm font-medium text-green-800 dark:text-green-200">
                          AI Analysis Complete
                        </span>
                        <Badge variant="outline" className="ml-2">
                          {Math.round((aiExtractionData.confidence || 0) * 100)}% confidence
                        </Badge>
                      </div>
                      <p className="text-sm text-green-700 dark:text-green-300">
                        Form fields have been automatically populated. Switch to Manual Entry to review and modify.
                      </p>
                    </div>
                  )}
                  
                  {uploadedFile && (
                    <div className="mt-4 p-3 border border-gray-200 dark:border-gray-700 rounded-lg bg-gray-50 dark:bg-gray-800">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <FileText className="h-4 w-4 text-gray-500" />
                          <div>
                            <p className="text-sm font-medium text-gray-900 dark:text-gray-100">
                              {uploadedFile.name}
                            </p>
                            <p className="text-xs text-gray-500 dark:text-gray-400">
                              {(uploadedFile.size / 1024 / 1024).toFixed(2)} MB
                            </p>
                          </div>
                        </div>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => {
                            setUploadedFile(null);
                            setAiExtractionData(null);
                          }}
                          data-testid="button-remove-file"
                        >
                          <X className="h-4 w-4" />
                        </Button>
                      </div>
                      {aiExtractionData && (
                        <div className="mt-2 p-2 bg-green-100 dark:bg-green-900 rounded text-xs">
                          <p className="text-green-700 dark:text-green-300">
                            AI extracted: {Object.keys(aiExtractionData.formData || {}).length} fields
                          </p>
                        </div>
                      )}
                    </div>
                  )}
                </CardContent>
              </Card>
            </TabsContent>
            
            <TabsContent value="manual">
              {/* Intelligent Suggestions Header */}
              {autoGeneratedBill && (
                <Card className="bg-blue-50 dark:bg-blue-950 border-blue-200 dark:border-blue-800">
                  <CardContent className="pt-4">
                    <div className="flex items-start gap-3">
                      <Lightbulb className="h-5 w-5 text-blue-500 mt-0.5" />
                      <div>
                        <h4 className="font-medium text-blue-900 dark:text-blue-100">Intelligent Suggestions</h4>
                        <p className="text-sm text-blue-700 dark:text-blue-300 mt-1">
                          Form fields have been pre-filled based on the previous bill from <strong>{autoGeneratedBill.vendor || 'this vendor'}</strong>.
                          {autoGeneratedBill.schedulePayment && (
                            <> The suggested start date is based on your <strong>{autoGeneratedBill.schedulePayment}</strong> schedule.</>  
                          )}
                        </p>
                        {aiExtractionData && (
                          <Badge variant="outline" className="mt-2">
                            Enhanced with AI analysis ({Math.round((aiExtractionData.confidence || 0) * 100)}% confidence)
                          </Badge>
                        )}
                      </div>
                    </div>
                  </CardContent>
                </Card>
              )}
            </TabsContent>
          </Tabs>

          {/* Bill Form */}
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                {/* Title */}
                <FormField
                  control={form.control}
                  name="title"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Title *</FormLabel>
                      <FormControl>
                        <Input 
                          {...field} 
                          placeholder={autoGeneratedBill?.title ? `Suggested: ${autoGeneratedBill.title}` : 'Enter bill title'}
                          data-testid="input-bill-title" 
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* Category */}
                <FormField
                  control={form.control}
                  name="category"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Category *</FormLabel>
                      <Select onValueChange={field.onChange} value={field.value}>
                        <FormControl>
                          <SelectTrigger data-testid="select-category">
                            <SelectValue placeholder="Select category" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem value="insurance">Insurance</SelectItem>
                          <SelectItem value="maintenance">Maintenance</SelectItem>
                          <SelectItem value="salary">Salary</SelectItem>
                          <SelectItem value="utilities">Utilities</SelectItem>
                          <SelectItem value="cleaning">Cleaning</SelectItem>
                          <SelectItem value="security">Security</SelectItem>
                          <SelectItem value="landscaping">Landscaping</SelectItem>
                          <SelectItem value="professional_services">Professional Services</SelectItem>
                          <SelectItem value="administration">Administration</SelectItem>
                          <SelectItem value="repairs">Repairs</SelectItem>
                          <SelectItem value="supplies">Supplies</SelectItem>
                          <SelectItem value="taxes">Taxes</SelectItem>
                          <SelectItem value="technology">Technology</SelectItem>
                          <SelectItem value="reserves">Reserves</SelectItem>
                          <SelectItem value="other">Other</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* Vendor */}
                <FormField
                  control={form.control}
                  name="vendor"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Vendor</FormLabel>
                      <FormControl>
                        <Input 
                          {...field} 
                          placeholder={autoGeneratedBill?.vendor ? `Suggested: ${autoGeneratedBill.vendor}` : 'Enter vendor name'}
                          data-testid="input-vendor" 
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* Total Amount */}
                <FormField
                  control={form.control}
                  name="totalAmount"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Total Amount *</FormLabel>
                      <FormControl>
                        <Input 
                          placeholder={autoGeneratedBill?.totalAmount ? `Suggested: $${autoGeneratedBill.totalAmount}` : '0.00'}
                          type="number" 
                          step="0.01" 
                          {...field}
                          data-testid="input-total-amount"
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* Start Date */}
                <FormField
                  control={form.control}
                  name="startDate"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="flex items-center gap-2">
                        <Calendar className="h-4 w-4" />
                        Start Date *
                        {autoGeneratedBill?.schedulePayment && (
                          <Badge variant="outline" className="text-xs">
                            Next {autoGeneratedBill.schedulePayment} period
                          </Badge>
                        )}
                      </FormLabel>
                      <FormControl>
                        <Input 
                          type="date" 
                          {...field}
                          data-testid="input-start-date"
                        />
                      </FormControl>
                      <FormDescription className="text-xs">
                        {autoGeneratedBill?.schedulePayment 
                          ? `Suggested based on ${autoGeneratedBill.schedulePayment} schedule`
                          : 'Select the bill start date'
                        }
                      </FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* End Date */}
                <FormField
                  control={form.control}
                  name="endDate"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>End Date</FormLabel>
                      <FormControl>
                        <Input 
                          type="date" 
                          {...field}
                          data-testid="input-end-date"
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              {/* Description */}
              <FormField
                control={form.control}
                name="description"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Description</FormLabel>
                    <FormControl>
                      <Textarea 
                        {...field} 
                        rows={3}
                        data-testid="textarea-description"
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              {/* Notes */}
              <FormField
                control={form.control}
                name="notes"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Notes</FormLabel>
                    <FormControl>
                      <Textarea 
                        {...field} 
                        rows={2}
                        data-testid="textarea-notes"
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              {/* Action Buttons */}
              <div className="flex justify-between pt-4">
                <Button
                  type="button"
                  variant="outline"
                  onClick={handleClose}
                  data-testid="button-cancel"
                >
                  Cancel
                </Button>
                <Button
                  type="submit"
                  disabled={createBillMutation.isPending}
                  data-testid="button-create-bill"
                  className="min-w-[120px]"
                >
                  {createBillMutation.isPending ? (
                    <>
                      <Sparkles className="h-4 w-4 mr-2 animate-spin" />
                      Creating...
                    </>
                  ) : (
                    'Create Bill'
                  )}
                </Button>
              </div>
            </form>
          </Form>

          {/* Workflow Info */}
          <div className="bg-amber-50 dark:bg-amber-950 border border-amber-200 dark:border-amber-800 rounded-lg p-3">
            <p className="text-sm text-amber-800 dark:text-amber-200">
              <strong>Smart Workflow:</strong> This bill is being created from your recurring template. 
              Creating it will automatically update the original bill to prevent duplicates and maintain accurate budgeting.
            </p>
          </div>
          
          {/* File Upload Notice */}
          {uploadedFile && (
            <div className="bg-blue-50 dark:bg-blue-950 border border-blue-200 dark:border-blue-800 rounded-lg p-3">
              <p className="text-sm text-blue-800 dark:text-blue-200">
                <strong>Note:</strong> The uploaded file ({uploadedFile.name}) has been used for AI analysis but will not be automatically attached to this bill. 
                You can manually attach documents to the bill after creation using the document management feature.
              </p>
            </div>
          )}
          
          {/* Hidden AI Extraction Component */}
          {uploadedFile && (
            <GeminiBillExtractor
              file={uploadedFile}
              onExtractionComplete={handleAiExtractionComplete}
            />
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}