import React, { useState, useEffect, useCallback, useRef } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQueryClient, useQuery } from '@tanstack/react-query';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Label } from '@/components/ui/label';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { FileText, Sparkles, Plus, X, Calendar, Trash2 } from 'lucide-react';
import { useLanguage } from '@/hooks/use-language';
import { useToast } from '@/hooks/use-toast';
import { apiRequest } from '@/lib/queryClient';
import { useCreateUpdateMutation } from '@/lib/common-hooks';
import { cn } from '@/lib/utils';
import { SharedUploader } from '@/components/document-management';
import { GeminiBillExtractor } from './GeminiBillExtractor';
import { AttachedFileSection } from '@/components/common/AttachedFileSection';
import { StandardFormGrid } from '@/components/common/StandardFormGrid';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import type { AttachedFile } from '@/components/common/StandardDocumentAttachments';
import type { Bill, Document } from '@shared/schema';
import type { UploadContext } from '@shared/config/upload-config';
import { BILL_CATEGORIES } from '@shared/schemas/financial';
import { AlertCircle } from 'lucide-react';
import {
  billFormSchema,
  parseBillPaymentData,
  getCategoryLabel,
  type FieldConfidenceData,
  type CustomPayment,
  type ModularBillFormProps,
  type BillFormData,
} from './bill-form-schema';
import { ConfidenceIndicator } from './ConfidenceIndicator';

export default function ModularBillForm({ bill, isTemplate = false, onSuccess, onCancel, buildingId }: ModularBillFormProps) {
  const { t, language } = useLanguage();
  const { toast } = useToast();
  const queryClient = useQueryClient();
  
  // Parse existing bill payment data
  const parsedPaymentData = parseBillPaymentData(bill);
  
  // State for AI extraction
  const [aiFile, setAiFile] = useState<File | null>(null);
  const [isAiMode, setIsAiMode] = useState(false);
  const [aiExtractionData, setAiExtractionData] = useState<any>(null);
  const [isExtracting, setIsExtracting] = useState(false);
  const [aiEnabled, setAiEnabled] = useState(true); // AI enabled by default for bills
  
  // State for document management
  const [attachedFiles, setAttachedFiles] = useState<AttachedFile[]>([]);
  const [uploadProgress, setUploadProgress] = useState<{ [key: string]: number }>({});
  const [customPayments, setCustomPayments] = useState<CustomPayment[]>(parsedPaymentData.customPayments);
  
  // State for document dialogs
  const [showDeleteDocDialog, setShowDeleteDocDialog] = useState(false);
  const [selectedDocument, setSelectedDocument] = useState<Document | null>(null);
  
  // Auto-save functionality
  const [isAutoSaving, setIsAutoSaving] = useState(false);
  const [autoSaveStatus, setAutoSaveStatus] = useState<string | null>(null);
  const autoSaveTimerRef = useRef<NodeJS.Timeout | null>(null);
  const lastSavedDataRef = useRef<string>('');
  
  
  // Upload context for secure storage
  const uploadContext: UploadContext = {
    type: 'bills',
    organizationId: 'default', // Would be dynamic based on user's org
    buildingId,
    userRole: 'admin', // Would be dynamic based on user's role
    userId: 'current-user' // Would be dynamic based on current user
  };

  // Form setup with properly populated defaultValues
  const form = useForm<BillFormData>({
    resolver: zodResolver(billFormSchema),
    defaultValues: {
      title: bill?.title || '',
      description: bill?.description || '',
      category: bill?.category || 'other',
      vendor: bill?.vendor || '',
      billType: (isTemplate && bill?.isAutoGenerated) ? 'recurrent' : parsedPaymentData.billType,
      paymentStructure: parsedPaymentData.paymentStructure,
      paymentCount: parsedPaymentData.paymentCount,
      recurrence: (isTemplate && bill?.isAutoGenerated) ? true : parsedPaymentData.recurrence,
      paymentType: bill?.paymentType || 'unique',
      schedulePayment: parsedPaymentData.schedulePayment,
      yearInterval: parsedPaymentData.yearInterval,
      customPayments: parsedPaymentData.customPayments,
      hasInitialPayment: parsedPaymentData.hasInitialPayment,
      recurringPaymentsEqual: parsedPaymentData.recurringPaymentsEqual,
      singlePaymentAmount: parsedPaymentData.singlePaymentAmount,
      initialPaymentAmount: parsedPaymentData.initialPaymentAmount,
      recurringPaymentAmount: parsedPaymentData.recurringPaymentAmount,
      totalAmount: parsedPaymentData.calculatedTotalFromCustomPayments || bill?.totalAmount?.toString() || '',
      startDate: bill?.startDate || '',
      endDate: bill?.endDate || '',
      status: bill?.status || 'draft',
      issueDate: parsedPaymentData.issueDate,
      vendorInvoiceNumber: parsedPaymentData.vendorInvoiceNumber,
    }
  });

  const billType = form.watch('billType');
  const paymentStructure = form.watch('paymentStructure');
  const paymentCount = form.watch('paymentCount');
  const recurrence = form.watch('recurrence');
  const paymentType = form.watch('paymentType');
  const schedulePayment = form.watch('schedulePayment');
  const hasInitialPayment = form.watch('hasInitialPayment');
  const recurringPaymentsEqual = form.watch('recurringPaymentsEqual');
  const singlePaymentAmount = form.watch('singlePaymentAmount');
  const initialPaymentAmount = form.watch('initialPaymentAmount');
  const recurringPaymentAmount = form.watch('recurringPaymentAmount');
  const watchedCustomPayments = form.watch('customPayments');

  // Calculate total amount based on payment structure
  const calculatedTotal = React.useMemo(() => {
    if (paymentStructure === 'single') {
      // For single payment, total equals the singlePaymentAmount
      return parseFloat(singlePaymentAmount || '0');
    } else if (paymentStructure === 'installment') {
      let total = 0;
      
      // For custom schedule, always sum custom payments regardless of recurringPaymentsEqual
      if (schedulePayment === 'custom' && watchedCustomPayments && watchedCustomPayments.length > 0) {
        total = watchedCustomPayments.reduce((sum, payment) => {
          return sum + parseFloat(payment.amount || '0');
        }, 0);
      } else if (recurringPaymentsEqual) {
        // For equal installment payments
        const maxPayments = 12; // Default to 12 monthly payments
        
        if (hasInitialPayment && initialPaymentAmount) {
          total += parseFloat(initialPaymentAmount || '0');
          
          if (recurringPaymentAmount) {
            // Add remaining payments (12 - 1 = 11)
            total += parseFloat(recurringPaymentAmount || '0') * (maxPayments - 1);
          }
        } else if (recurringPaymentAmount) {
          // All payments use the same recurring amount
          total += parseFloat(recurringPaymentAmount || '0') * maxPayments;
        }
      } else if (watchedCustomPayments && watchedCustomPayments.length > 0) {
        // For custom payments, sum all amounts
        total = watchedCustomPayments.reduce((sum, payment) => {
          return sum + parseFloat(payment.amount || '0');
        }, 0);
      }
      
      return total;
    }
    
    return 0;
  }, [
    paymentStructure,
    schedulePayment,
    singlePaymentAmount,
    hasInitialPayment,
    initialPaymentAmount,
    recurringPaymentsEqual,
    recurringPaymentAmount,
    watchedCustomPayments
  ]);

  // Update form's totalAmount field with calculated value - ALWAYS set for ALL cases
  useEffect(() => {
    const totalStr = calculatedTotal.toFixed(2);
    
    // Only update if the value has changed to avoid unnecessary re-renders
    if (form.getValues('totalAmount') !== totalStr) {
      form.setValue('totalAmount', totalStr, { shouldValidate: false });
    }
  }, [calculatedTotal, form]);

  // CRITICAL: Sync component customPayments state to form state
  // This ensures form validation sees the same data as what's displayed in the UI
  useEffect(() => {
    const currentFormPayments = form.getValues('customPayments');
    const currentFormPaymentsJson = JSON.stringify(currentFormPayments || []);
    const customPaymentsJson = JSON.stringify(customPayments);
    
    // Only update if different to avoid infinite loops
    if (currentFormPaymentsJson !== customPaymentsJson) {
      form.setValue('customPayments', customPayments, { shouldValidate: false, shouldDirty: true });
    }
  }, [customPayments, form]);

  // Auto-save function with 1.5 second delay
  const performAutoSave = useCallback(async (formData: BillFormData) => {
    try {
      setIsAutoSaving(true);
      setAutoSaveStatus('Saving...');
      
      const currentDataString = JSON.stringify(formData);
      
      // Skip save if data hasn't changed
      if (currentDataString === lastSavedDataRef.current) {
        setIsAutoSaving(false);
        setAutoSaveStatus('No changes');
        setTimeout(() => setAutoSaveStatus(null), 2000);
        return;
      }

      // Only auto-save if we're editing an existing bill (not creating from template)
      if (bill?.id && !isTemplate) {
        // CRITICAL: Derive legacy fields from new fields for backward compatibility
        // These fields MUST be included in every API request to prevent DB constraint violations
        const paymentType: 'unique' | 'recurrent' = formData.billType || 'unique';
        const paymentCount: '1' | 'multiple' = formData.paymentStructure === 'single' ? '1' : 'multiple';
        const recurrence: boolean = formData.billType === 'recurrent';
        
        // Calculate costs array based on payment structure (same logic as main submit)
        let costs: string[] = [];
        let calculatedTotalAmount = formData.totalAmount;
        
        if (formData.paymentStructure === 'single') {
          costs = [formData.singlePaymentAmount || '0'];
        } else if (formData.paymentStructure === 'installment') {
          if (formData.recurringPaymentsEqual) {
            const maxPayments = 12;
            
            if (formData.hasInitialPayment && formData.initialPaymentAmount) {
              costs.push(formData.initialPaymentAmount);
              if (formData.recurringPaymentAmount) {
                for (let i = 1; i < maxPayments; i++) {
                  costs.push(formData.recurringPaymentAmount);
                }
              }
            } else if (formData.recurringPaymentAmount) {
              for (let i = 0; i < maxPayments; i++) {
                costs.push(formData.recurringPaymentAmount);
              }
            }
          } else if (customPayments && customPayments.length > 0) {
            // Use component state customPayments for most up-to-date values
            costs = customPayments.map(p => p.amount).filter(a => a && a.trim() !== '');
            // ISSUE 2 FIX: Recompute totalAmount from custom payments during auto-save
            const computedTotal = customPayments.reduce((sum, p) => sum + parseFloat(p.amount || '0'), 0);
            calculatedTotalAmount = computedTotal.toFixed(2);
          }
          
          // Calculate total if not provided (for equal installments only)
          if (formData.recurringPaymentsEqual && (!calculatedTotalAmount || calculatedTotalAmount.trim() === '')) {
            const total = costs.reduce((sum, cost) => sum + parseFloat(cost || '0'), 0);
            calculatedTotalAmount = total.toString();
          }
        }
        
        // Use component state customPayments for schedule dates
        // IMPORTANT: Do NOT filter out empty dates - we need to preserve array indices
        // to match costs[i] with scheduleCustom[i] for budget calculations
        let scheduleCustom: string[] = [];
        if (formData.paymentStructure === 'installment' && !formData.recurringPaymentsEqual && customPayments && customPayments.length > 0) {
          scheduleCustom = customPayments.map(p => p.date || '');
        }
        
        // CRITICAL: Construct bill data with BOTH new fields (billType, paymentStructure) 
        // AND legacy fields (paymentType, paymentCount, recurrence) for backward compatibility
        const billData: any = {
          ...formData,
          billType: formData.billType,
          paymentStructure: formData.paymentStructure,
          paymentType,
          paymentCount,
          recurrence,
          buildingId: buildingId || bill.buildingId,
          totalAmount: calculatedTotalAmount,
          costs,
          scheduleCustom,
        };
        
        if (formData.paymentStructure === 'installment' && !formData.recurringPaymentsEqual) {
          // Custom payment schedule - explicitly set schedulePayment to 'custom'
          billData.schedulePayment = 'custom';
          billData.recurringPaymentsEqual = false;
        } else if (formData.paymentStructure === 'installment') {
          billData.schedulePayment = formData.schedulePayment;
          // Include yearInterval only for yearly schedules
          if (formData.schedulePayment === 'yearly') {
            billData.yearInterval = formData.yearInterval || 1;
          }
        } else if (formData.billType === 'recurrent') {
          // For single payment recurrent bills, default to yearly schedule
          billData.schedulePayment = 'yearly';
          billData.yearInterval = formData.yearInterval || 1;
        } else {
          delete billData.schedulePayment;
          delete billData.yearInterval;
        }

        const response = await apiRequest('PUT', `/api/bills/${bill.id}`, billData);
        
        if (response.ok) {
          lastSavedDataRef.current = currentDataString;
          setAutoSaveStatus('Saved');
          
          // Invalidate queries to refresh any related data
          queryClient.invalidateQueries({ queryKey: ['/api/bills'] });
        } else {
          throw new Error('Failed to auto-save');
        }
      } else {
        // For new bills, just update the status
        setAutoSaveStatus('Draft');
      }
      
      setIsAutoSaving(false);
      
      // Clear status after 3 seconds
      setTimeout(() => setAutoSaveStatus(null), 3000);
      
    } catch (error) {
      console.error('Auto-save failed:', error);
      setIsAutoSaving(false);
      setAutoSaveStatus('Save failed');
      setTimeout(() => setAutoSaveStatus(null), 3000);
    }
  }, [bill?.id, isTemplate, buildingId, queryClient, customPayments]);

  // Debounced auto-save function with 1.5 second delay
  const debouncedAutoSave = useCallback((formData: BillFormData) => {
    // Clear existing timer
    if (autoSaveTimerRef.current) {
      clearTimeout(autoSaveTimerRef.current);
    }
    
    // Set new timer for 1.5 seconds (1500ms)
    autoSaveTimerRef.current = setTimeout(() => {
      performAutoSave(formData);
    }, 1500);
  }, [performAutoSave]);

  // Query for attached documents when editing an existing bill
  const { data: attachedDocuments = [] } = useQuery<Document[]>({
    queryKey: ['/api/documents', { attachedToType: 'bill', attachedToId: bill?.id }],
    queryFn: async () => {
      if (!bill?.id) return [];
      
      // Fetching attached documents for bill
      
      const response = await fetch(`/api/documents?attachedToType=bill&attachedToId=${bill.id}`, {
        credentials: 'include'
      });
      
      if (!response.ok) {
        if (response.status === 404) return [];
        throw new Error('Failed to fetch attached documents');
      }
      
      const data = await response.json();
      // Attached documents received
      return Array.isArray(data.documents) ? data.documents : [];
    },
    enabled: !!bill?.id
  });

  // Sync customPayments state and form values when bill changes
  useEffect(() => {
    const newParsedData = parseBillPaymentData(bill);
    setCustomPayments(newParsedData.customPayments);
    
    // Update form values if bill has changed
    if (bill) {
      form.setValue('billType', (isTemplate && bill?.isAutoGenerated) ? 'recurrent' : newParsedData.billType);
      form.setValue('paymentStructure', newParsedData.paymentStructure);
      form.setValue('paymentCount', newParsedData.paymentCount);
      form.setValue('recurrence', (isTemplate && bill?.isAutoGenerated) ? true : newParsedData.recurrence);
      form.setValue('schedulePayment', newParsedData.schedulePayment);
      form.setValue('yearInterval', newParsedData.yearInterval);
      form.setValue('hasInitialPayment', newParsedData.hasInitialPayment);
      form.setValue('recurringPaymentsEqual', newParsedData.recurringPaymentsEqual);
      form.setValue('singlePaymentAmount', newParsedData.singlePaymentAmount);
      form.setValue('initialPaymentAmount', newParsedData.initialPaymentAmount);
      form.setValue('recurringPaymentAmount', newParsedData.recurringPaymentAmount);
      form.setValue('customPayments', newParsedData.customPayments);
      form.setValue('issueDate', newParsedData.issueDate);
      form.setValue('vendorInvoiceNumber', newParsedData.vendorInvoiceNumber);
    }
  }, [bill?.id, form, isTemplate]);

  // Auto-set schedulePayment to 'yearly' for recurring bills with single payment
  // This ensures validation passes since schedulePayment is required but not visible in UI for this combination
  useEffect(() => {
    if (billType === 'recurrent' && paymentStructure === 'single') {
      // Only set if not already set to avoid unnecessary updates
      if (!schedulePayment) {
        form.setValue('schedulePayment', 'yearly', { shouldDirty: true, shouldValidate: false });
      }
    } else if (paymentStructure === 'single') {
      // Clear schedulePayment when switching to unique bill with single payment
      if (schedulePayment) {
        form.setValue('schedulePayment', null, { shouldDirty: true, shouldValidate: false });
      }
    }
  }, [billType, paymentStructure, schedulePayment, form]);

  // Auto-save disabled - bills now only save when Update Bill button is clicked
  // useEffect(() => {
  //   const subscription = form.watch((data) => {
  //     // Trigger auto-save on any form change (with 1.5 second debounce)
  //     if (data && Object.keys(data).length > 0) {
  //       debouncedAutoSave(data as BillFormData);
  //     }
  //   });
  //   
  //   return () => subscription.unsubscribe();
  // }, [form, debouncedAutoSave]);


  // Handle AI extraction results with field-level confidence support
  const handleAiExtractionComplete = (data: any) => {
    // Handle loading state
    if (data.isLoading) {
      setIsExtracting(true);
      toast({
        title: 'AI Extraction Started',
        description: 'Processing your document... This may take a few seconds.',
      });
      return;
    }
    
    // Clear loading state
    setIsExtracting(false);
    
    if (data.success && data.formData) {
      // Store extraction data including field confidence
      const extractionDataWithConfidence = {
        ...data.formData,
        fieldConfidence: data.fieldConfidence,
        extractionNotes: data.extractionNotes || [],
        overallConfidence: data.confidence
      };
      setAiExtractionData(extractionDataWithConfidence);

      const formData = data.formData;
      const hasCustomPayments = Array.isArray(formData.customPayments) && formData.customPayments.length > 0;

      // Non-destructive setter: only overwrite empty / untouched fields so a
      // user who has already typed a value isn't clobbered by a re-extraction.
      const touched = form.formState.touchedFields as Record<string, unknown>;
      const isEmpty = (v: unknown) =>
        v === undefined || v === null || v === '' ||
        (Array.isArray(v) && v.length === 0);
      const setIfEmpty = (key: keyof BillFormData, value: any) => {
        if (value === undefined || value === null) return;
        if (touched[key as string]) return;
        if (!isEmpty(form.getValues(key))) return;
        form.setValue(key, value, { shouldDirty: true });
      };

      // STEP 1: Set payment structure fields FIRST (in correct order)
      // This ensures UI sections are visible before we populate them.
      // NOTE: paymentStructure / billType drive conditional UI rendering and
      // also need to stay in sync with the legacy fields paymentType /
      // paymentCount / recurrence (still required by the API/DB). We mirror
      // those here so the form passes server-side validation.

      // 1a. Set billType first (unique vs recurrent)
      const inferredBillType: 'unique' | 'recurrent' = formData.billType
        ? (formData.billType as 'unique' | 'recurrent')
        : (formData.recurrence || hasCustomPayments ? 'recurrent' : (formData.paymentType || 'unique'));
      setIfEmpty('billType', inferredBillType);
      setIfEmpty('paymentType', inferredBillType);
      setIfEmpty('recurrence', inferredBillType === 'recurrent');

      // 1b. Set paymentStructure (single vs installment)
      const inferredStructure: 'single' | 'installment' = formData.paymentStructure
        ? (formData.paymentStructure as 'single' | 'installment')
        : ((hasCustomPayments || formData.paymentCount === 'multiple') ? 'installment' : 'single');
      setIfEmpty('paymentStructure', inferredStructure);
      setIfEmpty('paymentCount', inferredStructure === 'installment' ? 'multiple' : '1');

      // 1c. Schedule + year interval
      if (hasCustomPayments) {
        setIfEmpty('schedulePayment', 'custom');
        setIfEmpty('recurringPaymentsEqual', false);
      } else if (formData.schedulePayment) {
        setIfEmpty('schedulePayment', formData.schedulePayment);
      }
      if (typeof formData.yearInterval === 'number' && formData.yearInterval >= 1) {
        setIfEmpty('yearInterval', formData.yearInterval);
      }

      // STEP 2: Set basic form fields (vendor, title, dates, etc.)
      const isRecurrentBill = inferredBillType === 'recurrent' || hasCustomPayments;
      setIfEmpty('title', formData.title);
      setIfEmpty('vendor', formData.vendor);
      setIfEmpty('description', formData.description);
      setIfEmpty('startDate', formData.startDate);
      setIfEmpty('issueDate', formData.issueDate);
      setIfEmpty('vendorInvoiceNumber', formData.vendorInvoiceNumber || formData.billNumber);
      if (!isRecurrentBill) {
        setIfEmpty('endDate', formData.endDate);
      }
      setIfEmpty('category', formData.category);

      // STEP 3: Set payment amount fields based on payment structure
      if (inferredStructure === 'single') {
        setIfEmpty('singlePaymentAmount', formData.singlePaymentAmount || formData.totalAmount);
      } else {
        // Installment: support unequal recurring (initial + recurring) or per-payment custom amounts
        if (formData.hasInitialPayment) {
          setIfEmpty('hasInitialPayment', true);
          setIfEmpty('initialPaymentAmount', formData.initialPaymentAmount);
        }
        setIfEmpty('recurringPaymentAmount', formData.recurringPaymentAmount);
        if (typeof formData.recurringPaymentsEqual === 'boolean') {
          setIfEmpty('recurringPaymentsEqual', formData.recurringPaymentsEqual);
        }
      }
      setIfEmpty('totalAmount', formData.totalAmount);

      // STEP 4: Set custom payments LAST (after payment structure is configured)
      if (hasCustomPayments && isEmpty(form.getValues('customPayments')) && !touched['customPayments']) {
        setCustomPayments(formData.customPayments);
        form.setValue('customPayments', formData.customPayments, { shouldDirty: true });
      }

      // Build toast description with confidence and notes
      const confidencePercent = Math.round((data.confidence || 0.9) * 100);
      let toastDescription = `Successfully extracted bill data with ${confidencePercent}% confidence`;
      
      // Add notes about fields needing review if confidence is low
      if (data.extractionNotes && data.extractionNotes.length > 0) {
        toastDescription += `. Note: ${data.extractionNotes[0]}`;
      } else if (data.fieldConfidence) {
        const lowConfidenceFields = [];
        if (data.fieldConfidence.vendorName < 0.7) lowConfidenceFields.push('vendor');
        if (data.fieldConfidence.totalAmount < 0.7) lowConfidenceFields.push('amount');
        if (data.fieldConfidence.dueDate < 0.7) lowConfidenceFields.push('date');
        
        if (lowConfidenceFields.length > 0) {
          toastDescription += `. Please verify: ${lowConfidenceFields.join(', ')}`;
        }
      }

      toast({
        title: 'AI Extraction Complete',
        description: toastDescription,
      });
    } else {
      toast({
        title: 'AI Extraction Failed',
        description: data.error || 'Failed to extract bill data',
        variant: 'destructive',
      });
    }
  };

  // Handle AI toggle
  const handleAiToggle = (enabled: boolean) => {
    setAiEnabled(enabled);
    if (!enabled) {
      setAiExtractionData(null);
      setIsExtracting(false);
    }
  };
  
  // Handle AI analysis completion
  const handleAiAnalysisComplete = (analysisData: any) => {
    if (analysisData.success) {
      setAiExtractionData(analysisData.extractedData);
      setIsExtracting(false);
      
      // Auto-populate form with extracted data (non-destructive)
      if (analysisData.extractedData) {
        const data = analysisData.extractedData;

        // Detect custom payment dates (indicates installment plan)
        const hasCustomPaymentDates = Array.isArray(data.customPaymentDates) && data.customPaymentDates.length > 0;
        const hasCustomPayments = Array.isArray(data.customPayments) && data.customPayments.length > 0;
        const isCustomFrequency = data.frequency === 'custom';
        const isInstallmentPlan = hasCustomPaymentDates || hasCustomPayments || isCustomFrequency;

        const touched = form.formState.touchedFields as Record<string, unknown>;
        const isEmpty = (v: unknown) =>
          v === undefined || v === null || v === '' ||
          (Array.isArray(v) && v.length === 0);
        const setIfEmpty = (key: keyof BillFormData, value: any) => {
          if (value === undefined || value === null) return;
          if (touched[key as string]) return;
          if (!isEmpty(form.getValues(key))) return;
          form.setValue(key, value, { shouldDirty: true });
        };

        // STEP 1: Payment structure (mirror legacy paymentType / paymentCount /
        // recurrence so server-side validation continues to pass).
        const inferredBillType: 'unique' | 'recurrent' = isInstallmentPlan
          ? 'recurrent'
          : (data.billType || (data.paymentType === 'recurring' ? 'recurrent' : 'unique'));
        setIfEmpty('billType', inferredBillType);
        setIfEmpty('paymentType', inferredBillType);
        setIfEmpty('recurrence', inferredBillType === 'recurrent');

        const inferredStructure: 'single' | 'installment' = isInstallmentPlan
          ? 'installment'
          : (data.paymentStructure || 'single');
        setIfEmpty('paymentStructure', inferredStructure);
        setIfEmpty('paymentCount', inferredStructure === 'installment' ? 'multiple' : '1');

        if (isInstallmentPlan) {
          setIfEmpty('schedulePayment', 'custom');
          setIfEmpty('recurringPaymentsEqual', false);
        } else if (data.frequency) {
          const freq = String(data.frequency).toLowerCase();
          const sched = freq.includes('week') ? 'weekly'
            : freq.includes('quarter') ? 'quarterly'
            : (freq.includes('year') || freq.includes('annual')) ? 'yearly'
            : freq.includes('month') ? 'monthly'
            : undefined;
          if (sched) setIfEmpty('schedulePayment', sched);
        }
        if (typeof data.yearInterval === 'number' && data.yearInterval >= 1) {
          setIfEmpty('yearInterval', data.yearInterval);
        }

        // STEP 2: Basic fields
        setIfEmpty('title', data.title);
        setIfEmpty('vendor', data.vendor || data.vendorName);
        setIfEmpty('description', data.description);
        setIfEmpty('startDate', data.date || data.startDate || data.dueDate);
        setIfEmpty('issueDate', data.issueDate);
        setIfEmpty('vendorInvoiceNumber', data.vendorInvoiceNumber || data.billNumber || data.invoiceNumber);
        setIfEmpty('category', data.category);

        // STEP 3: Amount fields
        const extractedAmount = data.amount ?? data.totalAmount;
        if (extractedAmount !== undefined && extractedAmount !== null) {
          setIfEmpty('totalAmount', extractedAmount.toString());
          if (!isInstallmentPlan) {
            setIfEmpty('singlePaymentAmount', extractedAmount.toString());
          }
        }
        if (isInstallmentPlan) {
          if (data.hasInitialPayment) {
            setIfEmpty('hasInitialPayment', true);
            if (data.initialPaymentAmount !== undefined && data.initialPaymentAmount !== null) {
              setIfEmpty('initialPaymentAmount', data.initialPaymentAmount.toString());
            }
          }
          if (data.recurringPaymentAmount !== undefined && data.recurringPaymentAmount !== null) {
            setIfEmpty('recurringPaymentAmount', data.recurringPaymentAmount.toString());
          }
        }

        // STEP 4: Custom payments
        if ((hasCustomPaymentDates || hasCustomPayments) &&
            isEmpty(form.getValues('customPayments')) && !touched['customPayments']) {
          let customPaymentsData: { amount: string; date: string; description: string }[] = [];
          if (hasCustomPayments) {
            // Prefer per-payment amounts the model returned
            customPaymentsData = data.customPayments.map((p: any, i: number) => ({
              amount: p.amount !== undefined && p.amount !== null ? p.amount.toString() : '0.00',
              date: p.date,
              description: p.description || `Payment ${i + 1}`,
            }));
          } else {
            const totalAmount = parseFloat((extractedAmount ?? '0').toString());
            const numPayments = data.customPaymentDates.length;
            const individualAmount = numPayments > 0 ? (totalAmount / numPayments).toFixed(2) : '0.00';
            customPaymentsData = data.customPaymentDates.map((date: string, i: number) => ({
              amount: individualAmount,
              date,
              description: `Payment ${i + 1}`,
            }));
          }
          setCustomPayments(customPaymentsData);
          form.setValue('customPayments', customPaymentsData, { shouldDirty: true });
        }
      }
      
      toast({
        title: 'AI Analysis Complete',
        description: 'Bill data has been extracted and populated in the form.',
      });
    } else {
      setIsExtracting(false);
      toast({
        title: 'AI Analysis Failed',
        description: analysisData.error || 'Failed to analyze document',
        variant: 'destructive',
      });
    }
  };

  // Handle file upload from SharedUploader
  const handleFileUpload = (file: File | null, text: string | null) => {
    if (file) {
      // Add file to attachments list
      const fileId = `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
      const isImage = file.type.startsWith('image/');
      
      const newAttachment: AttachedFile = {
        id: fileId,
        file,
        preview: isImage ? URL.createObjectURL(file) : undefined,
        uploadProgress: 0,
        aiAnalyzed: aiEnabled,
        category: getCategoryFromFileName(file.name)
      };
      
      setAttachedFiles(prev => [...prev, newAttachment]);
      
      // Simulate upload progress
      let progress = 0;
      const interval = setInterval(() => {
        progress += Math.random() * 30;
        if (progress >= 100) {
          progress = 100;
          clearInterval(interval);
        }
        setUploadProgress(prev => ({ ...prev, [fileId]: progress }));
      }, 200);
      
      if (aiEnabled) {
        setAiFile(file);
        setIsAiMode(true);
        setIsExtracting(true);
      }
    } else if (text) {
      // Handle text content - create a virtual file for text document
      // Text content received from file
      
      // Create a Blob from the text content
      const textBlob = new Blob([text], { type: 'text/plain' });
      const textFile = new File([textBlob], `bill-notes-${Date.now()}.txt`, { type: 'text/plain' });
      
      const fileId = `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
      
      const newAttachment: AttachedFile = {
        id: fileId,
        file: textFile,
        preview: undefined, // No preview for text files
        uploadProgress: 0,
        aiAnalyzed: false, // Text documents don't get AI analyzed
        category: 'document'
      };
      
      setAttachedFiles(prev => [...prev, newAttachment]);
      
      // Simulate upload progress for consistency
      let progress = 0;
      const interval = setInterval(() => {
        progress += Math.random() * 30;
        if (progress >= 100) {
          progress = 100;
          clearInterval(interval);
        }
        setUploadProgress(prev => ({ ...prev, [fileId]: progress }));
      }, 200);
      
      toast({
        title: 'Text Document Added',
        description: 'Your text content has been prepared for saving with the bill.',
      });
    }
  };

  // Remove file from attachments
  const removeAttachedFile = (fileId: string) => {
    setAttachedFiles(prev => {
      const file = prev.find(f => f.id === fileId);
      if (file?.preview) {
        URL.revokeObjectURL(file.preview);
      }
      return prev.filter(f => f.id !== fileId);
    });
    setUploadProgress(prev => {
      const { [fileId]: removed, ...rest } = prev;
      return rest;
    });
  };

  // Get category from file name
  const getCategoryFromFileName = (fileName: string): string => {
    const lower = fileName.toLowerCase();
    if (lower.includes('invoice') || lower.includes('bill')) return 'invoice';
    if (lower.includes('receipt')) return 'receipt';
    if (lower.includes('contract')) return 'contract';
    if (lower.includes('quote') || lower.includes('estimate')) return 'quote';
    return 'document';
  };

  // Handle document attachment to existing bill using SharedUploader
  const handleBillDocumentAttachment = async (file: File | null, text: string | null) => {
    if (!file || !bill?.id || !bill?.buildingId) {
      if (!file) {
        toast({
          title: 'No file selected',
          description: 'Please select a file to attach to this bill.',
          variant: 'destructive',
        });
      }
      return;
    }

    // For auto-generated bills with AI enabled, set aiFile to trigger extraction
    if (bill?.isAutoGenerated && !isTemplate && aiEnabled) {
      setAiFile(file);
      setIsExtracting(true);
    }

    try {
      // Upload document through documents API and link to bill
      const formData = new FormData();
      formData.append('file', file);
      formData.append('name', file.name);
      formData.append('description', `Document attached to bill: ${bill.title}`);
      formData.append('documentType', 'financial');
      formData.append('buildingId', bill.buildingId);
      formData.append('attachedToType', 'bill');
      formData.append('attachedToId', bill.id);

      const response = await fetch('/api/documents/upload', {
        method: 'POST',
        credentials: 'include',
        body: formData,
      });

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`Upload failed: ${response.status} ${errorText}`);
      }

      const result = await response.json();

      // Refresh the attached documents list
      queryClient.invalidateQueries({ 
        queryKey: ['/api/documents', { attachedToType: 'bill', attachedToId: bill.id }] 
      });

      toast({
        title: 'Document Attached',
        description: `${file.name} has been successfully attached to this bill.`,
      });
    } catch (error) {
      console.error('Failed to attach document:', error);
      toast({
        title: 'Upload Failed',
        description: error instanceof Error ? error.message : 'Failed to attach document to bill.',
        variant: 'destructive',
      });
    }
  };

  // Cleanup timer on unmount
  useEffect(() => {
    return () => {
      if (autoSaveTimerRef.current) {
        clearTimeout(autoSaveTimerRef.current);
      }
    };
  }, []);

  // Create/Update bill mutation
  // Exception (task #229): emits a per-document upload toast inside `mutationFn`
  // (data-dependent), so the success/error toast pair from `useCreateUpdateMutation`
  // would conflict — kept as raw `useMutation`.
  const billMutation = useMutation({
    mutationFn: async (data: BillFormData) => {
      // If isTemplate, always create new bill (POST), even if bill data is provided
      const endpoint = (bill && !isTemplate) ? `/api/bills/${bill.id}` : '/api/bills';
      const method = (bill && !isTemplate) ? 'PUT' : 'POST';
      
      // CRITICAL: Derive legacy fields from new fields for backward compatibility
      // These fields MUST be included in every API request to prevent DB constraint violations
      const paymentType: 'unique' | 'recurrent' = data.billType || 'unique';
      const paymentCount: '1' | 'multiple' = data.paymentStructure === 'single' ? '1' : 'multiple';
      const recurrence: boolean = data.billType === 'recurrent';
      
      // Calculate costs array based on payment structure
      let costs: string[] = [];
      let calculatedTotalAmount = data.totalAmount;
      
      if (data.paymentStructure === 'single') {
        costs = [data.singlePaymentAmount || '0'];
      } else if (data.paymentStructure === 'installment') {
        if (data.recurringPaymentsEqual) {
          // For equal installment payments - generate all 12 payment amounts
          const maxPayments = 12; // Default to 12 monthly payments
          
          if (data.hasInitialPayment && data.initialPaymentAmount) {
            // First payment is the initial amount
            costs.push(data.initialPaymentAmount);
            
            // Remaining payments use the recurring amount
            if (data.recurringPaymentAmount) {
              for (let i = 1; i < maxPayments; i++) {
                costs.push(data.recurringPaymentAmount);
              }
            }
          } else if (data.recurringPaymentAmount) {
            // All payments use the same recurring amount
            for (let i = 0; i < maxPayments; i++) {
              costs.push(data.recurringPaymentAmount);
            }
          }
        } else if (customPayments && customPayments.length > 0) {
          // For custom amounts - use component state customPayments for most up-to-date values
          costs = customPayments.map(p => p.amount).filter(a => a && a.trim() !== '');
          // ISSUE 2 FIX: Recompute totalAmount from custom payments during submission
          const computedTotal = customPayments.reduce((sum, p) => sum + parseFloat(p.amount || '0'), 0);
          calculatedTotalAmount = computedTotal.toFixed(2);
        }
        
        // Calculate total if not provided (for equal installments only)
        if (data.recurringPaymentsEqual && (!calculatedTotalAmount || calculatedTotalAmount.trim() === '')) {
          const total = costs.reduce((sum, cost) => sum + parseFloat(cost || '0'), 0);
          calculatedTotalAmount = total.toString();
        }
      }
      
      // Extract custom schedule dates for backend persistence - use component state customPayments
      // IMPORTANT: Do NOT filter out empty dates - we need to preserve array indices
      // to match costs[i] with scheduleCustom[i] for budget calculations
      let scheduleCustom: string[] = [];
      if (data.paymentStructure === 'installment' && !data.recurringPaymentsEqual && customPayments && customPayments.length > 0) {
        scheduleCustom = customPayments.map(p => p.date || '');
      }
      
      // CRITICAL: Construct bill data with BOTH new fields (billType, paymentStructure) 
      // AND legacy fields (paymentType, paymentCount, recurrence) for backward compatibility
      const billData: any = {
        ...data,
        billType: data.billType,
        paymentStructure: data.paymentStructure,
        paymentType,
        paymentCount,
        recurrence,
        buildingId: buildingId || bill?.buildingId,
        totalAmount: calculatedTotalAmount,
        costs,
        scheduleCustom,
        autoGenerateNextYear: data.billType === 'recurrent' && !data.endDate,
      };
      
      // Note: When updating an auto-generated bill, the backend will automatically
      // update the source template and sync changes. The auto-generated relationship
      // is preserved by design to keep bills in sync with their templates.
      
      if (data.paymentStructure === 'installment' && !data.recurringPaymentsEqual) {
        // Custom payment schedule - explicitly set schedulePayment to 'custom'
        billData.schedulePayment = 'custom';
        billData.recurringPaymentsEqual = false;
      } else if (data.paymentStructure === 'installment' && data.billType === 'recurrent') {
        // Installment payments with recurrent bills need schedule
        billData.schedulePayment = data.schedulePayment;
        // Include yearInterval only for yearly schedules
        if (data.schedulePayment === 'yearly') {
          billData.yearInterval = data.yearInterval || 1;
        }
      } else if (data.billType === 'recurrent' && data.paymentStructure === 'single') {
        // Single payment recurrent bills: default to yearly schedule
        billData.schedulePayment = 'yearly';
        billData.yearInterval = data.yearInterval || 1;
      } else {
        delete billData.schedulePayment;
        delete billData.yearInterval;
      }

      const response = await apiRequest(method, endpoint, billData);
      const billResponse = await response.json();
      
      // Upload attached documents if any
      const fileToUpload = aiFile;
      if (!bill && (fileToUpload || attachedFiles.length > 0)) {
        try {
          if (fileToUpload) {
            // Handle file upload
            // Uploading document for bill
            const formData = new FormData();
            formData.append('document', fileToUpload);
            
            const uploadResponse = await fetch(`/api/bills/${billResponse.id}/upload-document`, {
              method: 'POST',
              credentials: 'include',
              body: formData,
            });
            
            if (!uploadResponse.ok) {
              const errorText = await uploadResponse.text();
              console.error('[BILL FORM] Upload failed with status:', uploadResponse.status, errorText);
              throw new Error(`Upload failed: ${uploadResponse.status} ${errorText}`);
            }
            
            const uploadResult = await uploadResponse.json();
            // Document upload successful
            
            // Update the bill response with the document information from the upload
            if (uploadResult.bill) {
              billResponse.filePath = uploadResult.bill.filePath;
              billResponse.fileName = uploadResult.bill.fileName;
              billResponse.fileSize = uploadResult.bill.fileSize;
              billResponse.isAiAnalyzed = uploadResult.bill.isAiAnalyzed;
              billResponse.aiAnalysisData = uploadResult.bill.aiAnalysisData;
            }
            
            // Show success toast for document upload
            toast({
              title: 'Document Uploaded',
              description: `${fileToUpload.name} has been attached to the bill`,
            });
          } else if (attachedFiles.some(f => f.file.type === 'text/plain')) {
            // Handle text document from attached files
            const textFile = attachedFiles.find(f => f.file.type === 'text/plain');
            if (textFile) {
              // Creating text document for bill
              const formData = new FormData();
              formData.append('file', textFile.file);
            formData.append('name', `${billResponse.billNumber || billResponse.title} - Notes`);
            formData.append('description', 'Text document created for bill');
            formData.append('documentType', 'other');
            formData.append('attachedToType', 'bill');
            formData.append('attachedToId', billResponse.id);
            
            const uploadResponse = await fetch('/api/documents/upload', {
              method: 'POST',
              credentials: 'include',
              body: formData,
            });
            
            if (!uploadResponse.ok) {
              const errorText = await uploadResponse.text();
              console.error('[BILL FORM] Text document creation failed with status:', uploadResponse.status, errorText);
              throw new Error(`Text document creation failed: ${uploadResponse.status} ${errorText}`);
            }
            
            const uploadResult = await uploadResponse.json();
            // Text document creation successful
            
            // Show success toast for text document creation
            toast({
              title: 'Text Document Created',
              description: 'Your text content has been saved as a document attached to the bill',
            });
            }
          }
        } catch (uploadError) {
          console.error('[BILL FORM] Failed to upload/create document:', uploadError);
          const contentType = fileToUpload ? 'file' : 'text document';
          toast({
            title: 'Document Creation Failed',
            description: `Failed to create ${contentType}. The bill was created but without the document.`,
            variant: 'destructive',
          });
          // Don't fail the bill creation if document upload/creation fails
        }
      }
      
      return billResponse;
    },
    onSuccess: (data) => {
      // Invalidate all bill-related queries to ensure proper refresh
      queryClient.invalidateQueries({ queryKey: ['/api/bills'] });
      if (buildingId) {
        queryClient.invalidateQueries({ queryKey: ['/api/bills', buildingId] });
        queryClient.invalidateQueries({ queryKey: ['/api/bills/year-range', buildingId] });
      }
      toast({
        title: 'Success',
        description: `Bill ${(bill && !isTemplate) ? 'updated' : 'created'} successfully`,
      });
      onSuccess?.(data.id, (bill && !isTemplate) ? 'updated' : 'created');
    },
    onError: (error: any) => {
      toast({
        title: 'Error',
        description: error.message || `Failed to ${bill ? 'update' : 'create'} bill`,
        variant: 'destructive',
      });
    }
  });

  // Delete bill mutation
  const deleteBillMutation = useCreateUpdateMutation<unknown, void>({
    mutationFn: async () => {
      if (!bill?.id) throw new Error('No bill ID provided for deletion');
      return apiRequest('DELETE', `/api/bills/${bill.id}`, null);
    },
    successTitle: 'Success',
    successMessage: 'Bill deleted successfully',
    errorMessage: (error) => error?.message || 'Failed to delete bill',
    invalidateQueries: (_data, qc) => {
      // Invalidate all bill-related queries to ensure proper refresh
      qc.invalidateQueries({ queryKey: ['/api/bills'] });
      if (buildingId) {
        qc.invalidateQueries({ queryKey: ['/api/bills', buildingId] });
        qc.invalidateQueries({ queryKey: ['/api/bills/year-range', buildingId] });
      }
    },
    onSuccessCallback: () => {
      onSuccess?.(bill!.id, 'updated'); // Trigger parent refresh
    },
  });

  const onSubmit = (data: BillFormData) => {
    billMutation.mutate(data);
  };

  const handleDelete = () => {
    if (!bill) return;
    
    if (confirm(`Are you sure you want to delete bill "${bill.title}"? This action cannot be undone.`)) {
      deleteBillMutation.mutate();
    }
  };

  // Document management handlers
  const handleDeleteDocumentClick = (document: Document) => {
    setSelectedDocument(document);
    setShowDeleteDocDialog(true);
  };

  const deleteDocumentMutation = useCreateUpdateMutation<unknown, string>({
    mutationFn: async (documentId: string) => {
      return apiRequest('DELETE', `/api/documents/${documentId}`);
    },
    successTitle: t('success'),
    successMessage: t('documentDeletedSuccessfully'),
    errorTitle: t('error'),
    errorMessage: (error) => error?.message || t('documentDeleteFailed'),
    queryKeysToInvalidate: [
      ['/api/documents'],
      ['/api/bills', bill?.id, 'documents'],
    ],
    onSuccessCallback: () => {
      setShowDeleteDocDialog(false);
      setSelectedDocument(null);
    },
  });

  const handleConfirmDeleteDocument = () => {
    if (selectedDocument) {
      deleteDocumentMutation.mutate(selectedDocument.id);
    }
  };

  // Helper function to generate next payment date based on schedule
  const generateNextPaymentDate = (startDate: string, schedule: string, paymentIndex: number): string => {
    if (!startDate || !schedule) return '';
    
    const start = new Date(startDate);
    const endDate = form.getValues('endDate');
    
    // Calculate proper renewal date: endDate or startDate + 1 year
    let maxDate: Date;
    if (endDate && endDate.trim() !== '') {
      maxDate = new Date(endDate);
    } else {
      maxDate = new Date(start);
      maxDate.setFullYear(start.getFullYear() + 1);
    }
    
    let nextDate = new Date(start);
    
    switch (schedule) {
      case 'weekly':
        nextDate.setDate(start.getDate() + (paymentIndex * 7));
        break;
      case 'monthly':
        nextDate.setMonth(start.getMonth() + paymentIndex);
        break;
      case 'quarterly':
        nextDate.setMonth(start.getMonth() + (paymentIndex * 3));
        break;
      case 'yearly':
        nextDate.setFullYear(start.getFullYear() + paymentIndex);
        break;
      default:
        return '';
    }
    
    // Don't generate dates beyond the bill's renewal period
    if (nextDate >= maxDate) {
      return '';
    }
    
    return nextDate.toISOString().split('T')[0];
  };

  // Custom Payment Management
  const addCustomPayment = () => {
    const startDate = form.getValues('startDate');
    const endDate = form.getValues('endDate');
    const schedule = form.getValues('schedulePayment');
    const isCustomSchedule = schedule === 'custom';
    
    const newPayment: CustomPayment = { 
      amount: '', 
      date: isCustomSchedule ? '' : generateNextPaymentDate(startDate, schedule, customPayments.length),
      description: isCustomSchedule ? '' : `Payment ${customPayments.length + 1}` 
    };
    
    // Calculate proper renewal limit: endDate or startDate + 1 year
    let renewalLimit: Date;
    if (endDate && endDate.trim() !== '') {
      renewalLimit = new Date(endDate);
    } else if (startDate) {
      renewalLimit = new Date(startDate);
      renewalLimit.setFullYear(renewalLimit.getFullYear() + 1);
    } else {
      renewalLimit = new Date();
      renewalLimit.setFullYear(renewalLimit.getFullYear() + 1);
    }
    
    const paymentDate = new Date(newPayment.date);
    
    // Check if we're exceeding the bill's renewal period
    if (!isCustomSchedule && newPayment.date && paymentDate >= renewalLimit) {
      const limitDesc = endDate && endDate.trim() !== '' 
        ? 'the bill\'s end date' 
        : 'the next renewal period (1 year from start date)';
      toast({
        title: 'Payment Limit Reached',
        description: `Cannot add more payments beyond ${limitDesc}. Payment schedules are limited to the bill's active period.`,
        variant: 'destructive',
      });
      return;
    }
    
    const newPayments = [...customPayments, newPayment];
    setCustomPayments(newPayments);
    form.setValue('customPayments', newPayments, { shouldDirty: true, shouldTouch: true });
  };

  const removeCustomPayment = (index: number) => {
    const updated = customPayments.filter((_, i) => i !== index);
    setCustomPayments(updated);
    form.setValue('customPayments', updated, { shouldDirty: true, shouldTouch: true });
  };

  const updateCustomPayment = (index: number, field: keyof CustomPayment, value: string) => {
    const updated = customPayments.map((payment, i) => 
      i === index ? { ...payment, [field]: value } : payment
    );
    setCustomPayments(updated);
    form.setValue('customPayments', updated, { shouldDirty: true, shouldTouch: true });
  };

  return (
    <div className="space-y-6">
      {/* Notice for auto-generated bills - inform user that edits update the source template */}
      {bill?.isAutoGenerated && bill?.sourceTemplateId && (
        <div className="p-4 bg-blue-50 dark:bg-blue-950 rounded-lg border border-blue-200 dark:border-blue-800">
          <div className="flex items-center gap-2">
            <AlertCircle className="w-5 h-5 text-blue-600 dark:text-blue-400" />
            <span className="text-blue-700 dark:text-blue-300 font-medium">
              {language === 'fr' 
                ? 'Modification du modèle source' 
                : 'Editing source template'}
            </span>
          </div>
          <p className="text-sm text-blue-600 dark:text-blue-400 mt-1">
            {language === 'fr'
              ? 'Les modifications apportées à cette facture auto-générée seront appliquées au modèle source. Les futures factures générées automatiquement refléteront ces changements.'
              : 'Changes made to this auto-generated bill will be applied to the source template. Future auto-generated bills will reflect these changes.'}
          </p>
        </div>
      )}

      {aiExtractionData && (
        <div className="flex justify-end">
          <Badge variant="secondary" className="flex items-center gap-1">
            <Sparkles className="w-3 h-3" />
            {t('bills.aiExtracted')}
          </Badge>
        </div>
      )}

      {!bill && (
        <Tabs defaultValue="manual" className="space-y-4">
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger value="manual" data-testid="tab-manual">
              <FileText className="w-4 h-4 mr-2" />
              {t('bills.manualEntry')}
            </TabsTrigger>
            {aiEnabled && (
              <TabsTrigger value="ai" data-testid="tab-ai">
                <Sparkles className="w-4 h-4 mr-2" />
                {t('bills.aiExtraction')}
              </TabsTrigger>
            )}
          </TabsList>

          {aiEnabled && (
            <TabsContent value="ai" className="space-y-4">
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Sparkles className="w-5 h-5" />
                    {t('bills.uploadBillDocument')}
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <SharedUploader
                    onDocumentChange={handleFileUpload}
                    formType="bills"
                    uploadContext={uploadContext}
                    aiAnalysisEnabled={aiEnabled}
                    onAiToggle={handleAiToggle}
                    onAiAnalysisComplete={handleAiAnalysisComplete}
                    showAiToggle={false}
                    allowedFileTypes={['image/*', 'application/pdf']}
                    maxFileSize={25}
                  />
                  
                  {isExtracting && (
                    <div className="mt-4 p-4 bg-blue-50 dark:bg-blue-950 rounded-lg border border-blue-200 dark:border-blue-800">
                      <div className="flex items-center gap-2">
                        <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-blue-600"></div>
                        <span className="text-blue-700 dark:text-blue-300 font-medium">
                          Extracting data from your document...
                        </span>
                      </div>
                      <p className="text-sm text-blue-600 dark:text-blue-400 mt-1">
                        This may take a few seconds depending on document complexity.
                      </p>
                    </div>
                  )}
                  
                  {aiFile && (
                    <GeminiBillExtractor
                      file={aiFile}
                      language={language}
                      onExtractionComplete={handleAiExtractionComplete}
                    />
                  )}
                </CardContent>
              </Card>
            </TabsContent>
          )}


          <TabsContent value="manual" className="space-y-4">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <FileText className="w-5 h-5" />
                  {t('bills.uploadDocumentOptional')}
                </CardTitle>
              </CardHeader>
              <CardContent>
                <SharedUploader
                  onDocumentChange={handleFileUpload}
                  formType="bills"
                  uploadContext={uploadContext}
                  aiAnalysisEnabled={false} // Disabled in manual entry
                  showAiToggle={false} // Don't show toggle in manual entry
                  allowedFileTypes={['image/*', 'application/pdf']}
                  maxFileSize={25}
                />
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      )}

      {/* Bill Form */}
      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit, (errors) => {
          console.error('❌ [BILL FORM] Form validation failed:', errors);
          
          // Check for specific custom payments date error
          let errorDescription = t('validationFailed') || 'Please check the form for errors and try again.';
          if (errors.customPayments?.message) {
            errorDescription = errors.customPayments.message;
          }
          
          toast({
            title: t('validationFailed') || 'Form Validation Error',
            description: errorDescription,
            variant: 'destructive',
          });
        })} className="space-y-6">
          <StandardFormGrid>
            {/* Title */}
            <FormField
              control={form.control}
              name="title"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>{t('bills.title')} <span className="text-red-500">*</span></FormLabel>
                  <FormControl>
                    <Input placeholder="e.g., Monthly Electricity Bill" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            {/* Vendor */}
            <FormField
              control={form.control}
              name="vendor"
              render={({ field }) => (
                <FormItem>
                  <FormLabel className="flex items-center">
                    {t('bills.vendor')}
                    {aiExtractionData?.fieldConfidence && (
                      <ConfidenceIndicator 
                        confidence={aiExtractionData.fieldConfidence.vendorName} 
                        fieldName="vendor"
                        t={t}
                      />
                    )}
                  </FormLabel>
                  <FormControl>
                    <Input placeholder="e.g., Hydro Quebec" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            {/* Vendor invoice number (from the document, not the system bill #) */}
            <FormField
              control={form.control}
              name="vendorInvoiceNumber"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>{t('bills.vendorInvoiceNumber') || 'Bill / Invoice Number'}</FormLabel>
                  <FormControl>
                    <Input
                      placeholder="e.g., INV-12345"
                      {...field}
                      value={field.value ?? ''}
                      data-testid="input-vendor-invoice-number"
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            {/* Issue date (date printed on the document) */}
            <FormField
              control={form.control}
              name="issueDate"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>{t('bills.issueDate') || 'Issue Date'}</FormLabel>
                  <FormControl>
                    <Input
                      type="date"
                      {...field}
                      value={field.value ?? ''}
                      data-testid="input-issue-date"
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            {/* Category */}
            <FormField
              control={form.control}
              name="category"
              render={({ field }) => (
                <FormItem>
                  <FormLabel className="flex items-center">
                    {t('bills.category')} <span className="text-red-500">*</span>
                    {aiExtractionData?.fieldConfidence && (
                      <ConfidenceIndicator 
                        confidence={aiExtractionData.fieldConfidence.category} 
                        fieldName="category"
                        t={t}
                      />
                    )}
                  </FormLabel>
                  <Select onValueChange={field.onChange} value={field.value}>
                    <FormControl>
                      <SelectTrigger>
                        <SelectValue placeholder="Select category" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      {[...BILL_CATEGORIES]
                        .sort((a, b) => getCategoryLabel(a, t).localeCompare(getCategoryLabel(b, t)))
                        .map((category) => (
                          <SelectItem key={category} value={category}>
                            {getCategoryLabel(category, t)}
                          </SelectItem>
                        ))}
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />

            {/* Status */}
            <FormField
              control={form.control}
              name="status"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>{t('bills.status')} <span className="text-red-500">*</span></FormLabel>
                  <Select onValueChange={field.onChange} value={field.value}>
                    <FormControl>
                      <SelectTrigger>
                        <SelectValue placeholder="Select status" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      <SelectItem value="draft">{t('bills.statusDraft')}</SelectItem>
                      <SelectItem value="sent">{t('bills.statusSent')}</SelectItem>
                      <SelectItem value="overdue">{t('bills.statusOverdue')}</SelectItem>
                      <SelectItem value="paid">{t('bills.statusPaid')}</SelectItem>
                      <SelectItem value="cancelled">{t('bills.statusCancelled')}</SelectItem>
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />

            {/* Bill Type */}
            <FormField
              control={form.control}
              name="billType"
              render={({ field }) => (
                <FormItem>
                  <FormLabel className="flex items-center">
                    {t('bills.billType')} <span className="text-red-500">*</span>
                    {aiExtractionData?.fieldConfidence && (
                      <ConfidenceIndicator 
                        confidence={aiExtractionData.fieldConfidence.paymentType} 
                        fieldName="billType"
                        t={t}
                      />
                    )}
                  </FormLabel>
                  <FormControl>
                    <RadioGroup
                      onValueChange={field.onChange}
                      value={field.value}
                      className="flex gap-4"
                      data-testid="radio-bill-type"
                    >
                      <div className="flex items-center space-x-2">
                        <RadioGroupItem value="unique" id="bill-type-unique" data-testid="radio-bill-type-unique" />
                        <Label htmlFor="bill-type-unique" className="font-normal cursor-pointer">
                          {t('bills.billTypeUnique')}
                        </Label>
                      </div>
                      <div className="flex items-center space-x-2">
                        <RadioGroupItem value="recurrent" id="bill-type-recurrent" data-testid="radio-bill-type-recurrent" />
                        <Label htmlFor="bill-type-recurrent" className="font-normal cursor-pointer">
                          {t('bills.billTypeRecurrent')}
                        </Label>
                      </div>
                    </RadioGroup>
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            {/* Payment Structure */}
            <FormField
              control={form.control}
              name="paymentStructure"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>{t('bills.paymentStructure')} <span className="text-red-500">*</span></FormLabel>
                  <FormControl>
                    <RadioGroup
                      onValueChange={field.onChange}
                      value={field.value}
                      className="flex gap-4"
                      data-testid="radio-payment-structure"
                    >
                      <div className="flex items-center space-x-2">
                        <RadioGroupItem value="single" id="payment-structure-single" data-testid="radio-payment-structure-single" />
                        <Label htmlFor="payment-structure-single" className="font-normal cursor-pointer">
                          {t('bills.paymentStructureSingle')}
                        </Label>
                      </div>
                      <div className="flex items-center space-x-2">
                        <RadioGroupItem value="installment" id="payment-structure-installment" data-testid="radio-payment-structure-installment" />
                        <Label htmlFor="payment-structure-installment" className="font-normal cursor-pointer">
                          {t('bills.paymentStructureInstallment')}
                        </Label>
                      </div>
                    </RadioGroup>
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            {/* Payment Amount - Only for single payment */}
            {paymentStructure === 'single' && (
              <FormField
                control={form.control}
                name="singlePaymentAmount"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel className="flex items-center">
                      {t('bills.singlePaymentAmount')} <span className="text-red-500">*</span>
                      {aiExtractionData?.fieldConfidence && (
                        <ConfidenceIndicator 
                          confidence={aiExtractionData.fieldConfidence.totalAmount} 
                          fieldName="amount"
                          t={t}
                        />
                      )}
                    </FormLabel>
                    <FormControl>
                      <Input placeholder="0.00" type="number" step="0.01" {...field} data-testid="input-payment-amount" />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            )}

            {/* Start Date */}
            <FormField
              control={form.control}
              name="startDate"
              render={({ field }) => (
                <FormItem>
                  <FormLabel className="flex items-center">
                    {t('bills.startDate')} <span className="text-red-500">*</span>
                    {aiExtractionData?.fieldConfidence && (
                      <ConfidenceIndicator 
                        confidence={aiExtractionData.fieldConfidence.dueDate} 
                        fieldName="date"
                        t={t}
                      />
                    )}
                  </FormLabel>
                  <FormControl>
                    <Input type="date" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
          </StandardFormGrid>

          {/* Recurrent Bill Configuration - Only shown for recurrent bills with single payment */}
          {billType === 'recurrent' && paymentStructure === 'single' && (
            <div className="space-y-4">
              {/* Year Interval for Recurrent Single Payment */}
              <FormField
                control={form.control}
                name="yearInterval"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('bills.yearInterval')}</FormLabel>
                    <FormControl>
                      <Input 
                        type="number" 
                        min="1" 
                        max="99" 
                        placeholder="1" 
                        {...field}
                        onChange={(e) => field.onChange(e.target.value ? parseInt(e.target.value) : 1)}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              {/* End Date for Recurrent Bills */}
              <FormField
                control={form.control}
                name="endDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('bills.recurrenceEndDate')}</FormLabel>
                    <FormControl>
                      <Input 
                        type="date" 
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>
          )}

          {/* Payment Configuration - Only shown for installment payments */}
          {paymentStructure === 'installment' && (
            <div className="space-y-4">
              <FormField
                control={form.control}
                name="schedulePayment"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel className="flex items-center">
                      {t('bills.paymentSchedule')}
                      {aiExtractionData?.fieldConfidence && (
                        <ConfidenceIndicator 
                          confidence={aiExtractionData.fieldConfidence.frequency} 
                          fieldName="schedule"
                          t={t}
                        />
                      )}
                    </FormLabel>
                    <Select onValueChange={field.onChange} value={field.value || ''}>
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder="Select schedule" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        <SelectItem value="weekly">{t('bills.scheduleWeekly')}</SelectItem>
                        <SelectItem value="monthly">{t('bills.scheduleMonthly')}</SelectItem>
                        <SelectItem value="quarterly">{t('bills.scheduleQuarterly')}</SelectItem>
                        <SelectItem value="yearly">{t('bills.scheduleYearly')}</SelectItem>
                        <SelectItem value="custom">{t('bills.scheduleCustom')}</SelectItem>
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />

              {/* Year Interval - Only shown for yearly schedules */}
              {schedulePayment === 'yearly' && (
                <FormField
                  control={form.control}
                  name="yearInterval"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('bills.yearInterval')}</FormLabel>
                      <FormControl>
                        <Input 
                          type="number" 
                          min="1" 
                          max="99" 
                          placeholder="1" 
                          {...field}
                          onChange={(e) => field.onChange(e.target.value ? parseInt(e.target.value) : 1)}
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              )}

              {/* Smart Payment Configuration */}
              <div className="space-y-4 p-4 border rounded-lg bg-gray-50 dark:bg-gray-900">
                <h4 className="font-medium text-sm text-gray-700 dark:text-gray-300">{t('bills.paymentConfiguration')}</h4>
                
                {/* Initial Payment Question */}
                <FormField
                  control={form.control}
                  name="hasInitialPayment"
                  render={({ field }) => (
                    <FormItem className="flex flex-row items-center justify-between rounded-lg border p-3">
                      <div className="space-y-0.5">
                        <FormLabel className="text-base">{t('bills.initialPayment')}</FormLabel>
                      </div>
                      <FormControl>
                        <input
                          type="checkbox"
                          checked={field.value}
                          onChange={(e) => field.onChange(e.target.checked)}
                          className="h-4 w-4"
                        />
                      </FormControl>
                    </FormItem>
                  )}
                />

                {/* Recurring Payments Equal Question */}
                <FormField
                  control={form.control}
                  name="recurringPaymentsEqual"
                  render={({ field }) => (
                    <FormItem className="flex flex-row items-center justify-between rounded-lg border p-3">
                      <div className="space-y-0.5">
                        <FormLabel className="text-base">{t('bills.equalRecurringPayments')}</FormLabel>
                      </div>
                      <FormControl>
                        <input
                          type="checkbox"
                          checked={field.value}
                          onChange={(e) => field.onChange(e.target.checked)}
                          className="h-4 w-4"
                        />
                      </FormControl>
                    </FormItem>
                  )}
                />
              </div>

              {/* Conditional Payment Amount Fields */}
              <StandardFormGrid>
                {/* Initial Payment Amount */}
                {hasInitialPayment && (
                  <FormField
                    control={form.control}
                    name="initialPaymentAmount"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>{t('bills.initialPaymentAmount')}</FormLabel>
                        <FormControl>
                          <Input placeholder="0.00" type="number" step="0.01" {...field} />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                )}

                {/* Recurring Payment Amount - hide for custom schedule since amounts are defined per payment */}
                {recurringPaymentsEqual && schedulePayment !== 'custom' && (
                  <FormField
                    control={form.control}
                    name="recurringPaymentAmount"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>{t('bills.recurringPaymentAmount')}</FormLabel>
                        <FormControl>
                          <Input placeholder="0.00" type="number" step="0.01" {...field} />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                )}
              </StandardFormGrid>

              {/* End Date for Recurrent Bills with Installments */}
              {billType === 'recurrent' && (
                <FormField
                  control={form.control}
                  name="endDate"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('bills.recurrenceEndDate')}</FormLabel>
                      <FormControl>
                        <Input 
                          type="date" 
                          {...field}
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              )}

              {(schedulePayment === 'custom' || !recurringPaymentsEqual) && (
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center justify-between">
                      <span>{schedulePayment === 'custom' ? t('bills.customPaymentSchedule') : t('bills.individualPaymentAmounts')}</span>
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={addCustomPayment}
                      >
                        <Plus className="w-4 h-4 mr-2" />
                        {t('bills.addPayment')}
                      </Button>
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-3">
                    <div className="text-sm text-gray-600 dark:text-gray-400 mb-3">
                      {schedulePayment === 'custom' 
                        ? t('bills.customPaymentScheduleDescription')
                        : t('bills.individualPaymentAmountsDescription')}
                    </div>
                    <div className="max-h-60 overflow-y-auto space-y-3">
                      {customPayments.map((payment, index) => (
                        <div key={`payment-${index}-${payment.amount}`} className="flex gap-2 items-end p-3 border rounded bg-white dark:bg-gray-800">
                          <div className="flex-1">
                            <label className="text-xs text-gray-500 dark:text-gray-400">{t('bills.amount')}</label>
                            <Input
                              placeholder="0.00"
                              type="number"
                              step="0.01"
                              value={payment.amount}
                              onChange={(e) => updateCustomPayment(index, 'amount', e.target.value)}
                              className="mt-1"
                            />
                          </div>
                          {schedulePayment === 'custom' && (
                            <div className="flex-1">
                              <label className="text-xs text-gray-500 dark:text-gray-400">{t('bills.date')}</label>
                              <Input
                                type="date"
                                value={payment.date}
                                onChange={(e) => updateCustomPayment(index, 'date', e.target.value)}
                                max={new Date(new Date().getFullYear() + 1, 11, 31).toISOString().split('T')[0]}
                                className="mt-1"
                              />
                            </div>
                          )}
                          <div className="flex-1">
                            <label className="text-xs text-gray-500 dark:text-gray-400">{t('bills.description')}</label>
                            <Input
                              placeholder={schedulePayment === 'custom' ? 'Payment description' : `Payment ${index + 1}`}
                              value={payment.description || ''}
                              onChange={(e) => updateCustomPayment(index, 'description', e.target.value)}
                              className="mt-1"
                            />
                          </div>
                          <Button
                            type="button"
                            variant="outline"
                            size="sm"
                            onClick={() => removeCustomPayment(index)}
                            className="flex-shrink-0"
                          >
                            <X className="w-4 h-4" />
                          </Button>
                        </div>
                      ))}
                    </div>
                    {customPayments.length === 0 && (
                      <div className="text-center py-4 text-gray-500 dark:text-gray-400">
                        <Calendar className="w-8 h-8 mx-auto mb-2 opacity-50" />
                        <p className="text-sm">No payments added yet</p>
                        <p className="text-xs">Click "Add Payment" to get started</p>
                      </div>
                    )}
                  </CardContent>
                </Card>
              )}
            </div>
          )}

          {/* Description */}
          <FormField
            control={form.control}
            name="description"
            render={({ field }) => (
              <FormItem>
                <FormLabel>{t('bills.description')}</FormLabel>
                <FormControl>
                  <Textarea
                    placeholder="Additional details about this bill..."
                    className="min-h-[100px]"
                    {...field}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          {/* Display attached documents if editing existing bill */}
          {bill?.id && (
            <div className="space-y-4">
              <div className="border-t pt-6">
                <div className="space-y-4 mb-4">
                  <h4 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
                    {t('attachedDocuments')} ({attachedDocuments.length})
                  </h4>
                  
                  <Card>
                    <CardHeader>
                      <CardTitle className="text-base">{t('addDocument')}</CardTitle>
                    </CardHeader>
                    <CardContent>
                      <SharedUploader
                        onDocumentChange={handleBillDocumentAttachment}
                        formType="bills"
                        uploadContext={uploadContext}
                        aiAnalysisEnabled={bill?.isAutoGenerated && !isTemplate}
                        showAiToggle={bill?.isAutoGenerated && !isTemplate}
                        onAiToggle={handleAiToggle}
                        onAiAnalysisComplete={handleAiAnalysisComplete}
                        allowedFileTypes={['image/*', 'application/pdf']}
                        maxFileSize={25}
                      />
                      
                      {bill?.isAutoGenerated && !isTemplate && isExtracting && (
                        <div className="mt-4 p-4 bg-blue-50 dark:bg-blue-950 rounded-lg border border-blue-200 dark:border-blue-800">
                          <div className="flex items-center gap-2">
                            <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-blue-600"></div>
                            <span className="text-blue-700 dark:text-blue-300 font-medium">
                              {t('bills.extractingData') || 'Extracting data from your document...'}
                            </span>
                          </div>
                          <p className="text-sm text-blue-600 dark:text-blue-400 mt-1">
                            {t('bills.extractingDataNote') || 'This may take a few seconds depending on document complexity.'}
                          </p>
                        </div>
                      )}
                      
                      {bill?.isAutoGenerated && !isTemplate && aiFile && (
                        <GeminiBillExtractor
                          file={aiFile}
                          language={language}
                          onExtractionComplete={handleAiExtractionComplete}
                        />
                      )}
                    </CardContent>
                  </Card>
                </div>
                {attachedDocuments.length > 0 ? (
                  <div className="grid gap-3">
                    {attachedDocuments.map((document) => (
                      <div key={document.id} className="flex items-center gap-2 border rounded-lg p-4 bg-gray-50 dark:bg-gray-800">
                        <div className="flex-1">
                          <AttachedFileSection
                            entityType="document"
                            entityId={document.id}
                            filePath={document.filePath}
                            fileName={document.fileName || document.name}
                            fileSize={document.fileSize}
                            canView={true}
                            canDownload={true}
                            className="bg-transparent hover:bg-transparent p-0"
                            fallbackName={document.name || 'Bill Attachment'}
                            data-testid={`attachment-${document.id}`}
                          />
                        </div>
                        <Button
                          type="button"
                          variant="ghost"
                          size="sm"
                          onClick={() => handleDeleteDocumentClick(document)}
                          className="h-8 w-8 p-0 text-red-600 hover:text-red-700 hover:bg-red-50 dark:hover:bg-red-950"
                          data-testid={`button-delete-doc-${document.id}`}
                        >
                          <Trash2 className="w-4 h-4" />
                        </Button>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="text-center py-8 text-gray-500 dark:text-gray-400 border-2 border-dashed rounded-lg">
                    <FileText className="w-8 h-8 mx-auto mb-2 opacity-50" />
                    <p className="text-sm">{t('noDocumentsAttached')}</p>
                    <p className="text-xs">{t('clickAddDocumentToStart')}</p>
                  </div>
                )}
              </div>
            </div>
          )}

          {/* Calculated Total Amount Display */}
          <Card className="bg-blue-50 dark:bg-blue-950 border-blue-200 dark:border-blue-800">
            <CardContent className="pt-6">
              <div className="flex items-center justify-between">
                <div className="space-y-1">
                  <h4 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
                    {t('bills.calculatedTotalAmount')}
                  </h4>
                  <p className="text-sm text-gray-600 dark:text-gray-400">
                    {paymentStructure === 'single' 
                      ? t('bills.totalAmountSingleDescription')
                      : paymentStructure === 'installment' && recurringPaymentsEqual 
                        ? t('bills.totalAmountMultipleEqualDescription')
                        : t('bills.totalAmountMultipleCustomDescription')}
                  </p>
                </div>
                <div className="text-right">
                  <div className="text-3xl font-bold text-blue-600 dark:text-blue-400" data-testid="text-calculated-total">
                    ${paymentStructure === 'single' 
                      ? parseFloat(form.watch('totalAmount') || '0').toFixed(2)
                      : calculatedTotal.toFixed(2)}
                  </div>
                  <Badge variant="secondary" className="mt-2">
                    {paymentStructure === 'installment' ? t('bills.autoCalculatedBadge') : t('bills.fromPaymentAmountBadge')}
                  </Badge>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Form Actions */}
          <div className="flex justify-between items-center">
            {/* Delete button on the left (only for existing bills, not when using as template) */}
            <div>
              {bill?.id && !isTemplate && (
                <Button 
                  type="button" 
                  variant="destructive" 
                  onClick={handleDelete} 
                  disabled={deleteBillMutation.isPending}
                  data-testid="button-delete-bill"
                >
                  {deleteBillMutation.isPending ? t('bills.deleting') : t('bills.deleteBill')}
                </Button>
              )}
            </div>
            
            {/* Cancel and Save/Update buttons on the right */}
            <div className="flex gap-2">
              {onCancel && (
                <Button type="button" variant="outline" onClick={onCancel}>
                  {t('bills.cancel')}
                </Button>
              )}
              <Button 
                type="submit" 
                disabled={billMutation.isPending}
                data-testid={(bill && !isTemplate) ? "button-update-bill" : "button-create-bill"}
              >
                {billMutation.isPending ? t('bills.processing') : ((bill && !isTemplate) ? t('bills.updateBill') : t('bills.createBill'))}
              </Button>
            </div>
          </div>
        </form>
      </Form>

      {/* Document Delete Confirmation Dialog */}
      <AlertDialog open={showDeleteDocDialog} onOpenChange={setShowDeleteDocDialog}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>{t('confirmDeleteDocument')}</AlertDialogTitle>
            <AlertDialogDescription>
              {t('confirmDeleteDocumentMessage')}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel onClick={() => {
              setShowDeleteDocDialog(false);
              setSelectedDocument(null);
            }}>
              {t('cancel')}
            </AlertDialogCancel>
            <AlertDialogAction
              onClick={handleConfirmDeleteDocument}
              disabled={deleteDocumentMutation.isPending}
              className="bg-red-600 hover:bg-red-700"
            >
              {deleteDocumentMutation.isPending ? t('deleting') : t('delete')}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}