/**
 * @jest-environment jsdom
 *
 * Jank-regression guard for the manager Bills page (extends task #1163).
 *
 * BillsPage already routes free-form text filters through useDeferredValue
 * and dispatches non-text filter changes through startTransition (see the
 * `handleFilterChange` / `handleMonthToggle` / `handleAllMonthsToggle`
 * helpers in `client/src/pages/manager/bills.tsx`). Without those wrappers
 * the heavy `/api/bills` refetch + grouped category re-render runs inside
 * the click / change handler and Chromium prints the
 * "[Violation] '<event>' handler took N ms" warnings the harness is
 * designed to catch.
 *
 * This file mirrors the InventoryPage jank guard (task #1163) so a future
 * refactor that drops the deferred wrappers — or introduces new
 * synchronous heavy work into a search/filter handler — fails CI instead
 * of silently regressing the UX.
 */

import React from 'react';
import { render, screen, fireEvent, act } from '@testing-library/react';
import '@testing-library/jest-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

import { installJankDetector, type JankDetector } from '../../utils/jank-detector';

// HOC mock: pass a stable set of hierarchical props to the wrapped page so
// BillsPage actually renders its body instead of the org/building picker.
jest.mock('../../../client/src/components/hoc/withHierarchicalSelection', () => ({
  withHierarchicalSelection: (Component: any) =>
    function HierarchicalWrapper(props: any) {
      return (
        <Component
          {...props}
          organizationId="test-org-id"
          buildingId="test-building-id"
          buildingName="Test Building"
          showBackButton={false}
          backButtonLabel="Back"
          onBack={() => {}}
        />
      );
    },
}));

// Force the filters panel always-expanded and pass each filter's
// `customComponent` straight through. The real CollapsibleFilters keeps
// the inputs hidden until the user clicks the toggle, which would defeat
// the purpose of measuring keystroke / click handlers below.
jest.mock('../../../client/src/components/ui/collapsible-filters', () => ({
  CollapsibleFilters: ({ filters }: any) => (
    <div data-testid="collapsible-filters-stub">
      {filters?.map((f: any) => (
        <div key={f.id} data-testid={`filter-slot-${f.id}`}>
          {f.customComponent}
        </div>
      ))}
    </div>
  ),
}));

// Cheap stubs for the heavy bill bundles. The detector measures any
// wall-clock cost a future regression introduces directly into the
// BillsPage handlers themselves; the inner forms / viewers have their
// own coverage and are not the subject of this test.
jest.mock('../../../client/src/components/bill-management/ModularBillForm', () => ({
  __esModule: true,
  default: () => <div data-testid="modular-bill-form" />,
}));
jest.mock('../../../client/src/components/common/AiUnavailableBanner', () => ({
  AiUnavailableBanner: () => <div data-testid="ai-unavailable-banner" />,
}));
jest.mock('../../../client/src/components/common/DocumentInlineViewer', () => ({
  DocumentInlineViewer: () => <div data-testid="document-inline-viewer" />,
}));

jest.mock('../../../client/src/components/layout/header', () => ({
  Header: ({ title }: any) => <div data-testid="header">{title}</div>,
}));

// Lightweight stand-ins for shadcn primitives that wire the real
// onChange / onClick straight through, so fireEvent actually reaches the
// BillsPage handlers instead of being absorbed by Radix internals.
jest.mock('../../../client/src/components/ui/button', () => ({
  Button: ({ children, onClick, ...rest }: any) => (
    <button onClick={onClick} {...rest}>{children}</button>
  ),
}));
jest.mock('../../../client/src/components/ui/input', () => ({
  Input: ({ value, onChange, ...rest }: any) => (
    <input value={value ?? ''} onChange={onChange} {...rest} />
  ),
}));
jest.mock('../../../client/src/components/ui/label', () => ({
  Label: ({ children, ...rest }: any) => <label {...rest}>{children}</label>,
}));
jest.mock('../../../client/src/components/ui/badge', () => ({
  Badge: ({ children }: any) => <span>{children}</span>,
}));
jest.mock('../../../client/src/components/ui/skeleton', () => ({
  Skeleton: () => <div data-testid="skeleton" />,
}));
jest.mock('../../../client/src/components/ui/checkbox', () => ({
  Checkbox: ({ checked, onCheckedChange, ...rest }: any) => (
    <input
      type="checkbox"
      checked={!!checked}
      onChange={(e) => onCheckedChange?.(e.target.checked)}
      {...rest}
    />
  ),
}));
jest.mock('../../../client/src/components/ui/auto-generated-badge', () => ({
  AutoGeneratedBadge: ({ children }: any) => <span>{children}</span>,
}));
jest.mock('../../../client/src/components/ui/clear-filters', () => ({
  ClearFilters: () => <div data-testid="clear-filters" />,
}));

// Tabs / Dialog / AlertDialog / Popover are not exercised by the
// keystroke + filter flows under test; render their children so the
// page tree mounts without pulling in Radix.
jest.mock('../../../client/src/components/ui/tabs', () => ({
  Tabs: ({ children }: any) => <div>{children}</div>,
  TabsContent: ({ children }: any) => <div>{children}</div>,
  TabsList: ({ children }: any) => <div>{children}</div>,
  TabsTrigger: ({ children }: any) => <div>{children}</div>,
}));
jest.mock('../../../client/src/components/ui/dialog', () => ({
  Dialog: ({ children }: any) => <div>{children}</div>,
  DialogContent: ({ children }: any) => <div>{children}</div>,
  DialogDescription: ({ children }: any) => <div>{children}</div>,
  DialogHeader: ({ children }: any) => <div>{children}</div>,
  DialogTitle: ({ children }: any) => <div>{children}</div>,
  DialogTrigger: ({ children }: any) => <div>{children}</div>,
}));
jest.mock('../../../client/src/components/ui/alert-dialog', () => ({
  AlertDialog: ({ children }: any) => <div>{children}</div>,
  AlertDialogContent: ({ children }: any) => <div>{children}</div>,
  AlertDialogDescription: ({ children }: any) => <div>{children}</div>,
  AlertDialogFooter: ({ children }: any) => <div>{children}</div>,
  AlertDialogHeader: ({ children }: any) => <div>{children}</div>,
  AlertDialogTitle: ({ children }: any) => <div>{children}</div>,
  AlertDialogCancel: ({ children }: any) => <div>{children}</div>,
  AlertDialogAction: ({ children }: any) => <div>{children}</div>,
}));
jest.mock('../../../client/src/components/ui/popover', () => ({
  Popover: ({ children }: any) => <div>{children}</div>,
  PopoverContent: ({ children }: any) => <div>{children}</div>,
  PopoverTrigger: ({ children }: any) => <div>{children}</div>,
}));

// shadcn Select wired so onValueChange fires when we click a SelectItem,
// matching the way the real popover works from the user's perspective.
jest.mock('../../../client/src/components/ui/select', () => {
  const ActualReact = jest.requireActual('react') as typeof import('react');
  const SelectCtx = ActualReact.createContext<((v: string) => void) | undefined>(undefined);
  return {
    Select: ({ children, onValueChange }: any) => (
      <SelectCtx.Provider value={onValueChange}>
        <div data-testid="select-root">{children}</div>
      </SelectCtx.Provider>
    ),
    SelectTrigger: ({ children, ...rest }: any) => <div {...rest}>{children}</div>,
    SelectValue: ({ placeholder }: any) => <span>{placeholder}</span>,
    SelectContent: ({ children }: any) => <div>{children}</div>,
    SelectItem: ({ children, value }: any) => {
      const onValueChange = ActualReact.useContext(SelectCtx);
      return (
        <button
          data-testid={`select-item-${value}`}
          onClick={() => onValueChange?.(value)}
        >
          {children}
        </button>
      );
    },
  };
});

jest.mock('lucide-react', () => new Proxy({}, {
  get: () => () => <span />,
}));

jest.mock('@/hooks/use-toast', () => ({
  useToast: () => ({ toast: jest.fn() }),
}));

jest.mock('@/hooks/use-language', () => ({
  useLanguage: () => ({
    language: 'en',
    t: (key: string) => key,
    setLanguage: jest.fn(),
  }),
  LanguageProvider: ({ children }: any) => children,
}));

jest.mock('@/lib/queryClient', () => ({
  apiRequest: jest.fn().mockResolvedValue({
    ok: true,
    json: async () => ({}),
  }),
  queryClient: {
    invalidateQueries: jest.fn(),
    refetchQueries: jest.fn(),
  },
}));

import BillsPage from '../../../client/src/pages/manager/bills';

function renderBillsPage() {
  const queryClient = new QueryClient({
    defaultOptions: { queries: { retry: false }, mutations: { retry: false } },
  });
  return render(
    <QueryClientProvider client={queryClient}>
      <BillsPage />
    </QueryClientProvider>,
  );
}

describe('BillsPage — UI jank guard (extends task #1163)', () => {
  let detector: JankDetector;

  beforeEach(() => {
    // 100 ms convention shared across the jank-guard suites: anything
    // above this prints as "[Violation] '<event>' handler took N ms" in
    // Chromium, which is the user-visible regression we want to catch.
    detector = installJankDetector({ thresholdMs: 100 });
    global.fetch = jest.fn().mockResolvedValue({
      ok: true,
      headers: { get: () => 'application/json' },
      json: async () => [],
    }) as any;
  });

  afterEach(() => {
    detector.uninstall();
  });

  it('typing in the bills search field stays responsive', () => {
    renderBillsPage();

    const input = screen.getByTestId('input-search-bills') as HTMLInputElement;

    // BillsPage routes the active filters through useDeferredValue so the
    // controlled <Input> updates urgently while the heavy `/api/bills`
    // refetch + grouped category re-render run at lower priority.
    for (const value of ['e', 'el', 'ele', 'elec', 'elect', 'electric']) {
      detector.runAndMeasure(`type "${value}"`, () => {
        fireEvent.change(input, { target: { value } });
      });
    }
    act(() => {});

    detector.assertNoJank();
  });

  it('changing a non-text filter does not block the click handler', () => {
    renderBillsPage();

    // Category is dispatched through startTransition inside the
    // `handleFilterChange` helper. Without that wrapper the heavy
    // `/api/bills` refetch would run inside the click and trip the
    // detector.
    detector.runAndMeasure('change category filter', () => {
      fireEvent.click(screen.getByTestId('select-item-utilities'));
    });
    act(() => {});

    detector.assertNoJank();
  });
});
