/**
 * Task #1313 — Project Edit dialog must surface a friendly error when the
 * save mutation fails. This test forces the mutation to fail and asserts
 * that both the toast notification and the inline error alert are rendered.
 */

import React from 'react';
import { render, screen, waitFor, act } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import '@testing-library/jest-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { LanguageProvider } from '../../../client/src/hooks/use-language';
import { ProjectForm } from '../../../client/src/components/maintenance/projects/ProjectForm';
import type { MaintenanceProject } from '../../../shared/schemas/maintenance';

if (typeof (globalThis as any).ResizeObserver === 'undefined') {
  class ResizeObserverStub {
    observe(): void {}
    unobserve(): void {}
    disconnect(): void {}
    takeRecords(): unknown[] { return []; }
  }
  (globalThis as any).ResizeObserver = ResizeObserverStub;
}
if (typeof (Element.prototype as any).hasPointerCapture !== 'function') {
  (Element.prototype as any).hasPointerCapture = () => false;
}
if (typeof (Element.prototype as any).releasePointerCapture !== 'function') {
  (Element.prototype as any).releasePointerCapture = () => {};
}
if (typeof (Element.prototype as any).scrollIntoView !== 'function') {
  (Element.prototype as any).scrollIntoView = () => {};
}

const mockToast = jest.fn();

jest.mock('../../../client/src/hooks/use-building-context', () => ({
  useBuildingContext: () => ({
    buildingId: '11111111-1111-1111-1111-111111111111',
    organizationId: '22222222-2222-2222-2222-222222222222',
    hasPermission: () => true,
    building: null,
    availableBuildings: [],
    setBuildingId: () => {},
    setOrganizationId: () => {},
  }),
  useBuildingPermissions: () => ({
    hasPermission: () => true,
    permissions: {},
    isLoadingPermissions: false,
  }),
  BuildingContextProvider: ({ children }: { children: React.ReactNode }) => children,
}));

jest.mock('../../../client/src/hooks/use-toast', () => ({
  useToast: () => ({ toast: mockToast }),
}));

let capturedOnErrorCallback: ((error: Error) => void) | null = null;
let capturedMutate: jest.Mock;

jest.mock('../../../client/src/lib/common-hooks', () => {
  const actual = jest.requireActual('../../../client/src/lib/common-hooks') as Record<string, unknown>;
  return {
    ...actual,
    useCreateUpdateMutation: (opts: {
      onErrorCallback?: (error: Error) => void;
      errorTitle?: string | ((error: Error) => string);
      errorMessage?: string | ((error: Error) => string);
      silentError?: boolean;
      [key: string]: unknown;
    }) => {
      capturedOnErrorCallback = (error: Error) => {
        if (!opts.silentError) {
          const title = typeof opts.errorTitle === 'function' ? opts.errorTitle(error) : (opts.errorTitle ?? 'Error');
          const description = typeof opts.errorMessage === 'function' ? opts.errorMessage(error) : (opts.errorMessage ?? error.message ?? 'Failed to save item');
          mockToast({ title, description, variant: 'destructive' });
        }
        opts.onErrorCallback?.(error);
      };
      capturedMutate = jest.fn();
      return {
        mutate: capturedMutate,
        isPending: false,
        isError: false,
        isSuccess: false,
      };
    },
  };
});

const mockProject: MaintenanceProject = {
  id: '33333333-3333-3333-3333-333333333333',
  buildingId: '11111111-1111-1111-1111-111111111111',
  projectNumber: '202601-001',
  title: 'Test Project',
  status: 'planned',
  priority: 'medium',
  type: 'repair',
  origin: 'manual',
  totalBudget: '10000',
  actualCost: '0',
  plannedStartDate: '2026-03-01',
  plannedEndDate: '2026-06-30',
  createdBy: 'user-1',
  financialYear: 2026,
  planningDescription: '',
  planningStartDate: null,
  estimatedCost: null,
  actualStartDate: null,
  actualEndDate: null,
  suggestionId: null,
  autoGeneratedId: null,
  skipSubmission: false,
  skipPreWork: false,
  skipInProgress: false,
  skipPostWork: false,
  completionSummary: null,
  workStartDate: null,
  isQuickProject: false,
  createdAt: new Date('2026-01-01'),
  updatedAt: new Date('2026-01-01'),
};

function renderWithProviders(ui: React.ReactElement) {
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: { retry: false, refetchOnWindowFocus: false, gcTime: Infinity },
      mutations: { retry: false },
    },
  });
  return render(
    <QueryClientProvider client={queryClient}>
      <LanguageProvider>{ui}</LanguageProvider>
    </QueryClientProvider>,
  );
}

describe('ProjectForm edit error handling', () => {
  beforeEach(() => {
    jest.clearAllMocks();
    capturedOnErrorCallback = null;
  });

  it('shows an inline error alert and destructive toast when the mutation error callback fires', async () => {
    renderWithProviders(
      <ProjectForm
        isOpen={true}
        onOpenChange={() => {}}
        project={mockProject}
        mode="edit"
      />,
    );

    await screen.findByRole('dialog');

    expect(screen.queryByTestId('error-alert')).not.toBeInTheDocument();

    await act(async () => {
      capturedOnErrorCallback?.(new Error('Server error: could not save project'));
    });

    await waitFor(() => {
      const errorAlert = screen.queryByTestId('error-alert');
      expect(errorAlert).toBeInTheDocument();
    });

    expect(mockToast).toHaveBeenCalledWith(
      expect.objectContaining({ variant: 'destructive' }),
    );
  });

  it('does not show an error alert before any failure', async () => {
    renderWithProviders(
      <ProjectForm
        isOpen={true}
        onOpenChange={() => {}}
        project={mockProject}
        mode="edit"
      />,
    );

    await screen.findByRole('dialog');

    expect(screen.queryByTestId('error-alert')).not.toBeInTheDocument();
  });

  it('renders a submit button in edit mode', async () => {
    renderWithProviders(
      <ProjectForm
        isOpen={true}
        onOpenChange={() => {}}
        project={mockProject}
        mode="edit"
      />,
    );

    await screen.findByRole('dialog');

    const submitButton = screen.getByTestId('submit-button');
    expect(submitButton).toBeInTheDocument();
  });

  it('keeps the dialog open after a mutation failure', async () => {
    const onOpenChange = jest.fn();

    renderWithProviders(
      <ProjectForm
        isOpen={true}
        onOpenChange={onOpenChange}
        project={mockProject}
        mode="edit"
      />,
    );

    await screen.findByRole('dialog');

    await act(async () => {
      capturedOnErrorCallback?.(new Error('Network failure'));
    });

    await waitFor(() => {
      expect(screen.queryByTestId('error-alert')).toBeInTheDocument();
    });

    expect(onOpenChange).not.toHaveBeenCalledWith(false);
  });
});
