/**
 * @file Workflow config dialog — delete project callback chain
 * @description Regression tests for Task #919.
 *
 * Verifies that when a project is deleted from the WorkflowSkipConfigDialog:
 *  - The `onDelete` callback fires on success but NOT on failure.
 *  - The config dialog and confirm dialog both close on success.
 *  - ProjectWorkflowModal closes and calls `onProjectDelete` when deletion succeeds.
 *  - BudgetProjectDialogs clears its own modal state and forwards `onProjectDelete`.
 */

import React from 'react';
import { describe, it, expect, jest, beforeEach, afterEach } from '@jest/globals';
import { cleanup, render, screen, waitFor, fireEvent } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import type { UseMutationResult } from '@tanstack/react-query';
import '@testing-library/jest-dom';

jest.mock('@/hooks/use-language', () => ({
  useLanguage: () => ({ t: (key: string) => key, language: 'en' }),
}));

// Expose toast so tests can assert it was called
let capturedToast: ReturnType<typeof jest.fn>;
jest.mock('@/hooks/use-toast', () => ({
  useToast: () => ({ toast: (...args: unknown[]) => capturedToast(...args) }),
}));

// Mutable holder so tests can configure mutate behaviour without reassigning
// the reference captured by the mock factory.
let mutateImpl: (id: string, opts: Record<string, unknown>) => void = jest.fn();

jest.mock('@/hooks/useProjectWorkflow', () => ({
  useUpdateSkipFlags: () => ({ mutate: jest.fn(), isPending: false }),
  useDeleteProject: () => ({
    mutate: (id: string, opts: Record<string, unknown>) => mutateImpl(id, opts),
    isPending: false,
  }),
  useProjectWorkflowState: () => ({
    data: {
      currentStatus: 'planned',
      skipFlags: {},
      canAdvance: false,
      accessibleTabs: ['planned'],
      firstIncompleteTab: 'planned',
      project: { id: 'proj-1', title: 'Test Project', projectNumber: 'P-001', isQuickProject: false },
    },
    isLoading: false,
    error: null,
    refetch: jest.fn(),
  }),
  useMarkStatusComplete: () => ({ mutateAsync: jest.fn(), isPending: false }),
}));

jest.mock('@/hooks/use-building-context', () => ({
  useBuildingContext: () => ({ buildingId: 'bld-1', organizationId: 'org-1' }),
  BuildingContextProvider: ({ children }: { children: React.ReactNode }) => <>{children}</>,
}));

jest.mock('@/components/maintenance/projects/workflow/lazy-components', () => ({
  WorkflowTabNavigation: () => <div data-testid="tab-nav" />,
  PlannedTab: () => <div data-testid="planned-tab" />,
  SubmissionTab: () => <div />,
  PreWorkTab: () => <div />,
  InProgressTab: () => <div />,
  PostWorkTab: () => <div />,
  CompleteTab: () => <div />,
  ProjectWorkflowModal: jest.requireActual('@/components/maintenance/projects/workflow/lazy-components').ProjectWorkflowModal,
}));

import { WorkflowSkipConfigDialog } from '@/components/maintenance/projects/workflow/WorkflowSkipConfigDialog';
import { ProjectWorkflowModal } from '@/components/maintenance/projects/workflow/ProjectWorkflowModal';
import { BudgetProjectDialogs } from '@/pages/manager/budget/BudgetProjectDialogs';
import type { MaintenanceProject } from '@shared/schemas/maintenance';
import type { CreateProjectPayload, UpdateProjectPayload } from '@/pages/manager/budget/BudgetProjectDialogs';

const mockProject: MaintenanceProject = {
  id: 'proj-1',
  title: 'Test Project',
  projectNumber: 'P-001',
  buildingId: 'bld-1',
  isQuickProject: false,
  type: 'replacement',
  status: 'planned',
  priority: 'medium',
  origin: 'manual',
  totalBudget: '10000',
  actualCost: '0',
  financialYear: 2026,
  createdBy: 'user-1',
  createdAt: new Date('2026-01-01'),
  updatedAt: new Date('2026-01-01'),
  skipSubmission: false,
  skipPreWork: false,
  skipInProgress: false,
  skipPostWork: false,
  plannedStartDate: null,
  plannedEndDate: null,
  actualStartDate: null,
  actualEndDate: null,
  planningDescription: null,
  planningStartDate: null,
  completionSummary: null,
  workStartDate: null,
  estimatedCost: null,
  autoGeneratedId: null,
  suggestionId: null,
};

const mockWorkflowState = {
  currentStatus: 'planned' as const,
  skipFlags: {} as Record<string, boolean>,
  canAdvance: false,
  accessibleTabs: ['planned'] as string[],
  firstIncompleteTab: 'planned' as string,
  project: mockProject,
};

function makeMutationStub<T = unknown, P = unknown>(): UseMutationResult<T, Error, P> {
  return {
    mutate: jest.fn(),
    mutateAsync: jest.fn().mockResolvedValue(undefined),
    isPending: false,
    data: undefined,
    error: null,
    isError: false,
    isIdle: true,
    isPaused: false,
    isSuccess: false,
    reset: jest.fn(),
    status: 'idle',
    variables: undefined,
    context: undefined,
    submittedAt: 0,
    failureCount: 0,
    failureReason: null,
  } as unknown as UseMutationResult<T, Error, P>;
}

function makeQueryClient() {
  return new QueryClient({ defaultOptions: { queries: { retry: false } } });
}

function Wrapper({ children }: { children: React.ReactNode }) {
  return (
    <QueryClientProvider client={makeQueryClient()}>
      {children}
    </QueryClientProvider>
  );
}

async function openConfigAndClickDelete() {
  fireEvent.click(screen.getByTestId('button-workflow-config'));
  await waitFor(() => expect(screen.getByTestId('button-delete-project')).toBeInTheDocument());
  fireEvent.click(screen.getByTestId('button-delete-project'));
  await waitFor(() => expect(screen.getByTestId('confirm-delete-project')).toBeInTheDocument());
  fireEvent.click(screen.getByTestId('confirm-delete-project'));
}

beforeEach(() => {
  mutateImpl = jest.fn();
  capturedToast = jest.fn();
});

afterEach(() => {
  cleanup();
});

describe('WorkflowSkipConfigDialog — delete callback', () => {
  it('calls onDelete and closes both dialogs after a successful deletion', async () => {
    const onDelete = jest.fn();
    mutateImpl = jest.fn((_id: string, opts: Record<string, unknown>) => {
      (opts?.onSuccess as (() => void) | undefined)?.();
    });

    render(
      <Wrapper>
        <WorkflowSkipConfigDialog
          projectId="proj-1"
          workflowState={mockWorkflowState}
          onUpdate={jest.fn()}
          onDelete={onDelete}
          isQuickProject={false}
        />
      </Wrapper>
    );

    await openConfigAndClickDelete();

    await waitFor(() => expect(mutateImpl).toHaveBeenCalledWith('proj-1', expect.any(Object)));
    await waitFor(() => expect(onDelete).toHaveBeenCalledTimes(1));
    // Both the confirm dialog and the config dialog must close
    await waitFor(() =>
      expect(screen.queryByTestId('confirm-delete-project')).not.toBeInTheDocument()
    );
    await waitFor(() =>
      expect(screen.queryByTestId('workflow-skip-config-dialog')).not.toBeInTheDocument()
    );
  });

  it('does not call onDelete and leaves dialogs open when deletion is not confirmed (failure path)', async () => {
    const onDelete = jest.fn();
    mutateImpl = jest.fn((_id: string, _opts: Record<string, unknown>) => {});

    render(
      <Wrapper>
        <WorkflowSkipConfigDialog
          projectId="proj-1"
          workflowState={mockWorkflowState}
          onUpdate={jest.fn()}
          onDelete={onDelete}
          isQuickProject={false}
        />
      </Wrapper>
    );

    await openConfigAndClickDelete();

    await waitFor(() => expect(mutateImpl).toHaveBeenCalled());
    expect(onDelete).not.toHaveBeenCalled();
  });
});

describe('ProjectWorkflowModal — onProjectDelete wired to config dialog', () => {
  it('calls onOpenChange(false) and onProjectDelete when delete succeeds', async () => {
    const onOpenChange = jest.fn();
    const onProjectDelete = jest.fn();
    mutateImpl = jest.fn((_id: string, opts: Record<string, unknown>) => {
      (opts?.onSuccess as (() => void) | undefined)?.();
    });

    render(
      <Wrapper>
        <ProjectWorkflowModal
          isOpen={true}
          onOpenChange={onOpenChange}
          project={mockProject}
          onProjectDelete={onProjectDelete}
        />
      </Wrapper>
    );

    await waitFor(() => expect(screen.getByTestId('button-workflow-config')).toBeInTheDocument());
    await openConfigAndClickDelete();

    await waitFor(() => expect(mutateImpl).toHaveBeenCalledWith('proj-1', expect.any(Object)));
    await waitFor(() => expect(onOpenChange).toHaveBeenCalledWith(false));
    await waitFor(() => expect(onProjectDelete).toHaveBeenCalledTimes(1));
  });
});

describe('BudgetProjectDialogs — onProjectDelete clears workflow state', () => {
  it('closes the workflow modal and calls onProjectDelete when inner delete succeeds', async () => {
    const setSelectedProjectForWorkflow = jest.fn();
    const setShowProjectWorkflowModal = jest.fn();
    const onProjectDelete = jest.fn();
    mutateImpl = jest.fn((_id: string, opts: Record<string, unknown>) => {
      (opts?.onSuccess as (() => void) | undefined)?.();
    });

    render(
      <Wrapper>
        <BudgetProjectDialogs
          addQuickProjectDialogOpen={false}
          setAddQuickProjectDialogOpen={jest.fn()}
          newQuickProject={{ title: '', totalBudget: '', financialYear: '2026', plannedMonth: '1', plannedDay: '1', description: '' }}
          setNewQuickProject={jest.fn()}
          createQuickProjectMutation={makeMutationStub<MaintenanceProject, CreateProjectPayload>()}
          editProjectDialogOpen={false}
          setEditProjectDialogOpen={jest.fn()}
          editingProject={null}
          setEditingProject={jest.fn()}
          updateProjectMutation={makeMutationStub<MaintenanceProject, UpdateProjectPayload>()}
          deleteQuickProjectMutation={makeMutationStub<void, string>()}
          selectedProjectForWorkflow={mockProject}
          setSelectedProjectForWorkflow={setSelectedProjectForWorkflow}
          showProjectWorkflowModal={true}
          setShowProjectWorkflowModal={setShowProjectWorkflowModal}
          buildingId="bld-1"
          organizationId="org-1"
          onProjectWorkflowClose={jest.fn()}
          onProjectUpdate={jest.fn()}
          onProjectDelete={onProjectDelete}
        />
      </Wrapper>
    );

    await waitFor(() => expect(screen.getByTestId('button-workflow-config')).toBeInTheDocument());
    await openConfigAndClickDelete();

    await waitFor(() => expect(mutateImpl).toHaveBeenCalledWith('proj-1', expect.any(Object)));
    await waitFor(() => expect(setShowProjectWorkflowModal).toHaveBeenCalledWith(false));
    await waitFor(() => expect(setSelectedProjectForWorkflow).toHaveBeenCalledWith(null));
    await waitFor(() => expect(onProjectDelete).toHaveBeenCalledTimes(1));
  });
});
