import cron from 'node-cron';
import { billAutoGenerationService } from '../services/bill-generation-service';

/**
 * Background job scheduler for automatic bill generation.
 * Handles scheduled and manual triggers for bulk bill generation.
 */
export class BillAutoGenerationJobScheduler {
  private isRunning = false;
  private lastRun: Date | null = null;
  private runCount = 0;

  /**
   * Initialize the job scheduler.
   */
  init(): void {
    console.log('🕐 Initializing bill auto-generation job scheduler...');
    
    // Schedule for the first day of each month at 2:00 AM
    // This gives time for building managers to update recurrent bills in December
    cron.schedule('0 2 1 1 *', async () => {
      await this.runMonthlyGeneration();
    }, {
      timezone: 'America/Montreal' // Quebec timezone
    });

    // Optional: Daily check for any missed generations (runs at 3:00 AM)
    cron.schedule('0 3 * * *', async () => {
      await this.runDailyCheck();
    }, {
      timezone: 'America/Montreal'
    });

    console.log('✅ Bill auto-generation jobs scheduled');
    console.log('📅 Monthly generation: 1st January at 2:00 AM (America/Montreal)');
    console.log('🔍 Daily check: Every day at 3:00 AM (America/Montreal)');
  }

  /**
   * Monthly generation job - runs once per year in January.
   */
  private async runMonthlyGeneration(): Promise<void> {
    if (this.isRunning) {
      console.log('⏭️ Monthly generation already running, skipping...');
      return;
    }

    try {
      this.isRunning = true;
      this.lastRun = new Date();
      this.runCount++;

      console.log('🗓️ Starting monthly auto-generation job (January)...');
      
      const result = await billAutoGenerationService.runScheduledGeneration();
      
      if (result.success) {
        console.log('✅ Monthly auto-generation completed successfully');
        console.log(`📊 ${result.summary}`);
      } else {
        console.error('❌ Monthly auto-generation failed');
        console.error(`💥 ${result.summary}`);
      }

      // Log to application for monitoring
      this.logJobResult('monthly', result);

    } catch (error: any) {
      console.error('❌ Critical error in monthly generation job:', error);
    } finally {
      this.isRunning = false;
    }
  }

  /**
   * Daily check job - lightweight check for any issues.
   */
  private async runDailyCheck(): Promise<void> {
    try {
      console.log('🔍 Running daily auto-generation health check...');
      
      // Check if it's January and we haven't run this month
      const now = new Date();
      if (now.getMonth() === 0 && (!this.lastRun || this.lastRun.getMonth() !== 0)) {
        console.log('📅 January detected but monthly job hasn\'t run - triggering backup generation');
        await this.runMonthlyGeneration();
        return;
      }

      // Basic health check - count pending recurrent bills
      const stats = await this.getGenerationStats();
      
      if (stats.pendingRecurrentBills > 0 && now.getMonth() === 0) {
        console.log(`⚠️ Found ${stats.pendingRecurrentBills} recurrent bills that may need generation`);
      }
      
      console.log('✅ Daily check completed');
      
    } catch (error: any) {
      console.error('❌ Error in daily check job:', error);
    }
  }

  /**
   * Manual trigger for testing and immediate execution.
   */
  async triggerManual(options: {
    organizationId?: string;
    buildingIds?: string[];
    forceRegenerate?: boolean;
  } = {}): Promise<any> {
    console.log('🔄 Manual trigger requested for auto-generation job...');
    
    try {
      const result = await billAutoGenerationService.triggerManualGeneration(options);
      
      this.logJobResult('manual', {
        success: result.status === 'completed',
        summary: `Manual job ${result.jobId}: ${result.status}`,
        details: result.result
      });
      
      return result;
      
    } catch (error: any) {
      console.error('❌ Error in manual trigger:', error);
      throw error;
    }
  }

  /**
   * Get current job statistics and status.
   */
  async getJobStatus(): Promise<{
    isRunning: boolean;
    lastRun: Date | null;
    runCount: number;
    nextScheduled: string;
    stats: any;
  }> {
    const stats = await this.getGenerationStats();
    
    // Calculate next scheduled run (January 1st, 2:00 AM)
    const now = new Date();
    const nextRun = new Date(now.getFullYear() + 1, 0, 1, 2, 0, 0); // Next January 1st
    
    return {
      isRunning: this.isRunning,
      lastRun: this.lastRun,
      runCount: this.runCount,
      nextScheduled: nextRun.toISOString(),
      stats
    };
  }

  /**
   * Get basic generation statistics.
   */
  private async getGenerationStats(): Promise<{
    pendingRecurrentBills: number;
    totalAutoGenerated: number;
    lastGenerationDate: Date | null;
  }> {
    try {
      // This would normally query the database for stats
      // For now, return basic structure
      return {
        pendingRecurrentBills: 0,
        totalAutoGenerated: 0,
        lastGenerationDate: this.lastRun
      };
    } catch (error: any) {
      console.error('❌ Error getting generation stats:', error);
      return {
        pendingRecurrentBills: 0,
        totalAutoGenerated: 0,
        lastGenerationDate: null
      };
    }
  }

  /**
   * Log job results for monitoring and debugging.
   */
  private logJobResult(jobType: 'monthly' | 'daily' | 'manual', result: any): void {
    const logEntry = {
      timestamp: new Date().toISOString(),
      jobType,
      success: result.success,
      summary: result.summary,
      runCount: this.runCount,
      details: result.details
    };
    
    // In a production environment, this would write to a proper logging system
    console.log('📋 Job Log:', JSON.stringify(logEntry, null, 2));
  }

  /**
   * Stop all scheduled jobs (for graceful shutdown).
   */
  destroy(): void {
    console.log('🛑 Stopping bill auto-generation job scheduler...');
    cron.getTasks().forEach(task => task.destroy());
    console.log('✅ Job scheduler stopped');
  }
}

// Export singleton instance
export const billJobScheduler = new BillAutoGenerationJobScheduler();