import {
  describe,
  it,
  expect,
  beforeEach,
  afterEach,
  beforeAll,
  afterAll,
} from '@jest/globals';
import { PaymentGenerationService } from '../../server/services/payment-generation-service';
import { db } from '../../server/db';
import { bills, payments, users, organizations, buildings } from '../../shared/schema';
import { eq } from 'drizzle-orm';
import * as bcrypt from 'bcryptjs';

/**
 * Integration tests for Bill-Payment Workflow
 * Tests the complete integration between bills and payments including:
 * - End-to-end bill creation to payment generation workflow
 * - Status synchronization between bills and payments
 * - Bill lifecycle impact on payment states
 * - Complex scenarios with multiple bills and payment schedules
 * - Data consistency and integrity checks
 * - Performance with large datasets
 */

describe('Bill-Payment Workflow Integration', () => {
  let paymentService: PaymentGenerationService;
  let testUser: any;
  let testOrganization: any;
  let testBuilding: any;

  beforeAll(async () => {
    paymentService = new PaymentGenerationService();

    // Create test organization
    const [organization] = await db
      .insert(organizations)
      .values({
        id: 'workflow-org-123',
        name: 'Workflow Test Organization',
        type: 'demo',
        address: '123 Workflow St',
        city: 'Montreal',
        province: 'QC',
        postalCode: 'H1A 1A1',
        country: 'Canada',
      })
      .returning();
    testOrganization = organization;

    // Create test building
    const [building] = await db
      .insert(buildings)
      .values({
        id: 'workflow-building-123',
        organizationId: testOrganization.id,
        name: 'Workflow Test Building',
        address: '456 Workflow Ave',
        city: 'Montreal',
        province: 'QC',
        postalCode: 'H2B 2B2',
        buildingType: 'condo',
        totalUnits: 50,
      })
      .returning();
    testBuilding = building;

    // Create test user
    const hashedPassword = await bcrypt.hash('password123', 10);
    const [user] = await db
      .insert(users)
      .values({
        id: 'workflow-user-123',
        email: 'workflow@example.com',
        firstName: 'Workflow',
        lastName: 'User',
        password: hashedPassword,
        role: 'manager',
        organizationId: testOrganization.id,
        isActive: true,
      })
      .returning();
    testUser = user;
  });

  afterAll(async () => {
    // Clean up test data
    await db.delete(payments).where(eq(payments.billId, 'workflow-bill-123'));
    await db.delete(payments).where(eq(payments.billId, 'workflow-bill-456'));
    await db.delete(bills).where(eq(bills.buildingId, 'workflow-building-123'));
    await db.delete(buildings).where(eq(buildings.id, 'workflow-building-123'));
    await db.delete(users).where(eq(users.id, 'workflow-user-123'));
    await db.delete(organizations).where(eq(organizations.id, 'workflow-org-123'));
  });

  beforeEach(async () => {
    // Clean up any existing test data
    await db.delete(payments).where(eq(payments.billId, 'workflow-bill-123'));
    await db.delete(payments).where(eq(payments.billId, 'workflow-bill-456'));
    await db.delete(bills).where(eq(bills.id, 'workflow-bill-123'));
    await db.delete(bills).where(eq(bills.id, 'workflow-bill-456'));
  });

  afterEach(async () => {
    // Clean up after each test
    await db.delete(payments).where(eq(payments.billId, 'workflow-bill-123'));
    await db.delete(payments).where(eq(payments.billId, 'workflow-bill-456'));
    await db.delete(bills).where(eq(bills.id, 'workflow-bill-123'));
    await db.delete(bills).where(eq(bills.id, 'workflow-bill-456'));
  });

  describe('complete bill creation to payment workflow', () => {
    it('should create bill and generate payments automatically', async () => {
      // Step 1: Create a bill
      const [bill] = await db
        .insert(bills)
        .values({
          id: 'workflow-bill-123',
          buildingId: testBuilding.id,
          billNumber: 'WORKFLOW-2024-001',
          title: 'Integration Test Bill',
          description: 'Test bill for workflow integration',
          category: 'maintenance',
          vendor: 'Workflow Corp',
          paymentType: 'recurrent',
          schedulePayment: 'monthly',
          costs: ['1200.00'],
          totalAmount: '1200.00',
          startDate: new Date('2024-01-01'),
          status: 'draft',
          autoGenerated: false,
          createdBy: testUser.id,
        })
        .returning();

      // Step 2: Generate payments
      await paymentService.generatePaymentsForBill(bill.id);

      // Step 3: Verify payments were created
      const payments = await paymentService.getPaymentsForBill(bill.id);
      expect(payments).toHaveLength(12);

      // Step 4: Verify payment details
      expect(payments[0]).toMatchObject({
        billId: bill.id,
        paymentNumber: 1,
        amount: '100.00',
        status: 'pending',
        scheduledDate: '2024-01-01',
      });

      // Step 5: Update bill status and verify payment cascade
      await paymentService.updatePaymentStatusFromBillStatus(bill.id, 'sent');

      // Verify all payments are still pending for sent status
      const updatedPayments = await paymentService.getPaymentsForBill(bill.id);
      expect(updatedPayments.every(p => p.status === 'pending')).toBe(true);
    });

    it('should maintain data consistency during bill updates', async () => {
      // Create bill
      const [bill] = await db
        .insert(bills)
        .values({
          id: 'workflow-bill-123',
          buildingId: testBuilding.id,
          billNumber: 'CONSISTENCY-2024-001',
          title: 'Consistency Test Bill',
          description: 'Test bill for data consistency',
          category: 'utilities',
          vendor: 'Utility Corp',
          paymentType: 'unique',
          schedulePayment: null,
          costs: ['750.00'],
          totalAmount: '750.00',
          startDate: new Date('2024-02-01'),
          status: 'draft',
          autoGenerated: false,
          createdBy: testUser.id,
        })
        .returning();

      // Generate payment
      await paymentService.generatePaymentsForBill(bill.id);

      // Update bill to paid
      await db
        .update(bills)
        .set({ status: 'paid' })
        .where(eq(bills.id, bill.id));

      // Update payments accordingly
      await paymentService.updatePaymentStatusFromBillStatus(bill.id, 'paid');

      // Verify consistency
      const [updatedBill] = await db
        .select()
        .from(bills)
        .where(eq(bills.id, bill.id));

      const payments = await paymentService.getPaymentsForBill(bill.id);

      expect(updatedBill.status).toBe('paid');
      expect(payments[0].status).toBe('paid');
      expect(payments[0].paidDate).toBeTruthy();
    });

    it('should handle bill deletion with payment cleanup', async () => {
      // Create bill with payments
      const [bill] = await db
        .insert(bills)
        .values({
          id: 'workflow-bill-123',
          buildingId: testBuilding.id,
          billNumber: 'DELETE-2024-001',
          title: 'Deletion Test Bill',
          description: 'Test bill for deletion workflow',
          category: 'maintenance',
          vendor: 'Delete Corp',
          paymentType: 'recurrent',
          schedulePayment: 'monthly',
          costs: ['600.00'],
          totalAmount: '600.00',
          startDate: new Date('2024-01-01'),
          status: 'draft',
          autoGenerated: false,
          createdBy: testUser.id,
        })
        .returning();

      await paymentService.generatePaymentsForBill(bill.id);

      // Verify payments exist
      const paymentsBefore = await paymentService.getPaymentsForBill(bill.id);
      expect(paymentsBefore.length).toBeGreaterThan(0);

      // Delete payments first (as would happen in the API)
      await paymentService.deletePaymentsForBill(bill.id);

      // Delete bill
      await db.delete(bills).where(eq(bills.id, bill.id));

      // Verify cleanup
      const paymentsAfter = await paymentService.getPaymentsForBill(bill.id);
      expect(paymentsAfter).toHaveLength(0);

      const billsAfter = await db
        .select()
        .from(bills)
        .where(eq(bills.id, bill.id));
      expect(billsAfter).toHaveLength(0);
    });
  });

  describe('complex bill-payment scenarios', () => {
    it('should handle multiple bills with different payment types', async () => {
      // Create unique bill
      const [uniqueBill] = await db
        .insert(bills)
        .values({
          id: 'workflow-bill-123',
          buildingId: testBuilding.id,
          billNumber: 'UNIQUE-2024-001',
          title: 'Unique Payment Bill',
          description: 'Test unique payment bill',
          category: 'maintenance',
          vendor: 'Unique Corp',
          paymentType: 'unique',
          schedulePayment: null,
          costs: ['2500.00'],
          totalAmount: '2500.00',
          startDate: new Date('2024-01-15'),
          status: 'sent',
          autoGenerated: false,
          createdBy: testUser.id,
        })
        .returning();

      // Create recurrent bill
      const [recurrentBill] = await db
        .insert(bills)
        .values({
          id: 'workflow-bill-456',
          buildingId: testBuilding.id,
          billNumber: 'RECURRENT-2024-001',
          title: 'Recurrent Payment Bill',
          description: 'Test recurrent payment bill',
          category: 'utilities',
          vendor: 'Recurrent Corp',
          paymentType: 'recurrent',
          schedulePayment: 'monthly',
          costs: ['1200.00'],
          totalAmount: '1200.00',
          startDate: new Date('2024-01-01'),
          status: 'sent',
          autoGenerated: false,
          createdBy: testUser.id,
        })
        .returning();

      // Generate payments for both
      await paymentService.generatePaymentsForBill(uniqueBill.id);
      await paymentService.generatePaymentsForBill(recurrentBill.id);

      // Verify unique bill has 1 payment
      const uniquePayments = await paymentService.getPaymentsForBill(uniqueBill.id);
      expect(uniquePayments).toHaveLength(1);
      expect(uniquePayments[0].amount).toBe('2500.00');

      // Verify recurrent bill has 12 payments
      const recurrentPayments = await paymentService.getPaymentsForBill(recurrentBill.id);
      expect(recurrentPayments).toHaveLength(12);
      expect(recurrentPayments[0].amount).toBe('100.00');

      // Update statuses independently
      await paymentService.updatePaymentStatusFromBillStatus(uniqueBill.id, 'paid');
      await paymentService.updatePaymentStatusFromBillStatus(recurrentBill.id, 'overdue');

      // Verify status updates
      const updatedUniquePayments = await paymentService.getPaymentsForBill(uniqueBill.id);
      const updatedRecurrentPayments = await paymentService.getPaymentsForBill(recurrentBill.id);

      expect(updatedUniquePayments[0].status).toBe('paid');
      expect(updatedRecurrentPayments.every(p => p.status === 'overdue')).toBe(true);
    });

    it('should handle partial payment scenarios correctly', async () => {
      // Create recurrent bill
      const [bill] = await db
        .insert(bills)
        .values({
          id: 'workflow-bill-123',
          buildingId: testBuilding.id,
          billNumber: 'PARTIAL-2024-001',
          title: 'Partial Payment Test',
          description: 'Test partial payment scenarios',
          category: 'maintenance',
          vendor: 'Partial Corp',
          paymentType: 'recurrent',
          schedulePayment: 'monthly',
          costs: ['1200.00'],
          totalAmount: '1200.00',
          startDate: new Date('2024-01-01'),
          status: 'sent',
          autoGenerated: false,
          createdBy: testUser.id,
        })
        .returning();

      await paymentService.generatePaymentsForBill(bill.id);
      const payments = await paymentService.getPaymentsForBill(bill.id);

      // Pay first 3 payments
      for (let i = 0; i < 3; i++) {
        await paymentService.updatePaymentStatus(
          payments[i].id,
          'paid',
          new Date().toISOString()
        );
      }

      // Mark next 2 as overdue
      for (let i = 3; i < 5; i++) {
        await paymentService.updatePaymentStatus(payments[i].id, 'overdue');
      }

      // Verify mixed payment statuses
      const updatedPayments = await paymentService.getPaymentsForBill(bill.id);
      
      expect(updatedPayments.slice(0, 3).every(p => p.status === 'paid')).toBe(true);
      expect(updatedPayments.slice(3, 5).every(p => p.status === 'overdue')).toBe(true);
      expect(updatedPayments.slice(5).every(p => p.status === 'pending')).toBe(true);
    });
  });

  describe('payment status lifecycle management', () => {
    beforeEach(async () => {
      // Create test bill for each lifecycle test
      const [bill] = await db
        .insert(bills)
        .values({
          id: 'workflow-bill-123',
          buildingId: testBuilding.id,
          billNumber: 'LIFECYCLE-2024-001',
          title: 'Lifecycle Test Bill',
          description: 'Test bill for payment lifecycle',
          category: 'utilities',
          vendor: 'Lifecycle Corp',
          paymentType: 'recurrent',
          schedulePayment: 'monthly',
          costs: ['600.00'],
          totalAmount: '600.00',
          startDate: new Date('2024-01-01'),
          status: 'draft',
          autoGenerated: false,
          createdBy: testUser.id,
        })
        .returning();

      await paymentService.generatePaymentsForBill(bill.id);
    });

    it('should track complete payment lifecycle: draft → sent → overdue → paid', async () => {
      const billId = 'workflow-bill-123';

      // Step 1: Draft status (payments should be pending)
      let payments = await paymentService.getPaymentsForBill(billId);
      expect(payments.every(p => p.status === 'pending')).toBe(true);

      // Step 2: Send bill (payments remain pending)
      await paymentService.updatePaymentStatusFromBillStatus(billId, 'sent');
      payments = await paymentService.getPaymentsForBill(billId);
      expect(payments.every(p => p.status === 'pending')).toBe(true);

      // Step 3: Mark as overdue
      await paymentService.updatePaymentStatusFromBillStatus(billId, 'overdue');
      payments = await paymentService.getPaymentsForBill(billId);
      expect(payments.every(p => p.status === 'overdue')).toBe(true);

      // Step 4: Pay individual payments
      await paymentService.updatePaymentStatus(
        payments[0].id,
        'paid',
        new Date().toISOString()
      );

      // Verify mixed statuses
      payments = await paymentService.getPaymentsForBill(billId);
      expect(payments[0].status).toBe('paid');
      expect(payments.slice(1).every(p => p.status === 'overdue')).toBe(true);

      // Step 5: Mark entire bill as paid
      await paymentService.updatePaymentStatusFromBillStatus(billId, 'paid');
      payments = await paymentService.getPaymentsForBill(billId);
      expect(payments.every(p => p.status === 'paid')).toBe(true);
      expect(payments.every(p => p.paidDate !== null)).toBe(true);
    });

    it('should handle cancellation at different stages', async () => {
      const billId = 'workflow-bill-123';

      // Pay some payments first
      let payments = await paymentService.getPaymentsForBill(billId);
      await paymentService.updatePaymentStatus(
        payments[0].id,
        'paid',
        new Date().toISOString()
      );
      await paymentService.updatePaymentStatus(payments[1].id, 'overdue');

      // Cancel bill (should only affect pending/overdue payments)
      await paymentService.updatePaymentStatusFromBillStatus(billId, 'cancelled');

      payments = await paymentService.getPaymentsForBill(billId);
      expect(payments[0].status).toBe('paid'); // Already paid should remain paid
      expect(payments.slice(1).every(p => p.status === 'cancelled')).toBe(true);
    });
  });

  describe('data integrity and error handling', () => {
    it('should maintain referential integrity between bills and payments', async () => {
      // Create bill
      const [bill] = await db
        .insert(bills)
        .values({
          id: 'workflow-bill-123',
          buildingId: testBuilding.id,
          billNumber: 'INTEGRITY-2024-001',
          title: 'Integrity Test Bill',
          description: 'Test bill for data integrity',
          category: 'maintenance',
          vendor: 'Integrity Corp',
          paymentType: 'unique',
          schedulePayment: null,
          costs: ['500.00'],
          totalAmount: '500.00',
          startDate: new Date('2024-01-01'),
          status: 'sent',
          autoGenerated: false,
          createdBy: testUser.id,
        })
        .returning();

      await paymentService.generatePaymentsForBill(bill.id);

      // Verify foreign key relationship
      const payments = await db
        .select()
        .from(payments)
        .where(eq(payments.billId, bill.id));

      expect(payments).toHaveLength(1);
      expect(payments[0].billId).toBe(bill.id);

      // Delete bill should clean up payments
      await paymentService.deletePaymentsForBill(bill.id);
      await db.delete(bills).where(eq(bills.id, bill.id));

      const orphanedPayments = await db
        .select()
        .from(payments)
        .where(eq(payments.billId, bill.id));

      expect(orphanedPayments).toHaveLength(0);
    });

    it('should handle concurrent payment updates gracefully', async () => {
      // Create bill with payment
      const [bill] = await db
        .insert(bills)
        .values({
          id: 'workflow-bill-123',
          buildingId: testBuilding.id,
          billNumber: 'CONCURRENT-2024-001',
          title: 'Concurrent Test Bill',
          description: 'Test bill for concurrent operations',
          category: 'utilities',
          vendor: 'Concurrent Corp',
          paymentType: 'unique',
          schedulePayment: null,
          costs: ['750.00'],
          totalAmount: '750.00',
          startDate: new Date('2024-01-01'),
          status: 'sent',
          autoGenerated: false,
          createdBy: testUser.id,
        })
        .returning();

      await paymentService.generatePaymentsForBill(bill.id);
      const payments = await paymentService.getPaymentsForBill(bill.id);
      const paymentId = payments[0].id;

      // Simulate concurrent updates
      const update1 = paymentService.updatePaymentStatus(paymentId, 'paid', new Date().toISOString());
      const update2 = paymentService.updatePaymentStatus(paymentId, 'overdue');

      // Both operations should complete without corruption
      await Promise.all([update1, update2]);

      // Verify final state is consistent
      const finalPayments = await paymentService.getPaymentsForBill(bill.id);
      expect(finalPayments[0].status).toMatch(/^(paid|overdue)$/);
    });

    it('should validate payment amount totals match bill amounts', async () => {
      // Create recurrent bill
      const [bill] = await db
        .insert(bills)
        .values({
          id: 'workflow-bill-123',
          buildingId: testBuilding.id,
          billNumber: 'AMOUNT-2024-001',
          title: 'Amount Validation Bill',
          description: 'Test bill for amount validation',
          category: 'maintenance',
          vendor: 'Amount Corp',
          paymentType: 'recurrent',
          schedulePayment: 'monthly',
          costs: ['1000.01'], // Amount that doesn't divide evenly
          totalAmount: '1000.01',
          startDate: new Date('2024-01-01'),
          status: 'sent',
          autoGenerated: false,
          createdBy: testUser.id,
        })
        .returning();

      await paymentService.generatePaymentsForBill(bill.id);
      const payments = await paymentService.getPaymentsForBill(bill.id);

      // Calculate total payment amounts
      const totalPaymentAmount = payments.reduce(
        (sum, payment) => sum + parseFloat(payment.amount),
        0
      );

      // Should match bill total exactly
      expect(totalPaymentAmount).toBeCloseTo(parseFloat(bill.totalAmount), 2);
    });
  });

  describe('performance and scalability', () => {
    it('should handle large number of payments efficiently', async () => {
      // Create bill with many payment installments (simulate large payment plan)
      const [bill] = await db
        .insert(bills)
        .values({
          id: 'workflow-bill-123',
          buildingId: testBuilding.id,
          billNumber: 'PERF-2024-001',
          title: 'Performance Test Bill',
          description: 'Test bill for performance',
          category: 'maintenance',
          vendor: 'Performance Corp',
          paymentType: 'recurrent',
          schedulePayment: 'monthly',
          costs: ['12000.00'], // Large amount
          totalAmount: '12000.00',
          startDate: new Date('2024-01-01'),
          status: 'sent',
          autoGenerated: false,
          createdBy: testUser.id,
        })
        .returning();

      const startTime = Date.now();
      await paymentService.generatePaymentsForBill(bill.id);
      const generationTime = Date.now() - startTime;

      // Should complete within reasonable time (adjust threshold as needed)
      expect(generationTime).toBeLessThan(5000); // 5 seconds

      // Verify all payments created
      const payments = await paymentService.getPaymentsForBill(bill.id);
      expect(payments).toHaveLength(12);

      // Test bulk status update performance
      const bulkStartTime = Date.now();
      await paymentService.updatePaymentStatusFromBillStatus(bill.id, 'paid');
      const bulkUpdateTime = Date.now() - bulkStartTime;

      expect(bulkUpdateTime).toBeLessThan(3000); // 3 seconds

      // Verify all payments updated
      const updatedPayments = await paymentService.getPaymentsForBill(bill.id);
      expect(updatedPayments.every(p => p.status === 'paid')).toBe(true);
    });
  });
});