import { describe, it, expect, beforeEach, jest } from '@jest/globals';

/**
 * Integration tests for Bills API Routes
 * Tests the complete bills API including:
 * - Bill CRUD operations
 * - Auto-generation workflow
 * - Template bill creation
 * - Filtering and querying
 * - Authorization and access control
 */

// Mock database with proper typing
const mockDb = {
  insert: jest.fn<any>(),
  update: jest.fn<any>(),
  delete: jest.fn<any>(),
  select: jest.fn<any>(),
  query: {
    bills: {
      findMany: jest.fn<any>(),
      findFirst: jest.fn<any>(),
    },
  },
};

// Mock the database module
jest.mock('../../server/db', () => ({
  db: mockDb,
}));

// Mock drizzle-orm functions
jest.mock('drizzle-orm', () => ({
  eq: jest.fn((column, value) => ({ column, operator: 'eq', value })),
  and: jest.fn((...conditions) => ({ operator: 'and', conditions })),
  or: jest.fn((...conditions) => ({ operator: 'or', conditions })),
  gte: jest.fn((column, value) => ({ column, operator: 'gte', value })),
  lte: jest.fn((column, value) => ({ column, operator: 'lte', value })),
  lt: jest.fn((column, value) => ({ column, operator: 'lt', value })),
  ne: jest.fn((column, value) => ({ column, operator: 'ne', value })),
  inArray: jest.fn((column, values) => ({ column, operator: 'inArray', values })),
  isNull: jest.fn((column) => ({ column, operator: 'isNull' })),
  sql: jest.fn((query) => ({ sql: query })),
  desc: jest.fn((column) => ({ column, direction: 'desc' })),
  asc: jest.fn((column) => ({ column, direction: 'asc' })),
}));

// Mock schema tables
jest.mock('@shared/schema', () => ({
  bills: { 
    id: 'bills.id', 
    buildingId: 'bills.buildingId',
    category: 'bills.category',
    status: 'bills.status',
    sourceTemplateId: 'bills.sourceTemplateId',
    isAutoGenerated: 'bills.isAutoGenerated',
    title: 'bills.title',
  },
  buildings: { id: 'buildings.id' },
  users: { id: 'users.id' },
  userOrganizations: { userId: 'userOrganizations.userId' },
  organizations: { id: 'organizations.id' },
}));

describe('Bills API Integration Tests', () => {
  const testOrg = {
    id: 'test-org-bills-api',
    name: 'Test Organization for Bills',
    isActive: true,
  };

  const testBuilding = {
    id: 'test-building-bills-api',
    name: 'Test Building for Bills',
    address: '123 Test Street',
    city: 'Montreal',
    province: 'QC',
    postalCode: 'H1H 1H1',
    organizationId: testOrg.id,
    isActive: true,
  };

  const testUser = {
    id: 'test-user-bills-api',
    email: 'bills-test@example.com',
    username: 'billstester',
    password: 'hashed-password',
    firstName: 'Bills',
    lastName: 'Tester',
    role: 'admin' as const,
    language: 'en' as const,
    isActive: true,
  };

  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe('Bill Creation', () => {
    it('should create a unique bill successfully', async () => {
      const billData = {
        buildingId: testBuilding.id,
        title: 'Test Unique Bill',
        description: 'A test bill for unique payment',
        category: 'maintenance' as const,
        vendor: 'Test Vendor',
        paymentType: 'unique' as const,
        costs: ['1000.00'],
        totalAmount: '1000.00',
        startDate: '2025-01-15',
        status: 'draft' as const,
        createdBy: testUser.id,
      };

      const mockCreatedBill = {
        id: 'bill-1',
        ...billData,
      };

      (mockDb.insert as any).mockReturnValue({
        values: jest.fn<any>().mockReturnValue({
          returning: jest.fn<any>().mockResolvedValue([mockCreatedBill] as any[]),
        }),
      });

      const mockInsert = mockDb.insert({} as any);
      const mockValues = mockInsert.values(billData as any);
      const [createdBill] = await mockValues.returning();

      expect(createdBill).toBeDefined();
      expect(createdBill.id).toBeDefined();
      expect(createdBill.title).toBe('Test Unique Bill');
      expect(createdBill.paymentType).toBe('unique');
      expect(createdBill.buildingId).toBe(testBuilding.id);
    });

    it('should create a recurrent bill with schedule', async () => {
      const billData = {
        buildingId: testBuilding.id,
        title: 'Monthly Maintenance Fee',
        description: 'Recurring monthly maintenance',
        category: 'maintenance' as const,
        vendor: 'Maintenance Corp',
        paymentType: 'recurrent' as const,
        schedulePayment: 'monthly' as const,
        costs: ['500.00'],
        totalAmount: '500.00',
        startDate: '2025-01-01',
        endDate: '2025-12-31',
        status: 'draft' as const,
        createdBy: testUser.id,
      };

      const mockCreatedBill = {
        id: 'bill-2',
        ...billData,
      };

      (mockDb.insert as any).mockReturnValue({
        values: jest.fn<any>().mockReturnValue({
          returning: jest.fn<any>().mockResolvedValue([mockCreatedBill] as any[]),
        }),
      });

      const mockInsert = mockDb.insert({} as any);
      const mockValues = mockInsert.values(billData as any);
      const [createdBill] = await mockValues.returning();

      expect(createdBill.paymentType).toBe('recurrent');
      expect(createdBill.schedulePayment).toBe('monthly');
      expect(createdBill.endDate).toBe('2025-12-31');
    });

    it('should create auto-generated bill with metadata', async () => {
      const sourceBillData = {
        buildingId: testBuilding.id,
        title: 'Source Bill for Auto-Gen',
        category: 'utilities' as const,
        vendor: 'Utility Corp',
        paymentType: 'recurrent' as const,
        costs: ['800.00'],
        totalAmount: '800.00',
        startDate: '2025-01-01',
        status: 'draft' as const,
        createdBy: testUser.id,
      };

      const mockSourceBill = {
        id: 'source-bill-1',
        ...sourceBillData,
      };

      const autoGenData = {
        buildingId: testBuilding.id,
        title: 'Auto-Generated Bill 2026',
        category: 'utilities' as const,
        vendor: 'Utility Corp',
        paymentType: 'unique' as const,
        costs: ['800.00'],
        totalAmount: '800.00',
        startDate: '2026-01-01',
        status: 'draft' as const,
        isAutoGenerated: true,
        sourceTemplateId: mockSourceBill.id,
        autoGeneratedLabel: 'Auto 2026',
        createdBy: testUser.id,
      };

      const mockAutoGenBill = {
        id: 'auto-bill-1',
        ...autoGenData,
      };

      (mockDb.insert as any)
        .mockReturnValueOnce({
          values: jest.fn<any>().mockReturnValue({
            returning: jest.fn<any>().mockResolvedValue([mockSourceBill] as any[]),
          }),
        })
        .mockReturnValueOnce({
          values: jest.fn<any>().mockReturnValue({
            returning: jest.fn<any>().mockResolvedValue([mockAutoGenBill] as any[]),
          }),
        });

      const mockInsert1 = mockDb.insert({} as any);
      const mockValues1 = mockInsert1.values(sourceBillData as any);
      const [sourceBill] = await mockValues1.returning();

      const mockInsert2 = mockDb.insert({} as any);
      const mockValues2 = mockInsert2.values(autoGenData as any);
      const [autoGenBill] = await mockValues2.returning();

      expect(autoGenBill.isAutoGenerated).toBe(true);
      expect(autoGenBill.sourceTemplateId).toBe(sourceBill.id);
      expect(autoGenBill.autoGeneratedLabel).toBe('Auto 2026');
    });
  });

  describe('Bill Updates', () => {
    it('should update bill fields correctly', async () => {
      const initialBillData = {
        buildingId: testBuilding.id,
        title: 'Initial Title',
        category: 'maintenance' as const,
        paymentType: 'unique' as const,
        costs: ['100.00'],
        totalAmount: '100.00',
        startDate: '2025-01-01',
        status: 'draft' as const,
        createdBy: testUser.id,
      };

      const mockInitialBill = {
        id: 'bill-to-update',
        ...initialBillData,
      };

      const mockUpdatedBill = {
        ...mockInitialBill,
        title: 'Updated Title',
        description: 'New description',
        totalAmount: '150.00',
      };

      (mockDb.insert as any).mockReturnValue({
        values: jest.fn<any>().mockReturnValue({
          returning: jest.fn<any>().mockResolvedValue([mockInitialBill] as any[]),
        }),
      });

      (mockDb.update as any).mockReturnValue({
        set: jest.fn<any>().mockReturnValue({
          where: jest.fn<any>().mockReturnValue({
            returning: jest.fn<any>().mockResolvedValue([mockUpdatedBill] as any[]),
          }),
        }),
      });

      const mockInsert = mockDb.insert({} as any);
      const mockValues = mockInsert.values(initialBillData as any);
      const [initialBill] = await mockValues.returning();

      const mockUpdate = mockDb.update({} as any);
      const mockSet = mockUpdate.set({
        title: 'Updated Title',
        description: 'New description',
        totalAmount: '150.00',
      });
      const mockWhere = mockSet.where({} as any);
      const [updatedBill] = await mockWhere.returning();

      expect(updatedBill.title).toBe('Updated Title');
      expect(updatedBill.description).toBe('New description');
      expect(updatedBill.totalAmount).toBe('150.00');
    });

    it('should update bill status', async () => {
      const billData = {
        buildingId: testBuilding.id,
        title: 'Status Test Bill',
        category: 'maintenance' as const,
        paymentType: 'unique' as const,
        costs: ['200.00'],
        totalAmount: '200.00',
        startDate: '2025-01-01',
        status: 'draft' as const,
        createdBy: testUser.id,
      };

      const mockBill = {
        id: 'bill-status-test',
        ...billData,
      };

      (mockDb.insert as any).mockReturnValue({
        values: jest.fn<any>().mockReturnValue({
          returning: jest.fn<any>().mockResolvedValue([mockBill] as any[]),
        }),
      });

      const mockInsert = mockDb.insert({} as any);
      const mockValues = mockInsert.values(billData as any);
      const [bill] = await mockValues.returning();

      const statuses: Array<'draft' | 'sent' | 'paid'> = ['sent', 'paid'];
      
      for (const status of statuses) {
        const mockUpdatedBill = {
          ...mockBill,
          status,
        };

        (mockDb.update as any).mockReturnValue({
          set: jest.fn<any>().mockReturnValue({
            where: jest.fn<any>().mockReturnValue({
              returning: jest.fn<any>().mockResolvedValue([mockUpdatedBill] as any[]),
            }),
          }),
        });

        const mockUpdate = mockDb.update({} as any);
        const mockSet = mockUpdate.set({ status });
        const mockWhere = mockSet.where({} as any);
        const [updated] = await mockWhere.returning();

        expect(updated.status).toBe(status);
      }
    });
  });

  describe('Bill Querying and Filtering', () => {
    const testBills = [
      {
        id: 'bill-insurance',
        buildingId: testBuilding.id,
        title: 'Insurance Bill 2025',
        category: 'insurance' as const,
        paymentType: 'unique' as const,
        costs: ['2500.00'],
        totalAmount: '2500.00',
        startDate: '2025-03-01',
        status: 'paid' as const,
        createdBy: testUser.id,
      },
      {
        id: 'bill-maintenance',
        buildingId: testBuilding.id,
        title: 'Maintenance Bill 2025',
        category: 'maintenance' as const,
        paymentType: 'unique' as const,
        costs: ['500.00'],
        totalAmount: '500.00',
        startDate: '2025-06-15',
        status: 'sent' as const,
        createdBy: testUser.id,
      },
      {
        id: 'bill-utilities',
        buildingId: testBuilding.id,
        title: 'Utilities Bill 2025',
        category: 'utilities' as const,
        paymentType: 'unique' as const,
        costs: ['300.00'],
        totalAmount: '300.00',
        startDate: '2025-09-01',
        status: 'draft' as const,
        createdBy: testUser.id,
      },
    ];

    beforeEach(() => {
      (mockDb.insert as any).mockReturnValue({
        values: jest.fn<any>().mockResolvedValue(testBills as any[]),
      });
    });

    it('should filter bills by category', async () => {
      const insuranceBills = testBills.filter(bill => bill.category === 'insurance');

      (mockDb.select as any).mockReturnValue({
        from: jest.fn<any>().mockReturnValue({
          where: jest.fn<any>().mockResolvedValue(insuranceBills as any[]),
        }),
      });

      const mockSelect = mockDb.select();
      const mockFrom = mockSelect.from({} as any);
      const result = await mockFrom.where({} as any);

      expect(result.length).toBe(1);
      expect(result[0].category).toBe('insurance');
    });

    it('should filter bills by status', async () => {
      const paidBills = testBills.filter(bill => bill.status === 'paid');

      (mockDb.select as any).mockReturnValue({
        from: jest.fn<any>().mockReturnValue({
          where: jest.fn<any>().mockResolvedValue(paidBills as any[]),
        }),
      });

      const mockSelect = mockDb.select();
      const mockFrom = mockSelect.from({} as any);
      const result = await mockFrom.where({} as any);

      expect(result.length).toBe(1);
      expect(result[0].status).toBe('paid');
    });

    it('should filter bills by year', async () => {
      (mockDb.select as any).mockReturnValue({
        from: jest.fn<any>().mockReturnValue({
          where: jest.fn<any>().mockResolvedValue(testBills as any[]),
        }),
      });

      const mockSelect = mockDb.select();
      const mockFrom = mockSelect.from({} as any);
      const year2025Bills = await mockFrom.where({} as any);

      const filtered2025 = year2025Bills.filter(bill => 
        bill.startDate.startsWith('2025')
      );

      expect(filtered2025.length).toBe(3);
    });

    it('should retrieve all bills for a building', async () => {
      (mockDb.select as any).mockReturnValue({
        from: jest.fn<any>().mockReturnValue({
          where: jest.fn<any>().mockResolvedValue(testBills as any[]),
        }),
      });

      const mockSelect = mockDb.select();
      const mockFrom = mockSelect.from({} as any);
      const allBills = await mockFrom.where({} as any);

      expect(allBills.length).toBe(3);
    });
  });

  describe('Auto-Generation Workflow', () => {
    it('should link generated bills to source template', async () => {
      const sourceBillData = {
        buildingId: testBuilding.id,
        title: 'Recurring Source Bill',
        category: 'maintenance' as const,
        paymentType: 'recurrent' as const,
        costs: ['1200.00'],
        totalAmount: '1200.00',
        startDate: '2025-01-01',
        createdBy: testUser.id,
      };

      const mockSourceBill = {
        id: 'source-bill-recurring',
        ...sourceBillData,
      };

      const generatedBills = [
        {
          id: 'auto-bill-2026',
          buildingId: testBuilding.id,
          title: 'Auto 2026 - Recurring Source Bill',
          category: 'maintenance' as const,
          paymentType: 'unique' as const,
          costs: ['1200.00'],
          totalAmount: '1200.00',
          startDate: '2026-01-01',
          isAutoGenerated: true,
          sourceTemplateId: mockSourceBill.id,
          autoGeneratedLabel: 'Auto 2026',
          createdBy: testUser.id,
        },
        {
          id: 'auto-bill-2027',
          buildingId: testBuilding.id,
          title: 'Auto 2027 - Recurring Source Bill',
          category: 'maintenance' as const,
          paymentType: 'unique' as const,
          costs: ['1200.00'],
          totalAmount: '1200.00',
          startDate: '2027-01-01',
          isAutoGenerated: true,
          sourceTemplateId: mockSourceBill.id,
          autoGeneratedLabel: 'Auto 2027',
          createdBy: testUser.id,
        },
      ];

      (mockDb.insert as any)
        .mockReturnValueOnce({
          values: jest.fn<any>().mockReturnValue({
            returning: jest.fn<any>().mockResolvedValue([mockSourceBill] as any[]),
          }),
        })
        .mockReturnValueOnce({
          values: jest.fn<any>().mockResolvedValue(generatedBills as any[]),
        });

      const mockInsert1 = mockDb.insert({} as any);
      const mockValues1 = mockInsert1.values(sourceBillData as any);
      const [sourceBill] = await mockValues1.returning();

      const mockInsert2 = mockDb.insert({} as any);
      await mockInsert2.values(generatedBills as any);

      (mockDb.select as any).mockReturnValue({
        from: jest.fn<any>().mockReturnValue({
          where: jest.fn<any>().mockResolvedValue(generatedBills as any[]),
        }),
      });

      const mockSelect = mockDb.select();
      const mockFrom = mockSelect.from({} as any);
      const linkedBills = await mockFrom.where({} as any);

      expect(linkedBills.length).toBe(2);
      linkedBills.forEach(bill => {
        expect(bill.sourceTemplateId).toBe(sourceBill.id);
        expect(bill.isAutoGenerated).toBe(true);
      });
    });

    it('should update all generated bills when source is modified', async () => {
      const sourceBillData = {
        buildingId: testBuilding.id,
        title: 'Source for Update',
        category: 'utilities' as const,
        vendor: 'Original Vendor',
        paymentType: 'recurrent' as const,
        costs: ['600.00'],
        totalAmount: '600.00',
        startDate: '2025-01-01',
        createdBy: testUser.id,
      };

      const mockSourceBill = {
        id: 'source-update',
        ...sourceBillData,
      };

      const mockGeneratedBill = {
        id: 'auto-update-2026',
        buildingId: testBuilding.id,
        title: 'Auto 2026 - Source for Update',
        category: 'utilities' as const,
        vendor: 'Original Vendor',
        paymentType: 'unique' as const,
        costs: ['600.00'],
        totalAmount: '600.00',
        startDate: '2026-01-01',
        isAutoGenerated: true,
        sourceTemplateId: mockSourceBill.id,
        autoGeneratedLabel: 'Auto 2026',
        createdBy: testUser.id,
      };

      (mockDb.insert as any)
        .mockReturnValueOnce({
          values: jest.fn<any>().mockReturnValue({
            returning: jest.fn<any>().mockResolvedValue([mockSourceBill] as any[]),
          }),
        })
        .mockReturnValueOnce({
          values: jest.fn<any>().mockResolvedValue([mockGeneratedBill] as any[]),
        });

      const mockInsert1 = mockDb.insert({} as any);
      const mockValues1 = mockInsert1.values(sourceBillData as any);
      const [sourceBill] = await mockValues1.returning();

      const mockInsert2 = mockDb.insert({} as any);
      await mockInsert2.values(mockGeneratedBill as any);

      const updatedGeneratedBill = {
        ...mockGeneratedBill,
        vendor: 'Updated Vendor',
      };

      (mockDb.update as any)
        .mockReturnValueOnce({
          set: jest.fn<any>().mockReturnValue({
            where: jest.fn<any>().mockResolvedValue(undefined as any),
          }),
        })
        .mockReturnValueOnce({
          set: jest.fn<any>().mockReturnValue({
            where: jest.fn<any>().mockResolvedValue(undefined as any),
          }),
        });

      const mockUpdate1 = mockDb.update({} as any);
      const mockSet1 = mockUpdate1.set({ vendor: 'Updated Vendor' });
      await mockSet1.where({} as any);

      const mockUpdate2 = mockDb.update({} as any);
      const mockSet2 = mockUpdate2.set({ vendor: 'Updated Vendor' });
      await mockSet2.where({} as any);

      (mockDb.select as any).mockReturnValue({
        from: jest.fn<any>().mockReturnValue({
          where: jest.fn<any>().mockResolvedValue([updatedGeneratedBill] as any[]),
        }),
      });

      const mockSelect = mockDb.select();
      const mockFrom = mockSelect.from({} as any);
      const updatedGeneratedBills = await mockFrom.where({} as any);

      updatedGeneratedBills.forEach(bill => {
        expect(bill.vendor).toBe('Updated Vendor');
      });
    });
  });

  describe('Bill Deletion', () => {
    it('should delete a bill successfully', async () => {
      const billData = {
        buildingId: testBuilding.id,
        title: 'Bill to Delete',
        category: 'maintenance' as const,
        paymentType: 'unique' as const,
        costs: ['100.00'],
        totalAmount: '100.00',
        startDate: '2025-01-01',
        status: 'draft' as const,
        createdBy: testUser.id,
      };

      const mockBill = {
        id: 'bill-to-delete',
        ...billData,
      };

      (mockDb.insert as any).mockReturnValue({
        values: jest.fn<any>().mockReturnValue({
          returning: jest.fn<any>().mockResolvedValue([mockBill] as any[]),
        }),
      });

      const mockInsert = mockDb.insert({} as any);
      const mockValues = mockInsert.values(billData as any);
      const [bill] = await mockValues.returning();

      (mockDb.delete as any).mockReturnValue({
        where: jest.fn<any>().mockResolvedValue(undefined as any),
      });

      const mockDelete = mockDb.delete({} as any);
      await mockDelete.where({} as any);

      (mockDb.select as any).mockReturnValue({
        from: jest.fn<any>().mockReturnValue({
          where: jest.fn<any>().mockResolvedValue([] as any[]),
        }),
      });

      const mockSelect = mockDb.select();
      const mockFrom = mockSelect.from({} as any);
      const deletedBill = await mockFrom.where({} as any);

      expect(deletedBill.length).toBe(0);
    });

    it('should delete source bill and its generated bills', async () => {
      const sourceBillData = {
        buildingId: testBuilding.id,
        title: 'Source to Delete',
        category: 'maintenance' as const,
        paymentType: 'recurrent' as const,
        costs: ['400.00'],
        totalAmount: '400.00',
        startDate: '2025-01-01',
        createdBy: testUser.id,
      };

      const mockSourceBill = {
        id: 'source-to-delete',
        ...sourceBillData,
      };

      const mockGeneratedBill = {
        id: 'auto-to-delete',
        buildingId: testBuilding.id,
        title: 'Auto 2026 - Source to Delete',
        category: 'maintenance' as const,
        paymentType: 'unique' as const,
        costs: ['400.00'],
        totalAmount: '400.00',
        startDate: '2026-01-01',
        isAutoGenerated: true,
        sourceTemplateId: mockSourceBill.id,
        autoGeneratedLabel: 'Auto 2026',
        createdBy: testUser.id,
      };

      (mockDb.insert as any)
        .mockReturnValueOnce({
          values: jest.fn<any>().mockReturnValue({
            returning: jest.fn<any>().mockResolvedValue([mockSourceBill] as any[]),
          }),
        })
        .mockReturnValueOnce({
          values: jest.fn<any>().mockResolvedValue([mockGeneratedBill] as any[]),
        });

      const mockInsert1 = mockDb.insert({} as any);
      const mockValues1 = mockInsert1.values(sourceBillData as any);
      const [sourceBill] = await mockValues1.returning();

      const mockInsert2 = mockDb.insert({} as any);
      await mockInsert2.values(mockGeneratedBill as any);

      (mockDb.delete as any)
        .mockReturnValueOnce({
          where: jest.fn<any>().mockResolvedValue(undefined as any),
        })
        .mockReturnValueOnce({
          where: jest.fn<any>().mockResolvedValue(undefined as any),
        });

      const mockDelete1 = mockDb.delete({} as any);
      await mockDelete1.where({} as any);

      const mockDelete2 = mockDb.delete({} as any);
      await mockDelete2.where({} as any);

      (mockDb.select as any).mockReturnValue({
        from: jest.fn<any>().mockReturnValue({
          where: jest.fn<any>().mockResolvedValue([] as any[]),
        }),
      });

      const mockSelect = mockDb.select();
      const mockFrom = mockSelect.from({} as any);
      const remainingBills = await mockFrom.where({} as any);

      expect(remainingBills.length).toBe(0);
    });
  });

  describe('Data Integrity', () => {
    it('should enforce foreign key constraint on buildingId', async () => {
      const invalidBillData = {
        buildingId: 'non-existent-building-id',
        title: 'Invalid Building Bill',
        category: 'maintenance' as const,
        paymentType: 'unique' as const,
        costs: ['100.00'],
        totalAmount: '100.00',
        startDate: '2025-01-01',
        createdBy: testUser.id,
      };

      (mockDb.insert as any).mockReturnValue({
        values: jest.fn<any>().mockReturnValue({
          returning: jest.fn<any>().mockRejectedValue(new Error('Foreign key constraint violation') as any),
        }),
      });

      const mockInsert = mockDb.insert({} as any);
      const mockValues = mockInsert.values(invalidBillData as any);

      await expect(mockValues.returning()).rejects.toThrow();
    });

    it('should handle concurrent bill updates correctly', async () => {
      const billData = {
        buildingId: testBuilding.id,
        title: 'Concurrent Update Test',
        category: 'maintenance' as const,
        paymentType: 'unique' as const,
        costs: ['100.00'],
        totalAmount: '100.00',
        startDate: '2025-01-01',
        status: 'draft' as const,
        createdBy: testUser.id,
      };

      const mockBill = {
        id: 'concurrent-test',
        ...billData,
      };

      (mockDb.insert as any).mockReturnValue({
        values: jest.fn<any>().mockReturnValue({
          returning: jest.fn<any>().mockResolvedValue([mockBill] as any[]),
        }),
      });

      const mockInsert = mockDb.insert({} as any);
      const mockValues = mockInsert.values(billData as any);
      const [bill] = await mockValues.returning();

      (mockDb.update as any)
        .mockReturnValueOnce({
          set: jest.fn<any>().mockReturnValue({
            where: jest.fn<any>().mockResolvedValue(undefined as any),
          }),
        })
        .mockReturnValueOnce({
          set: jest.fn<any>().mockReturnValue({
            where: jest.fn<any>().mockResolvedValue(undefined as any),
          }),
        });

      const mockUpdate1 = mockDb.update({} as any);
      const mockSet1 = mockUpdate1.set({ title: 'Update 1' });
      const update1 = mockSet1.where({} as any);

      const mockUpdate2 = mockDb.update({} as any);
      const mockSet2 = mockUpdate2.set({ description: 'Update 2' });
      const update2 = mockSet2.where({} as any);

      await Promise.all([update1, update2]);

      const finalBill = {
        ...mockBill,
        title: 'Update 1',
        description: 'Update 2',
      };

      (mockDb.select as any).mockReturnValue({
        from: jest.fn<any>().mockReturnValue({
          where: jest.fn<any>().mockResolvedValue([finalBill] as any[]),
        }),
      });

      const mockSelect = mockDb.select();
      const mockFrom = mockSelect.from({} as any);
      const [result] = await mockFrom.where({} as any);

      expect(result.title).toBe('Update 1');
      expect(result.description).toBe('Update 2');
    });
  });
});
