/**
 * @file Bills API Integration Tests
 * @description Full integration tests for bills API with real Express router stack
 * Tests the complete bills API including CRUD operations, auto-generation, and filtering
 */

import request from 'supertest';
import express, { type RequestHandler } from 'express';
import session from 'express-session';
import { describe, it, expect, beforeEach, jest } from '@jest/globals';
import type { AuthenticatedUser } from '../../server/rbac';

// Mock database operations
const mockDb = {
  query: {
    bills: {
      findMany: jest.fn<() => Promise<any[]>>(),
      findFirst: jest.fn<() => Promise<any | null>>(),
    },
  },
  select: jest.fn(),
  insert: jest.fn(),
  update: jest.fn(),
  delete: jest.fn(),
};

// Mock the database module
jest.mock('../../server/db', () => ({
  db: mockDb,
}));

// Mock drizzle-orm functions
jest.mock('drizzle-orm', () => ({
  eq: jest.fn((column, value) => ({ column, operator: 'eq', value })),
  and: jest.fn((...conditions) => ({ operator: 'and', conditions })),
  or: jest.fn((...conditions) => ({ operator: 'or', conditions })),
  gte: jest.fn((column, value) => ({ column, operator: 'gte', value })),
  lte: jest.fn((column, value) => ({ column, operator: 'lte', value })),
  lt: jest.fn((column, value) => ({ column, operator: 'lt', value })),
  ne: jest.fn((column, value) => ({ column, operator: 'ne', value })),
  inArray: jest.fn((column, values) => ({ column, operator: 'inArray', values })),
  isNull: jest.fn((column) => ({ column, operator: 'isNull' })),
  ilike: jest.fn((column, value) => ({ column, operator: 'ilike', value })),
  exists: jest.fn((query) => ({ operator: 'exists', query })),
  sql: jest.fn((strings: any, ...values: any[]) => {
    if (typeof strings === 'string') {
      return { sql: strings };
    }
    return { sql: strings.join('?'), values };
  }),
  desc: jest.fn((column) => ({ column, direction: 'desc' })),
  asc: jest.fn((column) => ({ column, direction: 'asc' })),
}));

// Mock schema tables
jest.mock('@shared/schema', () => ({
  bills: { 
    id: 'bills.id', 
    buildingId: 'bills.buildingId',
    billNumber: 'bills.billNumber',
    title: 'bills.title',
    description: 'bills.description',
    category: 'bills.category',
    vendor: 'bills.vendor',
    paymentType: 'bills.paymentType',
    schedulePayment: 'bills.schedulePayment',
    scheduleCustom: 'bills.scheduleCustom',
    costs: 'bills.costs',
    totalAmount: 'bills.totalAmount',
    startDate: 'bills.startDate',
    endDate: 'bills.endDate',
    status: 'bills.status',
    filePath: 'bills.filePath',
    fileName: 'bills.fileName',
    fileSize: 'bills.fileSize',
    isAiAnalyzed: 'bills.isAiAnalyzed',
    aiAnalysisData: 'bills.aiAnalysisData',
    isAutoGenerated: 'bills.isAutoGenerated',
    sourceTemplateId: 'bills.sourceTemplateId',
    autoGeneratedLabel: 'bills.autoGeneratedLabel',
    createdBy: 'bills.createdBy',
    createdAt: 'bills.createdAt',
    updatedAt: 'bills.updatedAt',
  },
  buildings: { id: 'buildings.id', name: 'buildings.name' },
  users: { id: 'users.id' },
  documents: { id: 'documents.id' },
  payments: { id: 'payments.id', billId: 'payments.billId' },
}));

// Mock financial service
jest.mock('../../server/services/consolidated-financial-service', () => ({
  financialService: {
    generatePaymentsForBill: jest.fn().mockResolvedValue(undefined),
    updatePaymentsForBill: jest.fn().mockResolvedValue(undefined),
    regenerateCompletePaymentSchedule: jest.fn().mockResolvedValue({ deletedCount: 0, createdCount: 0 }),
    scheduleBillUpdate: jest.fn().mockResolvedValue(undefined),
    createAutoGeneratedBill: jest.fn().mockResolvedValue(undefined),
  },
}));

// Mock AI service
jest.mock('../../server/services/consolidated-ai-service', () => ({
  aiService: {
    extractBillData: jest.fn().mockResolvedValue({
      title: 'Extracted Bill',
      category: 'utilities',
      totalAmount: '100.00',
    }),
  },
}));

// Mock secure file storage
jest.mock('../../server/services/secure-file-storage', () => ({
  secureFileStorage: {
    saveFile: jest.fn().mockResolvedValue({ path: '/test/path', filename: 'test.pdf' }),
  },
}));

// Mock authentication middleware
const mockAuthMiddleware = jest.fn<RequestHandler>();

jest.mock('../../server/auth', () => ({
  requireAuth: mockAuthMiddleware,
}));

// Import the bills routes registration function after mocks are set up
import { registerBillRoutes } from '../../server/api/bills';

describe('Bills API Integration Tests', () => {
  let app: express.Application;
  let agent: ReturnType<typeof request.agent>;

  const testOrg = {
    id: '00000000-0000-0000-0000-000000000001',
    name: 'Test Organization for Bills',
    isActive: true,
  };

  const testBuilding = {
    id: '00000000-0000-0000-0000-000000000002',
    name: 'Test Building for Bills',
    address: '123 Test Street',
    city: 'Montreal',
    province: 'QC',
    postalCode: 'H1H 1H1',
    organizationId: testOrg.id,
    isActive: true,
  };

  const testUser = {
    id: '00000000-0000-0000-0000-000000000003',
    email: 'bills-test@example.com',
    username: 'billstester',
    password: 'hashed-password',
    firstName: 'Bills',
    lastName: 'Tester',
    role: 'admin' as const,
    language: 'en' as const,
    isActive: true,
  };

  beforeEach(() => {
    // Reset all mocks
    jest.clearAllMocks();
    
    // Create fresh Express app for each test
    app = express();
    app.use(express.json());
    
    // Setup session middleware
    app.use(session({
      secret: 'test-secret',
      resave: false,
      saveUninitialized: false,
      cookie: { secure: false },
    }));

    // Configure auth middleware to inject test user
    mockAuthMiddleware.mockImplementation((req: any, res: any, next: any) => {
      req.user = {
        id: testUser.id,
        username: testUser.username,
        email: testUser.email,
        firstName: testUser.firstName,
        lastName: testUser.lastName,
        role: testUser.role,
        isActive: testUser.isActive,
        organizations: [testOrg.id],
      } as AuthenticatedUser;
      next();
    });

    // Set up default database mocks for syncAutoGeneratedBill
    // Mock for checking existing auto-generated bills
    const defaultSelectMock = {
      from: jest.fn().mockReturnValue({
        where: jest.fn().mockReturnValue({
          limit: jest.fn().mockResolvedValue([]), // No existing auto-generated bills by default
          orderBy: jest.fn().mockResolvedValue([]),
        }),
      }),
    };
    
    // Mock for update operations in syncAutoGeneratedBill
    const defaultUpdateMock = {
      set: jest.fn().mockReturnValue({
        where: jest.fn().mockResolvedValue(undefined),
      }),
    };
    
    // Mock for insert operations in syncAutoGeneratedBill
    const defaultInsertMock = {
      values: jest.fn().mockReturnValue({
        returning: jest.fn().mockResolvedValue([]),
      }),
    };
    
    // Mock for delete operations in syncAutoGeneratedBill
    const defaultDeleteMock = {
      where: jest.fn().mockResolvedValue(undefined),
    };

    (mockDb.select as any).mockReturnValue(defaultSelectMock);
    (mockDb.update as any).mockReturnValue(defaultUpdateMock);
    (mockDb.insert as any).mockReturnValue(defaultInsertMock);
    (mockDb.delete as any).mockReturnValue(defaultDeleteMock);

    // Register bills routes
    registerBillRoutes(app);
    
    agent = request.agent(app);
  });

  describe('Bill Creation', () => {
    it('should create a unique bill successfully', async () => {
      const billData = {
        buildingId: testBuilding.id,
        title: 'Test Unique Bill',
        description: 'A test bill for unique payment',
        category: 'maintenance',
        vendor: 'Test Vendor',
        paymentType: 'unique',
        costs: ['1000.00'],
        totalAmount: '1000.00',
        startDate: '2025-01-15',
        status: 'draft',
      };

      const mockCreatedBill = {
        id: 'bill-1',
        billNumber: 'BILL-TEST-001',
        ...billData,
        costs: [1000.00],
        totalAmount: 1000.00,
        isAutoGenerated: false,
        sourceTemplateId: null,
        autoGeneratedLabel: null,
        createdBy: testUser.id,
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      (mockDb.insert as any).mockReturnValue({
        values: jest.fn().mockReturnValue({
          returning: jest.fn().mockResolvedValue([mockCreatedBill]),
        }),
      });

      const response = await agent
        .post('/api/bills')
        .send(billData);

      expect(response.status).toBe(201);
      expect(response.body).toBeDefined();
      expect(response.body.id).toBeDefined();
      expect(response.body.title).toBe('Test Unique Bill');
      expect(response.body.paymentType).toBe('unique');
      expect(response.body.buildingId).toBe(testBuilding.id);
    });

    it('should create a recurrent bill with schedule', async () => {
      const billData = {
        buildingId: testBuilding.id,
        title: 'Monthly Maintenance Fee',
        description: 'Recurring monthly maintenance',
        category: 'maintenance',
        vendor: 'Maintenance Corp',
        paymentType: 'recurrent',
        schedulePayment: 'monthly',
        costs: ['500.00'],
        totalAmount: '500.00',
        startDate: '2025-01-01',
        endDate: '2025-12-31',
        status: 'draft',
      };

      const mockCreatedBill = {
        id: 'bill-2',
        billNumber: 'BILL-TEST-002',
        ...billData,
        costs: [500.00],
        totalAmount: 500.00,
        isAutoGenerated: false,
        sourceTemplateId: null,
        autoGeneratedLabel: null,
        createdBy: testUser.id,
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      (mockDb.insert as any).mockReturnValue({
        values: jest.fn().mockReturnValue({
          returning: jest.fn().mockResolvedValue([mockCreatedBill]),
        }),
      });

      const response = await agent
        .post('/api/bills')
        .send(billData);

      expect(response.status).toBe(201);
      expect(response.body.paymentType).toBe('recurrent');
      expect(response.body.schedulePayment).toBe('monthly');
      expect(response.body.endDate).toBe('2025-12-31');
    });

    it('should create auto-generated bill with metadata', async () => {
      const autoGenData = {
        buildingId: testBuilding.id,
        title: 'Auto-Generated Bill 2026',
        category: 'supplies',
        vendor: 'Supply Corp',
        paymentType: 'unique',
        costs: ['800.00'],
        totalAmount: '800.00',
        startDate: '2026-01-01',
        status: 'draft',
      };

      const mockAutoGenBill = {
        id: 'auto-bill-1',
        billNumber: 'BILL-AUTO-001',
        ...autoGenData,
        costs: [800.00],
        totalAmount: 800.00,
        isAutoGenerated: false,
        sourceTemplateId: null,
        autoGeneratedLabel: null,
        createdBy: testUser.id,
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      (mockDb.insert as any).mockReturnValue({
        values: jest.fn().mockReturnValue({
          returning: jest.fn().mockResolvedValue([mockAutoGenBill]),
        }),
      });

      const response = await agent
        .post('/api/bills')
        .send(autoGenData);

      expect(response.status).toBe(201);
      expect(response.body.id).toBeDefined();
      expect(response.body.category).toBe('supplies');
    });
  });

  describe('Bill Updates', () => {
    it('should update bill fields correctly', async () => {
      const billId = 'bill-to-update';
      const existingBill = {
        id: billId,
        buildingId: testBuilding.id,
        billNumber: 'BILL-TEST-003',
        title: 'Initial Title',
        description: null,
        category: 'maintenance',
        vendor: null,
        paymentType: 'unique',
        schedulePayment: null,
        scheduleCustom: null,
        costs: [100.00],
        totalAmount: 100.00,
        startDate: '2025-01-01',
        endDate: null,
        status: 'draft',
        isAutoGenerated: false,
        sourceTemplateId: null,
        autoGeneratedLabel: null,
        createdBy: testUser.id,
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      const updatedBill = {
        ...existingBill,
        title: 'Updated Title',
        description: 'New description',
        totalAmount: 150.00,
        updatedAt: new Date(),
      };

      (mockDb.select as any).mockReturnValue({
        from: jest.fn().mockReturnValue({
          where: jest.fn().mockReturnValue({
            limit: jest.fn().mockResolvedValue([existingBill]),
          }),
        }),
      });

      (mockDb.update as any).mockReturnValue({
        set: jest.fn().mockReturnValue({
          where: jest.fn().mockReturnValue({
            returning: jest.fn().mockResolvedValue([updatedBill]),
          }),
        }),
      });

      const response = await agent
        .put(`/api/bills/${billId}`)
        .send({
          title: 'Updated Title',
          description: 'New description',
          totalAmount: '150.00',
        });

      expect(response.status).toBe(200);
      expect(response.body.title).toBe('Updated Title');
      expect(response.body.description).toBe('New description');
      expect(response.body.totalAmount).toBe(150.00);
    });

    it('should update bill status', async () => {
      const billId = 'bill-status-test';
      const existingBill = {
        id: billId,
        buildingId: testBuilding.id,
        billNumber: 'BILL-TEST-004',
        title: 'Status Test Bill',
        description: null,
        category: 'maintenance',
        vendor: null,
        paymentType: 'unique',
        schedulePayment: null,
        scheduleCustom: null,
        costs: [200.00],
        totalAmount: 200.00,
        startDate: '2025-01-01',
        endDate: null,
        status: 'draft',
        isAutoGenerated: false,
        sourceTemplateId: null,
        autoGeneratedLabel: null,
        createdBy: testUser.id,
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      const statuses: Array<'draft' | 'sent' | 'paid'> = ['sent', 'paid'];
      
      for (const status of statuses) {
        const updatedBill = {
          ...existingBill,
          status,
          updatedAt: new Date(),
        };

        (mockDb.select as any).mockReturnValue({
          from: jest.fn().mockReturnValue({
            where: jest.fn().mockReturnValue({
              limit: jest.fn().mockResolvedValue([existingBill]),
            }),
          }),
        });

        (mockDb.update as any).mockReturnValue({
          set: jest.fn().mockReturnValue({
            where: jest.fn().mockReturnValue({
              returning: jest.fn().mockResolvedValue([updatedBill]),
            }),
          }),
        });

        const response = await agent
          .put(`/api/bills/${billId}`)
          .send({ status });

        expect(response.status).toBe(200);
        expect(response.body.status).toBe(status);
      }
    });
  });

  describe('Bill Querying and Filtering', () => {
    const testBills = [
      {
        id: 'bill-insurance',
        buildingId: testBuilding.id,
        billNumber: 'BILL-INS-001',
        title: 'Insurance Bill 2025',
        description: null,
        category: 'insurance',
        vendor: null,
        paymentType: 'unique',
        schedulePayment: null,
        scheduleCustom: null,
        costs: [2500.00],
        totalAmount: 2500.00,
        startDate: '2025-03-01',
        endDate: null,
        status: 'paid',
        isAutoGenerated: false,
        sourceTemplateId: null,
        autoGeneratedLabel: null,
        createdBy: testUser.id,
        createdAt: new Date('2025-03-01'),
        updatedAt: new Date('2025-03-01'),
      },
      {
        id: 'bill-maintenance',
        buildingId: testBuilding.id,
        billNumber: 'BILL-MNT-001',
        title: 'Maintenance Bill 2025',
        description: null,
        category: 'maintenance',
        vendor: null,
        paymentType: 'unique',
        schedulePayment: null,
        scheduleCustom: null,
        costs: [500.00],
        totalAmount: 500.00,
        startDate: '2025-06-15',
        endDate: null,
        status: 'sent',
        isAutoGenerated: false,
        sourceTemplateId: null,
        autoGeneratedLabel: null,
        createdBy: testUser.id,
        createdAt: new Date('2025-06-15'),
        updatedAt: new Date('2025-06-15'),
      },
      {
        id: 'bill-utilities',
        buildingId: testBuilding.id,
        billNumber: 'BILL-UTL-001',
        title: 'Supplies Bill 2025',
        description: null,
        category: 'supplies',
        vendor: null,
        paymentType: 'unique',
        schedulePayment: null,
        scheduleCustom: null,
        costs: [300.00],
        totalAmount: 300.00,
        startDate: '2025-09-01',
        endDate: null,
        status: 'draft',
        isAutoGenerated: false,
        sourceTemplateId: null,
        autoGeneratedLabel: null,
        createdBy: testUser.id,
        createdAt: new Date('2025-09-01'),
        updatedAt: new Date('2025-09-01'),
      },
    ];

    it('should filter bills by category', async () => {
      const insuranceBills = testBills.filter(bill => bill.category === 'insurance');

      (mockDb.select as any).mockReturnValue({
        from: jest.fn().mockReturnValue({
          where: jest.fn().mockReturnValue({
            orderBy: jest.fn().mockResolvedValue(insuranceBills),
          }),
        }),
      });

      const response = await agent
        .get('/api/bills')
        .query({ buildingId: testBuilding.id, category: 'insurance' });

      expect(response.status).toBe(200);
      expect(response.body.length).toBe(1);
      expect(response.body[0].category).toBe('insurance');
    });

    it('should filter bills by status', async () => {
      const paidBills = testBills.filter(bill => bill.status === 'paid');

      (mockDb.select as any).mockReturnValue({
        from: jest.fn().mockReturnValue({
          where: jest.fn().mockReturnValue({
            orderBy: jest.fn().mockResolvedValue(paidBills),
          }),
        }),
      });

      const response = await agent
        .get('/api/bills')
        .query({ buildingId: testBuilding.id, status: 'paid' });

      expect(response.status).toBe(200);
      expect(response.body.length).toBe(1);
      expect(response.body[0].status).toBe('paid');
    });

    it('should filter bills by year', async () => {
      (mockDb.select as any).mockReturnValue({
        from: jest.fn().mockReturnValue({
          where: jest.fn().mockReturnValue({
            orderBy: jest.fn().mockResolvedValue(testBills),
          }),
        }),
      });

      const response = await agent
        .get('/api/bills')
        .query({ buildingId: testBuilding.id, year: '2025' });

      expect(response.status).toBe(200);
      expect(response.body.length).toBe(3);
    });

    it('should retrieve all bills for a building', async () => {
      (mockDb.select as any).mockReturnValue({
        from: jest.fn().mockReturnValue({
          where: jest.fn().mockReturnValue({
            orderBy: jest.fn().mockResolvedValue(testBills),
          }),
        }),
      });

      const response = await agent
        .get('/api/bills')
        .query({ buildingId: testBuilding.id });

      expect(response.status).toBe(200);
      expect(response.body.length).toBe(3);
    });
  });

  describe('Auto-Generation Workflow', () => {
    it('should link generated bills to source template', async () => {
      const sourceBillId = 'source-bill-recurring';
      const generatedBills = [
        {
          id: 'auto-bill-2026',
          buildingId: testBuilding.id,
          billNumber: 'BILL-AUTO-2026',
          title: 'Auto 2026 - Recurring Source Bill',
          description: null,
          category: 'maintenance',
          vendor: null,
          paymentType: 'unique',
          schedulePayment: null,
          scheduleCustom: null,
          costs: [1200.00],
          totalAmount: 1200.00,
          startDate: '2026-01-01',
          endDate: null,
          status: 'draft',
          isAutoGenerated: true,
          sourceTemplateId: sourceBillId,
          autoGeneratedLabel: 'Auto 2026',
          createdBy: testUser.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 'auto-bill-2027',
          buildingId: testBuilding.id,
          billNumber: 'BILL-AUTO-2027',
          title: 'Auto 2027 - Recurring Source Bill',
          description: null,
          category: 'maintenance',
          vendor: null,
          paymentType: 'unique',
          schedulePayment: null,
          scheduleCustom: null,
          costs: [1200.00],
          totalAmount: 1200.00,
          startDate: '2027-01-01',
          endDate: null,
          status: 'draft',
          isAutoGenerated: true,
          sourceTemplateId: sourceBillId,
          autoGeneratedLabel: 'Auto 2027',
          createdBy: testUser.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ];

      (mockDb.select as any).mockReturnValue({
        from: jest.fn().mockReturnValue({
          where: jest.fn().mockReturnValue({
            orderBy: jest.fn().mockResolvedValue(generatedBills),
          }),
        }),
      });

      const response = await agent
        .get('/api/bills')
        .query({ buildingId: testBuilding.id, isAutoGenerated: 'true' });

      expect(response.status).toBe(200);
      expect(response.body.length).toBe(2);
      response.body.forEach((bill: any) => {
        expect(bill.sourceTemplateId).toBe(sourceBillId);
        expect(bill.isAutoGenerated).toBe(true);
      });
    });

    it('should update all generated bills when source is modified', async () => {
      const sourceBillId = 'source-update';
      const existingBill = {
        id: sourceBillId,
        buildingId: testBuilding.id,
        billNumber: 'BILL-SRC-001',
        title: 'Source for Update',
        description: null,
        category: 'repairs',
        vendor: 'Original Vendor',
        paymentType: 'recurrent',
        schedulePayment: 'monthly',
        scheduleCustom: null,
        costs: [600.00],
        totalAmount: 600.00,
        startDate: '2025-01-01',
        endDate: null,
        status: 'draft',
        isAutoGenerated: false,
        sourceTemplateId: null,
        autoGeneratedLabel: null,
        createdBy: testUser.id,
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      const updatedBill = {
        ...existingBill,
        vendor: 'Updated Vendor',
        updatedAt: new Date(),
      };

      (mockDb.select as any).mockReturnValue({
        from: jest.fn().mockReturnValue({
          where: jest.fn().mockReturnValue({
            limit: jest.fn().mockResolvedValue([existingBill]),
          }),
        }),
      });

      (mockDb.update as any).mockReturnValue({
        set: jest.fn().mockReturnValue({
          where: jest.fn().mockReturnValue({
            returning: jest.fn().mockResolvedValue([updatedBill]),
          }),
        }),
      });

      const response = await agent
        .put(`/api/bills/${sourceBillId}`)
        .send({ vendor: 'Updated Vendor' });

      expect(response.status).toBe(200);
      expect(response.body.vendor).toBe('Updated Vendor');
    });
  });

  describe('Bill Deletion', () => {
    it('should delete a bill successfully', async () => {
      const billId = 'bill-to-delete';
      const existingBill = {
        id: billId,
        buildingId: testBuilding.id,
        billNumber: 'BILL-DEL-001',
        title: 'Bill to Delete',
        description: null,
        category: 'maintenance',
        vendor: null,
        paymentType: 'unique',
        schedulePayment: null,
        scheduleCustom: null,
        costs: [100.00],
        totalAmount: 100.00,
        startDate: '2025-01-01',
        endDate: null,
        status: 'draft',
        isAutoGenerated: false,
        sourceTemplateId: null,
        autoGeneratedLabel: null,
        createdBy: testUser.id,
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      (mockDb.select as any).mockReturnValue({
        from: jest.fn().mockReturnValue({
          where: jest.fn().mockReturnValue({
            limit: jest.fn().mockResolvedValue([existingBill]),
          }),
        }),
      });

      (mockDb.delete as any).mockReturnValue({
        where: jest.fn().mockReturnValue({
          returning: jest.fn().mockResolvedValue([existingBill]),
        }),
      });

      const response = await agent
        .delete(`/api/bills/${billId}`);

      expect(response.status).toBe(200);
    });

    it('should delete source bill and its generated bills', async () => {
      const sourceBillId = 'source-to-delete';
      const sourceBill = {
        id: sourceBillId,
        buildingId: testBuilding.id,
        billNumber: 'BILL-SRC-DEL',
        title: 'Source to Delete',
        description: null,
        category: 'maintenance',
        vendor: null,
        paymentType: 'recurrent',
        schedulePayment: 'monthly',
        scheduleCustom: null,
        costs: [400.00],
        totalAmount: 400.00,
        startDate: '2025-01-01',
        endDate: null,
        status: 'draft',
        isAutoGenerated: false,
        sourceTemplateId: null,
        autoGeneratedLabel: null,
        createdBy: testUser.id,
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      (mockDb.select as any).mockReturnValue({
        from: jest.fn().mockReturnValue({
          where: jest.fn().mockReturnValue({
            limit: jest.fn().mockResolvedValue([sourceBill]),
          }),
        }),
      });

      (mockDb.delete as any).mockReturnValue({
        where: jest.fn().mockReturnValue({
          returning: jest.fn().mockResolvedValue([sourceBill]),
        }),
      });

      const response = await agent
        .delete(`/api/bills/${sourceBillId}`);

      expect(response.status).toBe(200);
    });
  });

  describe('Data Integrity', () => {
    it('should enforce foreign key constraint on buildingId', async () => {
      const invalidBillData = {
        buildingId: 'not-a-valid-uuid',
        title: 'Invalid Building Bill',
        category: 'maintenance',
        paymentType: 'unique',
        costs: ['100.00'],
        totalAmount: '100.00',
        startDate: '2025-01-01',
        status: 'draft',
      };

      const response = await agent
        .post('/api/bills')
        .send(invalidBillData);

      expect(response.status).toBe(400);
      expect(response.body).toHaveProperty('message');
      expect(response.body.message).toContain('Invalid bill data');
    });

    it('should handle concurrent bill updates correctly', async () => {
      const billId = 'concurrent-test';
      const existingBill = {
        id: billId,
        buildingId: testBuilding.id,
        billNumber: 'BILL-CONC-001',
        title: 'Concurrent Update Test',
        description: null,
        category: 'maintenance',
        vendor: null,
        paymentType: 'unique',
        schedulePayment: null,
        scheduleCustom: null,
        costs: [100.00],
        totalAmount: 100.00,
        startDate: '2025-01-01',
        endDate: null,
        status: 'draft',
        isAutoGenerated: false,
        sourceTemplateId: null,
        autoGeneratedLabel: null,
        createdBy: testUser.id,
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      const updatedBill1 = {
        ...existingBill,
        title: 'Update 1',
        updatedAt: new Date(),
      };

      const updatedBill2 = {
        ...updatedBill1,
        description: 'Update 2',
        updatedAt: new Date(),
      };

      // First update
      (mockDb.select as any).mockReturnValueOnce({
        from: jest.fn().mockReturnValue({
          where: jest.fn().mockReturnValue({
            limit: jest.fn().mockResolvedValue([existingBill]),
          }),
        }),
      });

      (mockDb.update as any).mockReturnValueOnce({
        set: jest.fn().mockReturnValue({
          where: jest.fn().mockReturnValue({
            returning: jest.fn().mockResolvedValue([updatedBill1]),
          }),
        }),
      });

      const response1 = await agent
        .put(`/api/bills/${billId}`)
        .send({ title: 'Update 1' });

      expect(response1.status).toBe(200);
      expect(response1.body.title).toBe('Update 1');

      // Second update
      (mockDb.select as any).mockReturnValueOnce({
        from: jest.fn().mockReturnValue({
          where: jest.fn().mockReturnValue({
            limit: jest.fn().mockResolvedValue([updatedBill1]),
          }),
        }),
      });

      (mockDb.update as any).mockReturnValueOnce({
        set: jest.fn().mockReturnValue({
          where: jest.fn().mockReturnValue({
            returning: jest.fn().mockResolvedValue([updatedBill2]),
          }),
        }),
      });

      const response2 = await agent
        .put(`/api/bills/${billId}`)
        .send({ description: 'Update 2' });

      expect(response2.status).toBe(200);
      expect(response2.body.description).toBe('Update 2');
    });
  });
});
