/**
 * @file Bills API Integration Tests
 * @description Full integration tests for bills API with real Express router stack
 * Tests the complete bills API including CRUD operations, auto-generation, and filtering
 */

import request from 'supertest';
import express, { type RequestHandler } from 'express';
import session from 'express-session';
import { describe, it, expect, beforeEach, jest } from '@jest/globals';
import type { AuthenticatedUser } from '../../server/rbac';

// Mock database operations
const mockDb = {
  query: {
    bills: {
      findMany: jest.fn<() => Promise<any[]>>(),
      findFirst: jest.fn<() => Promise<any | null>>(),
    },
  },
  select: jest.fn<any>(),
  insert: jest.fn<any>(),
  update: jest.fn<any>(),
  delete: jest.fn<any>(),
};

// Mock the database module
jest.mock('../../server/db', () => ({
  db: mockDb,
}));

// Short-circuit the MCP server import chain pulled in transitively via
// `server/utils/rest-db-error → server/mcp/server → workflow-service →
// shared/schemas/maintenance`. We don't exercise the MCP write-error
// classifier in these route tests, so a no-op stub is enough.
jest.mock('../../server/mcp/server', () => ({
  buildWriteErrorResponse: jest.fn((_err: unknown) => ({
    status: 500,
    body: { error: 'mocked' },
    retryAfterSeconds: undefined,
  })),
  createMcpServer: jest.fn(),
}));

// `uuid` ships pure ESM in newer versions which Jest's CJS transformer can't
// load directly. Stub the only export this route needs (`v4`) with a simple
// counter so the test file can require server/api/bills.ts without crashing.
let __uuidCounter = 0;
jest.mock('uuid', () => ({
  v4: jest.fn(() => `00000000-0000-0000-0000-${String(++__uuidCounter).padStart(12, '0')}`),
}));

// Mock drizzle-orm functions
jest.mock('drizzle-orm', () => ({
  eq: jest.fn((column, value) => ({ column, operator: 'eq', value })),
  and: jest.fn((...conditions) => ({ operator: 'and', conditions })),
  or: jest.fn((...conditions) => ({ operator: 'or', conditions })),
  gte: jest.fn((column, value) => ({ column, operator: 'gte', value })),
  lte: jest.fn((column, value) => ({ column, operator: 'lte', value })),
  lt: jest.fn((column, value) => ({ column, operator: 'lt', value })),
  ne: jest.fn((column, value) => ({ column, operator: 'ne', value })),
  inArray: jest.fn((column, values) => ({ column, operator: 'inArray', values })),
  isNull: jest.fn((column) => ({ column, operator: 'isNull' })),
  ilike: jest.fn((column, value) => ({ column, operator: 'ilike', value })),
  exists: jest.fn((query) => ({ operator: 'exists', query })),
  sql: Object.assign(
    jest.fn((strings: any, ...values: any[]) => {
      if (typeof strings === 'string') {
        return { sql: strings };
      }
      return { sql: strings.join('?'), values };
    }),
    {
      join: (parts: any[], _separator?: any) => ({ sql: 'join', parts }),
    },
  ),
  desc: jest.fn((column) => ({ column, direction: 'desc' })),
  asc: jest.fn((column) => ({ column, direction: 'asc' })),
}));

// Mock schema tables
jest.mock('@shared/schema', () => {
  const billsTable = { 
    id: 'bills.id', 
    buildingId: 'bills.buildingId',
    billNumber: 'bills.billNumber',
    title: 'bills.title',
    description: 'bills.description',
    category: 'bills.category',
    vendor: 'bills.vendor',
    paymentType: 'bills.paymentType',
    schedulePayment: 'bills.schedulePayment',
    scheduleCustom: 'bills.scheduleCustom',
    costs: 'bills.costs',
    totalAmount: 'bills.totalAmount',
    startDate: 'bills.startDate',
    endDate: 'bills.endDate',
    status: 'bills.status',
    filePath: 'bills.filePath',
    fileName: 'bills.fileName',
    fileSize: 'bills.fileSize',
    isAiAnalyzed: 'bills.isAiAnalyzed',
    aiAnalysisData: 'bills.aiAnalysisData',
    isAutoGenerated: 'bills.isAutoGenerated',
    sourceTemplateId: 'bills.sourceTemplateId',
    autoGeneratedLabel: 'bills.autoGeneratedLabel',
    parentBillId: 'bills.parentBillId',
    issueDate: 'bills.issueDate',
    billType: 'bills.billType',
    paymentStructure: 'bills.paymentStructure',
    createdBy: 'bills.createdBy',
    createdAt: 'bills.createdAt',
    updatedAt: 'bills.updatedAt',
    financialYearStart: 'bills.financialYearStart',
  };
  const paymentsTable = { 
    id: 'payments.id', 
    billId: 'payments.billId',
    scheduledDate: 'payments.scheduledDate',
    amount: 'payments.amount',
    status: 'payments.status',
  };
  const buildingsTable = { 
    id: 'buildings.id', 
    name: 'buildings.name',
    financialYearStart: 'buildings.financialYearStart',
  };
  const makeMockSchema: any = () => {
    const s: any = {
      parse: jest.fn((data: any) => data),
      extend: jest.fn(() => makeMockSchema()),
      partial: jest.fn(() => makeMockSchema()),
      omit: jest.fn(() => makeMockSchema()),
    };
    return s;
  };
  return {
    bills: billsTable,
    buildings: buildingsTable,
    users: { id: 'users.id' },
    documents: { id: 'documents.id' },
    payments: paymentsTable,
    insertBillSchema: makeMockSchema(),
  };
});

// Mock financial service
jest.mock('../../server/services/consolidated-financial-service', () => ({
  financialService: {
    generatePaymentsForBill: jest.fn<any>().mockResolvedValue(undefined as any),
    updatePaymentsForBill: jest.fn<any>().mockResolvedValue(undefined as any),
    regenerateCompletePaymentSchedule: jest.fn<any>().mockResolvedValue({ deletedCount: 0, createdCount: 0 } as any),
    scheduleBillUpdate: jest.fn<any>().mockResolvedValue(undefined as any),
    createAutoGeneratedBill: jest.fn<any>().mockResolvedValue(undefined as any),
  },
}));

// Mock AI service
jest.mock('../../server/services/consolidated-ai-service', () => ({
  aiService: {
    extractBillData: jest.fn<any>().mockResolvedValue({
      title: 'Extracted Bill',
      category: 'utilities',
      totalAmount: '100.00',
    } as any),
  },
}));

// Mock secure file storage
jest.mock('../../server/services/secure-file-storage', () => ({
  secureFileStorage: {
    saveFile: jest.fn<any>().mockResolvedValue({ path: '/test/path', filename: 'test.pdf' } as any),
  },
}));

// Mock authentication middleware
jest.mock('../../server/auth', () => {
  const middleware = (req: any, res: any, next: any) => next();
  return {
    requireAuth: middleware,
    requireRole: jest.fn(() => middleware),
  };
});

// Mock storage
jest.mock('../../server/storage', () => ({
  storage: {
    getBill: jest.fn().mockResolvedValue(null),
    createBill: jest.fn().mockResolvedValue({}),
    updateBill: jest.fn().mockResolvedValue({}),
    deleteBill: jest.fn().mockResolvedValue(true),
  },
}));

// Mock payment generation service
jest.mock('../../server/services/payment-generation-service', () => ({
  paymentGenerationService: {
    generatePayments: jest.fn().mockResolvedValue([]),
    deletePaymentsForBill: jest.fn().mockResolvedValue(0),
    updatePaymentStatusFromBillStatus: jest.fn().mockResolvedValue(undefined),
  },
}));

// Mock bill generation service
jest.mock('../../server/services/bill-generation-service', () => ({
  billAutoGenerationService: {
    checkAndGenerateBills: jest.fn().mockResolvedValue([]),
    syncAutoGeneratedBills: jest.fn().mockResolvedValue(undefined),
  },
}));

// Mock money flow job
jest.mock('../../server/jobs/money_flow_job', () => ({
  moneyFlowJob: {
    trigger: jest.fn(),
  },
}));

// Mock file upload middleware
jest.mock('../../server/middleware/fileUpload', () => ({
  uploadInvoiceFile: (req: any, res: any, next: any) => next(),
  handleUploadError: jest.fn(),
}));

// Mock document service
jest.mock('../../server/services/document-service', () => ({
  documentService: {
    getDocument: jest.fn().mockResolvedValue(null),
    createDocument: jest.fn().mockResolvedValue({}),
  },
}));

// Mock logger
jest.mock('../../server/utils/logger', () => ({
  logDebug: jest.fn(),
  logInfo: jest.fn(),
  logWarn: jest.fn(),
  logError: jest.fn(),
}));

// Mock filename normalization
jest.mock('../../server/utils/filenameNormalization', () => ({
  normalizeFilename: jest.fn((name: string) => name),
}));

// Mock bills queries
jest.mock('../../server/db/queries/bills-queries', () => ({
  getBillById: jest.fn().mockResolvedValue(null),
  getBillWithPayments: jest.fn().mockResolvedValue(null),
  getBillsWithPayments: jest.fn().mockResolvedValue([]),
  getEffectiveBillType: jest.fn().mockReturnValue('unique'),
}));

// Mock financial schemas
jest.mock('@shared/schemas/financial', () => ({
  BILL_CATEGORIES: ['maintenance', 'utilities', 'insurance', 'taxes', 'management', 'professional_services', 'capital_improvements', 'common_areas', 'administrative', 'other'],
}));

// Import the bills routes registration function after mocks are set up
import { registerBillRoutes } from '../../server/api/bills';
import { getBillById, getBillsWithPayments } from '../../server/db/queries/bills-queries';

describe('Bills API Integration Tests', () => {
  let app: express.Application;
  let agent: ReturnType<typeof request.agent>;

  const testOrg = {
    id: '00000000-0000-0000-0000-000000000001',
    name: 'Test Organization for Bills',
    isActive: true,
  };

  const testBuilding = {
    id: '00000000-0000-0000-0000-000000000002',
    name: 'Test Building for Bills',
    address: '123 Test Street',
    city: 'Montreal',
    province: 'QC',
    postalCode: 'H1H 1H1',
    organizationId: testOrg.id,
    isActive: true,
  };

  const testUser = {
    id: '00000000-0000-0000-0000-000000000003',
    email: 'bills-test@example.com',
    username: 'billstester',
    password: 'hashed-password',
    firstName: 'Bills',
    lastName: 'Tester',
    role: 'admin' as const,
    language: 'en' as const,
    isActive: true,
  };

  beforeEach(() => {
    // Reset all mocks
    jest.clearAllMocks();
    
    // Create fresh Express app for each test
    app = express();
    app.use(express.json());
    
    // Setup session middleware
    app.use(session({
      secret: 'test-secret',
      resave: false,
      saveUninitialized: false,
      cookie: { secure: false },
    }));

    // Inject test user via middleware (before route registration)
    app.use((req: any, res: any, next: any) => {
      req.user = {
        id: testUser.id,
        username: testUser.username,
        email: testUser.email,
        firstName: testUser.firstName,
        lastName: testUser.lastName,
        role: testUser.role,
        isActive: testUser.isActive,
        organizations: [testOrg.id],
      } as AuthenticatedUser;
      next();
    });

    // Set up default database mocks
    // Create a deeply chainable select mock that handles all drizzle patterns
    const createChainMock = (resolveValue: any = []): any => {
      const chain: any = {};
      const methods = ['from', 'where', 'limit', 'orderBy', 'groupBy', 'having', 'leftJoin', 'innerJoin', 'rightJoin', 'fullJoin', 'offset'];
      methods.forEach(method => {
        chain[method] = jest.fn<any>().mockImplementation(() => chain);
      });
      chain.then = (resolve: any) => resolve(resolveValue);
      return chain;
    };

    const defaultSelectMock = createChainMock([]);
    
    // Mock for update operations in syncAutoGeneratedBill
    const defaultUpdateMock = {
      set: jest.fn<any>().mockReturnValue({
        where: jest.fn<any>().mockResolvedValue(undefined as any),
      }),
    };
    
    // Mock for insert operations in syncAutoGeneratedBill
    const defaultInsertMock = {
      values: jest.fn<any>().mockReturnValue({
        returning: jest.fn<any>().mockResolvedValue([] as any),
      }),
    };
    
    // Mock for delete operations in syncAutoGeneratedBill
    const defaultDeleteMock = {
      where: jest.fn<any>().mockResolvedValue(undefined as any),
    };

    (mockDb.select as any).mockReturnValue(defaultSelectMock);
    (mockDb.update as any).mockReturnValue(defaultUpdateMock);
    (mockDb.insert as any).mockReturnValue(defaultInsertMock);
    (mockDb.delete as any).mockReturnValue(defaultDeleteMock);

    // Register bills routes
    registerBillRoutes(app as any);
    
    agent = request.agent(app);
  });

  describe('Bill Creation', () => {
    it('should create a unique bill successfully', async () => {
      const billData = {
        buildingId: testBuilding.id,
        title: 'Test Unique Bill',
        description: 'A test bill for unique payment',
        category: 'maintenance',
        vendor: 'Test Vendor',
        paymentType: 'unique',
        costs: ['1000.00'],
        totalAmount: '1000.00',
        startDate: '2025-01-15',
        status: 'draft',
      };

      const mockCreatedBill = {
        id: 'bill-1',
        billNumber: 'BILL-TEST-001',
        ...billData,
        costs: [1000.00],
        totalAmount: 1000.00,
        isAutoGenerated: false,
        sourceTemplateId: null,
        autoGeneratedLabel: null,
        createdBy: testUser.id,
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      (mockDb.insert as any).mockReturnValue({
        values: jest.fn<any>().mockReturnValue({
          returning: jest.fn<any>().mockResolvedValue([mockCreatedBill] as any),
        }),
      });

      const response = await agent
        .post('/api/bills')
        .send(billData);

      expect(response.status).toBe(201);
      expect(response.body).toBeDefined();
      expect(response.body.id).toBeDefined();
      expect(response.body.title).toBe('Test Unique Bill');
      expect(response.body.paymentType).toBe('unique');
      expect(response.body.buildingId).toBe(testBuilding.id);
    });

    it('should create a recurrent bill with schedule', async () => {
      const billData = {
        buildingId: testBuilding.id,
        title: 'Monthly Maintenance Fee',
        description: 'Recurring monthly maintenance',
        category: 'maintenance',
        vendor: 'Maintenance Corp',
        paymentType: 'recurrent',
        schedulePayment: 'monthly',
        costs: ['500.00'],
        totalAmount: '500.00',
        startDate: '2025-01-01',
        endDate: '2025-12-31',
        status: 'draft',
      };

      const mockCreatedBill = {
        id: 'bill-2',
        billNumber: 'BILL-TEST-002',
        ...billData,
        costs: [500.00],
        totalAmount: 500.00,
        isAutoGenerated: false,
        sourceTemplateId: null,
        autoGeneratedLabel: null,
        createdBy: testUser.id,
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      (mockDb.insert as any).mockReturnValue({
        values: jest.fn<any>().mockReturnValue({
          returning: jest.fn<any>().mockResolvedValue([mockCreatedBill] as any),
        }),
      });

      const response = await agent
        .post('/api/bills')
        .send(billData);

      expect(response.status).toBe(201);
      expect(response.body.paymentType).toBe('recurrent');
      expect(response.body.schedulePayment).toBe('monthly');
      expect(response.body.endDate).toBe('2025-12-31');
    });

    it('should create auto-generated bill with metadata', async () => {
      const autoGenData = {
        buildingId: testBuilding.id,
        title: 'Auto-Generated Bill 2026',
        category: 'other',
        vendor: 'Supply Corp',
        paymentType: 'unique',
        costs: ['800.00'],
        totalAmount: '800.00',
        startDate: '2026-01-01',
        status: 'draft',
      };

      const mockAutoGenBill = {
        id: 'auto-bill-1',
        billNumber: 'BILL-AUTO-001',
        ...autoGenData,
        costs: [800.00],
        totalAmount: 800.00,
        isAutoGenerated: false,
        sourceTemplateId: null,
        autoGeneratedLabel: null,
        createdBy: testUser.id,
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      (mockDb.insert as any).mockReturnValue({
        values: jest.fn<any>().mockReturnValue({
          returning: jest.fn<any>().mockResolvedValue([mockAutoGenBill] as any),
        }),
      });

      const response = await agent
        .post('/api/bills')
        .send(autoGenData);

      expect(response.status).toBe(201);
      expect(response.body.id).toBeDefined();
      expect(response.body.category).toBe('other');
    });
  });

  describe('Bill Updates', () => {
    it('should update bill fields correctly', async () => {
      const billId = 'bill-to-update';
      const existingBill = {
        id: billId,
        buildingId: testBuilding.id,
        billNumber: 'BILL-TEST-003',
        title: 'Initial Title',
        description: null,
        category: 'maintenance',
        vendor: null,
        paymentType: 'unique',
        schedulePayment: null,
        scheduleCustom: null,
        costs: [100.00],
        totalAmount: 100.00,
        startDate: '2025-01-01',
        endDate: null,
        status: 'draft',
        isAutoGenerated: false,
        sourceTemplateId: null,
        autoGeneratedLabel: null,
        createdBy: testUser.id,
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      const updatedBill = {
        ...existingBill,
        title: 'Updated Title',
        description: 'New description',
        totalAmount: 150.00,
        updatedAt: new Date(),
      };

      (getBillById as jest.Mock).mockResolvedValue(existingBill);

      (mockDb.select as any).mockReturnValue({
        from: jest.fn<any>().mockReturnValue({
          where: jest.fn<any>().mockReturnValue({
            limit: jest.fn<any>().mockResolvedValue([existingBill] as any),
          }),
        }),
      });

      (mockDb.update as any).mockReturnValue({
        set: jest.fn<any>().mockReturnValue({
          where: jest.fn<any>().mockReturnValue({
            returning: jest.fn<any>().mockResolvedValue([updatedBill] as any),
          }),
        }),
      });

      const response = await agent
        .put(`/api/bills/${billId}`)
        .send({
          title: 'Updated Title',
          description: 'New description',
          totalAmount: '150.00',
        });

      expect(response.status).toBe(200);
      expect(response.body.title).toBe('Updated Title');
      expect(response.body.description).toBe('New description');
      expect(response.body.totalAmount).toBe(150.00);
    });

    it('should update bill status', async () => {
      const billId = 'bill-status-test';
      const existingBill = {
        id: billId,
        buildingId: testBuilding.id,
        billNumber: 'BILL-TEST-004',
        title: 'Status Test Bill',
        description: null,
        category: 'maintenance',
        vendor: null,
        paymentType: 'unique',
        schedulePayment: null,
        scheduleCustom: null,
        costs: [200.00],
        totalAmount: 200.00,
        startDate: '2025-01-01',
        endDate: null,
        status: 'draft',
        isAutoGenerated: false,
        sourceTemplateId: null,
        autoGeneratedLabel: null,
        createdBy: testUser.id,
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      (getBillById as jest.Mock).mockResolvedValue(existingBill);

      const statuses: Array<'draft' | 'sent' | 'paid'> = ['sent', 'paid'];
      
      for (const status of statuses) {
        const updatedBill = {
          ...existingBill,
          status,
          updatedAt: new Date(),
        };

        (mockDb.select as any).mockReturnValue({
          from: jest.fn<any>().mockReturnValue({
            where: jest.fn<any>().mockReturnValue({
              limit: jest.fn<any>().mockResolvedValue([existingBill] as any),
            }),
          }),
        });

        (mockDb.update as any).mockReturnValue({
          set: jest.fn<any>().mockReturnValue({
            where: jest.fn<any>().mockReturnValue({
              returning: jest.fn<any>().mockResolvedValue([updatedBill] as any),
            }),
          }),
        });

        const response = await agent
          .put(`/api/bills/${billId}`)
          .send({ status });

        expect(response.status).toBe(200);
        expect(response.body.status).toBe(status);
      }
    });
  });

  describe('Bill Querying and Filtering', () => {
    const testBills = [
      {
        id: 'bill-insurance',
        buildingId: testBuilding.id,
        billNumber: 'BILL-INS-001',
        title: 'Insurance Bill 2025',
        description: null,
        category: 'insurance',
        vendor: null,
        paymentType: 'unique',
        schedulePayment: null,
        scheduleCustom: null,
        costs: [2500.00],
        totalAmount: 2500.00,
        startDate: '2025-03-01',
        endDate: null,
        status: 'paid',
        isAutoGenerated: false,
        sourceTemplateId: null,
        autoGeneratedLabel: null,
        createdBy: testUser.id,
        createdAt: new Date('2025-03-01'),
        updatedAt: new Date('2025-03-01'),
      },
      {
        id: 'bill-maintenance',
        buildingId: testBuilding.id,
        billNumber: 'BILL-MNT-001',
        title: 'Maintenance Bill 2025',
        description: null,
        category: 'maintenance',
        vendor: null,
        paymentType: 'unique',
        schedulePayment: null,
        scheduleCustom: null,
        costs: [500.00],
        totalAmount: 500.00,
        startDate: '2025-06-15',
        endDate: null,
        status: 'sent',
        isAutoGenerated: false,
        sourceTemplateId: null,
        autoGeneratedLabel: null,
        createdBy: testUser.id,
        createdAt: new Date('2025-06-15'),
        updatedAt: new Date('2025-06-15'),
      },
      {
        id: 'bill-utilities',
        buildingId: testBuilding.id,
        billNumber: 'BILL-UTL-001',
        title: 'Supplies Bill 2025',
        description: null,
        category: 'other',
        vendor: null,
        paymentType: 'unique',
        schedulePayment: null,
        scheduleCustom: null,
        costs: [300.00],
        totalAmount: 300.00,
        startDate: '2025-09-01',
        endDate: null,
        status: 'draft',
        isAutoGenerated: false,
        sourceTemplateId: null,
        autoGeneratedLabel: null,
        createdBy: testUser.id,
        createdAt: new Date('2025-09-01'),
        updatedAt: new Date('2025-09-01'),
      },
    ];

    it('should filter bills by category', async () => {
      const insuranceBills = testBills.filter(bill => bill.category === 'insurance');
      (getBillsWithPayments as jest.Mock).mockResolvedValue(insuranceBills);

      const response = await agent
        .get('/api/bills')
        .query({ buildingId: testBuilding.id, category: 'insurance' });

      expect(response.status).toBe(200);
      expect(response.body.length).toBe(1);
      expect(response.body[0].category).toBe('insurance');
    });

    it('should filter bills by status', async () => {
      const paidBills = testBills.filter(bill => bill.status === 'paid');
      (getBillsWithPayments as jest.Mock).mockResolvedValue(paidBills);

      const response = await agent
        .get('/api/bills')
        .query({ buildingId: testBuilding.id, status: 'paid' });

      expect(response.status).toBe(200);
      expect(response.body.length).toBe(1);
      expect(response.body[0].status).toBe('paid');
    });

    it('should filter bills by year', async () => {
      (getBillsWithPayments as jest.Mock).mockResolvedValue(testBills);

      const response = await agent
        .get('/api/bills')
        .query({ buildingId: testBuilding.id, year: '2025' });

      expect(response.status).toBe(200);
      expect(response.body.length).toBe(3);
    });

    it('should retrieve all bills for a building', async () => {
      (getBillsWithPayments as jest.Mock).mockResolvedValue(testBills);

      const response = await agent
        .get('/api/bills')
        .query({ buildingId: testBuilding.id });

      expect(response.status).toBe(200);
      expect(response.body.length).toBe(3);
    });
  });

  describe('Auto-Generation Workflow', () => {
    it('should link generated bills to source template', async () => {
      const sourceBillId = 'source-bill-recurring';
      const generatedBills = [
        {
          id: 'auto-bill-2026',
          buildingId: testBuilding.id,
          billNumber: 'BILL-AUTO-2026',
          title: 'Auto 2026 - Recurring Source Bill',
          description: null,
          category: 'maintenance',
          vendor: null,
          paymentType: 'unique',
          schedulePayment: null,
          scheduleCustom: null,
          costs: [1200.00],
          totalAmount: 1200.00,
          startDate: '2026-01-01',
          endDate: null,
          status: 'draft',
          isAutoGenerated: true,
          sourceTemplateId: sourceBillId,
          autoGeneratedLabel: 'Auto 2026',
          createdBy: testUser.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 'auto-bill-2027',
          buildingId: testBuilding.id,
          billNumber: 'BILL-AUTO-2027',
          title: 'Auto 2027 - Recurring Source Bill',
          description: null,
          category: 'maintenance',
          vendor: null,
          paymentType: 'unique',
          schedulePayment: null,
          scheduleCustom: null,
          costs: [1200.00],
          totalAmount: 1200.00,
          startDate: '2027-01-01',
          endDate: null,
          status: 'draft',
          isAutoGenerated: true,
          sourceTemplateId: sourceBillId,
          autoGeneratedLabel: 'Auto 2027',
          createdBy: testUser.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ];

      (getBillsWithPayments as jest.Mock).mockResolvedValue(generatedBills);

      const response = await agent
        .get('/api/bills')
        .query({ buildingId: testBuilding.id, isAutoGenerated: 'true' });

      expect(response.status).toBe(200);
      expect(response.body.length).toBe(2);
      response.body.forEach((bill: any) => {
        expect(bill.sourceTemplateId).toBe(sourceBillId);
        expect(bill.isAutoGenerated).toBe(true);
      });
    });

    it('should update all generated bills when source is modified', async () => {
      const sourceBillId = 'source-update';
      const existingBill = {
        id: sourceBillId,
        buildingId: testBuilding.id,
        billNumber: 'BILL-SRC-001',
        title: 'Source for Update',
        description: null,
        category: 'maintenance',
        vendor: 'Original Vendor',
        paymentType: 'recurrent',
        schedulePayment: 'monthly',
        scheduleCustom: null,
        costs: [600.00],
        totalAmount: 600.00,
        startDate: '2025-01-01',
        endDate: null,
        status: 'draft',
        isAutoGenerated: false,
        sourceTemplateId: null,
        autoGeneratedLabel: null,
        createdBy: testUser.id,
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      const updatedBill = {
        ...existingBill,
        vendor: 'Updated Vendor',
        updatedAt: new Date(),
      };

      (getBillById as jest.Mock).mockResolvedValue(existingBill);

      (mockDb.select as any).mockReturnValue({
        from: jest.fn<any>().mockReturnValue({
          where: jest.fn<any>().mockReturnValue({
            limit: jest.fn<any>().mockResolvedValue([existingBill] as any),
          }),
        }),
      });

      (mockDb.update as any).mockReturnValue({
        set: jest.fn<any>().mockReturnValue({
          where: jest.fn<any>().mockReturnValue({
            returning: jest.fn<any>().mockResolvedValue([updatedBill] as any),
          }),
        }),
      });

      const response = await agent
        .put(`/api/bills/${sourceBillId}`)
        .send({ vendor: 'Updated Vendor' });

      expect(response.status).toBe(200);
      expect(response.body.vendor).toBe('Updated Vendor');
    });
  });

  describe('Bill Deletion', () => {
    it('should delete a bill successfully', async () => {
      const billId = 'bill-to-delete';
      const existingBill = {
        id: billId,
        buildingId: testBuilding.id,
        billNumber: 'BILL-DEL-001',
        title: 'Bill to Delete',
        description: null,
        category: 'maintenance',
        vendor: null,
        paymentType: 'unique',
        schedulePayment: null,
        scheduleCustom: null,
        costs: [100.00],
        totalAmount: 100.00,
        startDate: '2025-01-01',
        endDate: null,
        status: 'draft',
        isAutoGenerated: false,
        sourceTemplateId: null,
        autoGeneratedLabel: null,
        createdBy: testUser.id,
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      (mockDb.select as any).mockReturnValue({
        from: jest.fn<any>().mockReturnValue({
          where: jest.fn<any>().mockReturnValue({
            limit: jest.fn<any>().mockResolvedValue([existingBill] as any),
          }),
        }),
      });

      (mockDb.delete as any).mockReturnValue({
        where: jest.fn<any>().mockReturnValue({
          returning: jest.fn<any>().mockResolvedValue([existingBill]),
        }),
      });

      const response = await agent
        .delete(`/api/bills/${billId}`);

      expect(response.status).toBe(200);
    });

    it('should delete source bill and its generated bills', async () => {
      const sourceBillId = 'source-to-delete';
      const sourceBill = {
        id: sourceBillId,
        buildingId: testBuilding.id,
        billNumber: 'BILL-SRC-DEL',
        title: 'Source to Delete',
        description: null,
        category: 'maintenance',
        vendor: null,
        paymentType: 'recurrent',
        schedulePayment: 'monthly',
        scheduleCustom: null,
        costs: [400.00],
        totalAmount: 400.00,
        startDate: '2025-01-01',
        endDate: null,
        status: 'draft',
        isAutoGenerated: false,
        sourceTemplateId: null,
        autoGeneratedLabel: null,
        createdBy: testUser.id,
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      (mockDb.select as any).mockReturnValue({
        from: jest.fn<any>().mockReturnValue({
          where: jest.fn<any>().mockReturnValue({
            limit: jest.fn<any>().mockResolvedValue([sourceBill] as any),
          }),
        }),
      });

      (mockDb.delete as any).mockReturnValue({
        where: jest.fn<any>().mockReturnValue({
          returning: jest.fn<any>().mockResolvedValue([sourceBill] as any),
        }),
      });

      const response = await agent
        .delete(`/api/bills/${sourceBillId}`);

      expect(response.status).toBe(200);
    });
  });

  describe('Data Integrity', () => {
    it('should enforce foreign key constraint on buildingId', async () => {
      const invalidBillData = {
        buildingId: 'not-a-valid-uuid',
        title: 'Invalid Building Bill',
        category: 'maintenance',
        paymentType: 'unique',
        costs: ['100.00'],
        totalAmount: '100.00',
        startDate: '2025-01-01',
        status: 'draft',
      };

      const response = await agent
        .post('/api/bills')
        .send(invalidBillData);

      expect(response.status).toBe(400);
      expect(response.body).toHaveProperty('message');
      expect(response.body.message).toContain('Invalid bill data');
    });

    it('should handle concurrent bill updates correctly', async () => {
      const billId = 'concurrent-test';
      const existingBill = {
        id: billId,
        buildingId: testBuilding.id,
        billNumber: 'BILL-CONC-001',
        title: 'Concurrent Update Test',
        description: null,
        category: 'maintenance',
        vendor: null,
        paymentType: 'unique',
        schedulePayment: null,
        scheduleCustom: null,
        costs: [100.00],
        totalAmount: 100.00,
        startDate: '2025-01-01',
        endDate: null,
        status: 'draft',
        isAutoGenerated: false,
        sourceTemplateId: null,
        autoGeneratedLabel: null,
        createdBy: testUser.id,
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      const updatedBill1 = {
        ...existingBill,
        title: 'Update 1',
        updatedAt: new Date(),
      };

      const updatedBill2 = {
        ...updatedBill1,
        description: 'Update 2',
        updatedAt: new Date(),
      };

      // First update
      (getBillById as jest.Mock).mockResolvedValueOnce(existingBill);

      (mockDb.select as any).mockReturnValueOnce({
        from: jest.fn<any>().mockReturnValue({
          where: jest.fn<any>().mockReturnValue({
            limit: jest.fn<any>().mockResolvedValue([existingBill] as any),
          }),
        }),
      });

      (mockDb.update as any).mockReturnValueOnce({
        set: jest.fn<any>().mockReturnValue({
          where: jest.fn<any>().mockReturnValue({
            returning: jest.fn<any>().mockResolvedValue([updatedBill1] as any),
          }),
        }),
      });

      const response1 = await agent
        .put(`/api/bills/${billId}`)
        .send({ title: 'Update 1' });

      expect(response1.status).toBe(200);
      expect(response1.body.title).toBe('Update 1');

      // Second update
      (getBillById as jest.Mock).mockResolvedValueOnce(updatedBill1);

      (mockDb.select as any).mockReturnValueOnce({
        from: jest.fn<any>().mockReturnValue({
          where: jest.fn<any>().mockReturnValue({
            limit: jest.fn<any>().mockResolvedValue([updatedBill1] as any),
          }),
        }),
      });

      (mockDb.update as any).mockReturnValueOnce({
        set: jest.fn<any>().mockReturnValue({
          where: jest.fn<any>().mockReturnValue({
            returning: jest.fn<any>().mockResolvedValue([updatedBill2] as any),
          }),
        }),
      });

      const response2 = await agent
        .put(`/api/bills/${billId}`)
        .send({ description: 'Update 2' });

      expect(response2.status).toBe(200);
      expect(response2.body.description).toBe('Update 2');
    });
  });

  /**
   * Task #366: Coverage for the issueDateFrom / issueDateTo filter on
   * GET /api/bills, added in Task #356. The explicit contract is:
   *   - issueDateFrom adds a `gte(bills.issueDate, value)` condition
   *   - issueDateTo adds a `lte(bills.issueDate, value)` condition
   *   - Both bounds combine
   *   - Bills with NULL issue_date are excluded when either bound is set
   *     (the route deliberately does NOT add an `or(isNull(...), ...)`
   *     escape, relying on SQL NULL semantics where gte/lte vs NULL is
   *     NULL — i.e. effectively false).
   *   - The new filter composes with year / months / category.
   *
   * These tests inspect the structured where-clause object captured by
   * the mocked `getBillsWithPayments` (drizzle-orm operators are mocked
   * to return tagged objects), so a future refactor that drops the
   * filter, swaps the operator, or wraps it in an isNull-OR will fail.
   */
  describe('Issue-date range filter (Task #366)', () => {
    /** Recursively collect every operator-tagged condition node in the where-clause tree. */
    const collectConditions = (node: any): any[] => {
      if (!node || typeof node !== 'object') return [];
      const out: any[] = [node];
      if (Array.isArray(node.conditions)) {
        for (const c of node.conditions) out.push(...collectConditions(c));
      }
      return out;
    };

    const findIssueDateConditions = (where: any) =>
      collectConditions(where).filter(
        (c: any) => c?.column === 'bills.issueDate' && (c.operator === 'gte' || c.operator === 'lte'),
      );

    const captureWhere = async (query: Record<string, string>) => {
      (getBillsWithPayments as jest.Mock).mockResolvedValue([]);
      const response = await agent.get('/api/bills').query(query);
      expect(response.status).toBe(200);
      expect(getBillsWithPayments as jest.Mock).toHaveBeenCalledTimes(1);
      return (getBillsWithPayments as jest.Mock).mock.calls[0][0];
    };

    it('applies a gte(bills.issueDate, value) condition when only issueDateFrom is set', async () => {
      const where = await captureWhere({ issueDateFrom: '2025-03-01' });

      const conds = findIssueDateConditions(where);
      expect(conds).toHaveLength(1);
      expect(conds[0]).toMatchObject({
        column: 'bills.issueDate',
        operator: 'gte',
        value: '2025-03-01',
      });
      // Must NOT silently allow NULL issue_date through (no isNull escape).
      expect(
        collectConditions(where).some(
          (c: any) => c?.operator === 'isNull' && c?.column === 'bills.issueDate',
        ),
      ).toBe(false);
    });

    it('applies a lte(bills.issueDate, value) condition when only issueDateTo is set', async () => {
      const where = await captureWhere({ issueDateTo: '2025-09-30' });

      const conds = findIssueDateConditions(where);
      expect(conds).toHaveLength(1);
      expect(conds[0]).toMatchObject({
        column: 'bills.issueDate',
        operator: 'lte',
        value: '2025-09-30',
      });
      expect(
        collectConditions(where).some(
          (c: any) => c?.operator === 'isNull' && c?.column === 'bills.issueDate',
        ),
      ).toBe(false);
    });

    it('applies both gte and lte when issueDateFrom and issueDateTo are set together', async () => {
      const where = await captureWhere({
        issueDateFrom: '2025-03-01',
        issueDateTo: '2025-09-30',
      });

      const conds = findIssueDateConditions(where);
      expect(conds).toHaveLength(2);
      expect(conds).toEqual(
        expect.arrayContaining([
          expect.objectContaining({ column: 'bills.issueDate', operator: 'gte', value: '2025-03-01' }),
          expect.objectContaining({ column: 'bills.issueDate', operator: 'lte', value: '2025-09-30' }),
        ]),
      );
      // Still no isNull escape — NULL issue_date stays excluded.
      expect(
        collectConditions(where).some(
          (c: any) => c?.operator === 'isNull' && c?.column === 'bills.issueDate',
        ),
      ).toBe(false);
    });

    it('ignores malformed issueDateFrom / issueDateTo values', async () => {
      const where = await captureWhere({
        issueDateFrom: 'not-a-date',
        issueDateTo: '2025/09/30',
      });
      expect(findIssueDateConditions(where)).toHaveLength(0);
    });

    it('does not add any issue-date condition when neither bound is provided', async () => {
      const where = await captureWhere({ buildingId: testBuilding.id });
      expect(findIssueDateConditions(where)).toHaveLength(0);
      expect(
        collectConditions(where).some(
          (c: any) => c?.operator === 'isNull' && c?.column === 'bills.issueDate',
        ),
      ).toBe(false);
    });

    it('composes with the building and category filters', async () => {
      const where = await captureWhere({
        buildingId: testBuilding.id,
        category: 'insurance',
        issueDateFrom: '2025-03-01',
        issueDateTo: '2025-09-30',
      });

      const all = collectConditions(where);

      // Issue-date bounds are still present.
      expect(findIssueDateConditions(where)).toHaveLength(2);

      // Building filter present.
      expect(
        all.some(
          (c: any) =>
            c?.operator === 'eq' && c?.column === 'bills.buildingId' && c?.value === testBuilding.id,
        ),
      ).toBe(true);

      // Category filter present.
      expect(
        all.some(
          (c: any) => c?.operator === 'eq' && c?.column === 'bills.category' && c?.value === 'insurance',
        ),
      ).toBe(true);
    });

    it('composes with the months filter (payment-existence subquery still present)', async () => {
      const where = await captureWhere({
        buildingId: testBuilding.id,
        months: '3,9',
        issueDateFrom: '2025-03-01',
        issueDateTo: '2025-09-30',
      });

      // Issue-date bounds still present.
      expect(findIssueDateConditions(where)).toHaveLength(2);

      // Months filter contributes a payment `exists(...)` subquery.
      expect(collectConditions(where).some((c: any) => c?.operator === 'exists')).toBe(true);
    });

    it('composes simultaneously with category, year, months and issue-date bounds', async () => {
      const where = await captureWhere({
        buildingId: testBuilding.id,
        category: 'insurance',
        year: '2025',
        months: '3,9',
        issueDateFrom: '2025-03-01',
        issueDateTo: '2025-09-30',
      });

      const all = collectConditions(where);

      // Both issue-date bounds present.
      expect(findIssueDateConditions(where)).toHaveLength(2);

      // Building + category eq filters present.
      expect(
        all.some(
          (c: any) =>
            c?.operator === 'eq' && c?.column === 'bills.buildingId' && c?.value === testBuilding.id,
        ),
      ).toBe(true);
      expect(
        all.some(
          (c: any) => c?.operator === 'eq' && c?.column === 'bills.category' && c?.value === 'insurance',
        ),
      ).toBe(true);

      // Year and months both push payment `exists(...)` subqueries — at
      // least two distinct exists nodes should be in the where tree.
      const existsCount = all.filter((c: any) => c?.operator === 'exists').length;
      expect(existsCount).toBeGreaterThanOrEqual(2);

      // NULL-exclusion contract still holds even with everything stacked.
      expect(
        all.some((c: any) => c?.operator === 'isNull' && c?.column === 'bills.issueDate'),
      ).toBe(false);
    });

    it('composes with the year filter (payment-existence subquery still present)', async () => {
      const where = await captureWhere({
        buildingId: testBuilding.id,
        year: '2025',
        issueDateFrom: '2025-03-01',
      });

      // Issue-date lower bound still present.
      const issueConds = findIssueDateConditions(where);
      expect(issueConds).toHaveLength(1);
      expect(issueConds[0]).toMatchObject({ operator: 'gte', value: '2025-03-01' });

      // Year filter contributes at least one `exists(...)` payment subquery.
      expect(collectConditions(where).some((c: any) => c?.operator === 'exists')).toBe(true);
    });
  });
});
