/**
 * @file Bills Cross-Org Write Denial — Task #1271 regression coverage.
 * @description Wires the real `server/api/bills.ts` router into an Express
 * app with mocked db + rbac, and walks each write path that calls
 * `assertBuildingWriteAccess` / `assertBillWriteAccess`. The contract under
 * test is the same one the code review demanded: a manager pinned to org
 * "alpha" must NOT be able to create, update, delete, re-attach, re-trigger
 * AI on, or generate forward bills against a building that lives in org
 * "beta", regardless of whether the bill id is real.
 *
 * The goal is symmetry with the read-side `tests/integration/bills-buildings-access.test.ts`
 * file but focused on the write paths that previously trusted the request
 * body / params for buildingId.
 */

import request from 'supertest';
import express from 'express';
import session from 'express-session';
import { describe, it, expect, beforeEach, jest } from '@jest/globals';

const ORG_ALPHA = '00000000-0000-0000-0000-00000000aaaa';
const ORG_BETA = '00000000-0000-0000-0000-00000000bbbb';

const ALPHA_BUILDING = '00000000-0000-0000-0000-0000000000a1';
const BETA_BUILDING = '00000000-0000-0000-0000-0000000000b1';

const ALPHA_BILL = '00000000-0000-0000-0000-0000000000a2';
const BETA_BILL = '00000000-0000-0000-0000-0000000000b2';

const MANAGER_USER_ID = '00000000-0000-0000-0000-0000000000aa';

// Bill row caches keyed by id so the bills router and our org-scope helper
// observe the same fixtures.
const billRowsById = new Map<string, any>();
const buildingRowsById = new Map<string, any>();

const mockDb = {
  query: {
    bills: {
      findMany: jest.fn<() => Promise<any[]>>().mockResolvedValue([] as any),
      findFirst: jest.fn<() => Promise<any | null>>().mockResolvedValue(null),
    },
  },
  select: jest.fn<any>(),
  insert: jest.fn<any>(),
  update: jest.fn<any>(),
  delete: jest.fn<any>(),
};

jest.mock('../../server/db', () => ({
  db: mockDb,
}));

jest.mock('../../server/mcp/server', () => ({
  buildWriteErrorResponse: jest.fn((_err: unknown) => ({
    status: 500,
    body: { error: 'mocked' },
    retryAfterSeconds: undefined,
  })),
  createMcpServer: jest.fn(),
}));

let __uuidCounter = 0;
jest.mock('uuid', () => ({
  v4: jest.fn(
    () => `00000000-0000-0000-0000-${String(++__uuidCounter).padStart(12, '0')}`,
  ),
}));

// drizzle-orm operator mocks are tagged so our select chain mock can sniff
// which table+column combination is being filtered without parsing real SQL.
jest.mock('drizzle-orm', () => ({
  eq: jest.fn((column: any, value: any) => ({ kind: 'eq', column, value })),
  and: jest.fn((...conditions: any[]) => ({ kind: 'and', conditions })),
  or: jest.fn((...conditions: any[]) => ({ kind: 'or', conditions })),
  gte: jest.fn((column: any, value: any) => ({ kind: 'gte', column, value })),
  lte: jest.fn((column: any, value: any) => ({ kind: 'lte', column, value })),
  lt: jest.fn((column: any, value: any) => ({ kind: 'lt', column, value })),
  ne: jest.fn((column: any, value: any) => ({ kind: 'ne', column, value })),
  inArray: jest.fn((column: any, values: any[]) => ({ kind: 'inArray', column, values })),
  isNull: jest.fn((column: any) => ({ kind: 'isNull', column })),
  isNotNull: jest.fn((column: any) => ({ kind: 'isNotNull', column })),
  ilike: jest.fn((column: any, value: any) => ({ kind: 'ilike', column, value })),
  exists: jest.fn((query: any) => ({ kind: 'exists', query })),
  sql: Object.assign(
    jest.fn((strings: any, ...values: any[]) => {
      if (typeof strings === 'string') {
        return { sql: strings };
      }
      return { sql: (strings as any).join('?'), values };
    }),
    {
      join: (parts: any[]) => ({ sql: 'join', parts }),
    },
  ),
  desc: jest.fn((column: any) => ({ column, direction: 'desc' })),
  asc: jest.fn((column: any) => ({ column, direction: 'asc' })),
}));

jest.mock('@shared/schema', () => {
  const billsTable = {
    id: 'bills.id',
    buildingId: 'bills.buildingId',
    billNumber: 'bills.billNumber',
    title: 'bills.title',
    category: 'bills.category',
    status: 'bills.status',
    isAutoGenerated: 'bills.isAutoGenerated',
    sourceTemplateId: 'bills.sourceTemplateId',
    parentBillId: 'bills.parentBillId',
  };
  const buildingsTable = {
    id: 'buildings.id',
    name: 'buildings.name',
    organizationId: 'buildings.organizationId',
    isActive: 'buildings.isActive',
    financialYearStart: 'buildings.financialYearStart',
  };
  const paymentsTable = {
    id: 'payments.id',
    billId: 'payments.billId',
    status: 'payments.status',
  };
  const makeMockSchema: any = () => {
    const s: any = {
      parse: jest.fn((data: any) => data),
      extend: jest.fn(() => makeMockSchema()),
      partial: jest.fn(() => makeMockSchema()),
      omit: jest.fn(() => makeMockSchema()),
    };
    return s;
  };
  return {
    bills: billsTable,
    buildings: buildingsTable,
    users: { id: 'users.id' },
    documents: { id: 'documents.id' },
    payments: paymentsTable,
    insertBillSchema: makeMockSchema(),
  };
});

jest.mock('../../server/services/consolidated-financial-service', () => ({
  financialService: {
    generatePaymentsForBill: jest.fn<any>().mockResolvedValue(undefined as any),
    updatePaymentsForBill: jest.fn<any>().mockResolvedValue(undefined as any),
    regenerateCompletePaymentSchedule: jest
      .fn<any>()
      .mockResolvedValue({ deletedCount: 0, createdCount: 0 } as any),
    scheduleBillUpdate: jest.fn<any>().mockResolvedValue(undefined as any),
    createAutoGeneratedBill: jest.fn<any>().mockResolvedValue([] as any),
  },
}));

jest.mock('../../server/services/consolidated-ai-service', () => ({
  aiService: {
    extractBillData: jest.fn<any>().mockResolvedValue({} as any),
  },
}));

jest.mock('../../server/services/secure-file-storage', () => ({
  secureFileStorage: {
    saveFile: jest.fn<any>().mockResolvedValue({ path: '/test/path', filename: 'x.pdf' } as any),
  },
}));

jest.mock('../../server/auth', () => {
  const middleware = (_req: any, _res: any, next: any) => next();
  return {
    requireAuth: middleware,
    requireRole: jest.fn(() => middleware),
  };
});

jest.mock('../../server/storage', () => ({
  storage: {
    getBill: jest.fn<any>().mockResolvedValue(null),
    createBill: jest.fn<any>().mockResolvedValue({}),
    updateBill: jest.fn<any>().mockResolvedValue({}),
    deleteBill: jest.fn<any>().mockResolvedValue(true),
  },
}));

jest.mock('../../server/services/payment-generation-service', () => ({
  paymentGenerationService: {
    generatePayments: jest.fn<any>().mockResolvedValue([] as any),
    deletePaymentsForBill: jest.fn<any>().mockResolvedValue(0 as any),
    updatePaymentStatusFromBillStatus: jest.fn<any>().mockResolvedValue(undefined as any),
    updateBillStatusBasedOnPayments: jest.fn<any>().mockResolvedValue(undefined as any),
  },
}));

jest.mock('../../server/services/bill-generation-service', () => ({
  billAutoGenerationService: {
    checkAndGenerateBills: jest.fn<any>().mockResolvedValue([] as any),
    syncAutoGeneratedBills: jest.fn<any>().mockResolvedValue(undefined as any),
    bulkGenerateForAllBuildings: jest
      .fn<any>()
      .mockResolvedValue({ processedBuildings: 0, generatedBills: 0, errors: [] } as any),
  },
}));

jest.mock('../../server/jobs/money_flow_job', () => ({
  moneyFlowJob: { trigger: jest.fn() },
}));

jest.mock('../../server/middleware/fileUpload', () => ({
  uploadInvoiceFile: (_req: any, _res: any, next: any) => next(),
  handleUploadError: jest.fn(),
}));

jest.mock('../../server/services/document-service', () => ({
  documentService: {
    getDocument: jest.fn<any>().mockResolvedValue(null),
    createDocument: jest.fn<any>().mockResolvedValue({}),
  },
}));

jest.mock('../../server/utils/logger', () => ({
  logDebug: jest.fn(),
  logInfo: jest.fn(),
  logWarn: jest.fn(),
  logError: jest.fn(),
}));

jest.mock('../../server/utils/filenameNormalization', () => ({
  normalizeFilename: jest.fn((name: string) => name),
}));

jest.mock('../../server/db/queries/bills-queries', () => ({
  getBillById: jest.fn<any>().mockImplementation(async (id: string) => billRowsById.get(id) ?? null),
  getBillWithPayments: jest.fn<any>().mockResolvedValue(null),
  getBillsWithPayments: jest.fn<any>().mockResolvedValue([] as any),
  getEffectiveBillType: jest.fn<any>().mockReturnValue('unique'),
}));

jest.mock('@shared/schemas/financial', () => ({
  BILL_CATEGORIES: [
    'maintenance',
    'utilities',
    'insurance',
    'taxes',
    'management',
    'professional_services',
    'capital_improvements',
    'common_areas',
    'administrative',
    'other',
  ],
}));

// Hard-pin the manager user's accessible organizations to ORG_ALPHA so the
// helper denies any building/bill that belongs to ORG_BETA.
jest.mock('../../server/rbac', () => ({
  getUserAccessibleOrganizations: jest.fn<any>(async (_userId: string) => [ORG_ALPHA]),
  getAccessibleBuildingIds: jest.fn<any>(async () => [ALPHA_BUILDING]),
}));

import { registerBillRoutes } from '../../server/api/bills';

/**
 * Builds a chainable select mock that resolves based on which schema
 * column was passed to `.where(eq(...))`. The helper inspects the
 * recorded condition tree and returns the matching seeded row(s) so
 * `assertBuildingWriteAccess` and `assertBillWriteAccess` can read
 * realistic fixtures without us hand-rolling the Drizzle protocol.
 */
function buildSelectMock() {
  const state: { conditions: any[] } = { conditions: [] };
  const chain: any = {};

  const collectWhere = (cond: any) => {
    if (!cond) return;
    if (cond.kind === 'and' && Array.isArray(cond.conditions)) {
      cond.conditions.forEach(collectWhere);
      return;
    }
    state.conditions.push(cond);
  };

  const resolveRows = () => {
    // bills.id = ?
    const billCond = state.conditions.find(
      (c) => c?.kind === 'eq' && c?.column === 'bills.id',
    );
    if (billCond) {
      const row = billRowsById.get(billCond.value);
      return row ? [row] : [];
    }
    // buildings.id IN (...) — used by bulk-generate to validate that
    // every requested buildingId actually belongs to the requested org.
    // We honor any sibling eq filters on organizationId / isActive.
    const buildingsInCond = state.conditions.find(
      (c) => c?.kind === 'inArray' && c?.column === 'buildings.id',
    );
    if (buildingsInCond) {
      const orgCond = state.conditions.find(
        (c) => c?.kind === 'eq' && c?.column === 'buildings.organizationId',
      );
      const isActiveCond = state.conditions.find(
        (c) => c?.kind === 'eq' && c?.column === 'buildings.isActive',
      );
      const matched: any[] = [];
      for (const id of buildingsInCond.values) {
        const row = buildingRowsById.get(id);
        if (!row) continue;
        if (orgCond && row.organizationId !== orgCond.value) continue;
        if (isActiveCond && row.isActive !== isActiveCond.value) continue;
        matched.push(row);
      }
      return matched;
    }
    // buildings.id = ? (and isActive may also be present)
    const buildingCond = state.conditions.find(
      (c) => c?.kind === 'eq' && c?.column === 'buildings.id',
    );
    if (buildingCond) {
      const row = buildingRowsById.get(buildingCond.value);
      if (!row) return [];
      const isActiveCond = state.conditions.find(
        (c) => c?.kind === 'eq' && c?.column === 'buildings.isActive',
      );
      if (isActiveCond && row.isActive !== isActiveCond.value) {
        return [];
      }
      return [row];
    }
    return [];
  };

  ['from', 'leftJoin', 'innerJoin', 'rightJoin', 'fullJoin', 'orderBy', 'groupBy', 'having', 'limit', 'offset'].forEach((m) => {
    chain[m] = jest.fn(() => chain);
  });
  chain.where = jest.fn((cond: any) => {
    collectWhere(cond);
    return chain;
  });
  chain.then = (resolve: any) => resolve(resolveRows());
  return chain;
}

describe('Task #1271 — Bills cross-org write denial', () => {
  let app: express.Application;
  let agent: ReturnType<typeof request.agent>;

  beforeEach(() => {
    jest.clearAllMocks();
    billRowsById.clear();
    buildingRowsById.clear();

    buildingRowsById.set(ALPHA_BUILDING, {
      id: ALPHA_BUILDING,
      organizationId: ORG_ALPHA,
      isActive: true,
    });
    buildingRowsById.set(BETA_BUILDING, {
      id: BETA_BUILDING,
      organizationId: ORG_BETA,
      isActive: true,
    });
    billRowsById.set(ALPHA_BILL, {
      id: ALPHA_BILL,
      buildingId: ALPHA_BUILDING,
      title: 'Alpha Bill',
      category: 'utilities',
      status: 'draft',
      paymentType: 'unique',
      totalAmount: '100.00',
      isAutoGenerated: false,
      sourceTemplateId: null,
    });
    billRowsById.set(BETA_BILL, {
      id: BETA_BILL,
      buildingId: BETA_BUILDING,
      title: 'Beta Bill',
      category: 'utilities',
      status: 'draft',
      paymentType: 'unique',
      totalAmount: '200.00',
      isAutoGenerated: false,
      sourceTemplateId: null,
    });

    (mockDb.select as any).mockImplementation(() => buildSelectMock());
    (mockDb.update as any).mockReturnValue({
      set: jest.fn(() => ({ where: jest.fn(async () => undefined) })),
    });
    (mockDb.insert as any).mockReturnValue({
      values: jest.fn(() => ({ returning: jest.fn(async () => []) })),
    });
    (mockDb.delete as any).mockReturnValue({
      where: jest.fn(async () => undefined),
    });

    app = express();
    app.use(express.json());
    app.use(
      session({
        secret: 'test-secret',
        resave: false,
        saveUninitialized: false,
        cookie: { secure: false },
      }),
    );
    app.use((req: any, _res: any, next: any) => {
      req.user = {
        id: MANAGER_USER_ID,
        username: 'alpha-manager',
        email: 'alpha-manager@example.com',
        firstName: 'Alpha',
        lastName: 'Manager',
        role: 'manager',
        isActive: true,
        organizations: [ORG_ALPHA],
      };
      next();
    });

    registerBillRoutes(app as any);
    agent = request.agent(app);
  });

  // POST /api/bills — manager attempting to create a bill against a
  // building they don't own should get 403 INSUFFICIENT_PERMISSIONS,
  // not a 201.
  it('rejects POST /api/bills when buildingId belongs to a different organization', async () => {
    const response = await agent.post('/api/bills').send({
      buildingId: BETA_BUILDING,
      title: 'Cross-org bill',
      category: 'utilities',
      paymentType: 'unique',
      costs: ['100.00'],
      totalAmount: '100.00',
      startDate: '2026-01-01',
      status: 'draft',
    });

    expect(response.status).toBe(404);
    expect(response.body.code).toBe('NOT_FOUND');
  });

  // PATCH /api/bills/:id — manager hitting a bill that lives in another
  // org should get a 403, not a 404 (the bill exists, but the building
  // is gated). Asserting the deny status keeps us from accidentally
  // regressing to the read-side 404 oracle behavior.
  it('rejects PATCH /api/bills/:id for a bill in a different organization', async () => {
    const response = await agent.patch(`/api/bills/${BETA_BILL}`).send({
      title: 'Hijack',
    });
    expect(response.status).toBe(404);
    expect(response.body.code).toBe('NOT_FOUND');
  });

  // PUT /api/bills/:id — same contract as PATCH, but exercises the
  // full-replace handler whose body-validation path runs before the
  // org-scope assertion in the previous broken version.
  it('rejects PUT /api/bills/:id for a bill in a different organization', async () => {
    const response = await agent.put(`/api/bills/${BETA_BILL}`).send({
      title: 'Hijack',
      category: 'utilities',
      paymentType: 'unique',
      costs: ['200.00'],
      totalAmount: '200.00',
      startDate: '2026-01-01',
      status: 'draft',
    });
    expect(response.status).toBe(404);
    expect(response.body.code).toBe('NOT_FOUND');
  });

  // DELETE /api/bills/:id — same contract.
  it('rejects DELETE /api/bills/:id for a bill in a different organization', async () => {
    const response = await agent.delete(`/api/bills/${BETA_BILL}`);
    expect(response.status).toBe(404);
    expect(response.body.code).toBe('NOT_FOUND');
  });

  // POST /api/bills/:id/generate-future — recurrence-driven write that
  // previously trusted the bill row's buildingId without re-checking
  // org membership.
  it('rejects POST /api/bills/:id/generate-future for a bill in a different organization', async () => {
    const response = await agent.post(`/api/bills/${BETA_BILL}/generate-future`).send({});
    expect(response.status).toBe(404);
    expect(response.body.code).toBe('NOT_FOUND');
  });

  // POST /api/bills/:id/apply-ai-analysis — same.
  it('rejects POST /api/bills/:id/apply-ai-analysis for a bill in a different organization', async () => {
    const response = await agent
      .post(`/api/bills/${BETA_BILL}/apply-ai-analysis`)
      .send({ analysisData: {} });
    expect(response.status).toBe(404);
    expect(response.body.code).toBe('NOT_FOUND');
  });

  // POST /api/bills/:id/generate-next-year — same.
  it('rejects POST /api/bills/:id/generate-next-year for a bill in a different organization', async () => {
    const response = await agent.post(`/api/bills/${BETA_BILL}/generate-next-year`).send({});
    expect(response.status).toBe(404);
    expect(response.body.code).toBe('NOT_FOUND');
  });

  // DELETE /api/bills/:id/attachment — exercises the file-detach path
  // through the bill-loaded variant of the helper.
  it('rejects DELETE /api/bills/:id/attachment for a bill in a different organization', async () => {
    const response = await agent.delete(`/api/bills/${BETA_BILL}/attachment`);
    expect(response.status).toBe(404);
    expect(response.body.code).toBe('NOT_FOUND');
  });

  // POST /api/bills/from-template — exercises the building-only variant
  // of the helper, since the route never loads a bill before deciding.
  it('rejects POST /api/bills/from-template when buildingId belongs to a different organization', async () => {
    const response = await agent.post('/api/bills/from-template').send({
      buildingId: BETA_BUILDING,
      title: 'Cross-org from template',
      category: 'utilities',
      paymentType: 'unique',
      costs: ['100.00'],
      totalAmount: '100.00',
      startDate: '2026-01-01',
      status: 'draft',
    });
    expect(response.status).toBe(404);
    expect(response.body.code).toBe('NOT_FOUND');
  });

  // POST /api/bills/auto-generate — body says sourceTemplateId, but
  // the building is resolved from the template row and gated through
  // the helper.
  it('rejects POST /api/bills/auto-generate when source template lives in a different organization', async () => {
    const response = await agent.post('/api/bills/auto-generate').send({
      sourceTemplateId: BETA_BILL,
    });
    expect(response.status).toBe(404);
    expect(response.body.code).toBe('NOT_FOUND');
  });

  // POST /api/bills/bulk-generate — guards the organizationId field,
  // which previously was trusted from the body.
  it('rejects POST /api/bills/bulk-generate when organizationId is unreachable', async () => {
    const response = await agent.post('/api/bills/bulk-generate').send({
      organizationId: ORG_BETA,
    });
    expect(response.status).toBe(404);
    expect(response.body.code).toBe('NOT_FOUND');
  });

  // POST /api/bills/bulk-generate — without an explicit organizationId
  // the previous code expanded the service to "all buildings". The
  // gate now requires the field outright so that path is impossible.
  it('rejects POST /api/bills/bulk-generate when organizationId is omitted', async () => {
    const response = await agent.post('/api/bills/bulk-generate').send({});
    expect(response.status).toBe(400);
    expect(response.body.code).toBe('MISSING_ORGANIZATION_ID');
  });

  // POST /api/bills/bulk-generate — even when the org is one the
  // caller can access, every supplied buildingId must live in that
  // org. Mixing in a foreign id (BETA) must reject the whole request
  // — partial acceptance would leak whether the foreign id exists.
  it('rejects POST /api/bills/bulk-generate when buildingIds include a foreign building', async () => {
    const response = await agent.post('/api/bills/bulk-generate').send({
      organizationId: ORG_ALPHA,
      buildingIds: [ALPHA_BUILDING, BETA_BUILDING],
    });
    expect(response.status).toBe(404);
    expect(response.body.code).toBe('NOT_FOUND');
  });

  // POST /api/bills/bulk-generate — happy path: alpha manager,
  // alpha org, alpha building succeeds.
  it('allows POST /api/bills/bulk-generate when org and buildings are within scope', async () => {
    const response = await agent.post('/api/bills/bulk-generate').send({
      organizationId: ORG_ALPHA,
      buildingIds: [ALPHA_BUILDING],
    });
    expect(response.status).toBe(200);
  });

  // Sanity: same manager can still create against ALPHA. This proves
  // the new gate isn't a blanket-deny — it really is org-scoped.
  it('still allows POST /api/bills when buildingId belongs to the caller organization', async () => {
    const createdRow = {
      id: '00000000-0000-0000-0000-0000000000a3',
      buildingId: ALPHA_BUILDING,
      title: 'Alpha Bill 2',
      category: 'utilities',
      paymentType: 'unique',
      costs: ['100.00'],
      totalAmount: '100.00',
      startDate: '2026-01-01',
      status: 'draft',
      createdBy: MANAGER_USER_ID,
    };
    (mockDb.insert as any).mockReturnValue({
      values: jest.fn(() => ({ returning: jest.fn(async () => [createdRow]) })),
    });

    const response = await agent.post('/api/bills').send({
      buildingId: ALPHA_BUILDING,
      title: 'Alpha Bill 2',
      category: 'utilities',
      paymentType: 'unique',
      costs: ['100.00'],
      totalAmount: '100.00',
      startDate: '2026-01-01',
      status: 'draft',
    });
    expect([200, 201]).toContain(response.status);
  });
});
