/**
 * @jest-environment node
 *
 * Task #279: Cover the MCP `delete_project` cascade with a real
 * end-to-end integration test against Postgres.
 *
 * The mocked unit tests in `server/tests/mcp-tools.test.ts` historically
 * covered only the building cascade and stub `db.delete` chains, so they
 * cannot catch a regression where the project cascade misses a child
 * table or violates an FK. The real cascade relies on application-code
 * deletes inside a single transaction (so the MCP response can return
 * exact per-table counts) plus Postgres-level `ON DELETE CASCADE` /
 * `ON DELETE SET NULL` constraints declared in
 * `shared/schemas/maintenance.ts`. A schema change that drops a cascade
 * — or a future change to the handler that forgets a child table —
 * would silently pass mocked tests but blow up here.
 *
 * This test seeds a real maintenance project inside an MCP-scoped
 * organization, with at least one row in every dependent table the
 * cascade touches:
 *   - project_steps          (ON DELETE CASCADE)
 *   - project_elements       (ON DELETE CASCADE)
 *   - submission_vendors     (ON DELETE CASCADE)
 *   - workflow_tasks         (ON DELETE CASCADE)
 *   - project_notifications  (ON DELETE CASCADE)
 *   - element_project_updates(ON DELETE CASCADE)
 *   - evaluation_suggestions (ON DELETE SET NULL — projectId nulled out)
 *
 * It then invokes the production `delete_project` MCP tool handler
 * against the real database. Asserts:
 *   1. The MCP tool response reports the deleted project (matching the
 *      seeded id / projectNumber / title) and accurate per-table cascade
 *      counts.
 *   2. The project row is gone after the cascade.
 *   3. Every dependent row in every cascading child table is gone.
 *   4. The evaluation suggestion that pointed at the project still
 *      exists, but its projectId is now null.
 *   5. A sibling project in the same building (with its own
 *      project_steps / workflow_tasks) is untouched — regression guard
 *      against an over-broad delete.
 *
 * Follows the existing real-Postgres integration pattern
 * (`tests/integration/mcp-delete-bill-cascade.test.ts`): gated on
 * `_INTEGRATION_DB_URL` (auto-populated from `DATABASE_URL` by
 * `jest.polyfills.js`) and skips cleanly when no Postgres is
 * available.
 */

import { describe, it, expect, beforeAll, afterAll } from '@jest/globals';
import crypto from 'crypto';
import { eq, inArray } from 'drizzle-orm';
import type { NeonDatabase } from 'drizzle-orm/neon-serverless';
import * as schemaImport from '@shared/schema';

type Schema = typeof schemaImport;
type Db = NeonDatabase<Schema>;

const REAL_DB_URL = process.env._INTEGRATION_DB_URL;
const TEST_TAG = 'task279-mcp-project-cascade';
const describeIfDb = REAL_DB_URL ? describe : describe.skip;

interface ToolResult {
  content?: Array<{ text?: string }>;
}

function getToolHandler(server: unknown, toolName: string): (args: unknown, extra: unknown) => Promise<ToolResult> {
  const tools = (server as { _registeredTools?: Record<string, { handler?: unknown; callback?: unknown }> })._registeredTools;
  if (!tools || !tools[toolName]) throw new Error(`Tool "${toolName}" not registered`);
  const fn = (tools[toolName].handler ?? tools[toolName].callback) as
    | ((args: unknown, extra: unknown) => Promise<ToolResult>)
    | undefined;
  if (typeof fn !== 'function') throw new Error(`Tool "${toolName}" handler missing`);
  return fn;
}

function parseToolJson(result: ToolResult): Record<string, unknown> {
  const text = result?.content?.[0]?.text ?? '';
  return JSON.parse(text);
}

describeIfDb('MCP delete_project cascade — real Postgres (Task #279)', () => {
  let db: Db;
  let schema: Schema;
  let createMcpServer: typeof import('../../server/mcp/server').createMcpServer;

  // Track every row we insert so afterAll can clean up regardless of
  // which assertion (or which prior dev seed) was already in the DB.
  const created = {
    organizationId: null as string | null,
    organizationCreatedByUs: false,
    buildingId: null as string | null,
    userId: null as string | null,
    uniformatCode: null as string | null,
    uniformatCodeCreatedByUs: false,
    elementIds: new Set<string>(),
    suggestionIds: new Set<string>(),
    autoGeneratedProjectIds: new Set<string>(),
    projectIds: new Set<string>(), // primary + sibling project
    projectStepIds: new Set<string>(),
    projectElementIds: new Set<string>(),
    submissionVendorIds: new Set<string>(),
    workflowTaskIds: new Set<string>(),
    projectNotificationIds: new Set<string>(),
    elementProjectUpdateIds: new Set<string>(),
  };

  beforeAll(async () => {
    if (!REAL_DB_URL) return;
    process.env.DATABASE_URL = REAL_DB_URL;
    process.env.USE_MOCK_DB = 'false';
    db = require('../../server/db').db as Db;
    schema = require('@shared/schema') as Schema;
    ({ createMcpServer } = require('../../server/mcp/server'));
  }, 60000);

  afterAll(async () => {
    if (!REAL_DB_URL || !db) return;

    // Delete in FK-safe order: leaf tables first, then projects, then
    // building elements / suggestions / building / org / user.
    if (created.elementProjectUpdateIds.size) {
      await db
        .delete(schema.elementProjectUpdates)
        .where(inArray(schema.elementProjectUpdates.id, [...created.elementProjectUpdateIds]));
    }
    if (created.projectNotificationIds.size) {
      await db
        .delete(schema.projectNotifications)
        .where(inArray(schema.projectNotifications.id, [...created.projectNotificationIds]));
    }
    if (created.workflowTaskIds.size) {
      await db
        .delete(schema.workflowTasks)
        .where(inArray(schema.workflowTasks.id, [...created.workflowTaskIds]));
    }
    if (created.submissionVendorIds.size) {
      await db
        .delete(schema.submissionVendors)
        .where(inArray(schema.submissionVendors.id, [...created.submissionVendorIds]));
    }
    if (created.projectElementIds.size) {
      await db
        .delete(schema.projectElements)
        .where(inArray(schema.projectElements.id, [...created.projectElementIds]));
    }
    if (created.projectStepIds.size) {
      await db
        .delete(schema.projectSteps)
        .where(inArray(schema.projectSteps.id, [...created.projectStepIds]));
    }
    if (created.projectIds.size) {
      await db
        .delete(schema.maintenanceProjects)
        .where(inArray(schema.maintenanceProjects.id, [...created.projectIds]));
    }
    if (created.autoGeneratedProjectIds.size) {
      await db
        .delete(schema.autoGeneratedProjects)
        .where(inArray(schema.autoGeneratedProjects.id, [...created.autoGeneratedProjectIds]));
    }
    if (created.suggestionIds.size) {
      await db
        .delete(schema.evaluationSuggestions)
        .where(inArray(schema.evaluationSuggestions.id, [...created.suggestionIds]));
    }
    if (created.elementIds.size) {
      await db
        .delete(schema.buildingElements)
        .where(inArray(schema.buildingElements.id, [...created.elementIds]));
    }
    if (created.uniformatCode && created.uniformatCodeCreatedByUs) {
      await db
        .delete(schema.uniformatCodes)
        .where(eq(schema.uniformatCodes.code, created.uniformatCode));
    }
    if (created.buildingId) {
      await db.delete(schema.buildings).where(eq(schema.buildings.id, created.buildingId));
    }
    if (created.organizationId && created.organizationCreatedByUs) {
      await db
        .delete(schema.organizations)
        .where(eq(schema.organizations.id, created.organizationId));
    }
    if (created.userId) {
      await db.delete(schema.users).where(eq(schema.users.id, created.userId));
    }
  }, 60000);

  it('deletes the project and every dependent row, leaving sibling rows intact', async () => {
    // 1. Resolve (or seed) an MCP-scoped organization. The MCP scope
    //    check (`getMcpOrgIds`) only allows projects whose building
    //    lives in an org named "MCP-1" or "MCP-2", so reuse the
    //    existing sandbox org if it's already in the DB and only insert
    //    one when it isn't.
    const existingMcp = await db
      .select({ id: schema.organizations.id })
      .from(schema.organizations)
      .where(eq(schema.organizations.name, 'MCP-1'))
      .limit(1);

    if (existingMcp.length > 0) {
      created.organizationId = existingMcp[0].id;
    } else {
      const orgId = crypto.randomUUID();
      await db.insert(schema.organizations).values({
        id: orgId,
        name: 'MCP-1',
        type: 'syndicate',
        address: `${TEST_TAG} 1`,
        city: 'Montreal',
        province: 'QC',
        postalCode: 'H1A1A1',
      });
      created.organizationId = orgId;
      created.organizationCreatedByUs = true;
    }

    // 2. Seed a user that will own the maintenance projects
    //    (maintenance_projects.created_by NOT NULL).
    const userId = crypto.randomUUID();
    await db.insert(schema.users).values({
      id: userId,
      email: `${TEST_TAG}-${userId.slice(0, 8)}@example.com`,
      username: `t279-${userId.slice(0, 8)}`,
      password: 'x',
      firstName: 'T279',
      lastName: 'Tester',
      role: 'admin',
    });
    created.userId = userId;

    // 3. Building inside the MCP-scoped org.
    const buildingId = crypto.randomUUID();
    await db.insert(schema.buildings).values({
      id: buildingId,
      organizationId: created.organizationId,
      name: `${TEST_TAG} bldg`,
      address: '1 Cascade',
      city: 'Montreal',
      province: 'QC',
      postalCode: 'H1A1A1',
      buildingType: 'condo',
      totalUnits: 1,
      totalFloors: 1,
      isActive: true,
    });
    created.buildingId = buildingId;

    // 4. Resolve (or seed) a uniformat code we can attach building
    //    elements to (FK building_elements.uniformat_code →
    //    uniformat_codes.code).
    const existingCode = await db
      .select({ code: schema.uniformatCodes.code })
      .from(schema.uniformatCodes)
      .limit(1);
    if (existingCode.length > 0) {
      created.uniformatCode = existingCode[0].code;
    } else {
      const code = `T279`;
      await db.insert(schema.uniformatCodes).values({
        code,
        level: 1,
        nameFr: 'Test cascade',
        nameEn: 'Test cascade',
      });
      created.uniformatCode = code;
      created.uniformatCodeCreatedByUs = true;
    }
    const uniformatCode = created.uniformatCode!;

    // 5. Two building elements: one referenced by the primary project's
    //    project_elements + element_project_updates rows, and one used
    //    only by the sibling project (so we can verify the
    //    project_elements unique constraint isn't tripped).
    const elementId = crypto.randomUUID();
    const siblingElementId = crypto.randomUUID();
    await db.insert(schema.buildingElements).values([
      {
        id: elementId,
        buildingId,
        uniformatCode,
        name: `${TEST_TAG}-element`,
      },
      {
        id: siblingElementId,
        buildingId,
        uniformatCode,
        name: `${TEST_TAG}-sibling-element`,
      },
    ]);
    created.elementIds.add(elementId);
    created.elementIds.add(siblingElementId);

    // 6. Two maintenance projects in the same building:
    //    - primary: the one we'll delete, with at least one row in
    //      every cascade-tracked dependent table.
    //    - sibling: unrelated project in the same building with its
    //      own project_step + workflow_task. Used to verify the delete
    //      is scoped — if the cascade ever broadened to the building
    //      (or just dropped the WHERE clause), these would be wiped too.
    const projectId = crypto.randomUUID();
    const siblingProjectId = crypto.randomUUID();
    await db.insert(schema.maintenanceProjects).values([
      {
        id: projectId,
        buildingId,
        projectNumber: `T279-${projectId.slice(0, 8)}`,
        title: `${TEST_TAG}-project`,
        type: 'repair',
        origin: 'manual',
        status: 'planned',
        priority: 'medium',
        createdBy: userId,
      },
      {
        id: siblingProjectId,
        buildingId,
        projectNumber: `T279S-${siblingProjectId.slice(0, 8)}`,
        title: `${TEST_TAG}-sibling-project`,
        type: 'repair',
        origin: 'manual',
        status: 'planned',
        priority: 'medium',
        createdBy: userId,
      },
    ]);
    created.projectIds.add(projectId);
    created.projectIds.add(siblingProjectId);

    // 7. Seed at least one row in every cascade-tracked dependent
    //    table for the primary project.
    const stepId = crypto.randomUUID();
    const siblingStepId = crypto.randomUUID();
    await db.insert(schema.projectSteps).values([
      { id: stepId, projectId, stepType: 'submission', isRequired: true, status: 'pending' },
      { id: siblingStepId, projectId: siblingProjectId, stepType: 'submission', isRequired: true, status: 'pending' },
    ]);
    created.projectStepIds.add(stepId);
    created.projectStepIds.add(siblingStepId);

    const projectElementId = crypto.randomUUID();
    await db.insert(schema.projectElements).values({
      id: projectElementId,
      projectId,
      elementId,
      projectType: 'repair',
      workDescription: `${TEST_TAG} work`,
    });
    created.projectElementIds.add(projectElementId);

    const submissionVendorId = crypto.randomUUID();
    await db.insert(schema.submissionVendors).values({
      id: submissionVendorId,
      projectId,
      vendorName: `${TEST_TAG} vendor`,
      projectType: 'repair',
    });
    created.submissionVendorIds.add(submissionVendorId);

    const workflowTaskId = crypto.randomUUID();
    const siblingWorkflowTaskId = crypto.randomUUID();
    await db.insert(schema.workflowTasks).values([
      {
        id: workflowTaskId,
        projectId,
        phase: 'pre_work',
        taskName: `${TEST_TAG} task`,
        orderIndex: 1,
      },
      {
        id: siblingWorkflowTaskId,
        projectId: siblingProjectId,
        phase: 'pre_work',
        taskName: `${TEST_TAG} sibling task`,
        orderIndex: 1,
      },
    ]);
    created.workflowTaskIds.add(workflowTaskId);
    created.workflowTaskIds.add(siblingWorkflowTaskId);

    const notificationId = crypto.randomUUID();
    await db.insert(schema.projectNotifications).values({
      id: notificationId,
      projectId,
      messageText: `${TEST_TAG} reminder`,
      timingType: 'one_week_before',
    });
    created.projectNotificationIds.add(notificationId);

    const updateId = crypto.randomUUID();
    await db.insert(schema.elementProjectUpdates).values({
      id: updateId,
      projectId,
      elementId,
      updateStatus: 'nothing',
    });
    created.elementProjectUpdateIds.add(updateId);

    // 8. Evaluation suggestion that points at the project. Its
    //    projectId should be null-ed out (DB-level ON DELETE SET NULL,
    //    plus the handler counts the explicit UPDATE for the response).
    const suggestionId = crypto.randomUUID();
    await db.insert(schema.evaluationSuggestions).values({
      id: suggestionId,
      elementId,
      suggestedDate: '2030-06-01',
      suggestedType: 'inspection',
      reason: `${TEST_TAG} reason`,
      priority: 'medium',
      status: 'pending',
      projectId,
    });
    created.suggestionIds.add(suggestionId);

    // ---- Invoke the real MCP `delete_project` handler ----
    const server = createMcpServer();
    const handler = getToolHandler(server, 'delete_project');
    const result = await handler({ role: 'admin', projectId }, {});
    const parsed = parseToolJson(result);

    // The handler reports the deleted project summary, a cascade
    // summary whose counts must match the rows we seeded, and a
    // message referencing the cascade.
    expect(parsed.deleted).toEqual({
      id: projectId,
      projectNumber: `T279-${projectId.slice(0, 8)}`,
      title: `${TEST_TAG}-project`,
    });
    expect(parsed.cascaded).toEqual({
      projectSteps: 1,
      projectElements: 1,
      submissionVendors: 1,
      workflowTasks: 1,
      projectNotifications: 1,
      elementProjectUpdates: 1,
    });
    expect(parsed.evaluationSuggestionsCleared).toBe(1);
    expect(parsed.message).toMatch(/cascade/i);

    // The project row itself is gone…
    const remainingProject = await db
      .select({ id: schema.maintenanceProjects.id })
      .from(schema.maintenanceProjects)
      .where(eq(schema.maintenanceProjects.id, projectId));
    expect(remainingProject).toHaveLength(0);
    created.projectIds.delete(projectId);

    // …every dependent row that pointed at the deleted project is gone
    // (this is the regression guard: if any cascade FK is dropped or
    // the handler stops issuing the cascading delete in a way Postgres
    // can follow, these assertions fail immediately).
    const childChecks: Array<[string, Promise<unknown[]>, Set<string>, string]> = [
      [
        'projectSteps',
        db.select({ id: schema.projectSteps.id }).from(schema.projectSteps).where(eq(schema.projectSteps.id, stepId)),
        created.projectStepIds,
        stepId,
      ],
      [
        'projectElements',
        db.select({ id: schema.projectElements.id }).from(schema.projectElements).where(eq(schema.projectElements.id, projectElementId)),
        created.projectElementIds,
        projectElementId,
      ],
      [
        'submissionVendors',
        db.select({ id: schema.submissionVendors.id }).from(schema.submissionVendors).where(eq(schema.submissionVendors.id, submissionVendorId)),
        created.submissionVendorIds,
        submissionVendorId,
      ],
      [
        'workflowTasks',
        db.select({ id: schema.workflowTasks.id }).from(schema.workflowTasks).where(eq(schema.workflowTasks.id, workflowTaskId)),
        created.workflowTaskIds,
        workflowTaskId,
      ],
      [
        'projectNotifications',
        db.select({ id: schema.projectNotifications.id }).from(schema.projectNotifications).where(eq(schema.projectNotifications.id, notificationId)),
        created.projectNotificationIds,
        notificationId,
      ],
      [
        'elementProjectUpdates',
        db.select({ id: schema.elementProjectUpdates.id }).from(schema.elementProjectUpdates).where(eq(schema.elementProjectUpdates.id, updateId)),
        created.elementProjectUpdateIds,
        updateId,
      ],
    ];
    for (const [label, query, tracker, id] of childChecks) {
      const remaining = await query;
      expect({ table: label, remaining }).toEqual({ table: label, remaining: [] });
      tracker.delete(id);
    }

    // The evaluation suggestion is still there but its projectId is
    // null (set-null cascade fired AND the handler counted it).
    const remainingSuggestion = await db
      .select({ id: schema.evaluationSuggestions.id, projectId: schema.evaluationSuggestions.projectId })
      .from(schema.evaluationSuggestions)
      .where(eq(schema.evaluationSuggestions.id, suggestionId));
    expect(remainingSuggestion).toHaveLength(1);
    expect(remainingSuggestion[0].projectId).toBeNull();

    // …and the sibling project + its dependents in the same building
    // are untouched. If the cascade ever broadened to the building
    // scope (or dropped its WHERE clause), this would catch it.
    const remainingSiblingProject = await db
      .select({ id: schema.maintenanceProjects.id })
      .from(schema.maintenanceProjects)
      .where(eq(schema.maintenanceProjects.id, siblingProjectId));
    expect(remainingSiblingProject).toHaveLength(1);

    const remainingSiblingStep = await db
      .select({ id: schema.projectSteps.id, projectId: schema.projectSteps.projectId })
      .from(schema.projectSteps)
      .where(eq(schema.projectSteps.id, siblingStepId));
    expect(remainingSiblingStep).toHaveLength(1);
    expect(remainingSiblingStep[0].projectId).toBe(siblingProjectId);

    const remainingSiblingTask = await db
      .select({ id: schema.workflowTasks.id, projectId: schema.workflowTasks.projectId })
      .from(schema.workflowTasks)
      .where(eq(schema.workflowTasks.id, siblingWorkflowTaskId));
    expect(remainingSiblingTask).toHaveLength(1);
    expect(remainingSiblingTask[0].projectId).toBe(siblingProjectId);
  }, 60000);
});
