import { useState, useMemo, useCallback } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from '@/components/ui/collapsible';
import { useAutoGeneratedProjects, useBulkDismissAutoProjects } from '@/hooks/useAutoGeneratedProjects';
import { AutoProjectCard } from './AutoProjectCard';
import { AutoProjectDialog } from './AutoProjectDialog';
import { cn } from '@/lib/utils';
import {
  AutoGeneratedProjectWithMetadata,
  AUTO_PROJECT_STATUS_DISPLAY,
  PRIORITY_DISPLAY,
  PROJECT_TYPE_DISPLAY,
} from '@/types/autoProjects';
import {
  Sparkles,
  ChevronDown,
  ChevronRight,
  Search,
  Filter,
  CheckCircle2,
  X,
  RefreshCw,
  Info,
  AlertTriangle,
  Zap,
  Plus,
} from 'lucide-react';

export interface AutoProjectsSectionProps {
  buildingId?: string;
  className?: string;
  showHeader?: boolean;
  defaultExpanded?: boolean;
  onProjectAccepted?: (project: any) => void;
}

/**
 * AutoProjectsSection component for displaying and managing auto-generated projects
 * Integrates into the main Projects page with collapsible UI and bulk actions
 */
export function AutoProjectsSection({
  buildingId,
  className,
  showHeader = true,
  defaultExpanded = true,
  onProjectAccepted,
}: AutoProjectsSectionProps) {
  // State management
  const [isExpanded, setIsExpanded] = useState(defaultExpanded);
  const [selectedAutoProjects, setSelectedAutoProjects] = useState<string[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [priorityFilter, setPriorityFilter] = useState('');
  const [typeFilter, setTypeFilter] = useState('');
  const [showOnlyHighConfidence, setShowOnlyHighConfidence] = useState(false);

  // Dialog state
  const [selectedAutoProject, setSelectedAutoProject] = useState<AutoGeneratedProjectWithMetadata | null>(null);
  const [dialogMode, setDialogMode] = useState<'view' | 'edit' | 'accept'>('view');
  const [showDialog, setShowDialog] = useState(false);

  // Fetch auto-generated projects
  const {
    data: autoProjectsResponse,
    isLoading,
    error,
    refetch,
  } = useAutoGeneratedProjects(buildingId);

  // Bulk dismiss mutation
  const bulkDismissMutation = useBulkDismissAutoProjects();

  // Extract data from response
  const allAutoProjects: AutoGeneratedProjectWithMetadata[] = useMemo(() => {
    if (!autoProjectsResponse?.autoProjects) return [];
    
    // Enhance auto-projects with computed properties
    return autoProjectsResponse.autoProjects.map(project => ({
      ...project,
      confidenceLevel: project.confidence 
        ? (parseFloat(project.confidence) >= 0.7 ? 'high' : parseFloat(project.confidence) >= 0.4 ? 'medium' : 'low')
        : 'low',
      canEdit: project.status === 'pending',
      canAccept: project.status === 'pending',
      canDismiss: project.status === 'pending',
    }));
  }, [autoProjectsResponse]);

  // Filter auto-projects
  const filteredAutoProjects = useMemo(() => {
    return allAutoProjects.filter(project => {
      // Search filter
      if (searchTerm) {
        const searchLower = searchTerm.toLowerCase();
        const matchesSearch = 
          project.title.toLowerCase().includes(searchLower) ||
          project.description.toLowerCase().includes(searchLower) ||
          project.element?.name.toLowerCase().includes(searchLower);
        
        if (!matchesSearch) return false;
      }

      // Priority filter
      if (priorityFilter && project.suggestedPriority !== priorityFilter) {
        return false;
      }

      // Type filter
      if (typeFilter && project.suggestedType !== typeFilter) {
        return false;
      }

      // High confidence filter
      if (showOnlyHighConfidence && project.confidenceLevel !== 'high') {
        return false;
      }

      // Only show pending projects in this section
      return project.status === 'pending';
    });
  }, [allAutoProjects, searchTerm, priorityFilter, typeFilter, showOnlyHighConfidence]);

  // Summary statistics
  const summary = useMemo(() => {
    return {
      total: allAutoProjects.length,
      pending: allAutoProjects.filter(p => p.status === 'pending').length,
      highPriority: allAutoProjects.filter(p => p.suggestedPriority === 'critical' || p.suggestedPriority === 'high').length,
      highConfidence: allAutoProjects.filter(p => p.confidenceLevel === 'high').length,
      totalEstimatedCost: allAutoProjects
        .filter(p => p.estimatedCost)
        .reduce((sum, p) => sum + parseFloat(p.estimatedCost!), 0),
    };
  }, [allAutoProjects]);

  // Event handlers
  const handleViewProject = useCallback((autoProject: AutoGeneratedProjectWithMetadata) => {
    setSelectedAutoProject(autoProject);
    setDialogMode('view');
    setShowDialog(true);
  }, []);

  const handleEditProject = useCallback((autoProject: AutoGeneratedProjectWithMetadata) => {
    setSelectedAutoProject(autoProject);
    setDialogMode('edit');
    setShowDialog(true);
  }, []);

  const handleAcceptProject = useCallback((autoProject: AutoGeneratedProjectWithMetadata) => {
    setSelectedAutoProject(autoProject);
    setDialogMode('accept');
    setShowDialog(true);
  }, []);

  const handleDismissProject = useCallback((autoProject: AutoGeneratedProjectWithMetadata) => {
    // For individual dismiss, we can call the dismiss hook directly
    // This is handled by the AutoProjectCard component
  }, []);

  const handleSelectProject = useCallback((autoProject: AutoGeneratedProjectWithMetadata, selected: boolean) => {
    setSelectedAutoProjects(prev => 
      selected 
        ? [...prev, autoProject.id]
        : prev.filter(id => id !== autoProject.id)
    );
  }, []);

  const handleSelectAll = useCallback((checked: boolean) => {
    setSelectedAutoProjects(checked ? filteredAutoProjects.map(p => p.id) : []);
  }, [filteredAutoProjects]);

  const handleBulkDismiss = useCallback(() => {
    if (selectedAutoProjects.length === 0 || !buildingId) return;

    bulkDismissMutation.mutate({
      autoProjectIds: selectedAutoProjects,
      buildingId,
      reason: 'Bulk dismiss action',
    }, {
      onSuccess: () => {
        setSelectedAutoProjects([]);
      },
    });
  }, [selectedAutoProjects, buildingId, bulkDismissMutation]);

  const handleDialogSuccess = useCallback((result: any) => {
    if (dialogMode === 'accept') {
      onProjectAccepted?.(result);
    }
    // The mutations will handle cache invalidation automatically
  }, [dialogMode, onProjectAccepted]);

  // Don't render if no building ID
  if (!buildingId) {
    return null;
  }

  // Loading state
  if (isLoading) {
    return (
      <Card className={cn('mb-6', className)} data-testid="auto-projects-loading">
        <CardHeader>
          <div className="flex items-center gap-2">
            <Skeleton className="h-6 w-6" />
            <Skeleton className="h-6 w-48" />
          </div>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {Array.from({ length: 3 }).map((_, i) => (
              <Skeleton key={i} className="h-48" />
            ))}
          </div>
        </CardContent>
      </Card>
    );
  }

  // Error state
  if (error) {
    return (
      <Card className={cn('mb-6', className)} data-testid="auto-projects-error">
        <CardContent className="pt-6">
          <Alert variant="destructive">
            <AlertTriangle className="h-4 w-4" />
            <AlertDescription>
              Failed to load auto-generated projects. Please try refreshing.
              <Button
                variant="outline"
                size="sm"
                onClick={() => refetch()}
                className="ml-2"
                data-testid="auto-projects-retry"
              >
                <RefreshCw className="h-4 w-4 mr-2" />
                Retry
              </Button>
            </AlertDescription>
          </Alert>
        </CardContent>
      </Card>
    );
  }

  // No auto-projects state
  if (summary.total === 0) {
    return (
      <Card className={cn('mb-6', className)} data-testid="auto-projects-empty">
        <CardContent className="pt-6">
          <div className="text-center py-8">
            <Sparkles className="h-12 w-12 text-gray-400 mx-auto mb-4" />
            <h3 className="text-lg font-medium text-gray-900 dark:text-gray-100 mb-2">
              No Auto-Generated Projects
            </h3>
            <p className="text-gray-600 dark:text-gray-400 max-w-md mx-auto">
              AI-generated project suggestions will appear here when available. 
              These are automatically created based on building evaluations and maintenance schedules.
            </p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <>
      <Collapsible open={isExpanded} onOpenChange={setIsExpanded} className={cn('mb-6', className)}>
        <Card data-testid="auto-projects-section">
          {showHeader && (
            <CollapsibleTrigger asChild>
              <CardHeader className="cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-800/50 transition-colors">
                <div className="flex items-center justify-between">
                  <CardTitle className="flex items-center gap-2">
                    <Sparkles className="h-5 w-5 text-blue-500" />
                    AI-Generated Projects
                    <Badge variant="secondary" className="ml-2" data-testid="auto-projects-count">
                      {summary.pending} pending
                    </Badge>
                    {summary.highPriority > 0 && (
                      <Badge variant="destructive" className="ml-1">
                        <Zap className="h-3 w-3 mr-1" />
                        {summary.highPriority} urgent
                      </Badge>
                    )}
                  </CardTitle>
                  <div className="flex items-center gap-2">
                    {summary.totalEstimatedCost > 0 && (
                      <span className="text-sm text-gray-600 dark:text-gray-400">
                        Est. Total: ${summary.totalEstimatedCost.toLocaleString('en-CA')}
                      </span>
                    )}
                    {isExpanded ? (
                      <ChevronDown className="h-4 w-4" />
                    ) : (
                      <ChevronRight className="h-4 w-4" />
                    )}
                  </div>
                </div>
              </CardHeader>
            </CollapsibleTrigger>
          )}

          <CollapsibleContent>
            <CardContent className={cn(!showHeader && 'pt-6')}>
              {/* Info Banner */}
              <Alert className="mb-4 border-blue-200 bg-blue-50 dark:bg-blue-950/20 dark:border-blue-800">
                <Info className="h-4 w-4 text-blue-600" />
                <AlertDescription className="text-blue-800 dark:text-blue-200">
                  These projects were automatically generated by AI based on building evaluations and maintenance schedules. 
                  Review, edit if needed, and accept to convert them into active maintenance projects.
                </AlertDescription>
              </Alert>

              {/* Filters and Search */}
              <div className="flex flex-col sm:flex-row gap-4 mb-6">
                <div className="flex-1">
                  <div className="relative">
                    <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 h-4 w-4" />
                    <Input
                      placeholder="Search auto-projects..."
                      value={searchTerm}
                      onChange={(e) => setSearchTerm(e.target.value)}
                      className="pl-10"
                      data-testid="auto-projects-search"
                    />
                  </div>
                </div>

                <div className="flex gap-2">
                  <Select value={priorityFilter} onValueChange={setPriorityFilter}>
                    <SelectTrigger className="w-32" data-testid="auto-projects-priority-filter">
                      <SelectValue placeholder="Priority" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="">All Priorities</SelectItem>
                      {Object.entries(PRIORITY_DISPLAY).map(([key, display]) => (
                        <SelectItem key={key} value={key}>
                          {display.label}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>

                  <Select value={typeFilter} onValueChange={setTypeFilter}>
                    <SelectTrigger className="w-32" data-testid="auto-projects-type-filter">
                      <SelectValue placeholder="Type" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="">All Types</SelectItem>
                      {Object.entries(PROJECT_TYPE_DISPLAY).map(([key, display]) => (
                        <SelectItem key={key} value={key}>
                          {display.label}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>

                  <Button
                    variant="outline"
                    size="icon"
                    onClick={() => setShowOnlyHighConfidence(!showOnlyHighConfidence)}
                    className={cn(showOnlyHighConfidence && 'bg-green-50 border-green-200 text-green-700')}
                    data-testid="auto-projects-confidence-filter"
                  >
                    <Filter className="h-4 w-4" />
                  </Button>
                </div>
              </div>

              {/* Bulk Actions */}
              {filteredAutoProjects.length > 0 && (
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-2">
                    <Checkbox
                      checked={selectedAutoProjects.length === filteredAutoProjects.length}
                      onCheckedChange={handleSelectAll}
                      data-testid="auto-projects-select-all"
                    />
                    <span className="text-sm text-gray-600 dark:text-gray-400">
                      {selectedAutoProjects.length > 0 
                        ? `${selectedAutoProjects.length} selected`
                        : 'Select all'
                      }
                    </span>
                  </div>

                  {selectedAutoProjects.length > 0 && (
                    <div className="flex gap-2">
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={handleBulkDismiss}
                        disabled={bulkDismissMutation.isPending}
                        data-testid="auto-projects-bulk-dismiss"
                      >
                        <X className="h-4 w-4 mr-2" />
                        Dismiss Selected ({selectedAutoProjects.length})
                      </Button>
                    </div>
                  )}
                </div>
              )}

              {/* Auto-Projects Grid */}
              {filteredAutoProjects.length > 0 ? (
                <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-4" data-testid="auto-projects-grid">
                  {filteredAutoProjects.map((autoProject) => (
                    <AutoProjectCard
                      key={autoProject.id}
                      autoProject={autoProject}
                      onView={handleViewProject}
                      onEdit={handleEditProject}
                      onAccept={handleAcceptProject}
                      onDismiss={handleDismissProject}
                      selected={selectedAutoProjects.includes(autoProject.id)}
                      onSelect={handleSelectProject}
                    />
                  ))}
                </div>
              ) : (
                <div className="text-center py-8" data-testid="auto-projects-no-results">
                  <Search className="h-12 w-12 text-gray-400 mx-auto mb-4" />
                  <h3 className="text-lg font-medium text-gray-900 dark:text-gray-100 mb-2">
                    No projects match your filters
                  </h3>
                  <p className="text-gray-600 dark:text-gray-400">
                    Try adjusting your search terms or filters to see more results.
                  </p>
                  <Button
                    variant="outline"
                    onClick={() => {
                      setSearchTerm('');
                      setPriorityFilter('');
                      setTypeFilter('');
                      setShowOnlyHighConfidence(false);
                    }}
                    className="mt-4"
                    data-testid="auto-projects-clear-filters"
                  >
                    Clear Filters
                  </Button>
                </div>
              )}
            </CardContent>
          </CollapsibleContent>
        </Card>
      </Collapsible>

      {/* Auto-Project Dialog */}
      <AutoProjectDialog
        isOpen={showDialog}
        onOpenChange={setShowDialog}
        autoProject={selectedAutoProject || undefined}
        mode={dialogMode}
        onSuccess={handleDialogSuccess}
      />
    </>
  );
}