import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { Textarea } from '@/components/ui/textarea';
import { cn } from '@/lib/utils';
import {
  AutoGeneratedProjectWithMetadata,
  AutoProjectActions,
  CONFIDENCE_LEVELS,
  PROJECT_TYPE_DISPLAY,
  PRIORITY_DISPLAY,
  formatCurrency,
  formatConfidence,
  getConfidenceLevel,
} from '@/types/autoProjects';
import {
  Sparkles,
  Clock,
  DollarSign,
  Building,
  MoreHorizontal,
  Eye,
  Edit2,
  CheckCircle2,
  X,
} from 'lucide-react';
import { StandardCard } from '@/components/common/StandardCard';
import { useLanguage } from '@/hooks/use-language';

export interface AutoProjectCardProps extends AutoProjectActions {
  autoProject: AutoGeneratedProjectWithMetadata;
  showActions?: boolean;
  compact?: boolean;
  className?: string;
  selected?: boolean;
  onSelect?: (autoProject: AutoGeneratedProjectWithMetadata, selected: boolean) => void;
}

export function AutoProjectCard({
  autoProject,
  onView,
  onEdit,
  onAccept,
  onDismiss,
  showActions = true,
  compact = false,
  className,
  selected = false,
  onSelect,
}: AutoProjectCardProps) {
  const { t } = useLanguage();
  const [showDismissDialog, setShowDismissDialog] = useState(false);
  const [dismissReason, setDismissReason] = useState('');

  const confidenceLevel = getConfidenceLevel(autoProject.confidence ? parseFloat(autoProject.confidence) : undefined);
  const confidenceConfig = CONFIDENCE_LEVELS[confidenceLevel];
  const typeDisplay = PROJECT_TYPE_DISPLAY[autoProject.suggestedType];
  const priorityDisplay = PRIORITY_DISPLAY[autoProject.suggestedPriority];
  const confidencePercentage = autoProject.confidence ? parseFloat(autoProject.confidence) * 100 : 0;
  const isUrgent = autoProject.suggestedPriority === 'critical' || autoProject.suggestedPriority === 'high';

  const handleView = () => onView?.(autoProject);
  const handleEdit = () => onEdit?.(autoProject);
  const handleAccept = () => onAccept?.(autoProject);
  
  const handleDismiss = () => {
    setShowDismissDialog(true);
  };

  const confirmDismiss = () => {
    onDismiss?.(autoProject);
    setShowDismissDialog(false);
    setDismissReason('');
  };

  const handleSelect = () => {
    onSelect?.(autoProject, !selected);
  };

  const badges = compact ? [] : [
    {
      text: 'AI Generated',
      variant: 'secondary' as const,
      className: 'bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-300',
    },
  ];

  const topBadges = !compact ? [
    {
      text: priorityDisplay.label,
      variant: 'outline' as const,
      className: priorityDisplay.color,
    },
    {
      text: typeDisplay.label,
      variant: 'outline' as const,
    },
  ] : [];

  const metadata = compact ? [] : [
    ...(autoProject.estimatedCost ? [{
      icon: <DollarSign className="h-4 w-4 text-green-600" />,
      label: 'Est. Cost',
      value: formatCurrency(autoProject.estimatedCost),
    }] : []),
    ...(autoProject.estimatedDuration ? [{
      icon: <Clock className="h-4 w-4 text-blue-600" />,
      label: 'Est. Duration',
      value: `${autoProject.estimatedDuration} days`,
    }] : []),
  ];

  const actions = [];
  
  if (showActions && onSelect) {
    actions.push({
      icon: (
        <div className={cn(
          'w-4 h-4 border-2 rounded flex items-center justify-center',
          selected ? 'bg-blue-500 border-blue-500' : 'border-gray-300'
        )}>
          {selected && <CheckCircle2 className="h-3 w-3 text-white" />}
        </div>
      ),
      label: 'Select project',
      onClick: handleSelect,
      variant: 'ghost' as const,
      testId: `auto-project-select-${autoProject.id}`,
    });
  }

  const description = compact ? undefined : autoProject.description;

  const content = !compact ? (
    <div className="space-y-3">
      {topBadges.length > 0 && (
        <div className="flex items-center gap-2">
          {topBadges.map((badge, index) => (
            <Badge 
              key={index}
              variant={badge.variant}
              className={cn('text-xs', badge.className)}
            >
              {badge.text}
            </Badge>
          ))}
        </div>
      )}

      {autoProject.element && (
        <div className="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-400">
          <Building className="h-4 w-4" />
          <span data-testid={`auto-project-element-${autoProject.id}`}>
            {autoProject.element.name}
            {autoProject.element.location && ` - ${autoProject.element.location}`}
          </span>
        </div>
      )}

      <div>
        <div className="flex items-center justify-between mb-1">
          <span className="text-sm font-medium text-gray-700 dark:text-gray-300">
            AI Confidence
          </span>
          <span 
            className={cn('text-sm font-medium', confidenceConfig.color)}
            data-testid={`auto-project-confidence-${autoProject.id}`}
          >
            {formatConfidence(autoProject.confidence ? parseFloat(autoProject.confidence) : undefined)}
          </span>
        </div>
        <Progress 
          value={confidencePercentage} 
          className="h-2"
          data-testid={`auto-project-confidence-bar-${autoProject.id}`}
        />
        <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
          {confidenceConfig.label}
        </p>
      </div>
    </div>
  ) : null;

  const footer = !compact && showActions ? (
    <div className="flex gap-2 w-full">
      <Button
        onClick={handleView}
        variant="outline"
        size="sm"
        className="flex-1"
        data-testid={`auto-project-view-btn-${autoProject.id}`}
      >
        <Eye className="mr-2 h-4 w-4" />
        View Details
      </Button>
      
      {autoProject.canAccept && (
        <Button
          onClick={handleAccept}
          size="sm"
          className="flex-1 bg-green-600 hover:bg-green-700 text-white"
          data-testid={`auto-project-accept-btn-${autoProject.id}`}
        >
          <CheckCircle2 className="mr-2 h-4 w-4" />
          Accept
        </Button>
      )}
    </div>
  ) : null;

  const cardClassNames = cn(
    'border-l-4 bg-gradient-to-r from-blue-50/50 to-white dark:from-blue-950/20 dark:to-gray-900',
    'border-l-blue-400',
    isUrgent && 'border-l-orange-400 from-orange-50/50 dark:from-orange-950/20',
    autoProject.suggestedPriority === 'critical' && 'border-l-red-400 from-red-50/50 dark:from-red-950/20',
    selected && 'ring-2 ring-blue-500 ring-offset-2',
    className
  );

  return (
    <>
      <div className="relative">
        <StandardCard
          icon={<Sparkles className="h-4 w-4 text-blue-500" />}
          title={autoProject.title}
          description={description}
          badges={badges}
          metadata={metadata}
          actions={actions}
          footer={footer}
          compact={compact}
          testId={`auto-project-card-${autoProject.id}`}
          className={cardClassNames}
        >
          {content}
        </StandardCard>
        
        {showActions && (onEdit || onDismiss) && (
          <div className={cn(
            "absolute top-3 right-3 z-10",
            compact && "top-2 right-2"
          )}>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button
                  variant="ghost"
                  size="sm"
                  className="h-7 w-7 p-0"
                  data-testid={`auto-project-menu-${autoProject.id}`}
                  onClick={(e) => e.stopPropagation()}
                >
                  <MoreHorizontal className="h-4 w-4" />
                  <span className="sr-only">More actions</span>
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end" data-testid={`auto-project-menu-content-${autoProject.id}`}>
                {onEdit && (
                  <DropdownMenuItem
                    onClick={(e) => {
                      e.stopPropagation();
                      handleEdit();
                    }}
                    data-testid={`auto-project-edit-${autoProject.id}`}
                  >
                    <Edit2 className="mr-2 h-4 w-4" />
                    <span>Edit</span>
                  </DropdownMenuItem>
                )}
                {onDismiss && (
                  <>
                    {onEdit && <DropdownMenuSeparator />}
                    <DropdownMenuItem
                      onClick={(e) => {
                        e.stopPropagation();
                        handleDismiss();
                      }}
                      className="text-red-600 focus:text-red-600 dark:text-red-400 dark:focus:text-red-400"
                      data-testid={`auto-project-dismiss-${autoProject.id}`}
                    >
                      <X className="mr-2 h-4 w-4" />
                      <span>Dismiss</span>
                    </DropdownMenuItem>
                  </>
                )}
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        )}
      </div>

      <AlertDialog open={showDismissDialog} onOpenChange={setShowDismissDialog}>
        <AlertDialogContent data-testid={`auto-project-dismiss-dialog-${autoProject.id}`}>
          <AlertDialogHeader>
            <AlertDialogTitle>Dismiss Auto-Generated Project</AlertDialogTitle>
            <AlertDialogDescription>
              {t('areYouSureYouWantTo')}
            </AlertDialogDescription>
          </AlertDialogHeader>
          
          <div className="py-4">
            <label htmlFor="dismiss-reason" className="text-sm font-medium text-gray-700 dark:text-gray-300">
              {t('reasonForDismissalOptional')}
            </label>
            <Textarea
              id="dismiss-reason"
              value={dismissReason}
              onChange={(e) => setDismissReason(e.target.value)}
              placeholder="Provide a reason for dismissing this project..."
              className="mt-2"
              data-testid={`auto-project-dismiss-reason-${autoProject.id}`}
            />
          </div>
          
          <AlertDialogFooter>
            <AlertDialogCancel data-testid={`auto-project-dismiss-cancel-${autoProject.id}`}>
              Cancel
            </AlertDialogCancel>
            <AlertDialogAction
              onClick={confirmDismiss}
              className="bg-red-600 hover:bg-red-700"
              data-testid={`auto-project-dismiss-confirm-${autoProject.id}`}
            >
              Dismiss Project
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  );
}
