import { sql } from 'drizzle-orm';
import {
  pgTable,
  text,
  timestamp,
  uuid,
  pgEnum,
  boolean,
  integer,
  decimal,
  date,
  jsonb,
  varchar,
} from 'drizzle-orm/pg-core';
import { createInsertSchema } from 'drizzle-zod';
import { z } from 'zod';
import { relations } from 'drizzle-orm';
import { users } from './core';
import { residences, buildings } from './property';

// Financial enums
export const billStatusEnum = pgEnum('bill_status', [
  'draft',
  'sent',
  'overdue',
  'paid',
  'cancelled',
]);


export const billCategoryEnum = pgEnum('bill_category', [
  'insurance',
  'maintenance',
  'salary',
  'utilities',
  'cleaning',
  'security',
  'landscaping',
  'professional_services',
  'administration',
  'repairs',
  'supplies',
  'taxes',
  'technology',
  'reserves',
  'other',
]);

// Shared constant array for use in frontend components - SINGLE SOURCE OF TRUTH
export const BILL_CATEGORIES = [
  'insurance',
  'maintenance',
  'salary',
  'utilities',
  'cleaning',
  'security',
  'landscaping',
  'professional_services',
  'administration',
  'repairs',
  'supplies',
  'taxes',
  'technology',
  'reserves',
  'other',
] as const;

export const paymentTypeEnum = pgEnum('payment_type', ['unique', 'recurrent']);

export const schedulePaymentEnum = pgEnum('schedule_payment', [
  'weekly',
  'monthly',
  'quarterly',
  'yearly',
  'custom',
]);

export const paymentStatusEnum = pgEnum('payment_status', [
  'pending',
  'overdue', 
  'paid',
  'cancelled',
]);

export const investmentUrgencyEnum = pgEnum('investment_urgency', [
  'not_urgent',
  'urgent', 
  'suggested',
]);

export const investmentTypeEnum = pgEnum('investment_type', [
  'auto_generated',
  'custom',
]);

export const investmentOwnershipEnum = pgEnum('investment_ownership', [
  'residences',
  'owner',
]);

// Financial tables
/**
 * Enhanced bills table for tracking financial obligations with advanced scheduling.
 * Supports unique and recurrent payments with custom scheduling options.
 */
export const bills = pgTable('bills', {
  id: text('id')
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  buildingId: varchar('building_id')
    .notNull()
    .references(() => buildings.id),
  billNumber: varchar('bill_number', { length: 50 }).notNull().unique(),
  title: varchar('title', { length: 200 }).notNull(),
  description: text('description'),
  category: billCategoryEnum('category').notNull(),
  vendor: varchar('vendor', { length: 200 }), // Company or service provider
  paymentType: paymentTypeEnum('payment_type').notNull(), // unique or recurrent
  schedulePayment: schedulePaymentEnum('schedule_payment'), // Only for recurrent payments
  scheduleCustom: date('schedule_custom').array(), // Custom dates for custom schedules
  costs: decimal('costs', { precision: 10, scale: 2 }).array().notNull(), // Array of costs for payment plan
  totalAmount: decimal('total_amount', { precision: 10, scale: 2 }).notNull(),
  startDate: date('start_date').notNull(), // When the bill series starts
  endDate: date('end_date'), // For recurrent bills, when they end (optional for ongoing)
  status: billStatusEnum('status').notNull().default('draft'),
  filePath: text('file_path'), // Path to uploaded bill document
  fileName: text('file_name'), // Original filename
  fileSize: integer('file_size'), // File size in bytes
  isAiAnalyzed: boolean('is_ai_analyzed').default(false),
  aiAnalysisData: jsonb('ai_analysis_data'), // Store AI-extracted data
  notes: text('notes'),
  isAutoGenerated: boolean('is_auto_generated').notNull().default(false), // Indicates if this bill was auto-generated
  sourceTemplateId: varchar('source_template_id').references(() => bills.id), // References the original bill for auto-generated bills
  autoGeneratedLabel: varchar('auto_generated_label'), // Display label for auto-generated bills
  createdBy: varchar('created_by')
    .notNull()
    .references(() => users.id),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

/**
 * Payments table for tracking individual payment instances for each bill.
 * Supports both unique and recurring payment schedules with automatic generation.
 */
export const payments = pgTable('payments', {
  id: text('id')
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  billId: varchar('bill_id')
    .notNull()
    .references(() => bills.id, { onDelete: 'cascade' }),
  paymentNumber: integer('payment_number').notNull(), // 1, 2, 3... for recurring bills
  scheduledDate: date('scheduled_date').notNull(),
  paidDate: date('paid_date'), // nullable - set when payment is confirmed
  amount: decimal('amount', { precision: 10, scale: 2 }).notNull(),
  status: paymentStatusEnum('status').notNull().default('pending'),
  notes: text('notes'), // Optional notes for this specific payment
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});


/**
 * Budgets table for tracking financial planning by building and category.
 * Supports operational, reserve, and special project budgets.
 */
export const budgets = pgTable('budgets', {
  id: text('id')
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  buildingId: varchar('building_id')
    .notNull()
    .references(() => buildings.id),
  year: integer('year').notNull(),
  name: text('name').notNull(),
  description: text('description'),
  category: text('category').notNull(), // 'operational', 'reserve', 'special_project'
  budgetedAmount: decimal('budgeted_amount', { precision: 12, scale: 2 }).notNull(),
  actualAmount: decimal('actual_amount', { precision: 12, scale: 2 }).default('0'),
  variance: decimal('variance', { precision: 12, scale: 2 }).default('0'),
  approvedBy: varchar('approved_by').references(() => users.id),
  approvedDate: date('approved_date'),
  isActive: boolean('is_active').notNull().default(true),
  createdBy: varchar('created_by')
    .notNull()
    .references(() => users.id),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

/**
 * Monthly budgets table for detailed monthly tracking of income and spending by building.
 * Automatically populated for each building from construction date to 25 years in the future.
 * Updated monthly on the 1st and supports approval workflow.
 */
export const monthlyBudgets = pgTable('monthly_budgets', {
  id: text('id')
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  buildingId: varchar('building_id')
    .notNull()
    .references(() => buildings.id),
  year: integer('year').notNull(),
  month: integer('month').notNull(), // 1-12
  incomeTypes: text('income_types').array().notNull(), // Array of income categories from money_flow
  incomes: decimal('incomes', { precision: 12, scale: 2 }).array().notNull(), // Array of income amounts corresponding to incomeTypes
  spendingTypes: text('spending_types').array().notNull(), // Array of expense categories from money_flow
  spendings: decimal('spendings', { precision: 12, scale: 2 }).array().notNull(), // Array of spending amounts corresponding to spendingTypes
  approved: boolean('approved').notNull().default(false),
  approvedBy: varchar('approved_by').references(() => users.id),
  approvedDate: timestamp('approved_date'),
  originalBudgetId: varchar('original_budget_id').references(() => monthlyBudgets.id), // References the original budget if this is an approved copy
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

/**
 * Capital investments table for tracking building infrastructure investments and improvements.
 * Supports both auto-generated suggestions and custom user-defined investments.
 */
export const capitalInvestments = pgTable('capital_investments', {
  id: text('id')
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  buildingId: varchar('building_id')
    .notNull()
    .references(() => buildings.id),
  title: text('title').notNull(),
  description: text('description'),
  amount: decimal('amount', { precision: 12, scale: 2 }).notNull(),
  targetDate: date('target_date').notNull(),
  urgency: investmentUrgencyEnum('urgency').notNull(),
  type: investmentTypeEnum('type').notNull(),
  ownershipType: investmentOwnershipEnum('ownership_type').notNull(),
  category: text('category'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

// Insert schemas
// Removed insertMoneyFlowSchema - money flow table deleted

export const insertBillSchema = createInsertSchema(bills, {
  // Custom validations for strict schema compliance
  billNumber: z.string().min(1, "Bill number is required"),
  title: z.string().min(1, "Title is required"),
  category: z.enum(['insurance', 'maintenance', 'salary', 'utilities', 'cleaning', 'security', 'landscaping', 'professional_services', 'administration', 'repairs', 'supplies', 'taxes', 'technology', 'reserves', 'other']),
  paymentType: z.enum(['unique', 'recurrent']),
  schedulePayment: z.enum(['weekly', 'monthly', 'quarterly', 'yearly', 'custom']).optional(),
  scheduleCustom: z.array(z.coerce.date()).optional().refine(
    (dates) => !dates || dates.length === 0 || dates.every(date => date instanceof Date && !isNaN(date.getTime())),
    "All custom schedule dates must be valid dates"
  ),
  costs: z.array(z.coerce.number().positive("All costs must be positive")).min(1, "At least one cost is required"),
  totalAmount: z.coerce.number().positive("Total amount must be positive"),
  startDate: z.coerce.date(),
  endDate: z.coerce.date().optional(),
  status: z.enum(['draft', 'sent', 'overdue', 'paid', 'cancelled']).default('draft'),
  isAutoGenerated: z.boolean().default(false),
  sourceTemplateId: z.string().optional(),
  autoGeneratedLabel: z.string().optional(),
}).omit({ 
  id: true, 
  createdAt: true, 
  updatedAt: true 
});


export const insertBudgetSchema = z.object({
  buildingId: z.string().uuid(),
  year: z.number().int(),
  name: z.string(),
  description: z.string().optional(),
  category: z.string(),
  budgetedAmount: z.number(),
  actualAmount: z.number().optional(),
  createdBy: z.string().uuid(),
});

export const insertMonthlyBudgetSchema = createInsertSchema(monthlyBudgets).omit({ 
  id: true, 
  createdAt: true, 
  updatedAt: true 
});

export const insertPaymentSchema = createInsertSchema(payments, {
  paymentNumber: z.number().int().positive("Payment number must be positive"),
  scheduledDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Date must be in YYYY-MM-DD format"),
  paidDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Date must be in YYYY-MM-DD format").optional(),
  amount: z.string().regex(/^\d+(\.\d{1,2})?$/, "Amount must be a valid decimal with up to 2 decimal places"),
  status: z.enum(['pending', 'overdue', 'paid', 'cancelled']).default('pending'),
  notes: z.string().optional(),
}).omit({ 
  id: true, 
  createdAt: true, 
  updatedAt: true 
});

export const insertCapitalInvestmentSchema = createInsertSchema(capitalInvestments, {
  title: z.string().min(1, "Title is required"),
  amount: z.coerce.number().positive("Amount must be positive"),
  targetDate: z.coerce.date(),
  urgency: z.enum(['not_urgent', 'urgent', 'suggested']),
  type: z.enum(['auto_generated', 'custom']),
  ownershipType: z.enum(['residences', 'owner']),
  category: z.string().optional(),
}).omit({ 
  id: true, 
  createdAt: true, 
  updatedAt: true 
});

// Types

/**
 * Bills insert and select types.
 */
export type InsertBill = typeof bills.$inferInsert;
/**
 *
 */
export type Bill = typeof bills.$inferSelect;


/**
 * Budget insert and select types.
 */
export type InsertBudget = z.infer<typeof insertBudgetSchema>;
/**
 *
 */
export type Budget = typeof budgets.$inferSelect;

/**
 * Monthly budget insert and select types.
 */
export type InsertMonthlyBudget = typeof monthlyBudgets.$inferInsert;
/**
 *
 */
export type MonthlyBudget = typeof monthlyBudgets.$inferSelect;

/**
 * Payment insert and select types.
 */
export type InsertPayment = z.infer<typeof insertPaymentSchema>;
/**
 *
 */
export type Payment = typeof payments.$inferSelect;

/**
 * Capital investment insert and select types.
 */
export type InsertCapitalInvestment = z.infer<typeof insertCapitalInvestmentSchema>;
/**
 *
 */
export type CapitalInvestment = typeof capitalInvestments.$inferSelect;

// Relations - temporarily commented out due to drizzle-orm version compatibility
// Removed moneyFlow relations
//   }),
//   residence: one(residences, {
//   (removed money flow relations)
//   }),
// }));

// export const billsRelations = relations(bills, ({ one, many }) => ({
//   building: one(buildings, {
//     fields: [bills.buildingId],
//     references: [buildings.id],
//   }),
//   createdBy: one(users, {
//     fields: [bills.createdBy],
//     references: [users.id],
//   }),
//   originalBill: one(bills, {
//     fields: [bills.reference],
//     references: [bills.id],
//     relationName: 'billReference'
//   }),
//   generatedBills: many(bills, {
//     relationName: 'billReference'
//   }),
//   (removed money flow relations),
// }));


// export const budgetsRelations = relations(budgets, ({ one }) => ({
//   building: one(buildings, {
//     fields: [budgets.buildingId],
//     references: [buildings.id],
//   }),
//   createdBy: one(users, {
//     fields: [budgets.createdBy],
//     references: [users.id],
//   }),
//   approvedBy: one(users, {
//     fields: [budgets.approvedBy],
//     references: [users.id],
//   }),
// }));

// export const monthlyBudgetsRelations = relations(monthlyBudgets, ({ one }) => ({
//   building: one(buildings, {
//     fields: [monthlyBudgets.buildingId],
//     references: [buildings.id],
//   }),
//   approvedBy: one(users, {
//     fields: [monthlyBudgets.approvedBy],
//     references: [users.id],
//   }),
//   originalBudget: one(monthlyBudgets, {
//     fields: [monthlyBudgets.originalBudgetId],
//     references: [monthlyBudgets.id],
//     relationName: 'budgetCopy'
//   }),
// }));
