import {
  WRITE_METHODS,
  isExemptPath,
  type DiscoveredRoute,
  type RouteManifest,
} from './scan-server-routes';

function routeKey(r: DiscoveredRoute): string {
  return `${r.method} ${r.path}`;
}

function isUnguardedWrite(r: DiscoveredRoute): boolean {
  return WRITE_METHODS.includes(r.method) && isExemptPath(r.path);
}

function formatRouteRow(r: DiscoveredRoute): string {
  return `| \`${r.method}\` | \`${r.path}\` | \`${r.file}\` |`;
}

function formatAddedRouteRow(r: DiscoveredRoute): string {
  const note = isUnguardedWrite(r) ? ':warning: unguarded write' : '';
  return `| \`${r.method}\` | \`${r.path}\` | \`${r.file}\` | ${note} |`;
}

export function buildReport(
  base: RouteManifest | null,
  current: RouteManifest,
  stale: boolean
): string {
  const baseRoutes = base?.routes ?? [];
  const baseKeys = new Set(baseRoutes.map(routeKey));
  const currentKeys = new Set(current.routes.map(routeKey));

  const added = current.routes.filter((r) => !baseKeys.has(routeKey(r)));
  const removed = baseRoutes.filter((r) => !currentKeys.has(routeKey(r)));

  const addedUnguardedWrites = added.filter(isUnguardedWrite);

  const lines: string[] = [];
  lines.push('## Route Security Manifest');
  lines.push('');

  if (stale) {
    lines.push(
      '> :warning: **Manifest is out of date.** Run `npx tsx scripts/generate-route-manifest.ts` ' +
        'and commit the updated `server/route-manifest.json`. The diff below reflects what the ' +
        'manifest *should* look like based on the current source.'
    );
    lines.push('');
  }

  if (!base) {
    lines.push('_No base manifest was available to diff against; showing totals only._');
    lines.push('');
  }

  lines.push('**Totals**');
  lines.push('');
  lines.push('| Metric | Base | PR | Δ |');
  lines.push('| --- | ---: | ---: | ---: |');
  const baseTotals = base?.totals ?? { allRoutes: 0, writeRoutes: 0, apiWriteRoutes: 0 };
  const currentUnguarded = current.routes.filter(isUnguardedWrite).length;
  const baseUnguarded = baseRoutes.filter(isUnguardedWrite).length;
  const delta = (a: number, b: number) => {
    const d = b - a;
    if (d === 0) return '0';
    return d > 0 ? `+${d}` : `${d}`;
  };
  lines.push(
    `| All routes | ${baseTotals.allRoutes} | ${current.totals.allRoutes} | ${delta(
      baseTotals.allRoutes,
      current.totals.allRoutes
    )} |`
  );
  lines.push(
    `| Write routes | ${baseTotals.writeRoutes} | ${current.totals.writeRoutes} | ${delta(
      baseTotals.writeRoutes,
      current.totals.writeRoutes
    )} |`
  );
  lines.push(
    `| Demo-guarded writes (\`/api/*\`) | ${baseTotals.apiWriteRoutes} | ${current.totals.apiWriteRoutes} | ${delta(
      baseTotals.apiWriteRoutes,
      current.totals.apiWriteRoutes
    )} |`
  );
  lines.push(
    `| Unguarded writes (exempt or non-\`/api\`) | ${baseUnguarded} | ${currentUnguarded} | ${delta(
      baseUnguarded,
      currentUnguarded
    )} |`
  );
  lines.push('');

  if (addedUnguardedWrites.length > 0) {
    lines.push(
      `### :rotating_light: ${addedUnguardedWrites.length} new write route(s) missing the demo-mode guard`
    );
    lines.push('');
    lines.push(
      'These routes use a write method (`POST`/`PUT`/`PATCH`/`DELETE`) but do **not** sit ' +
        'behind the `/api/*` global demo-security middleware. Confirm this is intentional, or ' +
        'move the route under `/api/*` / remove it from the exempt list in ' +
        '`scripts/lib/scan-server-routes.ts`.'
    );
    lines.push('');
    lines.push('| Method | Path | File | Reason |');
    lines.push('| --- | --- | --- | --- |');
    for (const r of addedUnguardedWrites) {
      const reason = r.path.startsWith('/api')
        ? 'exempt path'
        : 'not under `/api`';
      lines.push(`| \`${r.method}\` | \`${r.path}\` | \`${r.file}\` | ${reason} |`);
    }
    lines.push('');
  }

  if (added.length > 0) {
    lines.push(`### :heavy_plus_sign: Added routes (${added.length})`);
    lines.push('');
    lines.push('| Method | Path | File | Note |');
    lines.push('| --- | --- | --- | --- |');
    for (const r of added) {
      lines.push(formatAddedRouteRow(r));
    }
    lines.push('');
  }

  if (removed.length > 0) {
    lines.push(`### :heavy_minus_sign: Removed routes (${removed.length})`);
    lines.push('');
    lines.push('| Method | Path | File |');
    lines.push('| --- | --- | --- |');
    for (const r of removed) {
      lines.push(formatRouteRow(r));
    }
    lines.push('');
  }

  if (added.length === 0 && removed.length === 0 && !stale) {
    lines.push('_No route changes detected._');
    lines.push('');
  }

  lines.push(
    '<sub>Generated by `scripts/diff-route-manifest.ts`. ' +
      '"Unguarded" means the route bypasses the `/api/*` demo-security middleware — either ' +
      'because it is not under `/api`, or because it appears in the exempt list ' +
      '(auth, MCP, `/api/test`, trial-requests).</sub>'
  );

  return lines.join('\n') + '\n';
}
