export interface BudgetProps {
  organizationId?: string;
  buildingId?: string;
  buildingName?: string;
}

export interface PunctualRevenueGrowth {
  id: string;
  year: number;
  month: number;
  percentage: number;
  inflationIncluded: boolean;
}

export interface BankAccountSettings {
  bankAccountStartAmount?: number;
  bankAccountStartDate?: string;
  bankAccountMinimums?: number;
  generalInflationRate?: number;
  financialYearStart?: string;
  emergencyFundMinimum?: number;
  operatingCashMinimum?: number;
  revenueGrowthRate?: number;
  costInflationRate?: number;
  utilityInflationRate?: number;
  maintenanceInflationRate?: number;
  specialInvestmentBudget?: number;
  investmentHorizonYears?: number;
  capitalProjectReserve?: number;
  useGlobalBillsInflation?: boolean;
  globalBillsInflationRate?: number;
  unplannedBillsAmount?: number;
  unplannedBillsStartDate?: string;
  historicalUniqueBillsAmount?: number;
  historicalUniqueBillsConfidence?: string;
  historicalUniqueBillsYearsAnalyzed?: number;
  categoryInflationRates?: {
    utilities?: number;
    maintenance?: number;
    general?: number;
    other?: number;
  };
  customBankFields?: { [fieldName: string]: number };
  punctualRevenueGrowth?: PunctualRevenueGrowth[];
}

export interface BankAccountData {
  bankAccountStartAmount?: string;
  bankAccountStartDate?: string;
  bankAccountMinimums?: string;
  generalInflationRate?: string;
  bankAccountUpdatedAt?: string;
}

export interface ForecastData {
  year: number;
  month: number;
  period?: string;
  revenue: number;
  spending: number;
  netCashFlow: number;
  balance: number;
  capitalInvestment: number;
  autoGeneratedInvestment?: number;
  balanceBeforeScenario?: number;
  projectCosts?: number;
  startingBalance?: number;
  status: 'red' | 'yellow' | 'green';
  inflatedIncome: number;
  inflatedRecurringExpenses: number;
  inflatedUnplannedBills: number;
}

export interface BudgetForecastResponse {
  buildingId: string;
  buildingName: string;
  forecastPeriod: string;
  startingBalance: number;
  effectiveStartYear?: number;
  effectiveStartMonth?: number;
  effectiveStartDay?: number;
  effectiveStartDate?: string;
  effectiveStartingBalance?: number;
  hasBankAccountStartDate?: boolean;
  minimumFund: number;
  generalInflationRate: number;
  revenueInflationRate: number;
  baselineMonthlyIncome: number;
  baselineMonthlyExpenses: number;
  recurrentBillsCount: number;
  uniqueBillsCount: number;
  forecast: ForecastData[];
}

export interface BudgetFilters {
  viewType: 'month' | 'year';
  periodLength: number;
  startMonth?: number;
  startYear?: number;
  dataVisibility: {
    revenue: boolean;
    spending: boolean;
    balanceStart: boolean;
    balanceEnd: boolean;
    netCashFlow: boolean;
    capitalInvestments: boolean;
    minimumRequirement: boolean;
    project: boolean;
  };
}

export interface CustomRevenueLine {
  id: string;
  description: string;
  monthlyAmount: number;
}

export interface CustomBankAccountField {
  id: string;
  fieldName: string;
  fieldValue: number;
}

export interface RevenueData {
  residenceRevenue: number;
  customRevenueLines: CustomRevenueLine[];
  totalRevenue: number;
}

export interface CapitalInvestment {
  id: string;
  title: string;
  description?: string;
  amount: number;
  targetDate: string;
  urgency: 'not_urgent' | 'urgent' | 'suggested';
  type: 'auto_generated' | 'custom';
  ownershipType: 'residences' | 'owner';
  category?: string;
  createdAt?: string;
}

export interface InvestmentFilters {
  urgency?: 'not_urgent' | 'urgent' | 'suggested' | 'all';
}

export interface InvestmentSummary {
  totalAmount: number;
  urgentAmount: number;
  suggestedAmount: number;
  notUrgentAmount: number;
  count: number;
  urgentCount: number;
  suggestedCount: number;
  notUrgentCount: number;
}

export interface Project {
  id: string;
  title: string;
  totalBudget: number;
  actualCost: number;
  financialYear: number;
  status: string;
  type: string;
  origin: string;
  isQuickProject: boolean;
  plannedStartDate?: string;
  plannedEndDate?: string;
  actualStartDate?: string;
  actualEndDate?: string;
  estimatedCost?: number;
  includeInBudget: boolean;
}

export interface ChartDataPoint {
  month: string;
  balanceStart: number | null;
  balanceEnd: number | null;
  status: string;
  revenue: number | null;
  spending: number | null;
  netCashFlow: number | null;
  capitalInvestments: number | null;
  urgentInvestments: number | null;
  suggestedInvestments: number | null;
  notUrgentInvestments: number | null;
  projects: number | null;
  isFuture: boolean;
}
