/**
 * Consolidated Financial Service
 * 
 * Consolidates all financial-related services into a single, optimized service:
 * - Bill generation and management
 * - Payment generation and processing  
 * - Project payment plans
 * - Budget calculations and management
 * - Financial automation and caching
 * 
 * Replaces:
 * - bill-generation-service.ts
 * - payment-generation-service.ts
 * - project-payment-service.ts
 * - monthly-budget-service.ts
 * - dynamic-financial-calculator.ts
 * - financial-automation-service.ts
 * - delayed-update-service.ts
 */

import { db } from '../db';
import { eq, and, gte, lte, sql, not, inArray, or, isNull } from 'drizzle-orm';
import { v4 as uuidv4 } from 'uuid';
import { BaseService } from './_base/base-service';
import type { 
  Bill, 
  InsertPayment, 
  InsertMonthlyBudget, 
  Building, 
  Residence,
  FinancialPeriodData,
  FinancialCacheEntry,
  DrizzleTransaction,
  DatabaseContext
} from '@shared/schema';
import * as schema from '@shared/schema';

const { bills, payments, monthlyBudgets, buildings, residences, submissionVendors } = schema;

interface PaymentPlan {
  costs: number[];
  schedule: 'weekly' | 'monthly' | 'quarterly' | 'yearly' | 'custom';
  customDates?: string[];
  startDate: string;
  totalAmount: number;
}

interface FinancialStats {
  activeBills: number;
  totalMonthlyRevenue: number;
  totalMonthlyExpenses: number;
  cashFlow: number;
  budgetVariance: number;
}

export class ConsolidatedFinancialService extends BaseService {
  private readonly CACHE_DURATION_HOURS = 24;
  private readonly MAX_CACHE_ENTRIES = 1000;
  private readonly YEARS_TO_PROJECT = 3;

  // Delayed update tracking
  private readonly DELAY_MINUTES = 15;
  private readonly DELAY_MS = this.DELAY_MINUTES * 60 * 1000;
  private pendingBillUpdates = new Set<string>();
  private pendingResidenceUpdates = new Set<string>();
  private pendingBuildingBudgetUpdates = new Set<string>();

  constructor() {
    super('ConsolidatedFinancialService');
  }

  // ====================
  // BILL GENERATION
  // ====================

  /**
   * Create an auto-generated bill from template and persist it to database
   */
  async createAutoGeneratedBill(
    templateBill: Bill, 
    newBillData: Partial<Bill>, 
    suggestedDate?: Date
  ): Promise<Bill> {
    return this.executeWithErrorHandling('createAutoGeneratedBill', async () => {
      if (templateBill.paymentType !== 'recurrent') {
        throw new Error('Can only create auto-generated bills from recurrent bills');
      }

      const startDate = suggestedDate || new Date();
      const uniqueBillNumber = await this.generateUniqueBillNumber(templateBill.category, startDate);
      
      const newBillData_prepared = {
        ...templateBill,
        ...newBillData,
        billNumber: uniqueBillNumber,
        paymentType: 'unique' as const,
        // NEW: Set payment structure fields for single payment
        paymentCount: '1' as const,
        recurrence: false,
        singlePaymentAmount: templateBill.totalAmount,
        // Clear multi-payment configuration
        hasInitialPayment: false,
        recurringPaymentsEqual: true,
        initialPaymentAmount: '',
        recurringPaymentAmount: '',
        customPayments: [],
        startDate: startDate.toISOString().split('T')[0],
        endDate: newBillData.endDate || templateBill.endDate,
        status: 'draft' as const,
        isAutoGenerated: false,
        sourceTemplateId: templateBill.sourceTemplateId,
        autoGeneratedLabel: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      // Remove the id field as it will be auto-generated on insert
      delete (newBillData_prepared as any).id;

      // Insert the bill into the database
      const insertedBills = await db.insert(bills).values(newBillData_prepared).returning();
      
      if (!insertedBills || insertedBills.length === 0) {
        throw new Error('Failed to insert auto-generated bill into database');
      }

      const insertedBill = insertedBills[0];
      // console.log(`✅ Created and persisted auto-generated bill: ${insertedBill.id} (${insertedBill.billNumber})`);

      // Generate payments for the newly created bill
      await this.generatePaymentsForBill(insertedBill.id);

      // Update source bill end date to prevent double counting
      if (templateBill.sourceTemplateId) {
        await this.updateSourceBillEndDate(templateBill.sourceTemplateId, startDate);
      }

      return insertedBill;
    });
  }

  /**
   * Generate unique bill number using timestamp + UUID approach
   */
  private async generateUniqueBillNumber(category: string, date: Date): Promise<string> {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    const categoryCode = category.toUpperCase().replace(/[^A-Z]/g, '').substring(0, 4);
    
    const timestamp = Date.now();
    const timestampStr = timestamp.toString(36).toUpperCase();
    
    return `${categoryCode}-${year}${month}${day}-${timestampStr}`;
  }

  private async updateSourceBillEndDate(sourceTemplateId: string, startDate: Date): Promise<void> {
    const endDate = new Date(startDate);
    endDate.setDate(endDate.getDate() - 1);
    
    await db
      .update(bills)
      .set({
        endDate: endDate.toISOString().split('T')[0],
        updatedAt: new Date()
      })
      .where(eq(bills.id, sourceTemplateId));
  }

  // ====================
  // PAYMENT GENERATION
  // ====================

  /**
   * Generate payments for a newly created bill
   */
  async generatePaymentsForBill(billId: string, tx?: DrizzleTransaction): Promise<void> {
    return this.executeWithErrorHandling('generatePaymentsForBill', async () => {
      const dbContext: DatabaseContext = tx || db;
      
      const bill = await dbContext.select().from(bills).where(eq(bills.id, billId)).limit(1);
      
      if (!bill || bill.length === 0) {
        throw new Error(`Bill with ID ${billId} not found`);
      }

      const billData = bill[0];
      const paymentsToInsert: InsertPayment[] = [];

      switch (billData.paymentType) {
        case 'unique':
          paymentsToInsert.push({
            billId,
            paymentNumber: 1,
            scheduledDate: billData.startDate,
            amount: billData.totalAmount.toString(),
            status: 'pending',
          });
          break;

        case 'recurrent':
        case 'auto-generated':
          const generatedPayments = this.generateRecurrentPayments(billData);
          paymentsToInsert.push(...generatedPayments);
          break;

        default:
          throw new Error(`Unsupported payment type: ${billData.paymentType}`);
      }

      if (paymentsToInsert.length > 0) {
        await dbContext.insert(payments).values(paymentsToInsert);
        // console.log(`✅ Generated ${paymentsToInsert.length} payments for bill ${billId}`);
      }
    });
  }

  /**
   * Generate recurrent payments based on bill schedule
   * OPTIMIZED: Simplified logic and extracted helper functions
   */
  private generateRecurrentPayments(bill: Bill): InsertPayment[] {
    const paymentDates = this.calculatePaymentDates(bill);
    
    return paymentDates.map((date, index) => ({
      billId: bill.id,
      paymentNumber: index + 1,
      scheduledDate: date.toISOString().split('T')[0],
      amount: bill.totalAmount.toString(),
      status: 'pending',
    }));
  }

  /**
   * OPTIMIZATION: Extracted payment date calculation logic
   */
  private calculatePaymentDates(bill: Bill): Date[] {
    const startDate = new Date(bill.startDate);
    const endDate = bill.endDate ? new Date(bill.endDate) : new Date(startDate.getFullYear() + 1, startDate.getMonth(), startDate.getDate());
    const dates: Date[] = [];
    
    const incrementMonths = this.getScheduleIncrement(bill.schedulePayment);
    if (incrementMonths === 0) return [startDate]; // Invalid schedule, return single payment
    
    let currentDate = new Date(startDate);
    let paymentCount = 0;
    const maxPayments = 1000; // Safety limit
    
    while (currentDate <= endDate && paymentCount < maxPayments) {
      dates.push(new Date(currentDate));
      
      if (incrementMonths > 0) {
        currentDate.setMonth(currentDate.getMonth() + incrementMonths);
      } else {
        currentDate.setFullYear(currentDate.getFullYear() + 1);
      }
      
      paymentCount++;
    }
    
    return dates;
  }

  /**
   * OPTIMIZATION: Extracted schedule increment calculation
   */
  private getScheduleIncrement(schedule: string): number {
    switch (schedule) {
      case 'monthly': return 1;
      case 'quarterly': return 3;
      case 'yearly': return -1; // Special case handled in calculatePaymentDates
      default: return 0; // Invalid schedule
    }
  }

  /**
   * Update payments when a bill is edited - prevents duplicates by clearing unpaid payments
   */
  async updatePaymentsForBill(billId: string, tx?: DrizzleTransaction): Promise<void> {
    return this.executeWithErrorHandling('updatePaymentsForBill', async () => {
      const dbContext: DatabaseContext = tx || db;
      
      // Get the updated bill details
      const bill = await dbContext.select().from(bills).where(eq(bills.id, billId)).limit(1);
      
      if (!bill || bill.length === 0) {
        throw new Error(`Bill with ID ${billId} not found`);
      }

      const billData = bill[0];

      // Get all existing payments for this bill
      const existingPayments = await dbContext.select().from(payments)
        .where(eq(payments.billId, billId));

      // Find the last paid payment to determine where to continue the sequence
      const paidPayments = existingPayments.filter(p => p.status === 'paid');
      const lastPaidPayment = paidPayments.length > 0 
        ? paidPayments[paidPayments.length - 1] 
        : null;

      // Delete all unpaid payments (pending + overdue) to regenerate with updated amounts
      // Only preserve payments that have already been paid
      await dbContext.delete(payments).where(
        and(
          eq(payments.billId, billId),
          not(eq(payments.status, 'paid'))
        )
      );

      // console.log(`🗑️ Cleared unpaid payments for bill ${billId} to prevent duplicates`);

      // Regenerate payments starting from where paid payments left off
      if (billData.paymentType === 'unique') {
        // For unique payments, only regenerate if no payments have been made
        if (!lastPaidPayment) {
          const paymentsToInsert: InsertPayment[] = [{
            billId,
            paymentNumber: 1,
            scheduledDate: billData.startDate,
            amount: billData.totalAmount.toString(),
            status: 'pending',
          }];
          await dbContext.insert(payments).values(paymentsToInsert);
        }
      } else {
        // For recurrent payments, continue from where paid payments left off
        const startingPaymentNumber = lastPaidPayment ? lastPaidPayment.paymentNumber + 1 : 1;
        const startingDate = lastPaidPayment ? this.calculateNextPaymentDate(lastPaidPayment.scheduledDate, billData.schedulePayment) : billData.startDate;
        
        const generatedPayments = this.generateRecurrentPaymentsAdvanced(
          billData, 
          startingPaymentNumber, 
          startingDate
        );
        
        if (generatedPayments.length > 0) {
          await dbContext.insert(payments).values(generatedPayments);
        }
      }
      
      // console.log(`✅ Updated payments for bill ${billId} without duplicates`);
    });
  }

  /**
   * Completely regenerate payment schedule for recurrent bills - deletes ALL payments
   */
  async regenerateCompletePaymentSchedule(billId: string, tx?: DrizzleTransaction): Promise<{ deletedCount: number; createdCount: number }> {
    return this.executeWithErrorHandling('regenerateCompletePaymentSchedule', async () => {
      const dbContext: DatabaseContext = tx || db;
      
      // Get the bill details
      const bill = await dbContext.select().from(bills).where(eq(bills.id, billId)).limit(1);
      
      if (!bill || bill.length === 0) {
        throw new Error(`Bill with ID ${billId} not found`);
      }

      const billData = bill[0];

      // Get count of existing payments for logging
      const existingPayments = await dbContext.select().from(payments).where(eq(payments.billId, billId));
      const deletedCount = existingPayments.length;

      // Delete ALL existing payments (including paid ones)
      await dbContext.delete(payments).where(eq(payments.billId, billId));
      // console.log(`🗑️ Deleted ${deletedCount} existing payments for bill ${billId} (including paid payments)`);

      // Regenerate the complete payment schedule from scratch
      const paymentsToInsert: InsertPayment[] = [];

      switch (billData.paymentType) {
        case 'unique':
          // Single payment for unique bills
          paymentsToInsert.push({
            billId,
            paymentNumber: 1,
            scheduledDate: billData.startDate,
            amount: billData.totalAmount.toString(),
            status: 'pending',
          });
          break;

        case 'recurrent':
        case 'auto-generated':
          // Generate complete payment schedule from the beginning
          const generatedPayments = this.generateRecurrentPayments(billData);
          paymentsToInsert.push(...generatedPayments);
          break;

        default:
          throw new Error(`Unsupported payment type: ${billData.paymentType}`);
      }

      // Insert all new payments
      if (paymentsToInsert.length > 0) {
        await dbContext.insert(payments).values(paymentsToInsert);
        // console.log(`✅ Generated ${paymentsToInsert.length} new payments for bill ${billId} (complete regeneration)`);
      }

      return {
        deletedCount,
        createdCount: paymentsToInsert.length
      };
    });
  }

  /**
   * Update associated payments when bill status changes
   */
  async updatePaymentStatusFromBillStatus(billId: string, billStatus: 'draft' | 'sent' | 'overdue' | 'paid' | 'cancelled', tx?: DrizzleTransaction): Promise<void> {
    return this.executeWithErrorHandling('updatePaymentStatusFromBillStatus', async () => {
      const dbContext: DatabaseContext = tx || db;
      
      const billPayments = await dbContext.select().from(payments).where(eq(payments.billId, billId));
      
      if (billPayments.length === 0) {
        // console.log(`⚠️ No payments found for bill ${billId}`);
        return;
      }

      switch (billStatus) {
        case 'draft':
          // Set all payments to pending
          await dbContext.update(payments)
            .set({ status: 'pending', paidDate: null })
            .where(eq(payments.billId, billId));
          // console.log(`✅ Set all payments for bill ${billId} to pending (draft status)`);
          break;

        case 'sent':
          // Payments become active - keep as pending but ready for processing
          await dbContext.update(payments)
            .set({ status: 'pending' })
            .where(
              and(
                eq(payments.billId, billId),
                not(eq(payments.status, 'paid')),
                not(eq(payments.status, 'cancelled'))
              )
            );
          // console.log(`✅ Activated payments for bill ${billId} (sent status)`);
          break;

        case 'paid':
          // Mark all payments as paid with current date
          const currentDate = new Date().toISOString();
          await dbContext.update(payments)
            .set({ status: 'paid', paidDate: currentDate })
            .where(eq(payments.billId, billId));
          // console.log(`✅ Marked all payments for bill ${billId} as paid`);
          break;

        case 'cancelled':
          // Cancel all pending payments (keep already paid ones as paid)
          await dbContext.update(payments)
            .set({ status: 'cancelled' })
            .where(
              and(
                eq(payments.billId, billId),
                sql`${payments.status} IN ('pending', 'overdue')`
              )
            );
          // console.log(`✅ Cancelled pending payments for bill ${billId}`);
          break;

        case 'overdue':
          // Update overdue payments based on their due dates
          const today = new Date().toISOString().split('T')[0];
          await dbContext.update(payments)
            .set({ status: 'overdue' })
            .where(
              and(
                eq(payments.billId, billId),
                eq(payments.status, 'pending'),
                sql`${payments.scheduledDate} < ${today}`
              )
            );
          // console.log(`✅ Updated overdue payments for bill ${billId}`);
          break;

        default:
          // console.log(`⚠️ Unknown bill status: ${billStatus}`);
      }
    });
  }

  /**
   * Generate payment schedule for recurrent bills with advanced options
   */
  private generateRecurrentPaymentsAdvanced(
    bill: Bill, 
    startingPaymentNumber: number = 1, 
    startingDate: string = bill.startDate
  ): InsertPayment[] {
    const payments: InsertPayment[] = [];
    const startDate = new Date(startingDate);
    const endDate = bill.endDate ? new Date(bill.endDate) : null;
    
    // Default to 12 months if no end date specified
    const maxPayments = 12;
    let paymentNumber = startingPaymentNumber;

    if (bill.schedulePayment === 'custom' && bill.scheduleCustom && bill.scheduleCustom.length > 0) {
      // Custom schedule - start from the appropriate index
      const startIndex = startingPaymentNumber - 1;
      
      for (let i = startIndex; i < bill.scheduleCustom.length; i++) {
        const dateStr = bill.scheduleCustom[i];
        payments.push({
          billId: bill.id,
          paymentNumber: i + 1,
          scheduledDate: dateStr,
          amount: bill.costs[i] ? bill.costs[i].toString() : (parseFloat(bill.totalAmount.toString()) / bill.scheduleCustom.length).toString(),
          status: 'pending',
        });
      }
    } else {
      // Standard schedule (weekly, monthly, quarterly, yearly)
      let currentDate = new Date(startDate);
      
      while (paymentNumber <= maxPayments && (!endDate || currentDate <= endDate)) {
        payments.push({
          billId: bill.id,
          paymentNumber,
          scheduledDate: currentDate.toISOString().split('T')[0],
          amount: bill.costs[paymentNumber - 1] ? bill.costs[paymentNumber - 1].toString() : (parseFloat(bill.totalAmount.toString()) / maxPayments).toString(),
          status: 'pending',
        });

        // Calculate next payment date
        switch (bill.schedulePayment) {
          case 'weekly':
            currentDate.setDate(currentDate.getDate() + 7);
            break;
          case 'monthly':
            currentDate.setMonth(currentDate.getMonth() + 1);
            break;
          case 'quarterly':
            currentDate.setMonth(currentDate.getMonth() + 3);
            break;
          case 'yearly':
            currentDate.setFullYear(currentDate.getFullYear() + 1);
            break;
          default:
            // Default to monthly if schedule not specified
            currentDate.setMonth(currentDate.getMonth() + 1);
        }

        paymentNumber++;
      }
    }

    return payments;
  }

  /**
   * Calculate the next payment date based on the schedule
   */
  private calculateNextPaymentDate(lastDate: string, schedule: string): string {
    const date = new Date(lastDate);
    
    switch (schedule) {
      case 'weekly':
        date.setDate(date.getDate() + 7);
        break;
      case 'monthly':
        date.setMonth(date.getMonth() + 1);
        break;
      case 'quarterly':
        date.setMonth(date.getMonth() + 3);
        break;
      case 'yearly':
        date.setFullYear(date.getFullYear() + 1);
        break;
      default:
        // Default to monthly
        date.setMonth(date.getMonth() + 1);
    }
    
    return date.toISOString().split('T')[0];
  }

  // ====================
  // PROJECT PAYMENTS
  // ====================

  /**
   * Generate payment plan for selected vendor
   */
  async generatePaymentPlan(
    vendorId: string,
    totalCost: number,
    schedule: 'weekly' | 'monthly' | 'quarterly' | 'yearly' | 'custom',
    customDates?: Date[],
    startDate?: Date
  ): Promise<PaymentPlan> {
    return this.executeWithErrorHandling('generatePaymentPlan', async () => {
      this.validatePaymentPlanInputs(totalCost, schedule, customDates);

      const planStartDate = startDate || new Date();
      const paymentSchedule = this.calculatePaymentSchedule(totalCost, schedule, planStartDate, customDates);
      
      return {
        costs: paymentSchedule.amounts,
        schedule,
        customDates: schedule === 'custom' ? paymentSchedule.dates.map(d => d.toISOString().split('T')[0]) : undefined,
        startDate: planStartDate.toISOString().split('T')[0],
        totalAmount: totalCost
      };
    });
  }

  private validatePaymentPlanInputs(
    totalCost: number,
    schedule: string,
    customDates?: Date[]
  ): void {
    if (totalCost <= 0) {
      throw new Error('Total cost must be greater than 0');
    }

    if (schedule === 'custom' && (!customDates || customDates.length === 0)) {
      throw new Error('Custom schedule requires custom dates');
    }
  }

  private calculatePaymentSchedule(
    totalCost: number,
    schedule: string,
    startDate: Date,
    customDates?: Date[]
  ): { amounts: number[]; dates: Date[] } {
    if (schedule === 'custom' && customDates) {
      const amountPerPayment = totalCost / customDates.length;
      return {
        amounts: customDates.map(() => amountPerPayment),
        dates: customDates
      };
    }

    // Standard schedules
    const intervals = {
      weekly: 7,
      monthly: 30,
      quarterly: 90,
      yearly: 365
    };

    const interval = intervals[schedule as keyof typeof intervals] || 30;
    const numberOfPayments = schedule === 'yearly' ? 1 : Math.max(2, Math.ceil(365 / interval));
    const amountPerPayment = totalCost / numberOfPayments;

    const dates: Date[] = [];
    const amounts: number[] = [];

    for (let i = 0; i < numberOfPayments; i++) {
      const paymentDate = new Date(startDate);
      paymentDate.setDate(paymentDate.getDate() + (i * interval));
      dates.push(paymentDate);
      amounts.push(amountPerPayment);
    }

    return { amounts, dates };
  }

  // ====================
  // BUDGET MANAGEMENT
  // ====================

  /**
   * Populate monthly budget entries for all buildings
   */
  async populateAllMonthlyBudgets(): Promise<{ budgetsCreated: number; buildingsProcessed: number }> {
    return this.executeWithErrorHandling('populateAllMonthlyBudgets', async () => {
      let budgetsCreated = 0;
      let buildingsProcessed = 0;

      const activeBuildings = await db.select().from(buildings).where(eq(buildings.isActive, true));

      for (const building of activeBuildings) {
        try {
          const buildingBudgets = await this.populateBudgetsForBuilding(building);
          budgetsCreated += buildingBudgets;
          buildingsProcessed++;
          // console.log(`✅ Created ${buildingBudgets} budget entries for building: ${building.name}`);
        } catch (error: any) {
          // console.error(`❌ Error processing building ${building.name}:`, error);
        }
      }

      // console.log(`📊 Monthly budget population completed: ${buildingsProcessed} buildings, ${budgetsCreated} budgets`);

      return { budgetsCreated, buildingsProcessed };
    });
  }

  /**
   * Populate monthly budget entries for a specific building
   */
  async populateBudgetsForBuilding(building: Building): Promise<number> {
    let constructionDate: Date;
    if (building.constructionDate) {
      constructionDate = new Date(building.constructionDate);
    } else {
      constructionDate = new Date();
      constructionDate.setFullYear(constructionDate.getFullYear(), 0, 1);
    }

    const endDate = new Date();
    endDate.setFullYear(endDate.getFullYear() + this.YEARS_TO_PROJECT, 11, 31);

    const { incomeCategories, expenseCategories } = await this.getCategoriesForBuilding(building.id);

    // Remove existing budget entries to avoid duplicates
    await this.cleanupExistingBudgets(building.id);

    // Generate monthly entries
    const budgetEntries: InsertMonthlyBudget[] = [];
    const currentDate = new Date(constructionDate);

    while (currentDate <= endDate) {
      const monthKey = `${currentDate.getFullYear()}-${String(currentDate.getMonth() + 1).padStart(2, '0')}`;
      
      // Create entries for income categories
      for (const category of incomeCategories) {
        budgetEntries.push({
          buildingId: building.id,
          monthYear: monthKey,
          category: category,
          type: 'income',
          budgetedAmount: '0.00',
          actualAmount: '0.00',
          variance: '0.00',
          lastUpdated: new Date()
        });
      }

      // Create entries for expense categories
      for (const category of expenseCategories) {
        budgetEntries.push({
          buildingId: building.id,
          monthYear: monthKey,
          category: category,
          type: 'expense',
          budgetedAmount: '0.00',
          actualAmount: '0.00',
          variance: '0.00',
          lastUpdated: new Date()
        });
      }

      currentDate.setMonth(currentDate.getMonth() + 1);
    }

    if (budgetEntries.length > 0) {
      await db.insert(monthlyBudgets).values(budgetEntries);
    }

    return budgetEntries.length;
  }

  private async getCategoriesForBuilding(buildingId: string): Promise<{
    incomeCategories: string[];
    expenseCategories: string[];
  }> {
    // Default categories for Quebec property management
    return {
      incomeCategories: ['rent', 'parking', 'storage', 'laundry', 'other_income'],
      expenseCategories: [
        'maintenance', 'utilities', 'insurance', 'property_tax', 
        'management_fees', 'legal_professional', 'repairs', 'cleaning',
        'landscaping', 'security', 'administration', 'other_expenses'
      ]
    };
  }

  private async cleanupExistingBudgets(buildingId: string): Promise<void> {
    await db.delete(monthlyBudgets).where(eq(monthlyBudgets.buildingId, buildingId));
  }

  // ====================
  // FINANCIAL CALCULATIONS
  // ====================

  /**
   * Get financial data for a building with smart caching
   */
  async getFinancialData(
    buildingId: string,
    startDate: string,
    endDate: string,
    forceRefresh = false
  ): Promise<FinancialPeriodData> {
    return this.executeWithErrorHandling('getFinancialData', async () => {
      const cacheKey = this.generateCacheKey(startDate, endDate);

      if (!forceRefresh) {
        const cached = await this.getCachedData(buildingId, cacheKey, startDate, endDate);
        if (cached) {
          return cached;
        }
      }

      const financialData = await this.calculateFinancialData(buildingId, startDate, endDate);
      await this.cacheFinancialData(buildingId, cacheKey, startDate, endDate, financialData);

      return financialData;
    });
  }

  private async calculateFinancialData(
    buildingId: string,
    startDate: string,
    endDate: string
  ): Promise<FinancialPeriodData> {
    const activeBills = await db
      .select()
      .from(bills)
      .where(
        and(
          eq(bills.buildingId, buildingId),
          eq(bills.paymentType, 'recurrent'),
          sql`${bills.status} IN ('sent', 'draft')`
        )
      );

    const activeResidences = await db
      .select()
      .from(residences)
      .where(
        and(
          eq(residences.buildingId, buildingId),
          eq(residences.isActive, true),
          sql`${residences.monthlyFees} > 0`
        )
      );

    const monthlyData = this.generateMonthlyDataPoints(activeBills, activeResidences, startDate, endDate);
    const summary = this.calculateSummary(monthlyData);

    return {
      buildingId,
      startDate,
      endDate,
      monthlyData,
      summary,
    };
  }

  private generateMonthlyDataPoints(
    bills: Bill[],
    residences: Residence[],
    startDateStr: string,
    endDateStr: string
  ): FinancialPeriodData['monthlyData'] {
    const monthlyData: FinancialPeriodData['monthlyData'] = [];
    const startDate = new Date(startDateStr);
    const endDate = new Date(endDateStr);

    const currentDate = new Date(startDate);
    while (currentDate <= endDate) {
      const monthKey = `${currentDate.getFullYear()}-${String(currentDate.getMonth() + 1).padStart(2, '0')}`;
      
      // Calculate income from residences
      const monthlyIncome = residences.reduce((total, residence) => {
        return total + parseFloat(residence.monthlyFees?.toString() || '0');
      }, 0);

      // Calculate expenses from bills
      const monthlyExpenses = bills.reduce((total, bill) => {
        return total + parseFloat(bill.totalAmount?.toString() || '0');
      }, 0);

      monthlyData.push({
        month: monthKey,
        income: monthlyIncome,
        expenses: monthlyExpenses,
        netCashFlow: monthlyIncome - monthlyExpenses,
        occupancyRate: 95, // Default occupancy rate
        maintenanceCosts: monthlyExpenses * 0.3, // Estimate 30% for maintenance
      });

      currentDate.setMonth(currentDate.getMonth() + 1);
    }

    return monthlyData;
  }

  private calculateSummary(monthlyData: FinancialPeriodData['monthlyData']): FinancialPeriodData['summary'] {
    const totalIncome = monthlyData.reduce((sum, month) => sum + month.income, 0);
    const totalExpenses = monthlyData.reduce((sum, month) => sum + month.expenses, 0);
    const netCashFlow = totalIncome - totalExpenses;
    const averageOccupancy = monthlyData.reduce((sum, month) => sum + month.occupancyRate, 0) / monthlyData.length;

    return {
      totalIncome,
      totalExpenses,
      netCashFlow,
      averageOccupancy,
      profitMargin: totalIncome > 0 ? (netCashFlow / totalIncome) * 100 : 0,
    };
  }

  // ====================
  // CACHE MANAGEMENT
  // ====================

  private generateCacheKey(startDate: string, endDate: string): string {
    return `financial-${startDate}-${endDate}`;
  }

  private async getCachedData(
    buildingId: string,
    cacheKey: string,
    startDate: string,
    endDate: string
  ): Promise<FinancialPeriodData | null> {
    // Simplified cache implementation
    // In production, this would use a proper cache store
    return null;
  }

  private async cacheFinancialData(
    buildingId: string,
    cacheKey: string,
    startDate: string,
    endDate: string,
    data: FinancialPeriodData
  ): Promise<void> {
    // Simplified cache implementation
    // console.log(`💾 Cached financial data for building ${buildingId}: ${cacheKey}`);
  }

  /**
   * Invalidate cache when source data changes
   */
  async invalidateCache(buildingId: string, reason: string): Promise<void> {
    // console.log(`🗑️ Cache invalidated for building ${buildingId}: ${reason}`);
  }

  // ====================
  // DELAYED UPDATES
  // ====================

  /**
   * Schedule delayed financial update for a bill
   */
  scheduleBillUpdate(billId: string): void {
    if (this.pendingBillUpdates.has(billId)) {
      return;
    }

    this.pendingBillUpdates.add(billId);
    // console.log(`⏰ Scheduling financial update for bill ${billId} in ${this.DELAY_MINUTES} minutes`);

    setTimeout(async () => {
      try {
        await this.processBillUpdate(billId);
      } finally {
        this.pendingBillUpdates.delete(billId);
      }
    }, this.DELAY_MS);
  }

  /**
   * Schedule delayed financial update for a residence
   */
  scheduleResidenceUpdate(residenceId: string): void {
    if (this.pendingResidenceUpdates.has(residenceId)) {
      return;
    }

    this.pendingResidenceUpdates.add(residenceId);
    // console.log(`⏰ Scheduling financial update for residence ${residenceId} in ${this.DELAY_MINUTES} minutes`);

    setTimeout(async () => {
      try {
        await this.processResidenceUpdate(residenceId);
      } finally {
        this.pendingResidenceUpdates.delete(residenceId);
      }
    }, this.DELAY_MS);
  }

  private async processBillUpdate(billId: string): Promise<void> {
    const buildingId = await this.getBuildingIdFromBill(billId);
    if (buildingId) {
      await this.invalidateCache(buildingId, `Bill update: ${billId}`);
      await this.scheduleBudgetUpdate(buildingId);
    }
  }

  private async processResidenceUpdate(residenceId: string): Promise<void> {
    const buildingId = await this.getBuildingIdFromResidence(residenceId);
    if (buildingId) {
      await this.invalidateCache(buildingId, `Residence update: ${residenceId}`);
      await this.scheduleBudgetUpdate(buildingId);
    }
  }

  private async scheduleBudgetUpdate(buildingId: string): Promise<void> {
    if (this.pendingBuildingBudgetUpdates.has(buildingId)) {
      return;
    }

    this.pendingBuildingBudgetUpdates.add(buildingId);
    setTimeout(async () => {
      try {
        const building = await db.select().from(buildings).where(eq(buildings.id, buildingId)).limit(1);
        if (building.length > 0) {
          await this.populateBudgetsForBuilding(building[0]);
        }
      } finally {
        this.pendingBuildingBudgetUpdates.delete(buildingId);
      }
    }, this.DELAY_MS);
  }

  private async getBuildingIdFromBill(billId: string): Promise<string | null> {
    try {
      const result = await db
        .select({ buildingId: bills.buildingId })
        .from(bills)
        .where(eq(bills.id, billId))
        .limit(1);

      return result.length > 0 ? result[0].buildingId : null;
    } catch (error: any) {
      // console.error('❌ Error getting building ID from bill:', error);
      return null;
    }
  }

  private async getBuildingIdFromResidence(residenceId: string): Promise<string | null> {
    try {
      const result = await db
        .select({ buildingId: residences.buildingId })
        .from(residences)
        .where(eq(residences.id, residenceId))
        .limit(1);

      return result.length > 0 ? result[0].buildingId : null;
    } catch (error: any) {
      // console.error('❌ Error getting building ID from residence:', error);
      return null;
    }
  }

  // ====================
  // STATISTICS & REPORTING
  // ====================

  /**
   * Get financial statistics for dashboard
   */
  async getFinancialStatistics(): Promise<FinancialStats> {
    return this.executeWithErrorHandling('getFinancialStatistics', async () => {
      const activeBillsCount = await db
        .select({ count: sql<number>`count(*)` })
        .from(bills)
        .where(eq(bills.status, 'sent'));

      const monthlyRevenue = await db
        .select({ total: sql<number>`sum(${bills.totalAmount})` })
        .from(bills)
        .where(and(
          eq(bills.paymentType, 'recurrent'),
          eq(bills.status, 'sent')
        ));

      return {
        activeBills: activeBillsCount[0]?.count || 0,
        totalMonthlyRevenue: monthlyRevenue[0]?.total || 0,
        totalMonthlyExpenses: 0, // Calculate from expense bills
        cashFlow: 0, // Revenue - expenses
        budgetVariance: 0, // Budget vs actual variance
      };
    });
  }

  /**
   * Get delayed update status
   */
  getDelayedUpdateStatus(): {
    delayMinutes: number;
    pendingBillUpdates: number;
    pendingResidenceUpdates: number;
    pendingBudgetUpdates: number;
  } {
    return {
      delayMinutes: this.DELAY_MINUTES,
      pendingBillUpdates: this.pendingBillUpdates.size,
      pendingResidenceUpdates: this.pendingResidenceUpdates.size,
      pendingBudgetUpdates: this.pendingBuildingBudgetUpdates.size,
    };
  }
}

// Export singleton instance
export const financialService = new ConsolidatedFinancialService();

// Export backward compatibility aliases
export const billGenerationService = financialService;
export const paymentGenerationService = financialService;
export const projectPaymentService = financialService;
export const monthlyBudgetService = financialService;
export const dynamicFinancialCalculator = financialService;
export const financialAutomationService = financialService;
export const delayedUpdateService = financialService;