import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { apiRequest } from '@/lib/queryClient';
import { useLanguage } from '@/lib/i18n';
import { useToast } from '@/hooks/use-toast';
import type { Bill } from '@shared/schema';

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from './dialog';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from './form';
import { Input } from './input';
import { Textarea } from './textarea';
import { Button } from './button';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from './select';
import { Card, CardContent, CardHeader, CardTitle } from './card';
import { Badge } from './badge';
import { Bot } from 'lucide-react';

interface PrePopulatedBillFormProps {
  bill: Bill | null;
  isOpen: boolean;
  onClose: () => void;
  buildingId: string;
}

const billFormSchema = z.object({
  title: z.string().min(1, 'Title is required'),
  description: z.string().optional(),
  category: z.enum([
    'insurance',
    'maintenance',
    'salary',
    'utilities',
    'cleaning',
    'security',
    'landscaping',
    'professional_services',
    'administration',
    'repairs',
    'supplies',
    'taxes',
    'technology',
    'reserves',
    'other',
  ]),
  vendor: z.string().optional(),
  paymentType: z.enum(['unique', 'recurrent']),
  schedulePayment: z.enum(['weekly', 'monthly', 'quarterly', 'yearly', 'custom']).optional(),
  scheduleCustom: z.array(z.string()).optional(),
  costs: z.array(z.string()),
  totalAmount: z.string(),
  startDate: z.string(),
  endDate: z.string().optional(),
  status: z.enum(['draft', 'sent', 'overdue', 'paid', 'cancelled']),
  notes: z.string().optional(),
});

type BillFormData = z.infer<typeof billFormSchema>;

export function PrePopulatedBillForm({ bill, isOpen, onClose, buildingId }: PrePopulatedBillFormProps) {
  const { t } = useLanguage();
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [isSubmitting, setIsSubmitting] = useState(false);

  const form = useForm<BillFormData>({
    resolver: zodResolver(billFormSchema),
    defaultValues: bill ? {
      title: bill.title,
      description: bill.description || '',
      category: bill.category,
      vendor: bill.vendor || '',
      paymentType: 'unique', // Auto-generated bills become unique
      schedulePayment: undefined,
      scheduleCustom: undefined,
      costs: bill.costs || [],
      totalAmount: bill.totalAmount,
      startDate: bill.startDate,
      endDate: bill.endDate || '',
      status: 'draft',
      notes: `Based on auto-generated template: ${bill.autoGeneratedLabel || bill.title}`,
    } : {
      title: '',
      description: '',
      category: 'other',
      vendor: '',
      paymentType: 'unique',
      costs: [],
      totalAmount: '',
      startDate: '',
      endDate: '',
      status: 'draft',
      notes: '',
    },
  });

  const createBillMutation = useMutation({
    mutationFn: (data: BillFormData) =>
      apiRequest(`/api/bills`, {
        method: 'POST',
        body: { ...data, buildingId },
      }),
    onSuccess: () => {
      toast({
        title: t('success'),
        description: t('billCreatedSuccessfully'),
      });
      queryClient.invalidateQueries({ queryKey: ['/api/bills'] });
      onClose();
      form.reset();
    },
    onError: (error: any) => {
      toast({
        title: t('error'),
        description: error.message || t('billCreationFailed'),
        variant: 'destructive',
      });
    },
  });

  const onSubmit = async (data: BillFormData) => {
    setIsSubmitting(true);
    try {
      await createBillMutation.mutateAsync(data);
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!bill) return null;

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Bot className="h-5 w-5" />
            {t('createBillFromTemplate')}
          </DialogTitle>
        </DialogHeader>

        <Card className="mb-4">
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <Badge variant="secondary" className="gap-1">
                <Bot className="h-3 w-3" />
                {t('autoGenerated')}
              </Badge>
              {t('templateSource')}
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-0">
            <p className="text-sm text-muted-foreground">
              {bill.autoGeneratedLabel || bill.title}
            </p>
            {bill.description && (
              <p className="text-xs text-muted-foreground mt-1">
                {bill.description}
              </p>
            )}
          </CardContent>
        </Card>

        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <FormField
                control={form.control}
                name="title"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('title')}</FormLabel>
                    <FormControl>
                      <Input {...field} data-testid="input-bill-title" />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="category"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('category')}</FormLabel>
                    <Select onValueChange={field.onChange} defaultValue={field.value}>
                      <FormControl>
                        <SelectTrigger data-testid="select-bill-category">
                          <SelectValue placeholder={t('selectCategory')} />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        <SelectItem value="insurance">{t('insurance')}</SelectItem>
                        <SelectItem value="maintenance">{t('maintenance')}</SelectItem>
                        <SelectItem value="salary">{t('salary')}</SelectItem>
                        <SelectItem value="utilities">{t('utilities')}</SelectItem>
                        <SelectItem value="cleaning">{t('cleaning')}</SelectItem>
                        <SelectItem value="security">{t('security')}</SelectItem>
                        <SelectItem value="landscaping">{t('landscaping')}</SelectItem>
                        <SelectItem value="professional_services">{t('professionalServices')}</SelectItem>
                        <SelectItem value="administration">{t('administration')}</SelectItem>
                        <SelectItem value="repairs">{t('repairs')}</SelectItem>
                        <SelectItem value="supplies">{t('supplies')}</SelectItem>
                        <SelectItem value="taxes">{t('taxes')}</SelectItem>
                        <SelectItem value="technology">{t('technology')}</SelectItem>
                        <SelectItem value="reserves">{t('reserves')}</SelectItem>
                        <SelectItem value="other">{t('other')}</SelectItem>
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <FormField
              control={form.control}
              name="description"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>{t('description')} ({t('optional')})</FormLabel>
                  <FormControl>
                    <Textarea {...field} data-testid="textarea-bill-description" />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <FormField
                control={form.control}
                name="vendor"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('vendor')} ({t('optional')})</FormLabel>
                    <FormControl>
                      <Input {...field} data-testid="input-bill-vendor" />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="totalAmount"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('totalAmount')}</FormLabel>
                    <FormControl>
                      <Input 
                        {...field} 
                        type="number" 
                        step="0.01" 
                        data-testid="input-bill-amount" 
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <FormField
                control={form.control}
                name="startDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('startDate')}</FormLabel>
                    <FormControl>
                      <Input 
                        {...field} 
                        type="date" 
                        data-testid="input-bill-start-date" 
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="endDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('endDate')} ({t('optional')})</FormLabel>
                    <FormControl>
                      <Input 
                        {...field} 
                        type="date" 
                        data-testid="input-bill-end-date" 
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <FormField
              control={form.control}
              name="notes"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>{t('notes')} ({t('optional')})</FormLabel>
                  <FormControl>
                    <Textarea {...field} data-testid="textarea-bill-notes" />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <div className="flex justify-end gap-2 pt-4">
              <Button 
                type="button" 
                variant="outline" 
                onClick={onClose}
                data-testid="button-cancel"
              >
                {t('cancel')}
              </Button>
              <Button 
                type="submit" 
                disabled={isSubmitting || createBillMutation.isPending}
                data-testid="button-create-bill"
              >
                {isSubmitting || createBillMutation.isPending ? t('creating') : t('createBill')}
              </Button>
            </div>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}