import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useCreateUpdateMutation } from '@/lib/common-hooks';
import { apiRequest } from '@/lib/queryClient';
import { useLanguage } from '@/hooks/use-language';
import { useToast } from '@/hooks/use-toast';
import type { Bill } from '@shared/schema';
import type { UploadContext } from '@shared/config/upload-config';
import { BILL_CATEGORIES } from '@shared/schemas/financial';
import { CategorySelectField } from '@/components/common/CategorySelectField';
import { CurrencyInputField } from '@/components/common/CurrencyInputField';
import { StandardFormGrid } from '@/components/common/StandardFormGrid';
import { DocumentAttachmentSection, type PendingFile } from '@/components/common/DocumentAttachmentSection';

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from './dialog';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from './form';
import { Input } from './input';
import { Textarea } from './textarea';
import { Button } from './button';
import { Card, CardContent, CardHeader, CardTitle } from './card';
import { Badge } from './badge';
import { Bot } from 'lucide-react';

interface PrePopulatedBillFormProps {
  bill: Bill | null;
  isOpen: boolean;
  onClose: () => void;
  buildingId: string;
}

const billFormSchema = z.object({
  title: z.string().min(1, 'Title is required'),
  description: z.string().optional(),
  category: z.enum(BILL_CATEGORIES as unknown as [string, ...string[]]),
  vendor: z.string().optional(),
  paymentType: z.enum(['unique', 'recurrent', 'auto-generated']),
  schedulePayment: z.enum(['weekly', 'monthly', 'quarterly', 'yearly', 'custom']).optional(),
  scheduleCustom: z.array(z.string()).optional(),
  costs: z.array(z.string()),
  totalAmount: z.string(),
  startDate: z.string(),
  endDate: z.string().optional(),
  status: z.enum(['draft', 'sent', 'overdue', 'paid', 'cancelled']),
  notes: z.string().optional(),
});

type BillFormData = z.infer<typeof billFormSchema>;

export function PrePopulatedBillForm({ bill, isOpen, onClose, buildingId }: PrePopulatedBillFormProps) {
  const { t, language } = useLanguage();
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [pendingFiles, setPendingFiles] = useState<PendingFile[]>([]);

  const uploadContext: UploadContext = {
    type: 'bills',
    organizationId: 'default',
    buildingId,
    userRole: 'admin',
    userId: 'current-user'
  };

  const templateData = (bill as any)?.templateData;
  const sourceInfo = (bill as any)?.sourceInfo;

  const form = useForm<BillFormData>({
    resolver: zodResolver(billFormSchema),
    defaultValues: templateData ? {
      title: templateData.title,
      description: templateData.description || '',
      category: templateData.category,
      vendor: templateData.vendor || '',
      paymentType: templateData.paymentType || 'unique',
      schedulePayment: templateData.schedulePayment,
      scheduleCustom: templateData.scheduleCustom || [],
      costs: Array.isArray(templateData.totalAmount) ? templateData.totalAmount : [templateData.totalAmount.toString()],
      totalAmount: templateData.totalAmount.toString(),
      startDate: templateData.startDate,
      endDate: templateData.endDate || '',
      status: templateData.status || 'draft',
      notes: templateData.notes || '',
    } : bill ? {
      title: bill.title,
      description: bill.description || '',
      category: bill.category,
      vendor: bill.vendor || '',
      paymentType: 'unique',
      schedulePayment: undefined,
      scheduleCustom: undefined,
      costs: bill.costs || [],
      totalAmount: bill.totalAmount.toString(),
      startDate: bill.startDate,
      endDate: bill.endDate || '',
      status: 'draft',
      notes: `Based on auto-generated template: ${bill.autoGeneratedLabel || bill.title}`,
    } : {
      title: '',
      description: '',
      category: 'other',
      vendor: '',
      paymentType: 'unique',
      costs: [],
      totalAmount: '',
      startDate: '',
      endDate: '',
      status: 'draft',
      notes: '',
    },
  });

  const handleFileAdd = (file: File) => {
    const fileId = `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
    setPendingFiles(prev => [...prev, { id: fileId, file, name: file.name }]);
  };

  const handleFileRemove = (fileId: string) => {
    setPendingFiles(prev => prev.filter(f => f.id !== fileId));
  };

  const uploadDocumentsToBill = async (billId: string, billTitle: string) => {
    for (const pendingFile of pendingFiles) {
      try {
        const formData = new FormData();
        formData.append('file', pendingFile.file);
        formData.append('name', pendingFile.name);
        formData.append('description', `Document attached to bill: ${billTitle}`);
        formData.append('documentType', 'financial');
        formData.append('buildingId', buildingId);
        formData.append('attachedToType', 'bill');
        formData.append('attachedToId', billId);

        const response = await fetch('/api/documents/upload', {
          method: 'POST',
          credentials: 'include',
          body: formData,
        });

        if (!response.ok) {
          console.error('Failed to upload document:', pendingFile.name);
        }
      } catch (error) {
        console.error('Error uploading document:', pendingFile.name, error);
      }
    }
  };

  const createBillMutation = useCreateUpdateMutation<any, BillFormData>({
    mutationFn: async (data: BillFormData) => {
      const response = await fetch('/api/bills/from-template', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ ...data, buildingId }),
      });
      
      if (!response.ok) {
        throw new Error('Failed to create bill from template');
      }
      
      return response.json();
    },
    successTitle: t('success'),
    successMessage: language === 'fr' ? 'Facture créée avec succès à partir du modèle' : 'Bill created successfully from template',
    errorTitle: t('error'),
    errorMessage: (error: any) => error?.message || 'Failed to create bill from template',
    queryKeysToInvalidate: [['/api/bills']],
    onSuccessCallback: async (result) => {
      if (pendingFiles.length > 0 && result?.id) {
        await uploadDocumentsToBill(result.id, form.getValues('title'));
      }
      queryClient.invalidateQueries({ queryKey: ['/api/documents'] });
      setPendingFiles([]);
      onClose();
      form.reset();
    },
  });

  const onSubmit = async (data: BillFormData) => {
    setIsSubmitting(true);
    try {
      await createBillMutation.mutateAsync(data);
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!bill) return null;

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Bot className="h-5 w-5" />
            Create Bill from Template
          </DialogTitle>
        </DialogHeader>

        <Card className="mb-4 border-blue-200 bg-blue-50/50 dark:border-blue-800 dark:bg-blue-950/20">
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium flex items-center gap-2">
              <Badge className="gap-1 border-blue-200 bg-blue-100 text-blue-700 dark:border-blue-800 dark:bg-blue-950 dark:text-blue-300">
                <Bot className="h-3 w-3" />
                Auto-Generated Template
              </Badge>
              Source Information
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-0 space-y-2">
            <div className="flex items-center gap-2">
              <span className="text-xs font-medium text-blue-700 dark:text-blue-300">Template:</span>
              <span className="text-sm font-medium">
                {sourceInfo?.title || bill.autoGeneratedLabel || bill.title}
              </span>
            </div>
            {sourceInfo && (
              <>
                <div className="flex items-center gap-2">
                  <span className="text-xs font-medium text-blue-700 dark:text-blue-300">Source Type:</span>
                  <Badge variant="secondary" className="text-xs">
                    {sourceInfo.isAutoGenerated ? 'Auto-Generated' : 'Recurrent Template'}
                  </Badge>
                </div>
                {sourceInfo.autoGeneratedLabel && (
                  <div className="flex items-start gap-2">
                    <span className="text-xs font-medium text-blue-700 dark:text-blue-300">Generated From:</span>
                    <span className="text-xs text-muted-foreground">{sourceInfo.autoGeneratedLabel}</span>
                  </div>
                )}
              </>
            )}
            {templateData?.isFromTemplate && templateData.sourceTemplateId && (
              <div className="flex items-center gap-2">
                <span className="text-xs font-medium text-blue-700 dark:text-blue-300">Template ID:</span>
                <span className="text-xs font-mono bg-gray-100 dark:bg-gray-800 px-2 py-1 rounded">
                  {templateData.sourceTemplateId.slice(0, 8)}...
                </span>
              </div>
            )}
            <div className="mt-3 p-2 bg-blue-100/50 dark:bg-blue-900/20 rounded-md">
              {/* eslint-disable-next-line i18n/no-untranslated-jsx-strings -- pre-existing untranslated string (task #708): translate in a follow-up */}
              <p className="text-xs text-blue-700 dark:text-blue-300">
                {t('formHasBeenPrePopulatedWith')}
              </p>
            </div>
          </CardContent>
        </Card>

        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
            <StandardFormGrid>
              <FormField
                control={form.control}
                name="title"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('title')}</FormLabel>
                    <FormControl>
                      <Input {...field} data-testid="input-bill-title" />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <CategorySelectField
                control={form.control}
                name="category"
              />
            </StandardFormGrid>

            <FormField
              control={form.control}
              name="description"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>{t('description')} ({t('optional')})</FormLabel>
                  <FormControl>
                    <Textarea {...field} data-testid="textarea-bill-description" />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <StandardFormGrid>
              <FormField
                control={form.control}
                name="vendor"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('vendor')} ({t('optional')})</FormLabel>
                    <FormControl>
                      <Input {...field} data-testid="input-bill-vendor" />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <CurrencyInputField
                control={form.control}
                name="totalAmount"
                label="Total Amount"
                data-testid="input-bill-amount"
              />
            </StandardFormGrid>

            <StandardFormGrid>
              <FormField
                control={form.control}
                name="startDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Start Date</FormLabel>
                    <FormControl>
                      <Input 
                        {...field} 
                        type="date" 
                        data-testid="input-bill-start-date" 
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="endDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>End Date (Optional)</FormLabel>
                    <FormControl>
                      <Input 
                        {...field} 
                        type="date" 
                        data-testid="input-bill-end-date" 
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </StandardFormGrid>

            <FormField
              control={form.control}
              name="notes"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Notes (Optional)</FormLabel>
                  <FormControl>
                    <Textarea {...field} data-testid="textarea-bill-notes" />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <DocumentAttachmentSection
              pendingFiles={pendingFiles}
              onFileAdd={handleFileAdd}
              onFileRemove={handleFileRemove}
              uploadContext={uploadContext}
              formType="bills"
            />

            <div className="flex justify-end gap-2 pt-4">
              <Button 
                type="button" 
                variant="outline" 
                onClick={onClose}
                data-testid="button-cancel"
              >
                {t('cancel')}
              </Button>
              <Button 
                type="submit" 
                disabled={isSubmitting || createBillMutation.isPending}
                data-testid="button-create-bill"
              >
                {isSubmitting || createBillMutation.isPending ? t('creating') : t('createBill')}
              </Button>
            </div>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}
