import { describe, it, expect, beforeEach } from '@jest/globals';
import { Bill } from '../../shared/schema';

/**
 * Comprehensive test suite for Bills Page Functionality
 * Tests all aspects of bill management including:
 * - Template workflow for auto-generated bills
 * - Recurrence checkbox behavior
 * - Form validation and data integrity
 * - Auto-generation safeguards
 * - Payment type mapping
 */

describe('Bills Page - Template Workflow', () => {
  describe('Auto-Generated Bill Detection', () => {
    it('should identify auto-generated bills by isAutoGenerated flag', () => {
      const autoGeneratedBill: Partial<Bill> = {
        id: 'test-bill-1',
        isAutoGenerated: true,
        sourceTemplateId: 'source-123',
        autoGeneratedLabel: 'Auto 2026',
      };

      expect(autoGeneratedBill.isAutoGenerated).toBe(true);
      expect(autoGeneratedBill.sourceTemplateId).toBeDefined();
      expect(autoGeneratedBill.autoGeneratedLabel).toContain('Auto');
    });

    it('should differentiate between regular and auto-generated bills', () => {
      const regularBill: Partial<Bill> = {
        id: 'regular-bill-1',
        isAutoGenerated: false,
        sourceTemplateId: undefined,
      };

      const autoGeneratedBill: Partial<Bill> = {
        id: 'auto-gen-bill-1',
        isAutoGenerated: true,
        sourceTemplateId: 'template-123',
      };

      expect(regularBill.isAutoGenerated).toBe(false);
      expect(autoGeneratedBill.isAutoGenerated).toBe(true);
    });
  });

  describe('Recurrence Checkbox Logic', () => {
    it('should pre-check recurrence for auto-generated bills in template mode', () => {
      const bill: Partial<Bill> = {
        id: 'template-bill',
        isAutoGenerated: true,
        paymentType: 'unique', // Auto-gen bills are converted to unique
      };
      
      const isTemplate = true;
      const shouldPreCheck = isTemplate && bill.isAutoGenerated === true;
      
      expect(shouldPreCheck).toBe(true);
    });

    it('should NOT pre-check recurrence for regular bills', () => {
      const bill: Partial<Bill> = {
        id: 'regular-bill',
        isAutoGenerated: false,
        paymentType: 'unique',
      };
      
      const isTemplate = true;
      const shouldPreCheck = isTemplate && bill.isAutoGenerated === true;
      
      expect(shouldPreCheck).toBe(false);
    });

    it('should NOT pre-check recurrence when NOT in template mode', () => {
      const bill: Partial<Bill> = {
        id: 'bill-1',
        isAutoGenerated: true,
        paymentType: 'unique',
      };
      
      const isTemplate = false;
      const shouldPreCheck = isTemplate && bill.isAutoGenerated === true;
      
      expect(shouldPreCheck).toBe(false);
    });

    it('should handle undefined isAutoGenerated gracefully', () => {
      const bill: Partial<Bill> = {
        id: 'bill-2',
        isAutoGenerated: undefined,
        paymentType: 'unique',
      };
      
      const isTemplate = true;
      const shouldPreCheck = isTemplate && bill.isAutoGenerated === true;
      
      expect(shouldPreCheck).toBe(false);
    });
  });

  describe('Payment Type Mapping', () => {
    it('should map recurrence=true to paymentType=recurrent', () => {
      const formData = {
        recurrence: true,
        paymentCount: '1' as const,
      };

      const paymentType = formData.recurrence ? 'recurrent' : 'unique';
      
      expect(paymentType).toBe('recurrent');
    });

    it('should map recurrence=false to paymentType=unique', () => {
      const formData = {
        recurrence: false,
        paymentCount: '1' as const,
      };

      const paymentType = formData.recurrence ? 'recurrent' : 'unique';
      
      expect(paymentType).toBe('unique');
    });

    it('should handle single payment recurrent bills', () => {
      const bill: Partial<Bill> = {
        paymentType: 'recurrent',
        schedulePayment: undefined,
        costs: ['1200.00'],
      };

      expect(bill.paymentType).toBe('recurrent');
      expect(bill.costs?.length).toBe(1);
    });

    it('should handle multiple payment recurrent bills', () => {
      const bill: Partial<Bill> = {
        paymentType: 'recurrent',
        schedulePayment: 'monthly',
        costs: ['500.00', '500.00', '500.00'],
      };

      expect(bill.paymentType).toBe('recurrent');
      expect(bill.costs?.length).toBeGreaterThan(1);
    });
  });

  describe('Template Mode Safeguards', () => {
    it('should force POST method for template bills', () => {
      const bill: Partial<Bill> = {
        id: 'existing-bill-id',
        isAutoGenerated: true,
      };
      
      const isTemplate = true;
      const shouldUsePost = isTemplate || !bill.id;
      
      expect(shouldUsePost).toBe(true);
    });

    it('should use PUT method for regular bill updates', () => {
      const bill: Partial<Bill> = {
        id: 'existing-bill-id',
        isAutoGenerated: false,
      };
      
      const isTemplate = false;
      const shouldUsePut = !isTemplate && !!bill.id;
      
      expect(shouldUsePut).toBe(true);
    });

    it('should use POST method for new bills', () => {
      const bill: Partial<Bill> = {
        id: undefined,
        isAutoGenerated: false,
      };
      
      const isTemplate = false;
      const shouldUsePost = isTemplate || !bill.id;
      
      expect(shouldUsePost).toBe(true);
    });

    it('should disable auto-save for template mode', () => {
      const bill: Partial<Bill> = {
        id: 'bill-123',
        isAutoGenerated: true,
      };
      
      const isTemplate = true;
      const shouldAutoSave = bill.id && !isTemplate;
      
      expect(shouldAutoSave).toBe(false);
    });

    it('should enable auto-save for regular edit mode', () => {
      const bill: Partial<Bill> = {
        id: 'bill-123',
        isAutoGenerated: false,
      };
      
      const isTemplate = false;
      const shouldAutoSave = bill.id && !isTemplate;
      
      expect(shouldAutoSave).toBe(true);
    });
  });

  describe('Bill Data Parsing', () => {
    it('should parse single payment bill correctly', () => {
      const bill: Partial<Bill> = {
        paymentType: 'unique',
        costs: ['1000.00'],
        totalAmount: '1000.00',
      };

      const paymentCount = bill.costs?.length === 1 ? '1' : 'multiple';
      const recurrence = bill.paymentType === 'recurrent';
      
      expect(paymentCount).toBe('1');
      expect(recurrence).toBe(false);
    });

    it('should parse multiple payment bill correctly', () => {
      const bill: Partial<Bill> = {
        paymentType: 'unique',
        costs: ['500.00', '500.00', '500.00'],
        totalAmount: '1500.00',
      };

      const paymentCount = (bill.costs?.length ?? 0) > 1 ? 'multiple' : '1';
      const recurrence = bill.paymentType === 'recurrent';
      
      expect(paymentCount).toBe('multiple');
      expect(recurrence).toBe(false);
    });

    it('should parse recurrent single payment bill correctly', () => {
      const bill: Partial<Bill> = {
        paymentType: 'recurrent',
        costs: ['2500.00'],
        totalAmount: '2500.00',
      };

      const paymentCount = bill.costs?.length === 1 ? '1' : 'multiple';
      const recurrence = bill.paymentType === 'recurrent';
      
      expect(paymentCount).toBe('1');
      expect(recurrence).toBe(true);
    });

    it('should parse recurrent multiple payment bill correctly', () => {
      const bill: Partial<Bill> = {
        paymentType: 'recurrent',
        costs: ['1000.00', '1000.00', '1000.00', '1000.00'],
        totalAmount: '4000.00',
      };

      const paymentCount = (bill.costs?.length ?? 0) > 1 ? 'multiple' : '1';
      const recurrence = bill.paymentType === 'recurrent';
      
      expect(paymentCount).toBe('multiple');
      expect(recurrence).toBe(true);
    });
  });

  describe('Auto-Generation Workflow Edge Cases', () => {
    it('should handle bills with empty costs array', () => {
      const bill: Partial<Bill> = {
        paymentType: 'unique',
        costs: [],
        totalAmount: '0.00',
      };

      const isValid = (bill.costs?.length ?? 0) > 0;
      
      expect(isValid).toBe(false);
    });

    it('should validate bill with required fields', () => {
      const bill: Partial<Bill> = {
        buildingId: 'building-123',
        title: 'Test Bill',
        category: 'maintenance',
        paymentType: 'unique',
        costs: ['100.00'],
        totalAmount: '100.00',
        startDate: '2025-01-01',
      };

      const hasRequiredFields = 
        !!bill.buildingId &&
        !!bill.title &&
        !!bill.category &&
        !!bill.paymentType &&
        (bill.costs?.length ?? 0) > 0 &&
        !!bill.totalAmount &&
        !!bill.startDate;
      
      expect(hasRequiredFields).toBe(true);
    });

    it('should detect missing required fields', () => {
      const bill: Partial<Bill> = {
        buildingId: 'building-123',
        title: '',
        category: 'maintenance',
        paymentType: 'unique',
        costs: ['100.00'],
      };

      const hasRequiredFields = 
        !!bill.buildingId &&
        !!bill.title &&
        !!bill.category &&
        !!bill.paymentType &&
        (bill.costs?.length ?? 0) > 0;
      
      expect(hasRequiredFields).toBe(false);
    });

    it('should handle auto-generated bills with all metadata', () => {
      const bill: Partial<Bill> = {
        id: 'auto-gen-123',
        buildingId: 'building-123',
        title: 'Annual Fee',
        category: 'administration',
        paymentType: 'unique',
        costs: ['1200.00'],
        totalAmount: '1200.00',
        startDate: '2026-01-01',
        isAutoGenerated: true,
        sourceTemplateId: 'template-456',
        autoGeneratedLabel: 'Auto 2026',
      };

      expect(bill.isAutoGenerated).toBe(true);
      expect(bill.sourceTemplateId).toBeDefined();
      expect(bill.autoGeneratedLabel).toContain('2026');
      expect(bill.paymentType).toBe('unique');
    });
  });

  describe('Bill Status and Category Validation', () => {
    it('should accept valid bill statuses', () => {
      const validStatuses = ['draft', 'sent', 'overdue', 'paid', 'cancelled'] as const;
      
      validStatuses.forEach(status => {
        const bill: Partial<Bill> = { status };
        expect(['draft', 'sent', 'overdue', 'paid', 'cancelled']).toContain(bill.status);
      });
    });

    it('should accept valid bill categories', () => {
      const validCategories = [
        'administration',
        'cleaning',
        'construction',
        'consulting',
        'equipment_rental',
        'insurance',
        'legal_services',
        'maintenance',
        'professional_services',
        'repairs',
        'supplies',
        'taxes',
        'utilities',
        'other',
      ] as const;
      
      validCategories.forEach(category => {
        const bill: Partial<Bill> = { category };
        expect(validCategories).toContain(bill.category);
      });
    });
  });

  describe('Total Amount Calculations', () => {
    it('should calculate total for single payment', () => {
      const costs = ['1000.00'];
      const total = costs.reduce((sum, cost) => sum + parseFloat(cost), 0);
      
      expect(total).toBe(1000);
    });

    it('should calculate total for multiple equal payments', () => {
      const costs = ['500.00', '500.00', '500.00', '500.00'];
      const total = costs.reduce((sum, cost) => sum + parseFloat(cost), 0);
      
      expect(total).toBe(2000);
    });

    it('should calculate total for unequal payments', () => {
      const costs = ['1000.00', '750.00', '500.00'];
      const total = costs.reduce((sum, cost) => sum + parseFloat(cost), 0);
      
      expect(total).toBe(2250);
    });

    it('should handle decimal amounts correctly', () => {
      const costs = ['123.45', '67.89', '0.99'];
      const total = costs.reduce((sum, cost) => sum + parseFloat(cost), 0);
      
      expect(total).toBeCloseTo(192.33, 2);
    });
  });

  describe('Form Mode Detection', () => {
    it('should detect create mode (no bill, no template)', () => {
      const bill = undefined;
      const isTemplate = false;
      const mode = bill ? (isTemplate ? 'template' : 'edit') : 'create';
      
      expect(mode).toBe('create');
    });

    it('should detect edit mode (has bill, not template)', () => {
      const bill = { id: 'bill-123' };
      const isTemplate = false;
      const mode = bill ? (isTemplate ? 'template' : 'edit') : 'create';
      
      expect(mode).toBe('edit');
    });

    it('should detect template mode (has bill, is template)', () => {
      const bill = { id: 'bill-123', isAutoGenerated: true };
      const isTemplate = true;
      const mode = bill ? (isTemplate ? 'template' : 'edit') : 'create';
      
      expect(mode).toBe('template');
    });
  });

  describe('Date Handling', () => {
    it('should validate start date format', () => {
      const bill: Partial<Bill> = {
        startDate: '2025-01-15',
      };

      const isValidFormat = /^\d{4}-\d{2}-\d{2}$/.test(bill.startDate || '');
      
      expect(isValidFormat).toBe(true);
    });

    it('should handle end date for recurrent bills', () => {
      const bill: Partial<Bill> = {
        paymentType: 'recurrent',
        startDate: '2025-01-01',
        endDate: '2025-12-31',
      };

      expect(bill.endDate).toBeDefined();
      expect(bill.paymentType).toBe('recurrent');
    });

    it('should allow undefined end date for open-ended bills', () => {
      const bill: Partial<Bill> = {
        paymentType: 'recurrent',
        startDate: '2025-01-01',
        endDate: undefined,
      };

      expect(bill.endDate).toBeUndefined();
      expect(bill.paymentType).toBe('recurrent');
    });
  });

  describe('Source Template Relationship', () => {
    it('should link auto-generated bill to source template', () => {
      const sourceBill: Partial<Bill> = {
        id: 'source-123',
        paymentType: 'recurrent',
        isAutoGenerated: false,
      };

      const generatedBill: Partial<Bill> = {
        id: 'generated-456',
        paymentType: 'unique',
        isAutoGenerated: true,
        sourceTemplateId: sourceBill.id,
      };

      expect(generatedBill.sourceTemplateId).toBe(sourceBill.id);
      expect(generatedBill.isAutoGenerated).toBe(true);
    });

    it('should not have sourceTemplateId for regular bills', () => {
      const regularBill: Partial<Bill> = {
        id: 'regular-123',
        paymentType: 'unique',
        isAutoGenerated: false,
        sourceTemplateId: undefined,
      };

      expect(regularBill.sourceTemplateId).toBeUndefined();
      expect(regularBill.isAutoGenerated).toBe(false);
    });
  });
});
