/**
 * @file Bills Page Shareable URL Tests
 * @description Verifies the bills page persists filters + sort to the URL
 *   and restores them on load so shared links keep working.
 *
 *   Note: the actual URL keys defined in client/src/pages/manager/bills.tsx
 *   are `sortField` + `sortDirection` (the original task brief listed
 *   `sortDir` informally; this test guards the real contract used by the
 *   parser/serializer).
 */

import React, { type ComponentType } from 'react';
import { render, screen, fireEvent, waitFor, act } from '@testing-library/react';
import { describe, it, expect, beforeEach, jest } from '@jest/globals';
import '@testing-library/jest-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

// The bills page is heavy to render in jsdom (full table + filter controls +
// hierarchical-selection HOC) and several cases drive multiple `fireEvent`
// interactions plus `waitFor` loops. Under the parallel `maxWorkers: 50%`
// pool the repo-wide 3 s `testTimeout` (see `jest.config.cjs`) is too tight
// and flakes intermittently. Mirror the fix used in
// `bills-template-workflow.test.tsx` and give this file headroom.
jest.setTimeout(20_000);

interface BillsPageProps {
  buildingId?: string;
  organizationId?: string;
  buildingName?: string;
}

jest.mock('@/hooks/use-language', () => ({
  useLanguage: () => ({
    language: 'en',
    setLanguage: jest.fn(),
    toggleLanguage: jest.fn(),
    t: (key: string) => key,
  }),
}));

jest.mock('@/hooks/use-toast', () => ({
  useToast: () => ({ toast: jest.fn() }),
}));

jest.mock('@/hooks/use-current-financial-year', () => ({
  useCurrentFinancialYear: () => ({
    currentFinancialYear: {
      label: '2025-2026',
      startYear: 2025,
      start: new Date('2025-01-01'),
      end: new Date('2025-12-31'),
    },
    isLoading: false,
  }),
}));

jest.mock('@/components/hoc/withHierarchicalSelection', () => ({
  withHierarchicalSelection: (Component: ComponentType<BillsPageProps>) => {
    const Wrapped = (props: BillsPageProps) => (
      <Component buildingId="building-1" organizationId="org-1" {...props} />
    );
    Wrapped.displayName = 'MockWithHierarchicalSelection';
    return Wrapped;
  },
}));

jest.mock('@/components/layout/header', () => ({ Header: () => null }));

jest.mock('@/components/common/DocumentInlineViewer', () => ({
  DocumentInlineViewer: () => null,
}));

jest.mock('@/components/bill-management/ModularBillForm', () => ({
  __esModule: true,
  default: () => null,
}));

jest.mock('@/components/ui/auto-generated-badge', () => ({
  AutoGeneratedBadge: () => null,
}));

jest.mock('@/lib/queryClient', () => ({
  apiRequest: jest.fn(),
  queryClient: { invalidateQueries: jest.fn() },
}));

type FetchInput = Parameters<typeof fetch>[0];
const mockFetch = jest.fn<typeof fetch>();
(globalThis as { fetch: typeof fetch }).fetch = mockFetch as unknown as typeof fetch;

const jsonResponse = (data: unknown): Response =>
  new Response(JSON.stringify(data), {
    status: 200,
    headers: { 'Content-Type': 'application/json' },
  });

// Imported after mocks so the module sees the mocked dependencies.
import BillsPage from '../../client/src/pages/manager/bills';

function renderAt(search: string) {
  window.history.replaceState({}, '', `/manager/bills${search}`);
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: { retry: false },
      mutations: { retry: false },
    },
  });
  return render(
    <QueryClientProvider client={queryClient}>
      <BillsPage />
    </QueryClientProvider>,
  );
}

beforeEach(() => {
  mockFetch.mockReset();
  mockFetch.mockImplementation((input: FetchInput) => {
    const url =
      typeof input === 'string'
        ? input
        : input instanceof URL
          ? input.toString()
          : input.url;
    if (url.includes('/api/manager/buildings/')) {
      return Promise.resolve(
        jsonResponse({ id: 'building-1', financialYearStart: '2025-01-01' }),
      );
    }
    if (url.includes('/api/bills/year-range')) {
      return Promise.resolve(jsonResponse({ years: [] }));
    }
    if (url.startsWith('/api/bills')) {
      return Promise.resolve(jsonResponse([]));
    }
    return Promise.resolve(jsonResponse({}));
  });
});

describe('Bills page shareable URLs', () => {
  it('restores filters and sort state from the query string on load', async () => {
    renderAt(
      '?category=utilities&year=2024-2025&sortField=issueDate&sortDirection=desc',
    );

    // Sort field is restored: bills page only renders the "clear sort"
    // button when one of the named sort fields is active.
    expect(await screen.findByTestId('button-clear-sort')).toBeInTheDocument();

    // Sort direction "desc" is restored: the issueDate sort button shows a
    // ChevronDown icon (lucide-react adds a `lucide-chevron-down` class).
    const issueSortButton = screen.getByTestId('button-sort-issue-date');
    expect(
      issueSortButton.querySelector('.lucide-chevron-down'),
    ).toBeInTheDocument();
    // The opposite direction must NOT be rendered for the active sort.
    expect(
      issueSortButton.querySelector('.lucide-chevron-up'),
    ).not.toBeInTheDocument();

    // The other sort buttons should not show a direction chevron because
    // they are not the active sort field.
    const dueDateSortButton = screen.getByTestId('button-sort-due-date');
    expect(
      dueDateSortButton.querySelector('.lucide-chevron-down'),
    ).not.toBeInTheDocument();
    expect(
      dueDateSortButton.querySelector('.lucide-chevron-up'),
    ).not.toBeInTheDocument();

    // Active filter chips reflect the parsed year + category from the URL.
    expect(screen.getByText('2024-2025')).toBeInTheDocument();
    expect(screen.getByText('utilities')).toBeInTheDocument();

    // The serializer should leave the existing search string untouched
    // because the parsed state already matches the URL exactly.
    await waitFor(() => {
      const params = new URLSearchParams(window.location.search);
      expect(params.get('category')).toBe('utilities');
      expect(params.get('year')).toBe('2024-2025');
      expect(params.get('sortField')).toBe('issueDate');
      expect(params.get('sortDirection')).toBe('desc');
    });
  });

  it('writes filter and sort changes back to the URL and Clear Filters wipes them', async () => {
    renderAt('');

    // Wait for the filter UI to mount.
    const filtersToggle = await screen.findByRole('button', { name: /show \/ hide filters/i });

    // No bill query params yet (year matches the default fiscal year so
    // it is intentionally omitted by the serializer).
    await waitFor(() => {
      expect(window.location.search).toBe('');
    });

    // Trigger a sort change so we can assert the sort keys are written
    // back to the URL with the exact contract names.
    const issueSortButton = screen.getByTestId('button-sort-issue-date');
    await act(async () => {
      fireEvent.click(issueSortButton);
    });
    await waitFor(() => {
      const params = new URLSearchParams(window.location.search);
      expect(params.get('sortField')).toBe('issueDate');
      expect(params.get('sortDirection')).toBe('asc');
    });

    // Expand the filter panel so the vendor input is reachable.
    await act(async () => {
      fireEvent.click(filtersToggle);
    });

    const vendorInput = await screen.findByTestId('input-search-vendor');
    await act(async () => {
      fireEvent.change(vendorInput, { target: { value: 'acme' } });
    });

    // The filter -> URL sync effect should mirror the new vendor filter
    // alongside the previously-applied sort.
    await waitFor(() => {
      const params = new URLSearchParams(window.location.search);
      expect(params.get('vendor')).toBe('acme');
      expect(params.get('sortField')).toBe('issueDate');
      expect(params.get('sortDirection')).toBe('asc');
    });

    // CollapsibleFilters renders the reset button with the resetLabel
    // text ("clearFilters" since our t() returns the key). Multiple
    // buttons may share that accessible name (the inline clear-sort
    // button uses the same label), so we pick the one that lives
    // outside the sort toolbar.
    const resetCandidates = screen.getAllByRole('button', { name: /clearFilters/i });
    const resetButton = resetCandidates.find(
      (btn) => btn.getAttribute('data-testid') !== 'button-clear-sort',
    );
    expect(resetButton).toBeDefined();
    await act(async () => {
      fireEvent.click(resetButton as HTMLElement);
    });

    // Clear Filters wipes every bill-related query param.
    await waitFor(() => {
      expect(window.location.search).toBe('');
    });
  });
});
