import { describe, it, expect, beforeEach, jest } from '@jest/globals';
import { render, screen, waitFor, fireEvent, act } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import '@testing-library/jest-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import ModularBillForm from '../../client/src/components/bill-management/ModularBillForm';
import { Bill } from '../../shared/schema';
import React, { ReactNode } from 'react';

const mockApiRequest = jest.fn();

jest.mock('@/hooks/use-language', () => ({
  useLanguage: () => ({
    language: 'en',
    setLanguage: jest.fn(),
    toggleLanguage: jest.fn(),
    t: (key: string) => key,
  }),
}));

jest.mock('@/hooks/use-toast', () => ({
  useToast: () => ({
    toast: jest.fn(),
  }),
}));

jest.mock('@/lib/queryClient', () => ({
  apiRequest: (...args: unknown[]) => mockApiRequest(...args),
  queryClient: {
    invalidateQueries: jest.fn(),
  },
}));

jest.mock('@/components/document-management', () => ({
  SharedUploader: () => null,
}));

jest.mock('../../client/src/components/bill-management/GeminiBillExtractor', () => ({
  GeminiBillExtractor: () => null,
}));

jest.mock('@/components/common/AttachedFileSection', () => ({
  AttachedFileSection: () => null,
}));

jest.mock('@/components/common/StandardFormGrid', () => ({
  StandardFormGrid: ({ children }: { children: ReactNode }) => <div>{children}</div>,
}));

jest.mock('../../client/src/components/bill-management/ConfidenceIndicator', () => ({
  ConfidenceIndicator: () => null,
}));

// PointerEvent + *PointerCapture polyfills for jsdom live in
// `jest.setup.simple.ts` so every pointer-driven test gets the same shim.
if (typeof Element.prototype.scrollIntoView !== 'function') {
  Element.prototype.scrollIntoView = function () {};
}

describe('Bills Template Workflow', () => {
  let queryClient: QueryClient;

  beforeEach(() => {
    queryClient = new QueryClient({
      defaultOptions: {
        queries: { retry: false },
        mutations: { retry: false },
      },
    });

    mockApiRequest.mockReset();
    mockApiRequest.mockResolvedValue({
      ok: true,
      json: async () => ({ id: 'new-bill-123', success: true }),
    });
  });

  describe('Auto-Generated Bill Template Creation', () => {
    it('should set billType to recurrent when creating from auto-generated bill', async () => {
      const autoGeneratedBill: Partial<Bill> = {
        id: 'auto-gen-123',
        buildingId: 'building-123',
        title: 'test1',
        description: 'Auto-generated test bill',
        category: 'maintenance',
        vendor: 'vendor 1',
        paymentType: 'unique',
        costs: ['1000.00'],
        totalAmount: '1000.00',
        startDate: '2026-01-29',
        status: 'draft',
        isAutoGenerated: true,
        sourceTemplateId: 'source-bill-id',
        autoGeneratedLabel: 'Auto 2026',
      };

      render(
        <QueryClientProvider client={queryClient}>
          <ModularBillForm
            bill={autoGeneratedBill as Bill}
            isTemplate={true}
            buildingId="building-123"
          />
        </QueryClientProvider>
      );

      await waitFor(() => {
        const recurrentRadio = screen.getByTestId('radio-bill-type-recurrent');
        expect(recurrentRadio).toBeInTheDocument();
        expect(recurrentRadio).toHaveAttribute('data-state', 'checked');
      });
    });

    it('should NOT set billType to recurrent for regular bills', async () => {
      const regularBill: Partial<Bill> = {
        id: 'regular-123',
        buildingId: 'building-123',
        title: 'test2',
        description: 'Regular bill',
        category: 'utilities',
        vendor: 'vendor 2',
        paymentType: 'unique',
        costs: ['500.00'],
        totalAmount: '500.00',
        startDate: '2025-01-15',
        status: 'draft',
        isAutoGenerated: false,
      };

      render(
        <QueryClientProvider client={queryClient}>
          <ModularBillForm
            bill={regularBill as Bill}
            isTemplate={true}
            buildingId="building-123"
          />
        </QueryClientProvider>
      );

      await waitFor(() => {
        const uniqueRadio = screen.getByTestId('radio-bill-type-unique');
        expect(uniqueRadio).toHaveAttribute('data-state', 'checked');
        const recurrentRadio = screen.getByTestId('radio-bill-type-recurrent');
        expect(recurrentRadio).toHaveAttribute('data-state', 'unchecked');
      });
    });

    it('should populate form fields with template bill data', async () => {
      const templateBill: Partial<Bill> = {
        id: 'template-123',
        buildingId: 'building-123',
        title: 'Insurance Premium',
        description: 'Annual building insurance',
        category: 'insurance',
        vendor: 'Insurance Corp',
        paymentType: 'recurrent',
        costs: ['2500.00'],
        totalAmount: '2500.00',
        startDate: '2025-06-01',
        status: 'active',
        isAutoGenerated: true,
        autoGeneratedLabel: 'Auto 2026',
      };

      render(
        <QueryClientProvider client={queryClient}>
          <ModularBillForm
            bill={templateBill as Bill}
            isTemplate={true}
            buildingId="building-123"
          />
        </QueryClientProvider>
      );

      await waitFor(() => {
        expect(screen.getByDisplayValue('Insurance Premium')).toBeInTheDocument();
        expect(screen.getByDisplayValue('Annual building insurance')).toBeInTheDocument();
        expect(screen.getByDisplayValue('Insurance Corp')).toBeInTheDocument();
      });
    });

    it('should show create button (not update) when isTemplate=true even when bill has ID', async () => {
      const templateBill: Partial<Bill> = {
        id: 'template-456',
        buildingId: 'building-123',
        title: 'Test Bill',
        category: 'other',
        paymentType: 'unique',
        costs: ['100.00'],
        totalAmount: '100.00',
        startDate: '2025-01-01',
        isAutoGenerated: true,
      };

      render(
        <QueryClientProvider client={queryClient}>
          <ModularBillForm
            bill={templateBill as Bill}
            isTemplate={true}
            buildingId="building-123"
          />
        </QueryClientProvider>
      );

      await waitFor(() => {
        expect(screen.getByTestId('button-create-bill')).toBeInTheDocument();
        expect(screen.queryByTestId('button-update-bill')).not.toBeInTheDocument();
      });
    });
  });

  describe('Template Safeguards', () => {
    it('should hide delete button when isTemplate=true', async () => {
      const templateBill: Partial<Bill> = {
        id: 'template-789',
        buildingId: 'building-123',
        title: 'Test Bill',
        category: 'maintenance',
        paymentType: 'unique',
        costs: ['200.00'],
        totalAmount: '200.00',
        startDate: '2025-02-01',
        isAutoGenerated: true,
      };

      render(
        <QueryClientProvider client={queryClient}>
          <ModularBillForm
            bill={templateBill as Bill}
            isTemplate={true}
            buildingId="building-123"
          />
        </QueryClientProvider>
      );

      await waitFor(() => {
        expect(screen.queryByTestId('button-delete-bill')).not.toBeInTheDocument();
      });
    });

    it('should use POST endpoint for template bills even when bill has ID', async () => {
      const templateBill: Partial<Bill> = {
        id: 'existing-bill-id',
        buildingId: 'building-123',
        title: 'Template Bill',
        category: 'utilities',
        vendor: 'Test Vendor',
        paymentType: 'unique',
        costs: ['300.00'],
        totalAmount: '300.00',
        startDate: '2025-03-01',
        isAutoGenerated: true,
      };

      render(
        <QueryClientProvider client={queryClient}>
          <ModularBillForm
            bill={templateBill as Bill}
            isTemplate={true}
            onSuccess={jest.fn()}
            buildingId="building-123"
          />
        </QueryClientProvider>
      );

      await waitFor(() => {
        expect(screen.getByTestId('button-create-bill')).toBeInTheDocument();
      });

      const createButton = screen.getByTestId('button-create-bill');
      await act(async () => {
        fireEvent.click(createButton);
      });

      await waitFor(() => {
        expect(mockApiRequest).toHaveBeenCalledWith(
          'POST',
          '/api/bills',
          expect.any(Object)
        );
        expect(mockApiRequest).not.toHaveBeenCalledWith(
          'PUT',
          expect.stringContaining(`/api/bills/${templateBill.id}`),
          expect.any(Object)
        );
      });
    });
  });

  describe('Bill Form Data Validation', () => {
    it('should validate required fields before submission', async () => {
      render(
        <QueryClientProvider client={queryClient}>
          <ModularBillForm buildingId="building-123" />
        </QueryClientProvider>
      );

      const createButton = screen.getByTestId('button-create-bill');
      await act(async () => {
        fireEvent.click(createButton);
      });

      await waitFor(() => {
        expect(mockApiRequest).not.toHaveBeenCalled();
      });
    });

    it('should map billType radio to paymentType correctly on submission', async () => {
      const recurrentBill: Partial<Bill> = {
        id: 'recurrent-map-123',
        buildingId: 'building-123',
        title: 'Recurrent Mapping Test',
        vendor: 'Test Vendor',
        category: 'maintenance',
        paymentType: 'recurrent',
        costs: ['500.00'],
        totalAmount: '500.00',
        startDate: '2025-01-01',
        isAutoGenerated: true,
      };

      render(
        <QueryClientProvider client={queryClient}>
          <ModularBillForm
            bill={recurrentBill as Bill}
            isTemplate={true}
            onSuccess={jest.fn()}
            buildingId="building-123"
          />
        </QueryClientProvider>
      );

      await waitFor(() => {
        expect(screen.getByTestId('radio-bill-type-recurrent')).toHaveAttribute('data-state', 'checked');
      });

      const createButton = screen.getByTestId('button-create-bill');
      await act(async () => {
        fireEvent.click(createButton);
      });

      await waitFor(() => {
        expect(mockApiRequest).toHaveBeenCalledWith(
          'POST',
          '/api/bills',
          expect.objectContaining({
            paymentType: 'recurrent',
            recurrence: true,
          })
        );
      });
    });
  });

  describe('Auto-Generation Workflow Edge Cases', () => {
    it('should handle single payment recurrent bills correctly', async () => {
      const singlePaymentRecurrent: Partial<Bill> = {
        id: 'single-recurrent-123',
        buildingId: 'building-123',
        title: 'Annual Fee',
        category: 'administration',
        vendor: 'Admin Corp',
        paymentType: 'recurrent',
        schedulePayment: undefined,
        costs: ['1200.00'],
        totalAmount: '1200.00',
        startDate: '2025-01-01',
        isAutoGenerated: true,
      };

      render(
        <QueryClientProvider client={queryClient}>
          <ModularBillForm
            bill={singlePaymentRecurrent as Bill}
            isTemplate={true}
            buildingId="building-123"
          />
        </QueryClientProvider>
      );

      await waitFor(() => {
        const recurrentRadio = screen.getByTestId('radio-bill-type-recurrent');
        expect(recurrentRadio).toHaveAttribute('data-state', 'checked');
        const singleRadio = screen.getByTestId('radio-payment-structure-single');
        expect(singleRadio).toHaveAttribute('data-state', 'checked');
      });
    });

    it('should handle multiple payment auto-generated bills', async () => {
      const multiplePaymentBill: Partial<Bill> = {
        id: 'multi-payment-123',
        buildingId: 'building-123',
        title: 'Quarterly Fees',
        category: 'utilities',
        paymentType: 'unique',
        schedulePayment: 'monthly',
        costs: ['500.00', '500.00', '500.00', '500.00'],
        totalAmount: '2000.00',
        startDate: '2025-01-01',
        isAutoGenerated: true,
      };

      render(
        <QueryClientProvider client={queryClient}>
          <ModularBillForm
            bill={multiplePaymentBill as Bill}
            isTemplate={true}
            buildingId="building-123"
          />
        </QueryClientProvider>
      );

      await waitFor(() => {
        const recurrentRadio = screen.getByTestId('radio-bill-type-recurrent');
        expect(recurrentRadio).toHaveAttribute('data-state', 'checked');
        const installmentRadio = screen.getByTestId('radio-payment-structure-installment');
        expect(installmentRadio).toHaveAttribute('data-state', 'checked');
      });
    });

    it('should preserve bill data when switching between template and regular mode', async () => {
      const bill: Partial<Bill> = {
        id: 'switch-mode-123',
        buildingId: 'building-123',
        title: 'Switchable Bill',
        category: 'cleaning',
        paymentType: 'unique',
        costs: ['250.00'],
        totalAmount: '250.00',
        startDate: '2025-04-01',
        isAutoGenerated: true,
      };

      const { rerender } = render(
        <QueryClientProvider client={queryClient}>
          <ModularBillForm
            bill={bill as Bill}
            isTemplate={true}
            buildingId="building-123"
          />
        </QueryClientProvider>
      );

      await waitFor(() => {
        expect(screen.getByDisplayValue('Switchable Bill')).toBeInTheDocument();
      });

      rerender(
        <QueryClientProvider client={queryClient}>
          <ModularBillForm
            bill={bill as Bill}
            isTemplate={false}
            buildingId="building-123"
          />
        </QueryClientProvider>
      );

      await waitFor(() => {
        expect(screen.getByDisplayValue('Switchable Bill')).toBeInTheDocument();
      });
    });
  });

  describe('Success Callbacks and Dialog Management', () => {
    it('should call onSuccess callback after successful bill creation', async () => {
      const onSuccessMock = jest.fn();
      const user = userEvent.setup();

      const templateBill: Partial<Bill> = {
        id: 'success-test-123',
        buildingId: 'building-123',
        title: 'Success Test Bill',
        vendor: 'Test Vendor',
        category: 'other',
        paymentType: 'unique',
        costs: ['100.00'],
        totalAmount: '100.00',
        startDate: '2025-01-01',
        isAutoGenerated: true,
      };

      render(
        <QueryClientProvider client={queryClient}>
          <ModularBillForm
            bill={templateBill as Bill}
            isTemplate={true}
            buildingId="building-123"
            onSuccess={onSuccessMock}
          />
        </QueryClientProvider>
      );

      await waitFor(() => {
        expect(screen.getByTestId('button-create-bill')).toBeInTheDocument();
      });

      const createButton = screen.getByTestId('button-create-bill');
      await act(async () => {
        fireEvent.click(createButton);
      });

      await waitFor(() => {
        expect(onSuccessMock).toHaveBeenCalled();
      });
    });

    it('should call onCancel callback when cancel is clicked', async () => {
      const onCancelMock = jest.fn();
      const user = userEvent.setup();

      render(
        <QueryClientProvider client={queryClient}>
          <ModularBillForm buildingId="building-123" onCancel={onCancelMock} />
        </QueryClientProvider>
      );

      const cancelButton = screen.getByRole('button', { name: /cancel/i });
      await user.click(cancelButton);

      expect(onCancelMock).toHaveBeenCalled();
    });
  });

  describe('Form Field Interactions', () => {
    it('should render bill type and payment structure radio groups', async () => {
      render(
        <QueryClientProvider client={queryClient}>
          <ModularBillForm buildingId="building-123" />
        </QueryClientProvider>
      );

      await waitFor(() => {
        expect(screen.getByTestId('radio-bill-type')).toBeInTheDocument();
        expect(screen.getByTestId('radio-bill-type-unique')).toBeInTheDocument();
        expect(screen.getByTestId('radio-bill-type-recurrent')).toBeInTheDocument();
        expect(screen.getByTestId('radio-payment-structure')).toBeInTheDocument();
        expect(screen.getByTestId('radio-payment-structure-single')).toBeInTheDocument();
        expect(screen.getByTestId('radio-payment-structure-installment')).toBeInTheDocument();
      });
    });

    it('should display payment amount input for single payment structure', async () => {
      render(
        <QueryClientProvider client={queryClient}>
          <ModularBillForm buildingId="building-123" />
        </QueryClientProvider>
      );

      await waitFor(() => {
        const singleRadio = screen.getByTestId('radio-payment-structure-single');
        expect(singleRadio).toHaveAttribute('data-state', 'checked');
        expect(screen.getByTestId('input-payment-amount')).toBeInTheDocument();
      });
    });

    it('should show calculated total display', async () => {
      const bill: Partial<Bill> = {
        id: 'total-calc-123',
        buildingId: 'building-123',
        title: 'Total Calculation Bill',
        category: 'utilities',
        paymentType: 'unique',
        costs: ['1500.00'],
        totalAmount: '1500.00',
        startDate: '2025-01-01',
        isAutoGenerated: false,
      };

      render(
        <QueryClientProvider client={queryClient}>
          <ModularBillForm
            bill={bill as Bill}
            isTemplate={false}
            buildingId="building-123"
          />
        </QueryClientProvider>
      );

      await waitFor(() => {
        expect(screen.getByTestId('text-calculated-total')).toBeInTheDocument();
      });
    });
  });

  describe('Data Persistence and Auto-Save', () => {
    it('should NOT auto-save when isTemplate=true', async () => {
      const user = userEvent.setup();

      const templateBill: Partial<Bill> = {
        id: 'no-autosave-123',
        buildingId: 'building-123',
        title: 'No Auto-Save Bill',
        category: 'maintenance',
        paymentType: 'unique',
        costs: ['100.00'],
        totalAmount: '100.00',
        startDate: '2025-01-01',
        isAutoGenerated: true,
      };

      render(
        <QueryClientProvider client={queryClient}>
          <ModularBillForm
            bill={templateBill as Bill}
            isTemplate={true}
            buildingId="building-123"
          />
        </QueryClientProvider>
      );

      const titleInput = screen.getByDisplayValue('No Auto-Save Bill');
      await user.clear(titleInput);
      await user.type(titleInput, 'Modified Title');

      await new Promise((resolve) => setTimeout(resolve, 2000));

      expect(mockApiRequest).not.toHaveBeenCalledWith(
        'PUT',
        `/api/bills/${templateBill.id}`,
        expect.any(Object)
      );
    });

    it('should show update button when isTemplate=false for existing bill', async () => {
      const existingBill: Partial<Bill> = {
        id: 'autosave-123',
        buildingId: 'building-123',
        title: 'Auto-Save Bill',
        category: 'utilities',
        paymentType: 'unique',
        costs: ['200.00'],
        totalAmount: '200.00',
        startDate: '2025-01-01',
        isAutoGenerated: false,
      };

      render(
        <QueryClientProvider client={queryClient}>
          <ModularBillForm
            bill={existingBill as Bill}
            isTemplate={false}
            buildingId="building-123"
          />
        </QueryClientProvider>
      );

      await waitFor(() => {
        expect(screen.getByTestId('button-update-bill')).toBeInTheDocument();
        expect(screen.queryByTestId('button-create-bill')).not.toBeInTheDocument();
        expect(screen.getByTestId('button-delete-bill')).toBeInTheDocument();
      });
    });
  });
});
